### ISSUE TITLE
Better support for Materials

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1105] opened 2015-05-06 05:55 UTC
Go should improve integration with materials (SCM/Package Repository/Pipeline).

* Provide `materials` view where user can see list of materials -> click on one of the materials provides list of `modifications` (with pagination) -> click on one of the modifications provides list of `modified files` (with pagination) -> click on the modified file show `changes` to the file in that modification

**Comment by srinivasupadhya** [comment] 2015-05-22 10:02
#1145 can be done as part of this

**Comment by arvindsv** [comment] 2016-06-04 13:13
Closing as a duplicate of #1545.

**Closed by arvindsv** 2016-06-04 13:13 UTC
Labels: enhancement, materials, ui / ux
