### ISSUE TITLE
SSL connection issues after upgrade

### ISSUE THREAD

**Issue by superbeeny** [gocd/gocd#1360] opened 2015-07-16 17:43 UTC
After the upgrade I see issues with the agent trying to connect to the go-server

```
2015-07-16 13:38:37,726 [loopThread] ERROR thoughtworks.go.agent.AgentController:145 - [Agent Loop] Error occurred during loop: 
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:953)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:709)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:827)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1525)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1975)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:54)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:47)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:482)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
	... 25 more
```

**Comment by arvindsv** [comment] 2015-07-16 17:50
Hi @superbeeny, do you think [this issue](https://github.com/gocd/gocd/issues/1350) is related? In that case, Java 6 was being used on the agent side. Which version do you have?

**Comment by superbeeny** [comment] 2015-07-16 17:58
I'm using JDK 8 on server and agent sides

**Comment by arvindsv** [comment] 2015-07-16 18:02
Ok. And, are all your agents missing as well? Or, are some of them working? What symptoms are you seeing?

I don't think we've tests in place to ensure it works with Java 8. But, I think Go should (soon) support it, especially since Java 7 is not getting any more updates. So, I'd like to see what is going on with 8.

**Comment by superbeeny** [comment] 2015-07-16 18:07
ok so it appears that the agents were using oracle java as configured and the upgrade put in the openjdk for java 8, once I have synced the 2 the error is resolved.

Nick

**Comment by arvindsv** [comment] 2015-07-16 18:10
Alright, thank you for letting us know! Can you tell me which exact versions did not work, please? Just so that we can document that if needed.

**Comment by superbeeny** [comment] 2015-07-16 18:19
These are the 2 that were causing the conflict for me
```
# java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
# /app/development/jdks/jdk1.8.0/bin/java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
```

**Comment by DrStrangepork** [comment] 2015-07-31 23:56
I experienced this same issue on Ubuntu 14.04 LTS. After upgrading to openjdk-7-jre-headless_7u79-2.5.6-0ubuntu1.14.04.1, my go-agent experienced these same errors. Downgrading to openjdk-7-jre-headless_7u51-2.4.6-1ubuntu4 resolved my issue.

**Comment by darrenhaken** [comment] 2015-08-05 14:30
Was there ever a fix for this?
We've been experiencing the same issue.

**Comment by DrStrangepork** [comment] 2015-08-06 12:37
I resolved my issue by upgrading the server to the latest JRE - 7u79. Now all clients can attach.

**Comment by darrenhaken** [comment] 2015-08-06 12:40
This worked for me only after upgrading to Go 15.2.

This is critical to resolving the issue.

**Comment by jyotisingh** [comment] 2015-08-06 12:47
Check [comment](https://github.com/gocd/gocd/issues/1381#issuecomment-127992774) on a [similar issue](https://github.com/gocd/gocd/issues/1381).

**Comment by mkrogemann** [comment] 2015-08-12 12:08
I am late to the party - just found out something that may help others to resolve the issue quickly.
In order to make the SSL handshake work again on CentOS 6.4, I downgraded the openjdk package

[root@go-server go-server]# yum downgrade java-1.7.0-openjdk
---> Package java-1.7.0-openjdk.x86_64 1:1.7.0.85-2.6.1.3.el6_6 will be a downgrade
---> Package java-1.7.0-openjdk.x86_64 1:1.7.0.85-2.6.1.3.el6_7 will be erased

What I find most surprising here is the fact that the jdk patch level has not been changed, it looks like Red Hat has applied some changes to the JRE?

Anyway, in case you are on CentOS or RHEL 6.4, the above should solve the problem

**Comment by lorijoan** [comment] 2015-08-17 12:45
@jyotisingh - I have the same issue as @mkrogemann 

I match java version in agent and server to be identical, but using openJDK on CentOS 6.6, we see the issue with this specific build:
java-1.7.0-openjdk.x86_64 1:1.7.0.85-2.6.1.3.el6_7

We were aiming to try to keep up-to-date with the latest java on both agent and server, so hitting an issue like this in which we may be potentially stuck on a specific java version is not ideal.

Do you have any thoughts why GO might be having a hiccup on this update?  
https://rhn.redhat.com/errata/RHBA-2015-1467.html
https://rhn.redhat.com/errata/RHBA-2015-1245.html

FWIW, I'm using custom certificates.

**Comment by jyotisingh** [comment] 2015-08-17 13:13
@lorijoan - I think you are using Go <=15.1. A bunch of SSL ciphers were disabled by default on java 7u85, specifically the RC4 ones which are the only ones that will work with Go  <=15.1 ([more details](https://github.com/gocd/gocd/issues/1381#issuecomment-127992774)). Java 7u85 should work just fine with Go 15.2. However if it does not, and you have verified that both Go server and agent are using the same version of java, then could you [turn on ssl-debugging](https://github.com/gocd/gocd/issues/1381#issuecomment-125098933) and post the logs here.

**Comment by lorijoan** [comment] 2015-08-17 14:32
@jyotisingh - yes, I am on 15.2 and it still is having this problem with 7u85.  However, it is only an issue when they are the el6_7 version rather than the el6_6 version.

I'll give the debugging a go and see if that sheds any light on the issue.

**Comment by lorijoan** [comment] 2015-08-17 15:52
Ok, this is what I'm seeing when they're both on el6_7:

{code}
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
qtp327089747-19, READ: TLSv1.2 Handshake, length = 165
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1423048754 bytes = { 189, 58, 189, 3, 125, 215, 227, 112, 134, 71, 166, 72, 253, 207, 171, 199, 2, 128, 189, 89, 11, 200, 244, 180, 225, 74, 40, 75 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1}
Extension ec_point_formats, formats: [uncompressed]
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA224withECDSA, SHA224withRSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA, MD5withRSA
***
%% Initialized:  [Session-5, SSL_NULL_WITH_NULL_NULL]
qtp327089747-19, fatal error: 80: problem unwrapping net record
java.lang.RuntimeException: java.security.KeyException
%% Invalidated:  [Session-5, SSL_NULL_WITH_NULL_NULL]
qtp327089747-19, SEND TLSv1.2 ALERT:  fatal, description = internal_error
qtp327089747-19, WRITE: TLSv1.2 Alert, length = 2
{code}

**Comment by srinivasupadhya** [comment] 2015-08-21 10:44
similar to http://blog.backslasher.net/java-ssl-crash.html?

**Comment by srinivasupadhya** [comment] 2015-08-24 06:32
I was able to reproduce the issue with exact ssl debug logs. as suggested by link previously posted - upgrading `nss` (sudo yum upgrade nss) fixed the problem. trying to find why the upgrade is required.

**Comment by lorijoan** [comment] 2015-08-24 08:30
@srinivasupadhya - sorry I did not get to try this last week.  Good job finding that article, NSS upgrade definitely fixes the issue on my end as well.

**Comment by lenucksi** [comment] 2016-01-19 09:27
We had similar issues revolving around JDK incompatibilities and thus failed upgrades and or connections. 
I would hope that the introduction of websocket based agent communication allows to put a reverse proxy in front of the server and thus remove parts of the JVM issues..

**Comment by arvindsv** [comment] 2016-06-04 13:33
Closing. There have been many changes around this since the issue was reported, and there are also some more changes coming in (for example, #2236).

**Closed by arvindsv** 2016-06-04 13:33 UTC
