### ISSUE TITLE
Error messages on Go installation on Ubuntu

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#1481] opened 2015-09-06 12:02 UTC
I'm using Ubuntu 14.04.3 server edition amd64 architecture.

I followed the instruction here (http://www.go.cd/documentation/user/current/installation/install/server/linux.html#debian-based-distributions-ie-ubuntu) and I get the following errors. However, I'm able to connect to go on port 8153.
=== begin quote ===
Selecting previously unselected package go-server.
(Reading database ... 56933 files and directories currently installed.)
Preparing to unpack .../go-server_15.2.0-2248_all.deb ...
dpkg: no packages found matching cruise-server
Adding system user `go' (UID 105) ...
Adding new group`go' (GID 112) ...
Adding new user `go' (UID 105) with group`go' ...
Creating home directory `/var/go' ...
Unpacking go-server (15.2.0-2248) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up go-server (15.2.0-2248) ...
Found Java /usr/lib/jvm/java-7-openjdk-amd64/jre in PATH, using it.
Appending to "/etc/default/go-server": export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/jre" # SET_BY_GO_INSTALLER__DONT_REMOVE
chown: cannot access '/var/lib/go-server/**': No such file or directory
Installation of Go Server completed.
using default settings from /etc/default/go-server
Started Go Server on http://ubuntu:8153/go
update-rc.d: warning: default start runlevel arguments (2 3 4 5) do not match go-server Default-Start values (3 4 5)
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match go-server Default-Stop values (0 1 2 6)

=== end quote ===

**Comment by ketan** [comment] 2015-09-06 12:16
Is there something in the server log to indicate any startup problems?

The server attempts to boot up on fust install after `[dpkg|rpm] -i go-server...`

**Comment by sriramnrn** [comment] 2015-09-06 13:07
The only problem that I see is related to the yum plugin not being found. However, the go server starts up and can be reached.
I can confirm that after an OS reboot, the go-server starts up automatically and is usable.

**Comment by mihaibb** [comment] 2015-09-17 15:35
I also have the same issue and I've used the install using the deb package.

```

**Comment by arvindsv** [comment] 2015-09-17 16:18
> I also have the same issue

I'm trying to understand what the issue is. It looks like the server starts up. Right?

The `chown` message can be ignored. I think it is because `/var/lib/go-server` is newly created and the glob `/var/lib/go-server/**` matches nothing. So, chown is given `/var/lib/go-server/**`, which is an invalid filename (when not expanded).

The warning about runlevel is probably due to [this (old) pull request](https://github.com/gocd/gocd/pull/669). That should be a warning, and should go away the next time. From what I understand, since the runlevels changed, the /etc/rcX.d links would need to be changed, and that is what the warning is probably related to.

Given all of that ... what is the real issue? Does the server not start? Something else? Is there any information in `/var/log/go-server/go-server.log`?

**Comment by mihaibb** [comment] 2015-09-17 17:31
The issue is that after installing the go.cd the browser shows the loading indefinitely with no result.
I've been using a digital ocean droplet to test go.cd.
After reading the issue https://github.com/gocd/gocd/issues/1470 and the article http://fredrik.wendt.se/2015/09/11/cloudy-performance-in-cloud/ it might be a issue with using a digital ocean droplet.

I'll try with aws and get back with more informations.

**Comment by arvindsv** [comment] 2015-09-17 17:35
Ok. If possible, try adding this line to the end of `/etc/default/go-server`:
`export GO_SERVER_SYSTEM_PROPERTIES="$GO_SERVER_SYSTEM_PROPERTIES -Djava.security.egd=file:/dev/./urandom gocd/gocd-server"` (in a single line) and see if it helps.

Context: [this](https://groups.google.com/d/msg/go-cd/BPQiOSNMT9I/E5cPH6Cb4xgJ) and [this](https://groups.google.com/d/msg/go-cd/XA211ZGIGiU/ratM9BbVI7wJ).

**Comment by mihaibb** [comment] 2015-09-18 14:44
I've retry using the setting that you specified and that makes go-server to fail starting.
```
Starting Go Server with command: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -server  -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=256m    -Djava.security.egd=file:/dev/./urandom gocd/gocd-server -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/etc/go -Dcruise.config.file=/etc/go/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /usr/share/go-server/go.jar
Starting Go Server in directory: 
Error: Could not find or load main class gocd.gocd-server
```

**Comment by arvindsv** [comment] 2015-09-18 14:50
Ah, sorry, I meant to say this:

```
export GO_SERVER_SYSTEM_PROPERTIES="$GO_SERVER_SYSTEM_PROPERTIES -Djava.security.egd=file:/dev/./urandom"
```

**Comment by mihaibb** [comment] 2015-09-18 14:54
:+1: 

Great man, is working. Thanks.

**Comment by arvindsv** [comment] 2015-09-18 14:59
Ok, good. In 15.3 that is automatically added, and it should help startup time in VMs where the entropy pool is depleted. I guess @sriramnrn had a different issue?

**Comment by sriramnrn** [comment] 2015-09-24 06:16
Yes, I had reported a different issue.
I've deleted the Ubuntu VM to recover sisk space for some Solaris
Clustering stuff, so I can't immediately reproduce the problem.

I suspect my reported problem to be caused by some installation package
directives. Just my arm chair speculation, though.

-- Ram

**Comment by moritz** [comment] 2016-01-24 15:39
Where do the debian packages come from? I mean there should be `debian` directory with `control` and `rules` files and so on, but it's not in this repo.

i'm guessing the chown error message comes from the `debian/postinst` file, which on my server creates this snippet here:

    function fix_go_server_lib_ownership {
        go_owned_toplevel /var/lib/go-server
        go_owned_toplevel /var/lib/go-server/**
        go_owned /var/lib/go-server/db/config.git
        go_owned /var/lib/go-server/db/deltas
        go_owned /var/lib/go-server/db/h2deltas
        go_owned /var/lib/go-server/db/h2db
        go_owned /var/lib/go-server/db/command_repository/default
    }

The `**` looks like a zsh feature to me, but the postinst script is executed
by bash.

Since this looks like it's supposed to recursively own all files in
`/var/lib/go-server`, one could just pass the `-R` or `--recursive` flag to
`chown` in function `go_owned_toplevel`.

**Comment by arvindsv** [comment] 2016-01-25 12:14
@moritz: I don't think it is supposed to recursively own files. If that was the case, [`go_owned`](https://github.com/gocd/gocd/blob/75f21bf7bebddc15fadf65651b709dbb4961ddbe/installers/shared/shared_post.sh#L25-L32) would have been used.

The problem with trying to do a `chown -R` was that it caused problems with huge artifact directories, where it would unnecessarily hold up upgrades, doing nothing, essentially.

I agree with you that the `**` should probably be replaced. I think it should be replaced with a `*`. However, having that `**`, even if it fails, shouldn't be failing the installation. I've seen it succeed.

**Comment by richbos** [comment] 2016-04-06 15:00
Hi, I am having somewhat similar issues to those as detailed here when trying to install to Ubuntu 16.04 (64 bit), with the following error post install (using either .deb package or apt/repo) -

```
chown: cannot access '/var/lib/go-server/**': No such file or directory
Installation of Go Server completed.
Job for go-server.service failed because the control process exited with error code. See "systemctl status go-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript go-server, action "start" failed.
```

Checking "systemctl status go-server.service" as advised shows - 

```
Apr 06 15:42:55 ubuntuN40 go-server[9659]: Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /usr/share/go-server/agent-launcher.jar (Permission denied)
Apr 06 15:42:55 ubuntuN40 go-server[9659]: Error trying to validate file cruise.war: java.io.FileNotFoundException: /usr/share/go-server/cruise.war (Permission denied)
Apr 06 15:42:55 ubuntuN40 go-server[9659]: Error trying to validate file historical_jars/h2-1.2.127.jar: java.io.FileNotFoundException: /usr/share/go-server/historical_jars/h2-1.2.127.jar (No su
Apr 06 15:42:55 ubuntuN40 go-server[9659]: /usr/share/go-server/db/h2deltas/2_create_indexes.sql (No such file or directory)
Apr 06 15:42:55 ubuntuN40 go-server[9659]: /usr/share/go-server/db/h2db/cruise.h2.db (No such file or directory)
Apr 06 15:43:25 ubuntuN40 go-server[9659]: Error starting Go Server.
Apr 06 15:43:25 ubuntuN40 systemd[1]: go-server.service: Control process exited, code=exited status=255
Apr 06 15:43:25 ubuntuN40 systemd[1]: Failed to start LSB: Go Server.
Apr 06 15:43:25 ubuntuN40 systemd[1]: go-server.service: Unit entered failed state.
Apr 06 15:43:25 ubuntuN40 systemd[1]: go-server.service: Failed with result 'exit-code'.
```

I have a couple of thoughts myself (which may or may not be way off so apologies if so) - 

1. I'm wondering if I need to create a systemd go-server.service file? Or should it be ok from /etc/init.d/go-server (as other services seem to be).
2. Should permissions on /usr/share/go-server be root:root or go:go?
3. Might it be a java error somewhere/somehow?

Any pointers most appreciated. Berations for using Ubuntu 16.04 accepted.

**Comment by richbos** [comment] 2016-04-06 16:15
Hi, just to update. I tried the experimental release (16.4.0-3187) and aside from the `chown: cannot access '/var/lib/go-server/**': No such file or directory` error (which seems to be a red herring) it went in ok and starts fine.

**Comment by statwonk** [comment] 2017-03-26 06:00
Any update on this? I'd like to give GoCD a whirl on Ubuntu 16.04 or really any version (tried 14.04, too).

**Comment by ketan** [comment] 2017-03-26 06:14
@statwonk — you've probably got openjdk 9 installed on ubuntu 16.04. Please downgrade to openjdk 8 instead.

**Comment by ketan** [comment] 2017-03-26 06:15
Closing this issue, since the original issue `chown: cannot access '/var/lib/go-server/**': No such file or directory` has since been resolved.

**Closed by ketan** 2017-03-26 06:15 UTC

**Comment by statwonk** [comment] 2017-03-26 15:25
Thanks!
