### ISSUE TITLE
Display active vs queued stages as different colors

### ISSUE THREAD

**Issue by dmag** [gocd/gocd#1413] opened 2015-08-04 18:18 UTC
When looking at the pipeline overview, a yellow bar in a pipeline means two radically different things: 1) The job has been picked up and is _actively_ being worked on by an agent, 2) The job is merely queued and nobody is working on your job. For example, today I waited 5m for my job to complete. When it didn't, I clicked to investigate and found out that the job hadn't even started because there were no agents running. That's frustrating, since it's so easy to prevent.

I propose a simple solution: display those two states as different colors. For example, ice blue for "stage is merely queued, not picked up yet" and yellow for "stage is actively being worked on by an agent".

Benefits:
- **Makes agent capacity problems easy to see**. A screen full of yellow would mean you have plenty of agents, and a screen full of blue would mean you have too few agents (or a resource bottleneck for some types of agents).  As far as I can tell, there is no way to see capacity problems today.
- **Gives a rough visual indication of queue**: The more blue on the screen, the longer it is you are likely to to wait. (This could be a quick way to address part of Issue #14 ).

**Comment by arvindsv** [comment] 2016-06-04 13:46
Agree. But, closing as a duplicate of #2173 (I know it's a newer issue, but it has a better chance of a more recent conversation happening on it).

**Closed by arvindsv** 2016-06-04 13:46 UTC
