### ISSUE TITLE
Unable to run a process in background using a shell-script in GO

### ISSUE THREAD

**Issue by jaideeprana45** [gocd/gocd#597] opened 2014-09-29 09:04 UTC
When I execute a shell script, which has code to run a process in background, then the go-pipeline gets struck. This happens because the process runs in foreground instead of background.

Here is the custom code in my start-server.sh
java -jar target/platform-1.0-SNAPSHOT.jar server developer.xml > server.log &

When I run this script via terminal and it works fine: sh start-server.sh

However, it gets struck when I configure the same command in GO

**Comment by thenano** [comment] 2015-05-22 09:13
Does anyone have a solution for this? I'm having the same problem: task gets stuck.

**Comment by zabil** [comment] 2015-05-22 10:58
have you tried bash -c?

For e.g
On your custom task use
  bash

and for args 
  -c
  python
  -m
  SimpleHTTPServer
  8000

**Comment by zabil** [comment] 2015-05-22 11:30
This works for me

In on the custom command for the task
set "bash" as the command

For arguments:
-c
python -m SimpleHTTPServer 8000 > /dev/null 2>&1 &

**Comment by thenano** [comment] 2015-05-25 07:50
Hi Zabil, thanks for your reply.

I've found a couple of interesting things:

If I change the order or the command, it hangs on the same task, for example if I run:
bundle exec rake server:stub 2>&1 > /dev/null &

it still keeps waiting for the task to finish. Any idea why?

Also, even though if I run the command with the order you suggested, and the task then finished, it seems that it kills my process as soon as the task finishes, because the stub server is no longer available for the next task. Again, any idea why?

Thanks for the help!

**Comment by thenano** [comment] 2015-05-25 08:15
Hi again :)

Sorry, there was a problem on my side that I can't exactly reproduce, but everything works fine now, so long as I put the "2>&1" last. So this works fine for me.

Thanks for the help!

**Comment by zabil** [comment] 2015-05-25 08:32
Cool,
 I hope @jaideeprana45 can use this too. 
 Closing up the issue.

**Closed by zabil** 2015-05-25 08:32 UTC

**Comment by jaideeprana45** [comment] 2015-05-26 05:10
Thanks everyone for the help.

**Comment by arvindsv** [comment] 2015-05-26 13:00
> If I change the order or the command, it hangs on the same task ...

There's actually a big difference between ```>blah 2>&1``` and ```2>&1 >blah```. See [this page](http://www.catonmat.net/blog/bash-one-liners-explained-part-three/) and search for "However be careful here!". As you can see, the latter doesn't close stderr at all, and that was probably why Go was waiting for the process to finish.

**Comment by thenano** [comment] 2015-05-27 07:36
Ah right. Thanks for the clarification. We could all do with your bash
super skills :)
