### ISSUE TITLE
HTTPS reverse proxy generates "ERR_TOO_MANY_REDIRECTS"

### ISSUE THREAD

**Issue by pejvan** [gocd/gocd#1432] opened 2015-08-11 15:30 UTC
I'm running an SSL reverse proxy in front of the Go instance, and everything works just fine, except the oauth configuration tab in the admin site at `/go/oauth/admin/clients` which generates too many redirects before failing in the browser.

I'm not sure whether it's related to #741 but i've checked all the tips there as well.

Here are the server details:

  param |  value
------------------ | ---------------------------
Go Server Version: | 15.2.0(2248-c1f90a6aa3192a) 
JVM version:       | 1.8.0_66-internal 
OS Information:    | Linux 3.19.0-18-generic 
Usable space in artifacts repository: | 131 GB 
Database schema version: | 1502001

**Comment by zabil** [comment] 2015-08-13 10:35
Can you share the section in your apache conf that configures this?

**Comment by ketan** [comment] 2015-08-13 10:47
@zabil - this is the same config as the one I pasted here(https://github.com/gocd/gocd/issues/741#issuecomment-106232088). Except that you change the `ProxyPass` and `ProxyPassReverse` to use port 8153. This error only seems to happen on `/go/oauth/*`, perhaps on the `/go/gadgets/*` url as well.

But I've not tested that since nobody has complained about it.

**Comment by ketan** [comment] 2015-08-13 10:48
@pejvan - I think this may be a duplicate of #1418. Could you check if this (https://github.com/gocd/gocd/issues/1418#issuecomment-130154159) resolve your problem?

**Comment by ketan** [comment] 2015-12-09 12:03
Closing as dup of #1418

**Closed** 2015-12-31 06:27 UTC
