### ISSUE TITLE
pipeline-repo-as-code health endpoint

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3910] opened 2017-10-04 05:50 UTC
##### Issue Type

- Feature proposal

##### Summary

I'd like to see a health check endpoint that shows the state of each config repo. Along with the following information (if possible):

- time when it was last updated
- any errors updating the repo (e.g. `"git pull" failed because ....`)
- any errors merging the pipeline config from a particular repo into the main pipeline config
- number of pipelines
- number of environments
- number of agents

**Comment by GaneshSPatil** [comment] 2018-10-26 06:42
Duplicate of: https://github.com/gocd/gocd/issues/5175

Closing this issue as https://github.com/gocd/gocd/issues/5175 is the epic story along with some discussion.

**Closed by GaneshSPatil** 2018-10-26 06:42 UTC
