### ISSUE TITLE
login form not escaping special characters

### ISSUE THREAD

**Issue by nskalis** [gocd/gocd#5317] opened 2018-10-24 11:02 UTC
##### Issue Type

- Bug Report

##### Summary

When the password field in the login form does not escape special characters.

##### Environment
Please see attachment

###### Basic environment details

* Go Version: `18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a).`
* JAVA Version: `1.8.0_191`
* OS: `Linux 3.10.0-862.11.6.el7.x86_64`

##### Steps to Reproduce

1. define a user in `password.properties` having a password with special characters, like `!` or `$$`
2. if the password contains `!` it has to be escaped by `\!`
3. if the password contains `$$` i do not know how to escape it
4.  etc.

##### Expected Results
As all webapps that at least i am working on, special characters should be escaped

##### Actual Results
user with a special character (as described above) not able to login

##### Possible Fix
Not all are technical users in order to escape their password, worse even if GoCD is LDAP integrated, forcing the user to change password because of 1 webapp would be "too much"

##### Log snippets

```
2018-10-24 12:12:51,969 ERROR [qtp961419791-30] PasswordFilePlugin:128 - [Authenticate] Failed to authenticate user: `xxx`
cd.go.authentication.passwordfile.exception.AuthenticationException: Unable to authenticate user, user not found or bad credentials
	at cd.go.authentication.passwordfile.Authenticator.authenticate(Authenticator.java:72)
```

**Comment by nskalis** [comment] 2018-10-24 11:03
[gocd-support.txt](https://github.com/gocd/gocd/files/2510183/gocd-support.txt)

**Comment by arvindsv** [comment] 2018-10-24 16:16
@nskalis I tried this and couldn't reproduce it. So, I'll close it for now. Happy to reopen it if needed.

Here's what I tried:

1. Password file contents:

    ```
    admin:$2y$05$14qyAvgIZ85nmMC3B2NB1ep7jEb33yWGzPgIuefaExDA5R93rhwgG
    operate:$2y$05$GA7r50jAex06zaGrl8RLgOw1s.oPwzAefIEwxhzlKMPmVSo4CSifm
    ```

2. Config:

    ```xml
    <security>
      <authConfigs>
        <authConfig id="id1" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>/path/to/password.properties</value>
          </property>
        </authConfig>
      </authConfigs>
    </security>
    ```

3. Log in using:

    - Password `!abc123` for user `admin`.
    - Password `$$abc123` for user `operate`.

**Closed by arvindsv** 2018-10-24 16:16 UTC

**Comment by nskalis** [comment] 2018-10-24 17:00
thanks! confirmed, i was generating pass with the python command, and escaping didn't work as i was expecting. once again thanks a lot.
