### ISSUE TITLE
API for plugin settings

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3402] opened 2017-04-17 06:26 UTC
##### Issue Type

- Feature proposal

##### Summary

Provide api that allows user to get, update, delete plugin settings through api

**Comment by varshavaradarajan** [comment] 2017-04-17 06:34
Closing it as a duplicate of https://github.com/gocd/gocd/issues/3354. If you have any particular representation or anything, put it up as a comment there?

**Closed by varshavaradarajan** 2017-04-17 06:34 UTC
