### ISSUE TITLE
GoCD 19.1.0 API: Error 500 when querying environment with secret variable

### ISSUE THREAD

**Issue by jlusiardi** [gocd/gocd#6642] opened 2019-07-18 09:58 UTC
##### Issue Type

Bug Report

##### Summary

The call `GET /go/api/admin/environments` fails with error 500 if there is at least one environment with a secret environment variable. This differs from #6128.

##### Environment

See https://gist.github.com/jlusiardi/c4cded47fb124ed1870833d8042d38df for complete environment.

###### Basic environment details

* Go Version: 19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4).
* JAVA Version: 1.8.0_191
* OS: Linux 4.19.0-5-amd64
* Browser vendor and version (if relevant): curl for the api

##### Steps to Reproduce

1. Create an Environment named TEST
2. `GET /go/api/admin/environments` should return a list of envs containing new one (if it fails, there is a secret environment variable somewhere)
3. `GET /go/api/admin/environments/TEST` should work as well
4. Add a secret env var to TEST
5. Repeat steps 2) and 3) and see the error 500

##### Expected Results
A valid JSON is returned containing the secret variables in encrypted form.

##### Actual Results
Error 500 is thrown

##### Log snippets

See https://gist.github.com/jlusiardi/7c812fd24f52589e17228173cbcb7fb6

**Comment by adityasood** [comment] 2019-07-18 12:25
@jlusiardi looks like a duplicate of https://github.com/gocd/gocd/issues/5807. Can you confirm if this is different?

**Comment by jlusiardi** [comment] 2019-07-18 12:39
@adityasood error message looks similar but there is not reference to secret variables in #5807. So i am not 100% sure

**Comment by adityasood** [comment] 2019-07-18 12:44
@jlusiardi one of the things mentioned in #5807 is also that there are environments defined in config repo (Pipeline as code). Do you have anything similar? Would it possible to add a gist of your config.xml to the issue for us to notice? Please ensure you omit any passwords in the gist.

**Comment by jlusiardi** [comment] 2019-07-18 12:50
@adityasood i will try to test with a newer version first. The config.xml is from my work environment so I would have to go through in very carefully...

**Comment by jlusiardi** [comment] 2019-07-19 07:06
@adityasood i tested with GoCD Server 19.2.0 and now I can use `GET /go/api/admin/environments/:NAME` to retrieve an environment, but encrypted vars show up as `"encrypted_value" : "****"`. This in 19.2.0 looks like #6128 to me.

**Comment by adityasood** [comment] 2019-07-19 07:27
@jlusiardi that issue was fixed in v19.3.0 through https://github.com/gocd/gocd/issues/5956. I will be closing this issue for now. However, please re-open it in case you still see any issue.

**Closed by adityasood** 2019-07-19 07:27 UTC

**Comment by jlusiardi** [comment] 2019-07-19 07:50
I agree with this!
