### ISSUE TITLE
feature: Add screen for managing git materials HEADs

### ISSUE THREAD

**Issue by woledzki** [gocd/gocd#1145] opened 2015-05-22 07:17 UTC
As a Admin,
I want to force update HEAD of git material,
So that when developer force pushes branch, I can update latest known hash of that git material.

**Comment by etiennetremel** [comment] 2016-02-02 15:09
+1

**Comment by arvindsv** [comment] 2016-06-04 13:15
Force push should be fixed as a part of release 16.5.0, by https://github.com/gocd/gocd/pull/2149. Also, this seems to be a duplicate of https://github.com/gocd/gocd/issues/985.

**Closed by arvindsv** 2016-06-04 13:15 UTC

**Comment by Stono** [comment] 2017-01-12 02:35
FYI this isn't fixed... did a force push today on 16.12.0.

```
22:18:35.974 [go] Job Started: 2017-01-11 22:18:35 UTC

22:18:35.974 [go] Start to prepare td.rabbitmq/135/build/1/build on gocd-agent-712248093-2bq5n [/var/lib/go-agent]
22:18:35.988 [go] Cleaning working directory "/var/lib/go-agent/pipelines/td.rabbitmq" since stage is configured to clean working directory
22:18:35.988 [go] Start to update materials.

22:18:35.988 [go] Start updating files at revision 595505af076ff596cbde297ec859908ce68a7489 from git@github.com:peopledata/td.rabbitmq.git
22:18:35.993 STDERR: Cloning into '/var/lib/go-agent/pipelines/td.rabbitmq'...
22:18:37.567 [GIT] Fetching changes
22:18:38.681 [GIT] Performing git gc
22:18:38.784 [GIT] Reset working directory pipelines/td.rabbitmq
22:18:38.784 [GIT] Cleaning all unversioned files in working copy
22:18:38.889 [GIT] Cleaning submodule configurations in .git/config
22:18:38.992 [GIT] Updating working copy to revision 595505af076ff596cbde297ec859908ce68a7489
22:18:38.995 STDERR: fatal: Could not parse object '595505af076ff596cbde297ec859908ce68a7489'.
22:18:39.096 git reset failed for [pipelines/td.rabbitmq]
22:18:39.130 [go] Job completed td.rabbitmq/135/build/1/build on gocd-agent-712248093-2bq5n [/var/lib/go-agent]
```

**Comment by ketan** [comment] 2017-01-12 04:28
What does `git branch --contains 595505af076ff596cbde297ec859908ce68a7489` have to say?

**Comment by scottbelden** [comment] 2017-03-08 15:02
@arvindsv Can you please explain how this is supposed to work? If I have a repo at commit A, push a commit B, and then force push back to A, I get the same problem as @Stono. Namely:

```
14:56:40.020 [go] Start updating files at revision 61521f8f2cf7c1e8d7ff9c7cb762df94c5f8d08e from https://...
14:56:40.034 STDERR: Cloning into '/var/lib/go-agent/pipelines/XXX'...
14:56:42.648 [GIT] Fetching changes
14:56:43.006 [GIT] Performing git gc
14:56:43.013 [GIT] Reset working directory pipelines/XXX
14:56:43.018 [GIT] Cleaning all unversioned files in working copy
14:56:43.132 [GIT] Cleaning submodule configurations in .git/config
14:56:43.239 [GIT] Updating working copy to revision 61521f8f2cf7c1e8d7ff9c7cb762df94c5f8d08e
14:56:43.250 STDERR: fatal: Could not parse object '61521f8f2cf7c1e8d7ff9c7cb762df94c5f8d08e'.
14:56:43.351 git reset failed for [pipelines/XXX]
14:56:43.554 [go] Job completed XXX/151/run/3/job on YYY [/var/lib/go-agent]
```

@ketan If I go on the go agent after this has happened and do your command, I get this:
```
go@YYY:/var/lib/go-agent/pipelines/XXX$ git branch --contains 61521f8f2cf7c1e8d7ff9c7cb762df94c5f8d08e
error: no such commit 61521f8f2cf7c1e8d7ff9c7cb762df94c5f8d08e
```

**Comment by matthias-k** [comment] 2018-10-25 22:45
And I just got the same problem in 18.10.0.

**Comment by PascalBourdier** [comment] 2019-01-11 08:38
Same problem with 18.12.0 again.

**Comment by antonmatsiuk** [comment] 2019-03-05 14:34
Just observed the same behaviour in 18.3.0. Described in https://github.com/gocd/gocd/issues/985
