### ISSUE TITLE
Unable to poll material when commit title contains leading spaces.

### ISSUE THREAD

**Issue by Meet116** [gocd/gocd#7845] opened 2020-03-11 14:18 UTC
##### Issue Type

- Bug  report

##### Summary

Whenever the pull request title contains  leading spaces gocd is unable to poll for the  latest material . Also in this case the error message miss leading. Instead of showing the error message in the commit title it shows error for the commit mesg.

* Go Version: 20.1.0
* JAVA Version: 13.0.1
* OS: Linux 16.04

The commit title (PR) in our case was "    WEB-XXXX  Feature "

For reference go-server logs:-

2020-03-11 13:32:54,756 WARN  [130@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:127 - [Material Update] Modification check failed for material: URL: https://username:******@github.com/projectName, Branch: develop
org.yaml.snakeyaml.scanner.ScannerException: while scanning an alias
 in 'string', line 102, column 5:
        * WEB-XXXX - add validating for ... 
        ^
expected alphabetic or numeric character, but found  (32)
 in 'string', line 102, column 6:
        * WEB-XXXX - add validating for  ... 
         ^
    at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1447)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAlias(ScannerImpl.java:918)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:366)
    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
    at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:201)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152)
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
    at com.thoughtworks.go.domain.materials.git.GitModificationParser.parse(GitModificationParser.java:34)
    at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:133)
    at com.thoughtworks.go.domain.materials.git.GitCommand.modificationsSince(GitCommand.java:116)
    at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:135)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:35)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:26)
    at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:128)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:56)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:157)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:149)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:108)
    at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:23)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$executeWithExceptionHandling$2(TransactionTemplate.java:43)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:40)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:105)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:64)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:32)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by arvindsv** [comment] 2020-03-11 14:27
@Meet116 Thank you. This is a duplicate of  https://github.com/gocd/gocd/issues/7709 and will be fixed in the upcoming release, 20.2.0 through https://github.com/gocd/gocd/pull/7838. So, I will close this.

The release should be out soon, probably early next week.

**Closed by arvindsv** 2020-03-11 14:27 UTC
