### ISSUE TITLE
Log4j errors thrown when running Go CD

### ISSUE THREAD

**Issue by fatmanmclone90** [gocd/gocd#2108] opened 2016-04-13 11:18 UTC
##### Issue Type

Bug Report
##### Summary

When running Go CD log4J Errors get thrown to console window, see snippets below.  Is this an error in the application or is there an issue with the environment / configuration?

I don't see any logs generated by Go CD, is this exception the cause for lack of logs?
##### Environment

```
=================
Config Statistics
=================

Valid Config.
Number of pipelines: 94
Number of agents: 2
Number of environments: 0
Number of unique materials: 46
Number of schedulable materials: 46
Security:
LDAP: false, Password: true
```
###### Basic environment details
- Go Version: `16.1.0`
- JAVA Version: `1.8.0_77`
- OS: `Windows Server 2012 R2 6.3`
  ###### Additional Environment Details
##### Steps to Reproduce

1) Start Go CD using default .\start-server.bat
##### Actual Results

Errors thrown to console relating to log4j, see snippets
##### Log snippets

```
log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assig
 a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [google.oauth.login [1]] whereas object of type
log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [WebApp
der=654845766@27082746].
log4j:ERROR Could not instantiate appender named "FileAppender".
log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assig
 a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [google.oauth.login [1]] whereas object of type
log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [WebApp
der=654845766@27082746].
log4j:ERROR Could not instantiate appender named "ShineFileAppender".
```

-->

**Comment by ketan** [comment] 2017-09-15 08:41
I'm going to close this bug as I'm unable to reproduce this anymore. If you are able to reproduce, let me know and I can re-open the bug.

**Closed by ketan** 2017-09-15 08:41 UTC
