### ISSUE TITLE
Get Pipeline API in Feeds doesn't honor pipeline name or pipeline ID

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4606] opened 2018-04-04 05:50 UTC
##### Issue Type
- Bug Report
##### Summary

The API documented [here](https://api.gocd.org/17.11.0/#get-pipeline) doesn't honor Pipeline name and there is no way for end user to know the pipeline_id

###### Basic environment details

* Go Version: 17.11.0
* JAVA Version: Java8
* OS: MacOS
* Browser vendor and version (if relevant): Google Chrome Version 64.0.

##### Steps to Reproduce

1. Create two pipelines foo and foo2.
2. Run the first pipeline foo twice
3. Run the second pipeline foo2 once
4. Run the first pipeline foo again
4. Use the curl command to see the results

##### Expected Results
The following curl command should return the 3 run of the pipeline foo

```
curl -k 'https://localhost:8154/go/api/pipelines/foo/3.xml' \
      -u 'username:password'

```
The following curl command should error out since there is no pipeline with the name "f"

```
curl -k 'https://localhost:8154/go/api/pipelines/f/3.xml' \
      -u 'username:password'

```

##### Actual Results
Instead, both the above commands returns the pipeline which was run third (foo2)

##### Possible Fix
The API should honor the pipeline name and use the pipeline counter (as pipeline ID)

<img width="1440" alt="screen shot 2018-04-04 at 11 04 48" src="https://user-images.githubusercontent.com/17826464/38290505-27e221fa-37f9-11e8-8082-2e8f42bcbbbc.png">
<img width="718" alt="screen shot 2018-04-04 at 11 19 31" src="https://user-images.githubusercontent.com/17826464/38290696-2229822a-37fa-11e8-9800-8afb546dd628.png">
<img width="718" alt="screen shot 2018-04-04 at 11 19 15" src="https://user-images.githubusercontent.com/17826464/38290697-2254a64e-37fa-11e8-936f-e7a713228e77.png">

**Comment by jyotisingh** [comment] 2018-04-04 05:58
That's true for all xml based APIs. 
What kind of information are you looking for in this API?
Does https://api.gocd.org/current/#get-pipeline-instance not have the required info?

**Comment by adityasood** [comment] 2018-04-04 06:42
@jyotisingh the https://api.gocd.org/current/#get-pipeline-instance has the required info. Since the XML based API is documented, opened this bug as a placeholder for the errors faced.

**Comment by jyotisingh** [comment] 2018-04-04 13:49
@adityasood - Just to clarify, this is not a bug. This has been the implementation forever. Its a limitation for someone trying to consume this xml based API by itself hence we came up with https://api.gocd.org/current/#get-pipeline-instance. Can you point out the kind of information a user might look for from this API which might not be available in the one we currently have/promote?

If a user really wants to consume the Feeds set of APIs (https://api.gocd.org/current/#get-pipeline in this case), then the starting point always needs to be https://api.gocd.org/current/#get-all-pipelines. This was a pain and another reason for building the new json based API, btw, it has been around for a few years so it's not really new.

Closing this for now, since we do not intend to fix the old feeds api for pipeline instance given there is a feature-complete (in our view) and versioned replacement for the same. Feel free to reopen if you think  the new API has some data missing.

**Closed by jyotisingh** 2018-04-04 13:49 UTC
