### ISSUE TITLE
Cleanup of old pipelines in agent work directory

### ISSUE THREAD

**Issue by hanej** [gocd/gocd#2146] opened 2016-04-28 17:21 UTC
##### Issue Type

- Feature enhancement
##### Summary

The existing cleanup of work directory for agents only works when a new job is about to be executed.  After the job is done executing the artifacts remain on the file system.  When there are multiple agents per server across multiple servers that can handle the same type of resources, these files build up and waste an enormous amount of space.
###### Basic environment details

- Go Version: `16.3.0`
- JAVA Version: `1.7.0_75`
- OS: `Linux 2.6.32-504.el6.x86_64`
##### Steps to Reproduce

1. Have multiple agents with the same resources tagged to each one
2. Run the same build multiple times across those pools of agents
3. Calculate the amount of duplicated space that one build uses across all agents
##### Possible Fix

The clean working directory should clean after the job has run or provide another option to do this function.

**Comment by heathsnow** [comment] 2017-08-28 17:11
+1

I'm currently writing a cron job to run on the agents to delete the pipelines directory on each agent.  It would be nice to have this built into GoCD.

**Comment by jreast** [comment] 2017-09-08 09:00
Potential duplicate of #2070

**Closed** 2017-09-08 09:07 UTC
