### ISSUE TITLE
The entirety of JUnit XML files is skipped if they are minified

### ISSUE THREAD

**Issue by underyx** [gocd/gocd#1132] opened 2015-05-15 13:39 UTC
I'm using py.test and its built-in JUnit XML generator to make reports of my tests. Go.cd always fails to display any of the contents, logging this:

```
13:16:44.907 Unable to publish test properties. Error was javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The element type "all-results" must be terminated by the matching end-tag "</all-results>".
13:16:44.912 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.913 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.914 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
13:16:44.915 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```

Now, bear with me here, cause I have zero knowledge of Java, but skimming through the source I think the issue is that the py.test JUnit files have no newlines in them, so [this line](https://github.com/gocd/gocd/blob/ed4536974c8e08d996ca3c8f8daf20d830696fad/config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java#L158) skips the complete file, with its 200 test cases. ~~If that's not the problem, please let me know and I'll edit the title of this issue.~~ _Edit:_ I tried reformatting the same XML file and it works now. This means that there's a workaround:
# Workaround
1. Install the `xmllib2-utils` package on your agents
2. Change your py.test config to output to `junit.min.xml` instead of `junit.xml`
3. Add the following step to the end of the pipeline:

``` xml
<exec command="/bin/bash">
  <arg>-c</arg>
  <arg>xmllint --format junit.min.xml > junit.xml</arg>
  <runif status="passed" />
</exec>
```

**Comment by srinivasupadhya** [comment] 2015-05-16 05:27
can you post sample XML file so someone can reproduce the issue?

**Comment by underyx** [comment] 2015-05-19 09:41
Sure, something like this:

```xml
<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="2" time="0.001"><testcase classname="test.test_api_app" name="test_get_context_from_headers_generic[header_dict0-expected_diff0]" time="0.003357410430908203"/><testcase classname="test.test_api_app" name="test_get_context_from_headers_generic[header_dict1-expected_diff1]" time="0.00024437904357910156"/></testsuite>
```

**Comment by ketan** [comment] 2015-12-11 04:39
@rajiesh - reopening for you to look at

**Comment by rajiesh** [comment] 2015-12-14 14:03
verified it on 15.3.0-2753(7aa885fe5c2d71de7544ed776f2c6e16ccc9a79a) and is working as expected.

**Comment by underyx** [comment] 2015-12-14 15:38
Yay :tada:

**Comment by arvindsv** [comment] 2015-12-23 19:33
Re-opening again. Causes issues with big (say 12MB) XML files.

```
2015-12-23 15:58:21,169 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [build-windows/632/build-server-windows/2/server-split-ru\
nInstance-6/140899]
2015-12-23 15:58:21,185 [loopThread] ERROR springframework.scheduling.timer.MethodInvokingTimerTaskFactoryBean:68 - Invocation of method 'loop' on target class [class com.though\
tworks.go.agent.AgentController] failed
java.lang.OutOfMemoryError: Java heap space
  at com.sun.org.apache.xerces.internal.util.XMLStringBuffer.append(XMLStringBuffer.java:208)
  at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(XMLEntityScanner.java:1370)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1654)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3020)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
  at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
  at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
  at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
  at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:88)
  at com.thoughtworks.go.domain.UnitTestReportGenerator.pumpFileContent(UnitTestReportGenerator.java:158)
  at com.thoughtworks.go.domain.UnitTestReportGenerator.pumpFileContentIfValid(UnitTestReportGenerator.java:152)
  at com.thoughtworks.go.domain.UnitTestReportGenerator.merge(UnitTestReportGenerator.java:142)
  at com.thoughtworks.go.domain.UnitTestReportGenerator.mergeAllTestResultToSingleFile(UnitTestReportGenerator.java:112)
  at com.thoughtworks.go.domain.UnitTestReportGenerator.generate(UnitTestReportGenerator.java:63)
  at com.thoughtworks.go.config.TestArtifactPlan.mergeAndUploadTestResult(TestArtifactPlan.java:101)
  at com.thoughtworks.go.config.TestArtifactPlan.publish(TestArtifactPlan.java:66)
  at com.thoughtworks.go.domain.DefaultJobPlan.publishArtifacts(DefaultJobPlan.java:105)
  at com.thoughtworks.go.remote.work.BuildWork.completeJob(BuildWork.java:198)
  at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:146)
  at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
  at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
  at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
  at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
  at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by darioblanco** [comment] 2016-07-07 12:09
I have the same problem with go-server 16.6.0-3590, for the very same case. The issue is still there.

```
06:30:23.178 Unable to publish test properties. Error was javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The element type "all-results" must be terminated by the matching end-tag "</all-results>".
```

The xml file is generated by py-test, and is one single line indeed.

After running @underyx solution with `xmllint --format -o junit-pytest.xml junit-pytest.xml` as another task command (will rewrite that file), I could get rid of the error. However, it will only show test results in the Tests tab from the job view, when I go into the Tests tab from the stage view, I get a `There are tests configured in this stage but could not compute results.`. So basically two problems in one.

**Comment by kmugrage** [comment] 2016-08-09 21:12
I'm seeing this with 16.7.0 (3819-b0b9921bdea58101121cc181d697355177d2f197)

      - unit_test:
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: py.test
                    arguments:
                      - --junitxml
                      - testoutput.xml
                      - "./unit_test/python_test.py"
              artifacts:
                - test:
                    source: testoutput.xml

Contents of the XML

```
<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="1" tests="2" time="0.018"><testcase classname="unit_test.python_test.SimpleTest" name="test_fail" time="0.000195026397705"><failure message="test failure">self = &lt;python_test.SimpleTest testMethod=test_fail&gt;

    def test_fail(self):
&gt;       self.assertEqual(11, 7 + 3)
E       AssertionError: 11 != 10

unit_test/python_test.py:18: AssertionError</failure></testcase><testcase classname="unit_test.python_test.SimpleTest" name="test_pass" time="7.41481781006e-05"/><testcase classname="unit_test.python_test.SimpleTest" name="test_skipped" time="9.79900360107e-05"><skipped message="demonstrating skipping" type="pytest.skip">/usr/lib/python2.7/dist-packages/_pytest/unittest.py:113: Skipped: demonstrating skipping</skipped></testcase></testsuite>
```

Error in GoCD

```
19:39:59.343 [go] Uploading artifacts from /var/lib/go-agent/pipelines/Application/testoutput.xml to [defaultRoot]
19:39:59.357 Unable to publish test properties. Error was javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The element type "all-results" must be terminated by the matching end-tag "</all-results>".
19:39:59.358 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
19:39:59.359 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
19:39:59.360 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
19:39:59.360 Could not publish property org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```

**Comment by kmugrage** [comment] 2016-08-09 21:31
Echoing @darioblanco - adding xmllint works for the job but not at the stage level

**Comment by bjorn-spire** [comment] 2017-09-25 11:09
and seeing the same problem with 17.10.0, running the xml file through `xmllint --format` allowed it to get picked up by Go. :)

**Comment by ketan** [comment] 2018-02-07 11:29
Closing as dup of #983

**Closed by ketan** 2018-02-07 11:29 UTC
Labels: [stream] other
