### ISSUE TITLE
Wrong git revision environment variable

### ISSUE THREAD

**Issue by aaujon** [gocd/gocd#1036] opened 2015-04-16 13:21 UTC
Using a pipeline many several git materials, the environment variables GO_FROM_REVISION_MATERIAL_NAME and GO_TO_REVISION_MATERIAL_NAME are always set to last commit hash.
There is this message in log : 
[go] Start updating MATERIAL at revision 77e17f6cb80480bb4623bff7d74d818be61895bc from URL
[GIT] Cleaning all unversioned files in working copy
[GIT] Cleaning submodule configurations in .git/config
[GIT] Fetching changes
ERROR: From URL
ERROR:    b9cb6b6..77e17f6  BRANCH    -> origin/BRANCH
[GIT] Performing git gc
[GIT] Updating working copy to revision 77e17f6cb80480bb4623bff7d74d818be61895bc
HEAD is now at 77e17f6 encore test ic 2
[GIT] Removing modified files in submodules
[GIT] Cleaning all unversioned files in working copy

We can see that material was at b9.. and is not at 77.. but both variable are set to 77..

We are using Go 14.2.0(377-d8a2866d6af85e)

**Comment by arvindsv** [comment] 2015-04-17 13:25
After it says "Updating working copy to revision 77e17f6cb80480bb4623bff7d74d818be61895bc", doing a "git log -n 1" in the first task, should show the 77e17f6cb80480bb4623bff7d74d818be61895bc commit. Go has tried to update to 77e17f6cb80480bb4623bff7d74d818be61895bc. Are you saying that's not happened?

Can you reproduce this with a small config and a public github repo, so that I can take a look?

**Comment by ksahin** [comment] 2015-04-17 13:52
I'm going to explain the problem again : 
The revision was  b9cb6b6.. before Go did the pull, and 77e17f6... after
So the environnement variable GO_FROM_REVISION_MATERIAL_NAME shoud be b9cb6b6...
and GO_TO_REVISION_MATERIAL_NAME shoud be 77e17f6... right ? 

In our case both GO_FROM_REVISION_MATERIAL_NAME and GO_TO_REVISION_MATERIAL_NAME are set to 77e17f6... 

Furthermore, git shows an error ( "ERROR: From URL ERROR: b9cb6b6..77e17f6 BRANCH -> origin/BRANCH" ) but the pull did works. 

Thank you

**Comment by arvindsv** [comment] 2015-04-17 14:11
The FROM version and the TO version should correspond to the commits which caused this build to happen. Not the previous revision in this agent. Let me try to explain differently:

```
Time T1: Commit C1: Agent 1 starts a build (using C1).
Time T2: Commit C2: Agent 2 starts a build (using C2).
Time T3: Commit C3: Agent 1 and 2 are busy. Wait.
Time T4: Commit C4: Agent 1 and 2 are busy. Wait.
Time T5: Commit C5: Agent 1 and 2 are busy. Wait.
Time T6: Agent 1 finishes.
Time T7: Agent 2 finishes.
Time T8: Agent 1 picks up C4. Server sets FROM to C3 and TO to C5. [Not C1 or C2 and C5]
```

This happens because the server is specifying that these are the commits that caused this build to happen. It doesn't know what the previous build left the state of the agent at, and doesn't care.

The ERROR bit happens because git outputs that on standard error, not standard output.

I'm closing this for now, since I think it is doing what it is meant to. Can always reopen it.

**Closed by arvindsv** 2015-04-17 14:11 UTC
