### ISSUE TITLE
Support for forward proxy between agent & server

### ISSUE THREAD

**Issue by mikhailadvani** [gocd/gocd#3365] opened 2017-04-06 10:04 UTC
##### Issue Type

- Feature proposal

##### Summary

When agent and server exist in different networks, a proxy might be valuable/required in certain environments
1. Multiple pipelines(and therefore agents) require the same build artifact and caching the artifact in the proxy would reduce the fetchartifact execution time
2. The network of the agent(s) can make requests outside only through proxy

##### Steps to Reproduce

Set JVM proxy parameters in the agent start script (viz. -Dhttp.proxyHost, -Dhttp.proxyPort, etc.)

##### Expected Results

Agent should be able to communicate with Go server and execute jobs

##### Actual Results

Agent fails to schedule jobs getting a 403 Access Denied error

**Comment by arvindsv** [comment] 2017-04-06 16:09
Hello. Closing this as a duplicate of #2731.

**Closed by arvindsv** 2017-04-06 16:09 UTC
