### ISSUE TITLE
Official package fails to install on redhat

### ISSUE THREAD

**Issue by venkat0100** [gocd/gocd#1833] opened 2016-01-24 08:16 UTC
Loaded plugins: langpacks, product-id, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package go-server.noarch 0:16.1.0-2855 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package            Arch            Version                Repository      Size
================================================================================
Installing:
 go-server          noarch          16.1.0-2855            go-cd          134 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 134 M
Installed size: 134 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
'Go Server' installation will now use group 'go'
'Go Server' installation will now use user 'go'
  Installing : go-server-16.1.0-2855.noarch                                 1/1 
Found Java /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75-2.5.4.7.el7_1.x86_64/jre in PATH, using it.
Installation of Go Server completed.
using default settings from /etc/default/go-server
Error starting Go Server.
warning: %posttrans(go-server-16.1.0-2855.noarch) scriptlet failed, exit status 255
Non-fatal POSTTRANS scriptlet failure in rpm package go-server-16.1.0-2855.noarch
  Verifying  : go-server-16.1.0-2855.noarch                                 1/1 

Installed:
  go-server.noarch 0:16.1.0-2855                                                

Complete!
####################### disabling SELINUX ###############################
$getenforce
Disabled

**Comment by arvindsv** [comment] 2016-01-25 12:20
I've tried that it works on a vanilla fedora box. It probably has something to do with [selinux](https://github.com/gocd/gocd/issues/1833). Can you take a look? If not, can you please provide more information about the failure? Maybe running rpm with `-vv`?

**Comment by venkat0100** [comment] 2016-01-27 02:39
even it worked fine on fedora VM... i dont know what is the issue with REDHAT. ya sure i will run with in verbose mode and send you the complete LOGS. thanks for the response

**Comment by arvindsv** [comment] 2016-01-28 12:29
@venkat0100: This could be a duplicate of https://github.com/gocd/gocd/issues/1467. I'll close this issue for now, so that it doesn't distract from others while waiting. I can reopen it when you come back with more information.

Please disable selinux and try, as well. If it succeeds, then it's probably an selinux problem.

**Closed by arvindsv** 2016-01-28 12:29 UTC
Labels: bug, installers
