### ISSUE TITLE
Allow pipelines without material

### ISSUE THREAD

**Issue by NachbarsLumpi** [gocd/gocd#448] opened 2014-08-22 06:36 UTC
That would allow one to create a pipeline that has to be triggered manually, which can be useful if one wants to automate some initialization/setup that has to be done on agents but should be run only when a user wants it to be run.

**Comment by mingfang** [comment] 2015-01-09 03:49
+1

**Comment by praveenpatidar007** [comment] 2015-05-05 02:04
+1

**Comment by jmassara** [comment] 2015-08-13 22:28
+1 Any consideration for this request? It's fairly old...

**Comment by etiennetremel** [comment] 2016-01-28 10:07
+1

**Comment by virtuald** [comment] 2016-02-08 18:50
+1

**Comment by baspeti** [comment] 2016-02-25 10:09
+1

**Comment by selimekizoglu** [comment] 2016-05-10 11:10
+1

**Comment by arvindsv** [comment] 2016-06-04 13:02
Closing as a duplicate of newer issue #876.

**Closed by arvindsv** 2016-06-04 13:02 UTC
