### ISSUE TITLE
Git history rewrite causing errors

### ISSUE THREAD

**Issue by matt-richardson** [gocd/gocd#985] opened 2015-03-27 11:49 UTC
(Re-raising here due to no response on the [mailing list](https://groups.google.com/d/topic/go-cd/tgAZ6YFIaB0/discussion))

We are facing an error where GoCD cant handle a git repo that has had its history re-written.

(Why would we do that? We are migrating from gitolite to github, and removing files larger than 100meg, which is why we've had to re-write history.)

```
Modification check failed for material: URL: user@url:reponame, Branch: master [Mar-24 12:06:32]
Error performing command: --- Command --- git log --date=iso --pretty=medium 2341bcde2f0edfcfc51b806d1b1b0f5be835479e.. --- Environment --- {} --- INPUT ---- --OUTPUT --- --- ERROR --- ERROR: fatal: Invalid revision range 2341bcde2f0edfcfc51b806d1b1b0f5be835479e..HEAD ---
```

Go seems to store the latest commit in the database, and the rewrite has changed the history so that that commit no longer exists.

The trick of adding a '/' on the end isn't working - it just shows an error:

```
Repository user@url:repo/ not found! : Error performing command: --- Command --- git ls-remote user@url:repo/ --- Environment --- {} --- INPUT ---- --OUTPUT --- --- ERROR --- ERROR: FATAL: 'repo/' ends with a '/' ERROR: fatal: The remote end hung up unexpectedly ---
```

I've searched the flyweight directories, and weirdly, it doesn't appear to have a local copy of this repo.

Any suggestions on how we can fix? Does deleting the material delete it from the database?

**Comment by srinivasupadhya** [comment] 2015-03-27 12:22
You deleted history but retained `url`? Can you by any chance create an alternate hostname or something. eg: `currenthost:currentport` to `newhost:newport`? Its just something to make Go treat it as a new repository. The `/` trick should have worked though.

Currently there is no way to make Go forget the history. And it makes sense because if a pipeline has already run with a revision & suddenly the revision is deleted from material (in db) its going to cause a lot of anomaly.

**Comment by srinivasupadhya** [comment] 2015-03-27 12:24
Also, Flyweights do not have anything to do with maintaining the history of a material.

**Comment by matt-richardson** [comment] 2015-03-29 17:46
Yeah, the url is the same. I could setup a separate url for the git server, but that really feels like a horrible hack.

Can we turn this into a feature request to deal with this situation, as its actually a recommend approach for GitHub imports (https://help.github.com/articles/working-with-large-files/#push-warnings-and-limits).

For now, we are (co-incidentally) going to move the entire git server to a new url, so the problem will go away for us.

**Comment by matt-richardson** [comment] 2015-04-01 10:27
We have re-written history in about 15 repositories, but this has only occurred on 2 of them.

Any idea why this could be the case?

**Comment by arvindsv** [comment] 2015-04-06 20:27
Go does the equivalent of ```git log old-revision-previous-seen-in-db..HEAD```. My guess is that the old revision stayed in git's reflog, or at least in the tree, for a while. So, this works for a while. After a certain period of time (30 days is the default, I think), it goes away from reflog, and a ```git gc``` which Go does as a part of looking for new commits, will remove that commit.

This is conjecture. I've seen this issue happen, but I haven't been able to verify that this is the cause of it not being consistently reproducible.

I think the solution should be a special way of telling Go to ignore the last known commit, and treat the repository as a new one (to just use the latest commit). History rewrite is usually frowned upon and called "mildly antisocial" in the git FAQ (though I understand why you had to do it). :)

**Comment by blatinville** [comment] 2015-05-28 13:29
I was about to open an issue when I finally found this similar issue.

I amend a commit on a git branch and forced push the branch.
The polling did not work.
Now when we launch the pipeline, gocd stays on the commit before amend.

On development branches, it is very common to rebase a branch to master, to squash commits ...
The last build commit may become unavailable.

The proposition to treat this **particular branch** of this repository as a new branch should be fine

**Comment by arvindsv** [comment] 2015-07-08 16:10
I think this case should be treated as an exceptional case than the norm. Deciding that it is an exceptional case can help decide how easily accessible the "fix" should be. I think Go should show a warning as it does today, saying something along the lines of "the commit is not available". This message comes from git itself.

Once that shows up, an *admin* should be able to go to a page which lists all the materials, find that material (how?) and be able to say that the next time this material is checked, its old commits should be ignored, and it should be treated as a new material. This means that Go should be able to not use `git log commit..HEAD`, but use `git log -n 1 HEAD` instead and move on from there.

Need to check whether compare pipeline works, when that happens.

**Comment by arvindsv** [comment] 2015-07-08 16:11
If everyone (including @jyotisingh) agrees, I can work on it.

**Comment by ketan** [comment] 2015-07-08 16:16
I don't think a force push is an exception. I regularly like to force push
to a remote so that the server picks up the changes and tests them out.

Also, when a force push does happen. The admin will have no other option
than to say, "yeah that looks OK". When there is no choice that needs to be
provided, why involve the admin at all?

**Comment by arvindsv** [comment] 2015-07-08 16:44
It seems wrong to just say: "Oh, I didn't find the commit you used previously. So, I'll just pick the latest and roll with it." without involving the user (if not an admin).

But, I see your point about the lack of choice. Ok, I'll wait to hear from others too. If everyone feels that way, then I'll probably put that behavior behind an option, and we can decide whether to enable it by default.

I can see that, for certain materials it might make sense (feature branches, pull requests, etc). For most other materials, the admins or users might want to know, was what I was thinking. But, it might not be Go's place to tell the user that.

**Comment by pepoirot** [comment] 2015-08-26 02:13
> My guess is that the old revision stayed in git's reflog, or at least in the tree, for a while. So, this works for a while. After a certain period of time (30 days is the default, I think), it goes away from reflog, and a git gc which Go does as a part of looking for new commits, will remove that commit.

To confirm, the setting for that is `gc.reflogExpireUnreachable`, which is by default [30 days](https://git-scm.com/docs/git-config). However it might be set to a more aggressive value on that particular server or particular ref. (`gc.reflogExpire` is 90 days, but it only affects still reachable commits).

**Comment by jeremyong** [comment] 2015-12-18 00:56
Not respecting the material repo/branch specified as a material is, in my opinion a bug. If the branch is force pushed, *NOT* reflecting the state of the branch is actually a serious problem, and can cause undue headache if an issue that gets introduced is not surfaced immediately. A manual retrigger of a build should reflect the actual state of the materials in my opinion.

**Comment by jeremyong** [comment] 2015-12-18 00:59
@arvindsv Right after the quote you issued regarding the Git FAQ describing rewriting history as "mildly antisocial," it states "Nonetheless, it is often appropriate."

**Comment by framegrace** [comment] 2015-12-29 16:42
I'm using the git.fb plugin, and same issue.
In our case, I can't even start using the repo. It starts on the forced point, and can't see any change more from this commit.
Anything I can do? 
Name/host change trick doesn't work.... it re-creates the repo, but obviously, go-cd does the same, and it gets stuck at that point in time.

**Comment by herby** [comment] 2016-02-28 22:16
Pls fix this. Thank you very much.

**Comment by framegrace** [comment] 2016-02-29 12:04
I managed to fix the repo by modifying the h2db and making the last commit there to be one after the force commit.
Don't ask for step by step instructions, I just fiddled too much there to be able to know exactly how in worked, but it did at the end.

**Comment by virtuald** [comment] 2016-02-29 20:10
This seems broken, particularly for the use case of testing feature branches.

**Comment by jyotisingh** [comment] 2016-03-01 09:10
> I managed to fix the repo by modifying the h2db and making the last commit there to be one after the force commit.
Don't ask for step by step instructions, I just fiddled too much there to be able to know exactly how in worked, but it did at the end.

Thats a little scary. If you know that only the right table was edited, then its fine. H2 database corruption is one thing I would advice you to stay away from. Not very pretty.

**Comment by framegrace** [comment] 2016-03-01 09:16
Yep, not very pretty... But this was blocking all our workflow. Was that or ditch go-cd entirely.

**Comment by jyotisingh** [comment] 2016-03-01 10:35
Like I said, if you know what you are doing, then its fine. 
Just to be clear, I was worried about this part
> I just fiddled too much there to be able to know exactly how in worked

But whatever suits you.

**Comment by framegrace** [comment] 2016-03-01 10:51
Maybe fiddling wasn't the most accurate word. I took backups an did all the modifications on a stopped server after carefully following the schema. I meant that it took me a lot of trials to got it right and didn't took note of the steps.
(h2db doesn't even let you handle an in use DB, so, that's a nice added safety measure)

**Comment by framegrace** [comment] 2016-03-10 16:46
It happened again this week. And looks like i solved it using a lot simpler method.

* The material is locked on a commit due to a history rewrite. DO some pipeline runs until you are sure is locked on that change.
* Identify the flyweight subdirectory for that material. (I did it just doing a "git remote -v" on each dir until I found it)
* Stop go server
* Do a backup of the flyweight directory
* Remove the flyweight subdir corresponding to your material.
* Start go server.
* The material must be pointing to the latest commit.

It worked for me for a couple of materials. Try at your own risk.

**Comment by scottbelden** [comment] 2016-03-17 12:42
It's quite confusing to have gocd building a commit that doesn't exist anymore (in the case of force pushing a repo back a commit). I understand a revert it technically the nicer way to do things, but if I accidentally push a commit I would rather just do a quick reset back one and force push.

I like this:
> I think the solution should be a special way of telling Go to ignore the last known commit, and treat the repository as a new one (to just use the latest commit).

**Comment by jguilloux71** [comment] 2016-04-22 13:58
I think we have the same issue here: https://github.com/gocd/gocd/issues/2110

**Comment by Chcap** [comment] 2016-04-23 11:38
I do not understand why GoCD is keeping track of the commit instead of the branch. A branch is indicated in the pipeline configuration, not a commit. Why does GoCD needs this commit ?

Git is a fantastic tool, as it allows you to use it in many ways to have a workflow which fits you (as tools like SVN is way way more directive). When working on a branch, you can merge it and have a merge commit, or you can rebase it first with your destination branch and then have a merge in fast-forward.

Both ways have theirs advantages and inconvenients, but both are perfectly valid.
In my team, before a merge, we choose to rebase with destination branch first, as we can build and test the rebased branch, and then when we merge it in destination branch (master, develop, or whatever), we are perfectly sure you are not breaking anything. If you have any conflict on a merge, you loose this guarantee. When resolving this conflict, there is always a chance you are breaking something. You may have then an unstable master (or develop) branch, and we choose to avoid that risk.
So, after rebasing a feature branch, you have to push force it, and rewrote it. That's an inconvenient, yes, but the price to have a stable master/develop. You may think otherwise, and I'm good with it, as Git allows you to choose a workflow that fits your needs.

In the current state, GoCD forbids us to use a rebase/merge-ff workflow, a valid workflow So, don't you agree it is a bug then ?

**Comment by arvindsv** [comment] 2016-04-27 00:09
> I do not understand why GoCD is keeping track of the commit instead of the branch. A branch is indicated in the pipeline configuration, not a commit. Why does GoCD needs this commit ?

Because the whole point of GoCD is to know what has changed between the last time it ran a pipeline and this time, and then run it. The commit is also needed for reruns of a pipeline (so that it can reset HEAD back to the commit it had seen before. In fact, the branch is just ancillary. The commit is more important.

But, I think it should be allowed to use rebase/merge-ff workflow. I don't know whether it should just ignore the previous commit and differences silently or make it optional, though.

**Comment by herby** [comment] 2016-04-27 11:14
Aravind SV wrote:
>     I do not understand why GoCD is keeping track of the commit
>     instead of the branch. A branch is indicated in the pipeline
>     configuration, not a commit. Why does GoCD needs this commit ?
>
> Because the whole point of GoCD is to know what has changed between 

Well, it does a lot more, but if you need that old commit so badly, keep a copy of it in local clone of the repo (per Go CD instance, per agnet or per pipeline is implementation detail), so you can integrate it there if missing.

**Comment by henriquegemignani** [comment] 2016-04-27 15:28
This is in fact similar to #2110, but that one has a much more dangerous outcome.
Not just that, but it seems that this bug is triggering in more cases.

**Comment by scriby** [comment] 2016-04-29 01:59
I just ran into this. I've worked with several build servers in the past and they all "just work" in this case by building the current HEAD. I was really surprised to discover gocd doesn't work the same way.

Trying to figure out what the best workaround is now...

**Comment by ketan** [comment] 2016-05-02 07:46
> It seems wrong to just say: "Oh, I didn't find the commit you used previously. So, I'll just pick the latest and roll with it." without involving the user (if not an admin).

What decision does the user get to make, and what are the implications of each of these decisions (on go)?

**Comment by framegrace** [comment] 2016-05-02 08:26
I think there are options between "I take the last commit without asking anyone" and "I refuse to use that dirty repo forever".
I'm okay on just be able to force to continue on a later commit. Maybe launching it manually. I think is an easy way to workaround this for now. 
I will not be a solution for the people that use a rebase worklfow, though.

**Comment by zabil** [comment] 2016-05-02 09:11
> What decision does the user get to make, and what are the implications of each of these decisions (on go)?

Also note this is specific to git. Do we need to make it consistent with other (scm) materials?

**Comment by herby** [comment] 2016-05-02 13:06
@zabil Specific to any history-rewriting VCS.

**Comment by tomas-forsman** [comment] 2016-05-05 08:40
We also had this problem, but with the twist that we actually had to restore the repository after someone (me :-P) had managed to wipe a bit too much with a hard reset. 

The repo in the flyweight directory became out of sync - saying something about being x commits behind and x commits before remote. For some reason this made the go pipeline just building forever - once one build was done, a new build was triggered. The two builds were comparing against two different old commits. 

The solution for us was to pause the job, delete the flyweight directory, create it again and make a manual clone of the git repository and branch that should be there. After this it started working again.

**Comment by zabil** [comment] 2016-05-09 10:27
https://github.com/gocd/gocd/commit/c144328243608301b16a7a4911ec7381cf204121 

Will resolve this.

**Comment by algra** [comment] 2016-05-23 11:52
Have same problem here, did git push --force and now pipeline is broken.

First it was building two revisions in a loop, tried solution from @framegrace (see comment from Mar 10) and from @tomas-forsman (from 18 days ago) and in both cases i was unable to trigger pipeline anymore because of:

```
2016-05-23 11:48:37,011  WARN [96@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:121 - [Material Update] Modification check failed for material: URL: git@github.com:Company/repo.git, Branch: master
com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
git log origin/master --date=iso --pretty=medium b744f4ab93eb632072a37fc58f99f1bac3790854..
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: fatal: Invalid revision range b744f4ab93eb632072a37fc58f99f1bac3790854..
---

        at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:485)
        at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:513)
        at com.thoughtworks.go.domain.materials.SCMCommand.runOrBomb(SCMCommand.java:42)
        at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:104)
        at com.thoughtworks.go.domain.materials.git.GitCommand.modificationsSince(GitCommand.java:87)
        at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:124)
        at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:37)
        at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:28)
        at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
        at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
        at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:51)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:31)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
```

Any ideas how to make Go to forget hash which does not exists anymore without waiting for 16.5?

**Comment by jyotisingh** [comment] 2016-05-23 13:44
@algra - try changing the url for your material from `git@github.com:Company/repo.git` to `git@github.com:Company/repo.git/`(note the forward slash at the end of the url).

**Comment by algra** [comment] 2016-05-23 14:41
@jyotisingh thanks for replying fast.

I tried to do it, but got an error:

Failed to run git clone command STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/cc3e1c49-de75-4874-8832-5928a90af6db'... STDERR: ERROR: Repository not found. STDERR: fatal: Could not read from remote repository. STDERR: STDERR: Please make sure you have the correct access rights STDERR: and the repository exists.

I'm pretty sure repo is exists and agent has right for it, without slash this error is not appearing, but the one with revision not exists error.

**Comment by arvindsv** [comment] 2016-05-23 15:24
@jyotisingh's idea is to make the server forget about the bad material, by changing the URL to be a new one. However, adding a slash at the end does not work, since github does not consider it a valid repo URL. So, you can try one of the other options:

```
# Does not work
$ git clone git@github.com:gocd/api.go.cd.git/
Cloning into 'api.go.cd'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


# Works (adding a slash after the colon)
$ git clone git@github.com:/gocd/api.go.cd.git
Cloning into 'api.go.cd'...
remote: Counting objects: 3381, done.
remote: Total 3381 (delta 1), reused 1 (delta 1), pack-reused 3379
Receiving objects: 100% (3381/3381), 1.33 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1835/1835), done.
Checking connectivity... done.


# Works (removing the .git at the end)
$ git clone git@github.com:gocd/api.go.cd
Cloning into 'api.go.cd'...
remote: Counting objects: 3381, done.
remote: Total 3381 (delta 1), reused 1 (delta 1), pack-reused 3379
Receiving objects: 100% (3381/3381), 1.33 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1835/1835), done.
Checking connectivity... done.


# Works (changing the case of the org in the URL)
$ git clone git@github.com:goCD/api.go.cd
Cloning into 'api.go.cd'...
remote: Counting objects: 3381, done.
remote: Total 3381 (delta 1), reused 1 (delta 1), pack-reused 3379
Receiving objects: 100% (3381/3381), 1.33 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1835/1835), done.
Checking connectivity... done.
```

Any of those three options above should do the trick.

**Comment by zabil** [comment] 2016-05-24 06:48
This is now fixed by https://www.github.com/gocd/gocd/commit/40eb198 and will be a part of 16.5

Closing this, however please feel free to continue pending conversations.

**Closed by zabil** 2016-05-24 06:48 UTC
Labels: materials
