### ISSUE TITLE
Clean database regularly

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1615] opened 2015-11-13 08:10 UTC
When I remove a pipeline from config - at least directly by editing the xml - the history of the pipeline remains in the database. When I add the pipeline again all information is visible again.

After a year of use the database gets very polluted and slow. Cleaning up non-existing pipelines after a couple of days makes sense here to keep the database in a good shape.

**Comment by zabil** [comment] 2015-11-13 08:28
Closing this as duplicate of #879

**Closed by zabil** 2015-11-13 08:28 UTC
