### ISSUE TITLE
Checking in a large number of files at the same time (20K+) results in a significant delay in scheduling

### ISSUE THREAD

**Issue by lbenhart** [gocd/gocd#946] opened 2015-03-11 17:36 UTC
We have been seeing this issue consistently for six months.  The scheduling of the pipeline will be accepted, however the agent selection and starting of the pipeline is delayed for a significant time period, with no indication to the end user that any work is ongoing.  There is nothing even logged to indicate a material list is being processed. We worked with the GO team several months ago and determined the problem in scheduling was related to the large number of files in a changelist (Perforce).  I do not know what the threshold is, but we do know that over 20K+ plus files will delay pipeline startup for many minutes. The only workaround is to pause all the pipelines which may include files from the intended changelist.  check thse files in, and then followup with a smaller changelist per each pipeline.  This is laborious and often forgotten.

**Comment by arvindsv** [comment] 2016-06-04 13:10
Closing as a duplicate of #443.

**Closed by arvindsv** 2016-06-04 13:10 UTC
Labels: bug, high, materials
