### ISSUE TITLE
java.lang.UnsatisfiedLinkError on windows agent in the currently developed v 16.7 

### ISSUE THREAD

**Issue by vkuptcov** [gocd/gocd#2484] opened 2016-07-25 15:20 UTC
##### Issue Type
- Bug Report

##### Summary

I faced with the same problem as described in #1936  on the currently developed 16.7 version.
The problem was that the gocd git-repository itself contains an old version of the javasysmon library (`local-maven-repo/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar` path).
I built a new one from the https://github.com/gocd/javasysmon (just run `ant package`) and copied the resulted file `javasysmon.jar` to `local-maven-repo/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar` and replaced it in the `~/.m2` repo.
After that I built a new deb-package and everything works fine now.

So, I guess that it's enought to include the new library in the gocd git-repo.

###### Basic environment details

* Go Version: `16.7 master` (at least commits from `996e231e47ded3cdbcb1cbd297eee12275e6a9c7` to `27511b3d02e0ef40b73d7140b47589811a0dd937`)
* JAVA Version: `1.8.102-b14 32 bit`
* OS: `Win 7`

**Comment by ketan** [comment] 2016-07-25 15:43
Hi,

You are right about this issue, there was a time when we'd fudged with the jar that is checked in into the repository.

If you remove the `.m2/repository` directory and build GoCD, do you still see this issue?

**Comment by ketan** [comment] 2016-07-25 15:43
I'm going to close this issue out, but if you're able to reproduce this on current master, please let us know and we will re-open this issue.

**Comment by vkuptcov** [comment] 2016-07-25 16:18
@ketan 
Yes, I can. Furthermore, I had the same library version in the current master and in the `~/.m2/repository`

```
$ git log | head -n 3
commit 27511b3d02e0ef40b73d7140b47589811a0dd937
Merge: 796af81 15a3ebc
Author: Ketan Padegaonkar <ketanpadegaonkar@gmail.com>

$ md5sum local-maven-repo/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar
4e29c92f6b55582e7eb27f0d87a80280  local-maven-repo/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar
$ md5sum ~/.m2/repository/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar 4e29c92f6b55582e7eb27f0d87a80280  /home/vladimir/.m2/repository/com/jezhumble/javasysmon/0.3.5/javasysmon-0.3.5.jar
```
And the newest library from the https://github.com/gocd/javasysmon has
```
$ md5sum target/javasysmon.jar 
b7a663c15206c289aa0e57d157c29ad2  target/javasysmon.jar
```

**Comment by ketan** [comment] 2016-07-26 01:59
> Yes, I can. Furthermore, I had the same library version in the current master and in the ~/.m2/repository

Could you provide us the complete stack trace of the error you see when you build from current master (`./gradlew installers:agentGenericZip installers:serverGenericZip`)? And the git sha you built from?

> And the newest library from the https://github.com/gocd/javasysmon has
>
> $ md5sum target/javasysmon.jar 
> b7a663c15206c289aa0e57d157c29ad2  target/javasysmon.jar


Everytime you build will give you a different checksum :) That's just the nature of how the jar is generated.

**Comment by ketan** [comment] 2016-07-27 14:23
Hi @vkuptcov — we've identified the issue and have pushed a fix https://github.com/gocd/gocd/pull/2490

Could you rebuild from current master, or try with a download of the latest experimental from https://www.go.cd/download/?experimental=true

Release 16.8 is due to be released in a couple of days and we'd love to get your feedback whether it fixes the issue.

**Closed** 2016-08-01 06:17 UTC

**Comment by vkuptcov** [comment] 2016-08-02 03:22
Hi @ketan . I'm really sorry for the delay with my response and I can't check the fix right now. I'm going to check it during the next week.

**Comment by vkuptcov** [comment] 2016-08-15 10:01
@ketan I've checked the latest master build. It seems it works.

**Comment by ketan** [comment] 2016-08-15 13:35
Thank you for confirming :)
