### ISSUE TITLE
Single-line custom command arguments entry

### ISSUE THREAD

**Issue by nvcexploder** [gocd/gocd#3014] opened 2016-12-15 16:42 UTC
##### Issue Type

Bug report/feature enhancement

- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report

##### Summary

Arguments for a custom command currently only have line for entry.

###### Basic environment details

* Go Version: 16.12.0 (4352-018c65856d46007240cc75577e9cc8535b44148d)
* JAVA Version: 1.8.0_72
* OS: Linux 4.4.36-boot2docker
* Browser vendor and version (if relevant): Safari: Version 10.0.1 (12602.2.14.0.7), and Chrome: Version 54.0.2840.98 (64-bit)

##### Steps to Reproduce

1. Add a custom task to a job
2. 
3. 
4. 

##### Expected Results

I should have a window to be able to see more than one line of arguments in the custom command

##### Actual Results

I only have one line of arguments for the custom command

##### Possible Fix

Not restrict the text field to 400px x 30px

##### Any other info

Thanks very much for all of your work!

**Comment by arvindsv** [comment] 2016-12-15 16:50
Assigning to @naveenbhaskar to consider.

@nvcexploder - Can you paste a screenshot?

**Comment by nvcexploder** [comment] 2016-12-15 18:08
Yep! 

<img width="746" alt="screen shot 2016-12-15 at 8 41 15 am" src="https://cloud.githubusercontent.com/assets/272524/21236081/710c4e62-c2ae-11e6-8b52-396cba044794.png">

**Comment by nvcexploder** [comment] 2016-12-15 18:10
<img width="756" alt="screen shot 2016-12-15 at 10 09 25 am" src="https://cloud.githubusercontent.com/assets/272524/21236132/a07e7116-c2ae-11e6-8e27-d5b722bceeee.png">

**Comment by nvcexploder** [comment] 2016-12-15 18:10
^ that's the safari one.

**Comment by arvindsv** [comment] 2016-12-15 19:57
Hmm. From what I understand, if the config has the exec command in this format:

```
<exec command="/usr/local/bin/docker.sh" args="build">
</exec>
```

then it shows in one line and you can separate the arguments by a space (the message is misleading). If the config has the exec command in the default format, like this:

```
<exec command="/usr/local/bin/docker.sh">
  <arg>build</arg>
</exec>
```

then the UI shows it as one-per line and switches to a text area. Is that consistent with what you see? Is it possible that you have an old exec which uses the `args` style?

Either way, @naveenbhaskar or @maheshp, the message is wrong when used in the `args` style.

**Comment by arvindsv** [comment] 2016-12-15 19:58
When I add a new custom command, this is what I am seeing:

![image](https://cloud.githubusercontent.com/assets/172235/21239913/f1f31d30-c2d6-11e6-9113-d1cd34ab7519.png)

**Comment by nvcexploder** [comment] 2016-12-15 20:06
If I create a new task, I get this:
<img width="764" alt="screen shot 2016-12-15 at 12 03 41 pm" src="https://cloud.githubusercontent.com/assets/272524/21240095/a3798a9e-c2be-11e6-8a86-6e6337ccda03.png">

This is outside the realm of interacting with the XML configuration

**Comment by arvindsv** [comment] 2016-12-15 20:07
I see. Then it's definitely something @naveenbhaskar and/or @maheshp need to to take a look at. Thanks for all the information!

**Comment by nvcexploder** [comment] 2016-12-15 20:08
No worries! I am going to test interacting with the XML configuration directly to confirm your statements, but it's not the usual folks interact with our installation. I'll post back into this issue.

Thanks, y'all! :D

**Comment by nvcexploder** [comment] 2016-12-15 20:11
looks like they're in the old version in the XML.

**Comment by maheshp** [comment] 2016-12-16 04:13
@arvindsv verified that the message ```Enter each argument on a new line```, its displayed only for ```arg``` and not for ```args```. 

@nvcexploder I was not able to reproduce this issue on safari or chrome. @naveenbhaskar will  look into this further.

**Comment by maheshp** [comment] 2016-12-16 04:14
@naveenbhaskar, while you are on that page can you please fix this as well.

![screen shot 2016-12-16 at 09 34 43](https://cloud.githubusercontent.com/assets/1061051/21251502/2c32f68a-c374-11e6-84fd-f8a6e7a88376.png)

**Comment by naveenbhaskar** [comment] 2016-12-16 09:27
fixed. gave a height specifically  for this textarea.

**Comment by arvindsv** [comment] 2016-12-16 12:37
@naveenbhaskar Were you able to reproduce this? Was it related to screen resolution?

**Comment by naveenbhaskar** [comment] 2016-12-21 05:09
I was not able to reproduce this bug. But I made it in such a way that , that textarea should take a particular height.

**Comment by rajiesh** [comment] 2017-02-21 08:27
Verified on 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45). The Lookup commands message alignment is fixed

**Closed by rajiesh** 2017-02-21 08:27 UTC
Labels: pipeline configuration, ui / ux

**Comment by naveenbhaskar** [comment] 2017-04-03 08:03
Hello Ben, 

I have sent an email to benacker@gmail.com regarding a usability test for GoCD. Can you please check.?
Thanks
