### ISSUE TITLE
Unable to start Go CD server with Java 16

### ISSUE THREAD

**Issue by sguptatw** [gocd/gocd#9469] opened 2021-07-02 00:30 UTC
##### Issue Type
Bug Report
 
##### Summary

Following the instruction on [GOCD installation](https://docs.gocd.org/current/installation/install/server/osx.html). Unable to start Go CD server. Getting an UnsatisfiedDependencyExceptions exception

###### Basic environment details
```
Mac OS 10.14.6
GoCD Version: 21.2.0-12498
jvm 1             Java Version: 16
jvm 1    xMac OS X(10.14.6)
```

##### Steps to Reproduce

* On Mac OSX, install using the zip/osx installer.
* Start the server using the command `./bin/go-server console` 

##### Expected Results
The exception stack trace is huge, hence have attached to the log file. The first exception is `UnsatisfiedDependencyExceptions` 

##### Actual Results
Should be able to run the server without an exception

##### Log snippets
Please find the logs here [logs.zip](https://github.com/gocd/gocd/files/6751377/logs.zip)

**Comment by arvindsv** [comment] 2021-07-05 16:08
Can you try with a Java version between 13 and 15?

But, overall, yes, I agree that it should be able to run.

**Comment by chadlwilson** [comment] 2021-07-15 09:02
The root of the problem is the use of `setAccessible` in deep cloning logic, which is disallowed by default on Java 16.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.util.NavigableMap java.util.TreeSet.m accessible: module java.base does not "opens java.util" to unnamed module @3f371cc0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.rits.cloning.Cloner.addAll(Cloner.java:563)
	at com.rits.cloning.Cloner.allFields(Cloner.java:577)
	at com.rits.cloning.Cloner.registerStaticFields(Cloner.java:209)
	at com.rits.cloning.Cloner.registerKnownConstants(Cloner.java:190)
	at com.rits.cloning.Cloner.init(Cloner.java:85)
	at com.rits.cloning.Cloner.<init>(Cloner.java:56)
	at com.thoughtworks.go.config.GoConfigCloner.<init>(GoConfigCloner.java:34)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.<clinit>(MagicalGoConfigXmlLoader.java:63)
```

If you really need to use Java 16, you can probably workaround in the short term with `--illegal-access=permit` in the appropriate arg to the wrapper configuration (maybe `wrapper.java.additional.100=--illegal-access=permit` in `${INSTALL_DIR}/wrapper-config/wrapper-properties.conf`)

Medium term it looks like the Maven co-ordinates for that library have moved to https://mvnrepository.com/artifact/io.github.kostaskougios/cloning and https://github.com/kostaskougios/cloning and the fix for this issue is possibly in https://github.com/kostaskougios/cloning/pull/96 / `1.10.3` depending on whether there are other object types which are problematic (see https://github.com/kostaskougios/cloning/issues/105)

**Comment by chadlwilson** [comment] 2021-07-15 11:02
I did a quick test with `1.10.3` and although that specific issue goes away on Java 16 when running tests, there are other issues with the `java.util.ImmutableCollections` as well as many `setAccessible` usages throughout GoCD codebase which have issues such as`Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible` in the `GoConfigFieldLoader` so would need a bit more work on Java 16 unless we are going to suggest people allow illegal access by design, and kick the can down the road for a later Java version where this potentially becomes impossible.

**Comment by sguptatw** [comment] 2021-07-16 10:36
Thank you for your suggestions and responses. I was working on a POC. As of now, instead of using older Java version, I used the docker installations of go server and agents. Thanks again!

**Comment by chadlwilson** [comment] 2021-07-18 09:56
Resolving this properly should probably consider the effect of [JEP403](https://openjdk.java.net/jeps/403) targeted for java 17 where this will become completely impossible to use `setAccessible` on internal Java APIs like this.

**Closed** 2022-02-05 13:21 UTC
Labels: installers
