### ISSUE TITLE
Elastic Agent Kubernetes Plugin gets stuck and cannot recover

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#6770] opened 2019-08-19 06:51 UTC
##### Issue Type

- Bug Report

##### Summary

Since upgrading from GoCD 19.3.0 to 19.70 about 7 days ago we have had two instances where GoCD loses connectivity with its Kubernetes Elastic agents for some reason or another. In both of these cases, even after killing all the agents, the Kubernetes Elastic Agent plugin seems unable to recover and the server needs to be restarted to resume scheduling onto agents.

###### Basic environment details

* Go Version: `19.7.0 (9567-727ea9db824eb6971170ac2a886ff1072ff5a235).`
* JAVA Version: `12.0.1`
* OS: `Linux 4.14.106-97.85.amzn2.x86_64`
* Browser vendor and version (if relevant): `N/A`

###### Additional Environment Details

Deployed on Kubernetes EKS 1.12.10 with EBS persistent volume.
* Using kube2iam to AssumeRole to talk to the Kube master/API server from the gocd server pod
* Also using kube2iam for agents to AssumeRole to talk to other cluster Kube masters/API servers from elastic agents. Elastic agents currently all running in the same cluster as the gocd server.

Server base image customizations
* `RUN apk --no-cache add python3 && pip3 install awscli`
* Custom gitconfig to be able to talk to AWS CodeCommit via credential-helper

Agent base image customizations
* `RUN apk --no-cache add python3 && pip3 install awscli`
* Install `kubectl`, `aws-iam-authenticator`, `helm`
* Custom gitconfig to be able to talk to AWS CodeCommit via credential-helper

##### Steps to Reproduce

Not able to determine how to reproduce this at the moment. 

At the most recent occurrence there were 15 elastic agents started, they all seemed to be stuck registering with the server with a `NullPointerException` on `AgentUpgradeService.java:108` ([here](https://github.com/gocd/gocd/blob/2d3e0f13d5fe1e798b9d622ec78556eeec4e7e3a/agent/src/main/java/com/thoughtworks/go/agent/service/AgentUpgradeService.java#L108).

It is worth noting that these agents have the DIND base image from `19.3.0`, however we have had issues with some agents that were using the `19.7.0` DIND base image as well.

##### Expected Results
* Agents should not have issues registering with the server
* The server's Kubernetes elastic agent plugin should not get stuck indefinitely, requiring a restart to fix - its handling should be robust enough to recover automatically.

##### Actual Results

The Kubernetes elastic agent plugin was unable to assign any agents for scheduling jobs and the server needed to be restarted.

##### Possible Fix

N/A

##### Log snippets

From the server, the below is repeated many times
```
jvm 1    | 2019-08-19 06:30:05,104 ERROR [157@MessageListener for CreateAgentListener] JMSMessageListenerAdapter:90 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener@405f5118
jvm 1    | java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to handle request cd.go.elastic-agent.create-agent'
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:58)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:142)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:60)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:43)
jvm 1    | 	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
jvm 1    | 	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2019-08-19 06:30:05,106 ERROR [158@MessageListener for CreateAgentListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:127 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request cd.go.elastic-agent.create-agent
jvm 1    | io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
jvm 1    | 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
jvm 1    | 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
jvm 1    | 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
jvm 1    | 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForCluster(KubernetesPlugin.java:134)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:142)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:60)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:43)
jvm 1    | 	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
jvm 1    | 	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: java.net.SocketTimeoutException: timeout
jvm 1    | 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
jvm 1    | 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
jvm 1    | 	at okhttp3.internal.http2.Http2Stream$FramingSource.waitUntilReadable(Http2Stream.java:374)
jvm 1    | 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:337)
jvm 1    | 	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
jvm 1    | 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
jvm 1    | 	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
jvm 1    | 	at java.base/java.io.BufferedInputStream.read(Unknown Source)
jvm 1    | 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227)
jvm 1    | 	... 22 common frames omitted
```
-->

**Comment by ketan** [comment] 2019-08-19 07:07
> At the most recent occurrence there were 15 elastic agents started, they all seemed to be stuck registering with the server with a `NullPointerException` on `AgentUpgradeService.java:108` ([here](https://github.com/gocd/gocd/blob/2d3e0f13d5fe1e798b9d622ec78556eeec4e7e3a/agent/src/main/java/com/thoughtworks/go/agent/service/AgentUpgradeService.java#L108).

Do you have a stacktrace for this error?

**Comment by chadlwilson** [comment] 2019-08-19 07:33
> > At the most recent occurrence there were 15 elastic agents started, they all seemed to be stuck registering with the server with a `NullPointerException` on `AgentUpgradeService.java:108` ([here](https://github.com/gocd/gocd/blob/2d3e0f13d5fe1e798b9d622ec78556eeec4e7e3a/agent/src/main/java/com/thoughtworks/go/agent/service/AgentUpgradeService.java#L108).
> 
> Do you have a stacktrace for this error?

Sadly, no. My bad. I thought I had captured it before killing the agent pods (with `kubectl delete pod/blah`) but I messed up. Will capture if it happens again.

**Comment by chadlwilson** [comment] 2019-08-21 04:35
This problem has happened again. This time there is nothing being reported in the agent logs, but the server is unable to talk to the agents with the same stack trace as above.

- At about `2019-08-21 03:46` GoCD seemed to stop being able to talk to 3 elastic agents  (on two diferrent profiles) that it had previously created. 
- Half an hour later, all 3 agents logged some MD5 validation NullPointerException.
- During this time the server is continuously logging the same stack trace above
- No new agents are able to be created. The old agents are stuck lingering around, no jobs are scheduled on them.

`latest-agent.status` headers from server
```
agent-content-md5: d869bf1f175d030803df10d178b500bd
agent-launcher-content-md5: 1e5465c22d67ce4eaa7a3c8ba474cfa4
agent-plugins-content-md5: 0933068dcb1d2a7336993cc6927f828e
tfs-sdk-content-md5: 8f282d8a2cb359a01daa042554e41cfd
gocd-agent-extra-properties: 
cruise-server-ssl-port: 8154
```

ps aux on gocd server
```
$ k exec -it gocd-app-server-7f74c97964-prz8m bash
bash-4.4$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
go           1  0.0  0.0   1152     4 ?        Ss   Aug19   0:02 /usr/local/sbin/tini -g -- /go-working-dir/bin/go-server con
go          51  0.0  0.0   1892  1384 ?        S    Aug19   0:00 /bin/sh /go-working-dir/bin/go-server console
go         122  0.0  0.0  21440   972 ?        Sl   Aug19   1:33 /go-server/bin/../wrapper/wrapper-linux-x86-64 /go-server/bi
go         135  4.1 21.2 3412832 1716988 ?     Sl   Aug19 114:49 /gocd-jre/bin/java -Xms512m -Xmx1024m -XX:MaxMetaspaceSize=4
go       16985  0.0  0.0   2324  2012 pts/0    Ss   04:16   0:00 bash
go       17016  0.0  0.0   1620   472 pts/0    R+   04:16   0:00 ps aux
```

ps aux on one agent (GoCD 19.7.0 DIND base docker image)
```
$ k exec -it aads-gocd-agent-b04e6726-a37d-4cff-bcc8-ad971536a308 bash
bash-5.0$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
go           1  0.0  0.0   1152     4 ?        Ss   03:45   0:00 /usr/local/sbin/tini -g -- /go/bin/go-agent console
go          30  0.0  0.0   1924  1256 ?        S    03:45   0:00 /bin/sh /go/bin/go-agent console
go         101  0.0  0.0  21436  3436 ?        Sl   03:45   0:01 /go-agent/bin/../wrapper/wrapper-linux-x86-64 /go-agent/bin/
go         114  0.4  1.5 4539892 123800 ?      Sl   03:45   0:08 /gocd-jre/bin/java -Dgo.console.stdout=true -Djava.library.p
go         135  1.3  2.4 2781432 196072 ?      Sl   03:45   0:28 /gocd-jre/bin/java -Xms128m -Xmx256m -Dagent.plugins.md5=093
go         359  0.0  0.0   2412  2072 pts/0    Ss   04:19   0:00 bash
go         366  0.0  0.0   1616   580 pts/0    R+   04:19   0:00 ps aux
```

Logs from 19.7.0 agent
```
2019-08-21 03:47:03,206 INFO  [scheduler-2] HttpService:148 - Got back 200 from server
2019-08-21 03:47:03,253 INFO  [scheduler-2] DefaultGoPublisher:87 - Stopping Transmission for Build [REDACTED]
2019-08-21 04:15:37,444 ERROR [scheduler-2] AgentController:91 - [Agent Loop] Error occurred during loop:
java.lang.NullPointerException: null
	at com.thoughtworks.go.agent.service.AgentUpgradeService.validateMd5(AgentUpgradeService.java:108)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:85)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:73)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

ps aux on another agent (GoCD 19.3.0 DIND base docker image)
```
PID   USER     TIME  COMMAND
    1 root      0:00 /usr/local/sbin/tini -- /usr/local/sbin/gosu go /docker-entrypoint.sh /go-agent/agent.sh
   39 go        0:08 java -Dgocd.agent.log.dir=/go/logs -Dgo.console.stdout=true -jar /go-agent/agent-bootstrapper.jar -serv
   70 go        0:23 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dgo.
  162 root      0:00 bash
  168 root      0:00 ps aux
```

Logs on 19.3.0 agent
```
2019-08-21 03:46:45,408 INFO  [scheduler-2] HttpService:148 - Got back 200 from server
2019-08-21 03:46:45,408 INFO  [scheduler-2] DefaultGoPublisher:99 - Agent [gocd-agent-fe781ed1-1722-48af-9f33-b938c144a572, 172.16.145.188, ffee1120-b8cf-41db-a4e3-7d6a75fd5d85] is reporting build result [Passed] to Go Server for Build [REDACTED]
2019-08-21 03:46:45,441 INFO  [scheduler-2] HttpService:148 - Got back 200 from server
2019-08-21 03:46:45,442 INFO  [scheduler-2] DefaultGoPublisher:93 - Agent [gocd-agent-fe781ed1-1722-48af-9f33-b938c144a572, 172.16.145.188, ffee1120-b8cf-41db-a4e3-7d6a75fd5d85] is reporting status [Completing] to Go Server for Build [REDACTED]
2019-08-21 03:46:45,457 INFO  [scheduler-2] ArtifactsPublisher:68 - Pluggable metadata folder is empty.
2019-08-21 03:46:45,457 INFO  [scheduler-2] DefaultGoPublisher:105 - Agent [gocd-agent-fe781ed1-1722-48af-9f33-b938c144a572, 172.16.145.188, ffee1120-b8cf-41db-a4e3-7d6a75fd5d85] is reporting build result [Passed] to Go Server for Build [REDACTED]
2019-08-21 03:46:45,467 INFO  [scheduler-2] HttpService:148 - Got back 200 from server
2019-08-21 03:46:45,487 INFO  [scheduler-2] DefaultGoPublisher:87 - Stopping Transmission for Build [REDACTED]
2019-08-21 04:16:28,519 ERROR [scheduler-2] AgentController:91 - [Agent Loop] Error occurred during loop:
java.lang.NullPointerException: null
	at com.thoughtworks.go.agent.service.AgentUpgradeService.validateMd5(AgentUpgradeService.java:108)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:85)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:73)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:83)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by arvindsv** [comment] 2019-08-21 19:12
I believe @GaneshSPatil is looking into this.

**Comment by chadlwilson** [comment] 2019-08-22 06:31
Thanks @arvindsv, @GaneshSPatil. For other's information, I've supplied more detailed (redacted) logs to the GoCD team outside this card for them to analyze what's going on here.

**Comment by ketan** [comment] 2019-08-22 07:47
FYI: the `ps aux` seems to be trimmed to the terminal width. Perhaps try `ps aux | cat` next time :(

**Comment by GaneshSPatil** [comment] 2019-08-23 05:37
Hi Chad,

Thanks for providing the detailed information.

From the GoCD server and Kubernetes plugin logs, we see the following exceptions:

##### From go-server.log
```
2019-08-21 03:46:49,347 ERROR [158@MessageListener for CreateAgentListener] JMSMessageListenerAdapter:90 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener@25a0a2a4
java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to handle request cd.go.elastic-agent.create-agent'
```

##### From plugin-cd.go.contrib.elasticagent.kubernetes.log.
```
2019-08-21 04:52:12,365 ERROR [156@MessageListener for CreateAgentListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.create-agent
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
```

The above-mentioned errors are happening due to plugin failing to fulfill the create-agent call (_resulting in no elastic-agents_).


As part of the create-agent call, the k8s plugin tries to [list all the existing pods](https://github.com/gocd/kubernetes-elastic-agents/blob/v3.0.0-175-exp/src/main/java/cd/go/contrib/elasticagent/KubernetesAgentInstances.java#L150) to compute the number of pending pods. The plugin fails to list all the pods from the cluster and fails with the following stack trace:

```
2019-08-22 08:23:44,161 ERROR [160@MessageListener for CreateAgentListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.create-agent
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
 at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
 at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
 at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
 at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
 at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
 at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
 at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
 at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:63)
 at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:38)
 at cd.go.contrib.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:44)
 at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
 at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
 at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
 at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
 at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
 at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
 at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:142)
 at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:60)
 at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:43)
 at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
 at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
 at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
 at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
 at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout
 at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
 at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
 at okhttp3.internal.http2.Http2Stream$FramingSource.waitUntilReadable(Http2Stream.java:374)
 at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:337)
 at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
 at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
 at java.base/java.io.BufferedInputStream.fill(Unknown Source)
 at java.base/java.io.BufferedInputStream.read(Unknown Source)
 at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227)
 ... 24 common frames omitted
```

From the stack trace of the exception, the cause of the failure is `Caused by: java.net.SocketTimeoutException: timeout`.  This exception can happen because of the following reasons:
**1. Slow response from the kube-apiserver of the k8s cluster.
2. No response. Or any error happened while unmarshaling the response received from the kube-apiserver.**


We were able to replicate this issue on one of our Kubernetes-based environments; Where it seems like the plugin is waiting for the response on a stale/closed connection. 
This could happen due to a stale Kubernetes Client (which possibly is losing connections). Hence, We've added [a fix](https://github.com/gocd/kubernetes-elastic-agents/commit/8fa0ea823f39d1b06322a50fca174bfa67202c40) to periodically recycle the Kubernetes client used for communication with kube-apiserver.

We have a new [Kubernetes Elastic Agent Plugin - v3.1.0-177](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.1.0-177) release with the above-mentioned issue fixes. You should be able to download the appropriate plugin from the Github Releases. We also have made a new [GoCD Helm Chart - v1.16.1](https://github.com/helm/charts/tree/master/stable/gocd) release to [use the latest Kubernetes Elastic Agent Plugin](https://github.com/helm/charts/pull/16586) which contains these fixes.


Do let us know if the mentioned release of the Kubernetes Elastic Agent Plugin fixes the mentioned issue.

Thanks,
Ganesh

**Comment by chadlwilson** [comment] 2019-08-23 06:13
Great work @GaneshSPatil and team, we'll give it a go.

**Comment by kritika-singh3** [comment] 2019-09-09 06:17
Closing this issue since it seems to be related to plugin. If the issue still persists, please open it again on the plugin [repo](https://github.com/gocd/kubernetes-elastic-agents).

**Closed by kritika-singh3** 2019-09-09 06:17 UTC
Labels: elastic-agents

**Comment by GaneshSPatil** [comment] 2019-09-11 11:27
The above-mentioned issue has been fixed as part of [this](https://github.com/gocd/kubernetes-elastic-agents/commit/8fa0ea823f39d1b06322a50fca174bfa67202c40) commit and is available from 
[Kubernetes Elastic Agent Plugin - v3.1.0-177](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.1.0-177) release.

Thanks a lot, @chadlwilson for reporting this issue!
