### ISSUE TITLE
Unable to delete existing pipeline

### ISSUE THREAD

**Issue by shru9289** [gocd/gocd#4938] opened 2018-07-10 17:34 UTC
##### Issue Type

Unable to delete Pipeline

- Bug Report
The delete option is grey, cannot delete any pipeline which is not required anymore
##### Summary
I have a pipeline created on my server, i am trying to delete the pipeline, bu the delete is greyed out. Cannot delete the pipeline.

environment:
Mac OS
![gocd](https://user-images.githubusercontent.com/29108502/42527206-d6de0e10-842c-11e8-82d4-d7280f4a561b.png)

**Comment by ankitsri11** [comment] 2018-07-10 17:54
Hi @shru9289 - Its not a bug. There might be a pipeline dependency which is not allowing to delete pipeline. You should see more info when you hover over delete link. Please refer below:

![delete_pipeline](https://user-images.githubusercontent.com/6838313/42528090-51561ad2-842f-11e8-8519-327d6e2fb281.gif)

**Comment by shru9289** [comment] 2018-07-10 18:01
Hi,
Thank you for your quick reply. So the message i see in the delete part is
, " Cannot delete 'GoCDGitHub' as it is present in 'GoCdGithub'
environment. Could you please help me deleting this pipeline .



Regards
Shruthi

**Comment by arvindsv** [comment] 2018-07-10 18:09
Closing this. The right place for questions is the mailing list.

**Closed by arvindsv** 2018-07-10 18:09 UTC
