### ISSUE TITLE
Agent page -> On low resolution screen first row is getting cropped

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#2961] opened 2016-12-08 06:19 UTC
##### Issue Type
- UI Issue

##### Summary
Agent page -> On low resolution screen first row is getting cropped

<img width="1046" alt="screen shot 2016-12-08 at 11 50 13 am" src="https://cloud.githubusercontent.com/assets/7871209/20999617/e3aad786-bd3b-11e6-90b7-1ce44585a696.png">

**Comment by naveenbhaskar** [comment] 2016-12-16 05:54
This works in mac air resolution (1388X 768). we do not support resolution less that this as of now.

**Comment by ketan** [comment] 2016-12-19 04:46
@naveenbhaskar — this page breaks pretty bad on mobiles as well. I know we don't specifically target smaller devices, but is there something that we can do to not make it so it renders something "useable"?

![agents go](https://cloud.githubusercontent.com/assets/10598/21301510/2c5da364-c5d4-11e6-93af-00fa5574c92f.png)

**Comment by cobrowserAlex** [comment] 2017-01-19 16:25
I just updated to 17.11 and on my Macbook prod 2560 x 1600 Retina i also can't see the first row. Browser Chrome, zoom 100%.

**Comment by ketan** [comment] 2017-01-19 16:27
Can you attach a screenshot?

**Comment by cobrowserAlex** [comment] 2017-01-19 17:11
@ketan I added one

**Comment by maheshp** [comment] 2017-02-10 06:34
This issue is reported [here](https://github.com/gocd/gocd/issues/3163) as well.

**Comment by naveenbhaskar** [comment] 2017-02-10 09:03
The lowest resolution we are supporting is the mac air resolution which is 1388X768. This page works fine till that resolution and will break in lower resolutions.

Any devices which has a resolution higher than 1388X768 should be working fine.

**Comment by rajiesh** [comment] 2017-02-21 08:00
Closing this issue as we are are not supporting resolutions below 1388X768. 

@cobrowserAlex we are unable to reproduce the issue on the resolution you have provided. If you are still facing the issue please reopen

**Closed by rajiesh** 2017-02-21 08:00 UTC
Labels: ui / ux

**Comment by arvindsv** [comment] 2017-02-27 20:01
@maheshp @naveenbhaskar - It's not just about the resolution. It's also about window size. In a high resolution, if you try and resize the window a bit, to make it smaller, this happens. Ideally, it doesn't do that. Is there something we can do to keep it from not covering that row?

**Comment by naveenbhaskar** [comment] 2017-03-01 03:11
yes.. actually both are same.. small window size on large screens and full window size on small resolution is the same issue. This is because the pages are not responsive and the table  width is high. I will fix this for a a width of 1280*768 in our next release. for window less than this size, there will be a horizontal scroll.
