### ISSUE TITLE
Quick Edit  - Gracefully handle missing task plugins

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3114] opened 2017-01-24 06:29 UTC
##### Issue Type

- Bug Report

##### Summary

Add a custom task using any Task Plugin. On removal of the task plugin from server the task is no longer listed on the Qucik Edit page. 

Quick Edit page should gracefully handle missing task plugins and give appropriate message.

While working on this, it may be good to verify this scenario for Pluggable SCM  materials as well.

**Comment by varshavaradarajan** [comment] 2017-03-27 11:15
Duplicate of https://github.com/gocd/gocd/issues/3318

**Closed by varshavaradarajan** 2017-03-27 11:15 UTC
