### ISSUE TITLE
Accessing a Pipeline's configuration from the Pipeline Runtime view

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2084] opened 2016-03-30 10:36 UTC
##### Issue Type
- Feature enhancement
- Documentation Report
  ##### Summary

When viewing a Job/Stage/Pipeline, we should be able to also view the related configuration. Currently, we need to click around a bit to get to the related configuration.
##### Any other info

This is being used as a criticism against Go.

See : http://concourse.ci/concourse-vs.html

Finding how to configure something is very difficult. There are two distinct sides of the application: watching jobs run and configuring them. You cannot be viewing a job run and easily get to the configuration of the same job. Everything is hidden in endless menus.

**Comment by varshavaradarajan** [comment] 2016-11-22 17:17
Closing as a duplicate of https://github.com/gocd/gocd/issues/2783

**Closed by varshavaradarajan** 2016-11-22 17:17 UTC
