### ISSUE TITLE
[go 15.2] Having 'fetch materials' set to true makes the stage delete fetched artifacts

### ISSUE THREAD

**Issue by vidvid** [gocd/gocd#1568] opened 2015-10-17 06:15 UTC
After upgrading to 15.2 I'm facing this problem in many of my pipelines. If 'fetch materials' is selected, any directory in home folder of pipeline (except for material directories) gets deleted. This makes some trouble if previous stages have fetched artifacts that are going to be used in the next stage. I haven't selected 'clean working directory'.

**Comment by astachurski** [comment] 2015-11-09 22:16
I have exactly the same behaviour. Didn't happen with 15.1.

**Comment by arvindsv** [comment] 2015-11-10 17:39
Correct. This is a duplicate of #1532, I believe. So, I'll close it. If you think it's not, I can reopen it. I'm not yet sure whether it can be fixed in 15.3, or will need to wait, sorry. :( If you can take a look at the code and help, that would be great!

**Closed by arvindsv** 2015-11-10 17:39 UTC
