### ISSUE TITLE
Logging broken on v17.2.0 when using docker

### ISSUE THREAD

**Issue by Stono** [gocd/gocd#3246] opened 2017-03-10 11:07 UTC
Hey folks!
I run gocd in a docker container, on kubernetes.  It appears when you start gocd in a docker container, your script starts gocd, and then attempts to tail the logs (so they appear in stdout, and thus in the docker logs).  However, you're tailing the wrong file.  

If you run with `MSG_TIME=0` you will see this as soon as the server boots:

```
tail: cannot open ‘/var/log/go-server/go-server.log’ for reading: No such file or directory
tail: no files remaining
```

I've fixed this by adding a symlink in my docker file:
```
FROM gocd/gocd-server:17.2.0

# Fix bug with logs
RUN ln -sf /var/log/go-server/go-server.out.log /var/log/go-server/go-server.log
```

Cheers!
Karl (ThoughtWorker - ping me internally if you want to debug with me)

**Comment by ketan** [comment] 2017-03-20 04:17
I suspect that the problem is because the tail executable is invoked because the log file is created.

We'll look into investigating this for 17.4.

**Comment by varshavaradarajan** [comment] 2017-04-04 03:25
@Stono, Since we have moved to the new alpine server image, I don't think this is a problem any longer. If you feel otherwise, log an issue [here](https://github.com/gocd/docker-gocd-server) and link to this if you want to. Closing this.

**Closed by varshavaradarajan** 2017-04-04 03:25 UTC
