### ISSUE TITLE
Slow artifact upload when saving to windows network share

### ISSUE THREAD

**Issue by ksulli** [gocd/gocd#11121] opened 2022-12-19 13:36 UTC
We are using GoCD 21.1.0 (12439-5a4959c7c4ede49165ec961b0219126cd5aa9e52) on a Windows server, running as a service under a domain account.

When our artifact store was on a local drive, artifact upload took about 2mins (for a 6GB artifact).
![image](https://user-images.githubusercontent.com/765353/208434933-ad492995-8946-42c7-b408-54b546c5a146.png)

After changing the destination to use a network share, the time went up to 26 minutes, but just copying the file from the source to the destination using total commander still takes only one or two minutes (probably no problem with connectivity).
![image](https://user-images.githubusercontent.com/765353/208435159-a3a75207-ac8e-4cfb-86bb-6ae5330bc1df.png)

I tried looking for the reason this could be slow.

Using procmon from sysinternals, I noticed that the file is being written to the share in about 1kb chunks. I tried looking through the code, I found that  `ArtifactsService.saveFile()` is using `IOUtils.copyLarge()` with the default buffer size, which should be 8KB https://commons.apache.org/proper/commons-io/apidocs/src-html/org/apache/commons/io/IOUtils.html

https://github.com/gocd/gocd/blob/4a1befaf5f2e6cb9604b2133041051747fda50ed/server/src/main/java/com/thoughtworks/go/server/service/ArtifactsService.java#L84

I thought about mapping the network drive to a drive letter, but MS very much [doesn't recommend](https://learn.microsoft.com/cs-cz/windows/win32/services/services-and-redirected-drives?redirectedfrom=MSDN) this.

Is there any way I could further diagnose or help fix this issue?

**Comment by chadlwilson** [comment] 2022-12-19 15:39
In the older `commons-io` version we are using (`2.6`, due to bugs/regressions in all subsequent versions) the buffer seems to be 4kB rather than 8kB, but not sure that would make a huge difference (who knows though?) and not sure about the discrepancy with what sysinternals sees.

If you are in a position to test a Windows build in realish-world-conditions, I could try changing the buffer size and producing a test Windows installer with increased buffer size.

**Comment by ksulli** [comment] 2022-12-20 12:07
Yes, I can do that and re-test.

**Comment by chadlwilson** [comment] 2022-12-23 01:30
Thanks for this, this is great work.

Just to clarify - if I produce an experimental build do you have a way to test without upgrading a real production server? I meant 'similar network and storage speed conditions' rather than suggesting putting an experimental build on a production server.

**Comment by ksulli** [comment] 2023-01-01 09:54
Sorry for the delay, happy new year! It is really no problem for me to upgrade prod with an experimental build and test (esp. compared with the inconvenience of the 25 minute artifact upload). We use GoCD to automate builds and releases but we do not have a real continuous delivery environment set up, all our triggers are manual and we run the pipelines only a few times a week (also I can make a snapshot of the VM pre-upgrade). We do not have the capacity to have a "testing" GoCD server.

**Comment by chadlwilson** [comment] 2023-02-02 08:32
There are experimental builds with the buffer size increased 4kB to 8kB for the artifact copies ( https://www.gocd.org/download > Experimental tab ) and ability to configure it via `-Dartifact.copy.buffer.size=16384` or whatever you want to try. No change yet to the possible lack of buffering on the `ZipInputStream`s underlying stream, haven't investigated that yet to see whether it's buffered properly or not.

This build is likely to be close to what will released as `23.1.0` but definitely need to be careful if using in your main environment, especially as you are about 2 years behind in versions. Might be better to get to a released version of `22.3.0` and validate the problem still exists (but that your server is stable) rather than going straight to an experimental build. And do the norm of taking backups of your config and database so you can roll back if there are problems.

**Comment by ksulli** [comment] 2023-03-11 08:56
We just got to install the build yesterday (23.1.0.-16068) after previously ypgrading to 22.3, and in the first run after the upgrade we haven't seen much improvement, I will investigate further. 
![image](https://user-images.githubusercontent.com/765353/224475143-10bc98c1-a933-4681-9ff9-2fe230e6e434.png)

**Comment by chadlwilson** [comment] 2023-03-11 13:12
Yeah, I had relatively low expectations that thie change in buffer size would fix the problem, but the changes at least are unlikely to have done any harm.

I guess it would help if you can do a similar analysis as earlier and see if it's at least writing chunks differently, and in bigger sizes.

I suppose the bigger question might be how, in Java-land, to replicate somrthing similar to what total commander (or windows itself) is doing when dealing with such large files.

**Comment by chadlwilson** [comment] 2023-03-12 07:35
Did you try using the system property I added to increase further and see if it makes any difference in your case? Can try 16k, 32k etc.

Official `23.1.0` is out now btw, so can do so on a official build.

**Comment by chadlwilson** [comment] 2024-04-08 13:44
Closing this now, as we seem stuck here and unable to determine what the problem is and whether it is something specific to GoCD and its buffers or just the nature of writing to Windows shares via Java. We can re-open this if further investigation can be done to track down the problem and trace it to GoCD.

**Closed by chadlwilson** 2024-04-08 13:44 UTC
Labels: artifacts, performance
