### ISSUE TITLE
"bash -c <command>" failing v19.12.0

### ISSUE THREAD

**Issue by thomasf1234** [gocd/gocd#7658] opened 2020-01-24 10:10 UTC
##### Issue Type

- Bug Report

##### Summary

`bash -c true` fails at execution time when command is added through the pipeline UI. However, upon saving the config xml (without editing) the command passes on the next run (and subsequent). This is a major issue for us as we heavily rely on `bash -c `for evaluating environment variables.

##### Environment

Docker Image: gocd/gocd-server:v19.12.0 
Go Server Version: | 19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11)
JVM version: | 13.0.1
OS Information: | Linux 4.15.0-74-generic
Underlying Host OS: Ubuntu 18.04.3 
Docker version 19.03.5, build 633a0ea838
Browser: Chrome + Safari (Remotely from MacOSX)

##### Steps to Reproduce

1.  Run new gocd server with agent of above versions
2. Create a new pipeline with a custom command with following parameters:
command: `bash`
arg1: `-c`
arg2: `true`
Working Directory: `blank`
Run If Conditions: `Passed`

3. Run the pipeline and it fails
4. As an admin, bring up the edit config xml page and save it without making any changes to the config.
5. Run the pipeline from earlier and it should pass.

##### Expected Results
Step 3 from above should pass.

##### Actual Results
Step 3 fails with the following error:
```
[go] Task: bash -c  
 true
bash: -
: invalid option
Usage:	bash [GNU long option] [option] ...
	bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--pretty-print
	--rcfile
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
[go] Task status: failed, took: 0.131s, exited: 2
```

##### Possible Fix
Looks like parsing issue when saving from the UI that is correctly formatted when the config is re-evaluated and saved.

**Comment by GaneshSPatil** [comment] 2020-01-24 10:20
@thomasf1234 -- Looks like this issue is duplicate of https://github.com/gocd/gocd/issues/7557.

A fix for the same has been merged as part of https://github.com/gocd/gocd/pull/7561 PR for the upcoming GoCD release `v20.1.0`

Closing this issue as duplicate.

**Closed by GaneshSPatil** 2020-01-24 10:20 UTC
