### ISSUE TITLE
Agent does not report success status if a system service is started from shell scritpt, which is invoked using custom command task

### ISSUE THREAD

**Issue by sandye** [gocd/gocd#1079] opened 2015-04-29 07:47 UTC
I have a pipeline, which triggers, a shell script (custom command).
This shell internally starts two linux services (a tomcat service and another one). The problem is the job never ends, but it executes the shell script till the end.

And I found that, if I stop this services manually from command line, then go agent reports a success status back to server.

**Comment by arvindsv** [comment] 2016-06-04 13:23
Closing. It looks like the service did not go into the background, or left some files open. [This mailing list thread](https://groups.google.com/d/topic/go-cd/LtIJsV_HWRs/discussion) might help. Can re-open if it is confirmed that it is a GoCD issue.

**Closed by arvindsv** 2016-06-04 13:23 UTC
