### ISSUE TITLE
[Bug] Job running on all agents will hang (not timeout) if any agent has status missing or lostcontact

### ISSUE THREAD

**Issue by chrislovsund** [gocd/gocd#2798] opened 2016-10-20 07:38 UTC
##### Issue Type

- Bug Report

##### Summary
We have a scenario where a job should run on all agents every 10 minutes matching some resources. If an agent is missing or lostcontact the job will "never" fail nor pass, hindering the other agents from getting a new job every 10 minutes. 

###### Basic environment details

* Go Version: `16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)`
* JAVA Version: `1.7.0_111`
* OS: `Linux 3.10.0-327.36.1.el7.x86_64`
* Browser vendor and version (if relevant): `N/A but Chrome`

##### Steps to Reproduce

1. create a job that has `run_instances: all` and run every 5 minutes
2. at least one of the agents is in `missing` or `lostcontact` state. 
3. wait for run to start and see how it will hang.

##### Expected Results
This shouldn't effect all the other agents

##### Actual Results
Job hangs "forever" and doesn't fail or pass.

##### Possible Fix

Work Around:
The way to make the job run again is to either repair the missing agent or cancel the job. But cancelling the job will only work once I believe.

Long term:
Add Timeout mentioned in issue #1926 
Issue #2603 is slightly related.

**Comment by zabil** [comment] 2016-10-20 08:18
@chrislovsund 
This is to ensure that setup jobs (for e.g. installing, or removing software) must run on all agents before they are picked up by other jobs. 

You can try setting a timeout for the job to mark failure if the job does not complete within a specified time.

Closing this as it's not a bug. But please feel free to discuss the behavior.

**Closed by zabil** 2016-10-20 08:18 UTC

**Comment by chrislovsund** [comment] 2016-10-20 10:45
@zabil 
That makes sense to for it to not just rerun everything. But the problem is that it "never" timeouts.
I just tried having an agent with status `missing`, setting the job timeout to 1 minute.  
See config:
```xml
    <pipeline name="CleanMavenCache" isLocked="false">
      <timer>0 30 20 * * ?</timer>
      <materials>
        <git url="ssh://git@host/gocd.git" shallowClone="true" />
      </materials>
      <stage name="PurgeOldBinaries" cleanWorkingDir="true">
        <jobs>
          <job name="defaultJob" runOnAllAgents="true" timeout="1">
            <tasks>
              <exec command="/bin/bash" workingdir="admin">
                <arg>-c</arg>
                <arg>./clean_go_user_m2_cache.sh</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <resources>
              <resource>linux</resource>
            </resources>
          </job>
        </jobs>
      </stage>
    </pipeline>
```

After 10 minutes (other times much longer) the `missing` agent is still stuck in `Scheduled` 

![image](https://cloud.githubusercontent.com/assets/1794869/19556745/dc0a226a-96c2-11e6-9892-e5036beb1de7.png)

I'm happy if it is just a config change, but I have tried quite a few variations.

**Comment by zabil** [comment] 2016-10-21 03:44
@chrislovsund 
You are right, as the job is scheduled and not yet picked up by the agent (which went missing in this case) the timeout does not apply.

Why do these agents go missing? 

A possible workaround is using the Agents [API](https://api.go.cd/current/#agents) to remove the resource that's used by the job from the agents that go missing. Before running your "purgeOldBinaries" stage.

**Comment by chrislovsund** [comment] 2016-10-21 06:45
@zabil 
It is typically infrastructure problems, a machine or go-agent on it dies for some reason. Which is fine since the model with agents in GoCD is very resilient and just assigns the job to another agent with matching resources. As long as `run_instances: all` is not set, then that concept is broken I think. I guess the code logic wouldn't assign a job to a `missing` agent when job has `run_instances: 1`?

We monitor the infrastructure in other ways as well, but it would be nice to quickly see the pipeline turning red. 

Another work around is to monitor `https://gocd-server/go/api/jobs/scheduled.xml` to see if things are in there to long, we have wanted to do that for a while. Do you know anyone doing that or how that could be done?

**Comment by zabil** [comment] 2016-10-21 09:08
> As long as run_instances: all is not set, then that concept is broken I think. I guess the code logic wouldn't assign a job to a missing agent when job has run_instances: 1?

The server does not assign jobs to agent(s), instead the server schedules a job and waits for an agent to pick up and run it. 
The job is then marked assigned while the server waits for the agent to report the final status (passed,failed).

Even when a job is configured to "run on one instance" it'll remain scheduled until an agent picks it up. So if all the agents (that can run the job) go missing it remains scheduled indefinitely.

Again, this behavior is intentional (even for run on all instances) to get feedback and time to fix an agent that's gone missing so that it runs with the right revision of materials that triggered the pipeline.

**Comment by arvindsv** [comment] 2016-10-31 12:25
> Again, this behavior is intentional (even for run on all instances) to get feedback and time to fix an agent that's gone missing so that it runs with the right revision of materials that triggered the pipeline.

Might be worth considering adding a timeout which will fail the job, though. You'd get feedback, but not have a stage be in limbo forever. Right?
