### ISSUE TITLE
Missing Emoji support between 17.4 and 17.12

### ISSUE THREAD

**Issue by gbigwood** [gocd/gocd#4178] opened 2018-01-12 14:53 UTC
##### Issue Type

- Bug Report

##### Summary

Emojis are now rendering as `?` in log output. Note not the "`?` inside a diamond" character as fixed by https://github.com/gocd/gocd/commit/2a21e7cfa7296273b4e2843967403e16330f586c but instead just a `?`.

I think the above commit may be involved fixing an issue? (https://github.com/gocd/gocd/pull/3486) . My best guess is this is related.

##### Environment

They rendered as correct emoji in GoCD 17.4, but after moving to 17.12 they do not now.

###### Basic environment details

* Go Version: `17.12.0 (5626-cb7df2ffe421e43f2a682a7a323cb3a3e30734cc).`
* JAVA Version: `1.8.0_151`
* OS: `Linux 4.4.0-108-generic`
* Browser vendor and version (if relevant): `Firefox/Chrome etc all up to date`

##### Steps to Reproduce

1. Output an emoji into stdout
2. it will render as `?` in "console output" view

##### Expected Results
I see my emoji
##### Actual Results
I see `?`

##### Possible Fix
Utf8 plz

**Comment by varshavaradarajan** [comment] 2018-01-12 14:57
@gbigwood - [this](https://github.com/gocd/gocd/pull/4044) PR addresses the issue. Marking this issue as a duplicate of https://github.com/gocd/gocd/issues/3926

**Closed by varshavaradarajan** 2018-01-12 14:57 UTC

**Comment by gbigwood** [comment] 2018-01-12 14:59
thanks!
