### ISSUE TITLE
Update Yum plugin to work on CentOS/RHEL 8

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#8389] opened 2020-07-29 01:05 UTC
RHEL 8 distros have switched to `dnf` as the package manager, with `yum` as an alias.

The `repoquery` tool in such newer distros does not support the `BUILDHOST` parameter. We should update the plugin to no longer query for this data. Currently, the `BUILDHOST` field is stored in the `comment` field in the `modifications` table. We should stop doing this so that the plugin works on RHEL 8 distros.

**Comment by maheshp** [comment] 2020-08-25 04:26
Duplicate of - https://github.com/gocd/gocd/issues/8404

**Closed by maheshp** 2020-08-25 04:26 UTC
Labels: package materials, technical-debt
