### ISSUE TITLE
Massive cpu load increase for version 18.2.0, server becomes unresponsive

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#4510] opened 2018-03-09 14:11 UTC
##### Issue Type

- Bug Report

##### Summary

After upgrading to go.cd version 18.2.0-6228 the cpu load on the server is much higher than it was on version  18.2.0-6228. It makes the go.cd server interface practically unusable.

![gocd-server-cpu-increase](https://user-images.githubusercontent.com/136472/37210665-d6a2008e-23a9-11e8-9a39-b864fe9ca4bb.png)

###### Basic environment details

* Go Version: `18.2.0 (6228-fbb379a451871b29aa47aef907a78dc64379233f)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.4.86+`

##### Expected Results

Usually after an upgrade a server is slower for the first couple of minutes, but then it settles and works fine.

##### Actual Results

Now it's still unresponsive after half an hour.

**Comment by JorritSalverda** [comment] 2018-03-09 14:43
I rolled back to the previous version on one of our largest servers and it works fine within minutes. I still have some servers on the new version to assist in getting to the bottom of this issue, although they work slightly better.

**Comment by ketan** [comment] 2018-03-09 14:47
Keep us posted, we're watching this issue and are planning another follow up release in a couple of weeks. (To make the new dashboard the default after fixing some of the known issues mentioned in the release notes)

**Comment by JorritSalverda** [comment] 2018-03-09 15:12
Not so sure it's cpu related. The rolled back version used up a lot of cpu for 10 minutes as well and then settled down. 

However in the servers still on the new version updating pipeline environment variables (or parameters, or any other settings) is much slower than it was on the previous version. Has anything changed in the way the config xml is updated / saved / loaded?

**Comment by ketan** [comment] 2018-03-09 15:36
> Not so sure it's cpu related. The rolled back version used up a lot of cpu for 10 minutes as well and then settled down.

That is expected — agents will perform an upgrade as soon as the server boots up. After a few minutes of usage, the JIT and hotspot kicks in and the performance improves (and decreasing the system load).

> However in the servers still on the new version updating pipeline environment variables (or parameters, or any other settings) is much slower than it was on the previous version. Has anything changed in the way the config xml is updated / saved / loaded?

That is a bit odd — I don't believe anything with the config xml save has changed (I will verify later). Are you using the new dashboard by any chance — and are you performing full config XML saves periodically?

**Comment by ketan** [comment] 2018-03-09 15:37
Fat fingered the send button. If you are performing a full config save periodically, could you hold off doing the changes for a few minutes and see if the performance improves?

**Comment by jyotisingh** [comment] 2018-03-09 15:38
> Has anything changed in the way the config xml is updated / saved / loaded?

Not really. However upon a successful config save, the new dashboard cache gets updated but that's a background activity. It will not stop your config save, but I am just wondering if that's what's causing the CPU spikes. Could you tell if you used the old UI or full config save or the 'quick edit' UI for updating your pipelines when you noticed slow config save? Would it be possible for you to use the 'quick edit' UI to save a pipeline and check if there is any difference? 

Needed some more information. 
* What's the pipeline count on the larger server that you had to rollback? By any chance do you have the output of api/support or thread-dumps from the time that you captured the attached graph?

* Could you share a few thread-dumps from one of the servers which is still on the new version when you see that slowness?

**Comment by JorritSalverda** [comment] 2018-03-14 16:16
I've used the full config save pipeline edit screen (the default). The larger server has 555 pipelines. I just took some dumps from api/support from a server with 450 pipelines while updating pipeline parameters. Is there any way I can send these to you via email so I don't have to redact them?

**Comment by ketan** [comment] 2018-03-14 16:21
Send it to support(at)thoughtworks.com with a link to this issue. Someone should be able to take a look at them.

**Comment by ketan** [comment] 2018-05-16 04:49
Closing since @JorritSalverda confirmed on the internal support ticket that the performance has improved with 18.5

**Closed by ketan** 2018-05-16 04:49 UTC

**Comment by d-led** [comment] 2018-12-19 09:32
![cpu_anomaly1](https://user-images.githubusercontent.com/1716584/50211526-22209e80-0379-11e9-98d0-6754a034bcb6.png)

We have noticed a pattern similar to the one in this issue after network disconnects, DNS down,  when agents get new IP addresses, and, perhaps, other events. I dont't have a stacktrace or a profiling info at hand, but when we looked at it, we couldn't see anything particular.

**Comment by bdpiparva** [comment] 2018-12-19 11:06
@d-led - @ketan and @JorritSalverda verified that issue has been resolved in 18.5.0. In order to replicate the issue locally please can you provide the `https://ci.example.com/go/api/support`.

**Comment by d-led** [comment] 2018-12-19 12:39
I think, my problem could have another reason. We're using 18.11
```
Go Server Version: | 18.11.0 (8024-68ad518659756345f346b74f7aa1cfa9ffd8a501)
-- | --
JVM version: | 1.8.0_191
OS Information: | Linux 4.15.0-42-generic
Usable space in artifacts repository: | 4.3 GB
Database schema version: | 1808002
Pipelines Count: | 114
```

**Comment by d-led** [comment] 2018-12-19 14:25
@arvindsv will do when it occurs again
