### ISSUE TITLE
Downstream Pipelines not scheduled after successful Manually Triggered Pipeline build

### ISSUE THREAD

**Issue by gavingmiller** [gocd/gocd#5028] opened 2018-08-14 14:33 UTC
##### Issue Type

- Bug Report

##### Summary

We've experienced a situation where our downstream, fan-out pipelines won't auto-schedule when the current pipeline (pictured below) has been manually or automatically triggered .

![screen shot 2018-08-03 at 11 35 26 am](https://user-images.githubusercontent.com/452161/43657122-0a2e6740-9712-11e8-845f-dcc4e4425110.png)

![screen shot 2018-08-03 at 11 36 08 am](https://user-images.githubusercontent.com/452161/43657128-0d7582bc-9712-11e8-804e-c3c2a8cb6e80.png)

We triggered the pipeline manually to start with and it was successfully picked up and scheduled by the downstream jobs. But then when we triggered the build with a commit, it was not picked up. We've also experienced the opposite. 

My initial hypothesis on the subsequent build not triggering was that the artifacts were binary equivalent, but that appears to not be the case:

```
$ diff rpm1-buildA.rpm rpm1-buildB.rpm
Binary files rpm1-buildA.rpm and rpm1-buildB.rpm differ
```

##### Environment

skipped. available if required

###### Basic environment details

* Go Version: `18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)` 
* JAVA Version: `1.8.0_181`  
* OS: `Linux 2.6.32-573.7.1.el6.x86_64` 

##### Steps to Reproduce

Not available at this time.

##### Expected Results

When manually triggered a pipeline build, I would expect the downstream builds to trigger as well once the pipeline completes successfully.

##### Actual Results

The triggered pipeline builds and runs to completion and the downstream pipelines do not trigger.

##### Log snippets

Unable to find any log snippets that appear relevant. Our original guess was a skewed clock on the go master server, but this issue still occurred once we resolved that issue.

Original issue was https://github.com/gocd/gocd/issues/4981 with an outdated go.cd instance.

**Comment by arvindsv** [comment] 2018-08-31 12:46
@gavingmiller This is strange. Would it be possible for you to provide more details to be able to reproduce this? Or, can you try with a different pipeline that you set up with a simple material, so that we can isolate this?

Could all the downstream pipelines have a material which is not found? So, they cannot trigger? If so, you'd look at the "Errors and Warnings" modal box and the VSM of an older run of one of those materials.

**Comment by gavingmiller** [comment] 2018-08-31 16:40
@arvindsv Went back to find details, and the pipeline did eventually trigger. 

![vsm-pipelines](https://user-images.githubusercontent.com/452161/44924312-23fe1d80-ad08-11e8-9812-dc1f6730bc96.png)


Here's the timestamps corresponding to the image above:

```
Pipeline A: Automatically triggered on 03 Aug 2018 at 10:14:58 Local TimeDuration: 00:34:33
Pipeline B: Automatically triggered on 03 Aug 2018 at 23:15:03 Local TimeDuration: 00:00:20
```

So an approximately 12 hour lag between being triggered downstream. I have logs for that day. Is there anything I can provide / look for that would help determine the root cause?

**Comment by arvindsv** [comment] 2018-08-31 17:17
@gavingmiller Ok. And, what does the VSM of Instance 1120 of Pipeline B look like?

**Comment by arvindsv** [comment] 2018-08-31 22:29
A little hard to understand because of all the redactions :), but I'm glad you know why. My guess is that the pipeline labeled "Pipeline D" is the same as the one labeled "Pipeline A" earlier. Essentially, "Pipeline D" was what you were looking at and you saw that "Pipeline B" didn't trigger.

What had happened was that "Pipeline D" had a sibling, "Pipeline C", which was waiting on "Pipeline E". Since there is a fan-in, "Pipeline B" was waiting.

Alright. Closing this issue then. Thanks for following up!

**Closed by arvindsv** 2018-08-31 22:29 UTC
