### ISSUE TITLE
go cd website uses a GitHub certificate for HTTPS

### ISSUE THREAD

**Issue by darrenhaken** [gocd/gocd#1582] opened 2015-10-27 14:49 UTC
Go CD should supply its own SSL cert or disable HTTPS traffic for now.

**Comment by matt-richardson** [comment] 2015-11-09 08:26
Because?

**Comment by darrenhaken** [comment] 2015-11-13 15:44
This means that when I tried to access the site via HTTPS my browser gives me a security warning telling me that the website should not be trusted.

Do you want to communicate this message to people?

**Comment by zabil** [comment] 2015-11-18 08:02
@darrenhaken thanks for pointing this out. 
It's caused by the github logo that's being fetched from github via the github oauth plugin. It won't happen on a stock installation.

A long term solution, if feasible, is to figure out how the plugins can bundle certs.

**Comment by darrenhaken** [comment] 2015-11-19 13:17
Thanks @zabil . Yep this is talking about go.cd

**Comment by arvindsv** [comment] 2015-12-06 18:42
This is done. Closing this.

**Closed by arvindsv** 2015-12-06 18:42 UTC
