### ISSUE TITLE
Issue with pipeline ordering on pipelines view

### ISSUE THREAD

**Issue by omnidavesz** [gocd/gocd#1813] opened 2016-01-19 10:20 UTC
I've found an issue where the order of the pipelines on the main pipeline view does not conform to the order in the pipeline administration section / config.xml. The following screenshots will highlight the issue.

1. This is the order in which the pipelines appear in the admin section and config.xml:
![adminview](https://cloud.githubusercontent.com/assets/12997902/12415900/30b7a770-be96-11e5-9708-317917387056.jpg)

2. And here is the order on the pipelines view:
![pipeview](https://cloud.githubusercontent.com/assets/12997902/12415904/36f80670-be96-11e5-8716-285ade2484fb.jpg)

As can be seen, the order of the PROD and PAT pipelines has gotten a bit mixed up. Could this issue be looked into please?

**Comment by xli** [comment] 2016-01-22 21:43
I'll check this out

**Comment by xli** [comment] 2016-01-22 22:58
@omnidavesz I can't reproduce the problem you mentioned. Could you provide more details? Is the pipelines view always like the screenshot you posted? 
"undeploy_PAT" and "undeploy_PROD" have no build in your screenshot, are they just created?
What's the order you created them and do you changed order after created them? Do you refresh pipelines view after changed order?

**Comment by omnidavesz** [comment] 2016-01-25 09:41
@xli Thanks for looking at this. The pipeline view is always displayed as the screenshot shows. We generate the pipeline via a Jenkins job which runs a Java jar using the GoCD SDK. 

I've put logging in place and that shows the order in which the pipelines are created is Build, PAT, undeploy_PAT, PROD, undeploy_PROD. We do not change the order after creation. 

Also, undeploy_PAT and undeploy_PROD are just created, they should not have a Build pipeline.

What I find particularly confusing is that when we specify an environment (e.g. AUPROD) that should have pipelines which run after the PROD pipelines they appear in the correct order. Not sure if this helps.

If you have any more queries please let me know.

**Comment by jyotisingh** [comment] 2016-01-25 12:45
@omnidavesz - Well the order of display of pipelines on dashboard depends on two things -  the positioning  of pipeline in config xml and second being the build status(ie. if the pipeline was ever built). If the pipeline has never been triggered (success or failure does not matter), then the pipeline moves to the bottom of the group as far as display on dashboard is concerned. Even if you have had a single trigger of the pipeline, it would start getting displayed in the order it appears in the config xml.

**Comment by ketan** [comment] 2016-01-27 04:58
Closing since @jyotisingh has explained the current behavior — and it seems consistent with what's being observed — that "undeploy_PAT" and "undeploy_UAT" are rendered at the end.

Once there's at-least one run of the pipeline, they'll appear in the right place.

**Closed by ketan** 2016-01-27 04:58 UTC
Labels: bug, dashboard
