### ISSUE TITLE
get server identifier in plugin developing

### ISSUE THREAD

**Issue by Qinmu-Xie** [gocd/gocd#3341] opened 2017-04-01 09:50 UTC
##### Issue Type

- Feature enhancement

##### Summary

How can I get serverId which is generated by server **IN Notification Plugins**.
I want to use this information to identify which server's data is notifying my service.

**Comment by varshavaradarajan** [comment] 2017-05-22 09:12
Closing as a duplicate of https://github.com/gocd/gocd/issues/3401

**Closed by varshavaradarajan** 2017-05-22 09:12 UTC
