### ISSUE TITLE
Feature enhancement: Add Agent 'Clean Working Directory' after artifacts upload

### ISSUE THREAD

**Issue by patrick92100** [gocd/gocd#2047] opened 2016-03-10 16:29 UTC
Feature enhancement

At the stage level , add Agent 'Clean Working Directory' after artifacts upload option;

in addition to the 'Clean Working Directory' before Job execution, it will be great to have the option to be able to Clean Working Directory at the end of the Job, after the artifacts upload.

benefits of clean Working Directory after execution
- do not consume disk space on Agents
- reduce visibility of the code distributed on Agents

**Comment by patrick92100** [comment] 2016-03-10 16:30
do not consume disk space 
reduce visibility of the code distributed on agents

**Comment by jreast** [comment] 2017-09-08 08:40
#2070

**Comment by jreast** [comment] 2017-09-08 08:42
Can this be closed as a duplicate of #2070 it is confusing as it seems this has been ignored but actually 2070 has much more information about why.

**Comment by ketan** [comment] 2017-09-08 08:48
Closing as dup of #2070 (thanks for triaging @jreast)

**Closed by ketan** 2017-09-08 08:48 UTC
Labels: agents, artifacts, enhancement
