### ISSUE TITLE
Environments API does not provide encrypted variables in 19.1

### ISSUE THREAD

**Issue by mortenhermanconsulting** [gocd/gocd#6128] opened 2019-04-11 11:59 UTC
##### Issue Type
- Bug Report
##### Summary

After upgrading from go server 18.12 to go server 19.1 the environments api no longer returns the encrypted value for secure variables.

secure      name                encrypted_value
  True        Pass                  ****           

previously I got Values like this one constructed below from the API

secure     name               encrypted_value                                      
  True       Pass                 AES:zhU33Hiix5SY9E/nS4rItw==:QwxTLtNxxa1rBTK6wImXAg==

##### Environment
I pasted the support json from the API, minus GC, threads and other items that would seem unrelated to API and configuration (if the problem is as such)

```plain
{
    "Timestamp": "2019-04-11T13:02:21+02:00",
    "Go Server Information": {
        "Version": "19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4)"
    },
    "Config Statistics": {
        "Valid Config": {
            "Number of pipelines": 2,
            "Number of agents": 1,
            "Number of environments": 1,
            "Number of unique materials": 1,
            "Number of schedulable materials": 1
        },
        "Security": {
            "Plugins": [
                {
                    "Password File Authentication Plugin for GoCD": false
                },
                {
                    "LDAP Authentication Plugin for GoCD": true
                }
            ],
            "Enabled": true
        }
    },
    "Config file locations": {
        "loc.config.dir": "D:\\app\\Go Server\\config",
        "loc.log.root.0": "D:\\APP\\Go Server\\logs",
        "loc.log.basename.0": "go-server.log",
        "loc.log.root.1": "D:\\APP\\Go Server\\logs",
        "loc.log.basename.1": "go-shine.log",
        "loc.log.root.2": "D:\\APP\\Go Server\\logs",
        "loc.log.basename.2": "plugin-cd.go.authentication.ldap.log",
        "loc.log.root.3": "D:\\APP\\Go Server\\logs",
        "loc.log.basename.3": "plugin-cd.go.authentication.passwordfile.log"
    },
    "OS Information": {
        "OS Name": "Windows Server 2016",
        "OS Version": "10.0",
        "System Architecture": "amd64",
        "Available Processors": 4,
        "Average System Load": -1.0
    },
    "Runtime Information": {
        "Name": "[SERVERNAME]",
        "Uptime": 1564829,
    "Uptime (in Time Format)": "[About 0 hours, 26 minutes, 4 seconds]",
        "Spec Name": "Java Virtual Machine Specification",
        "Spec Vendor": "Oracle Corporation",
        "Spec Version": "11",
        "Input Arguments": [
            "-Xms512m",
            "-Xmx1024m",
            "-DreservedForFuture.6",
            "-XX:MaxMetaspaceSize=400m",
            "-Duser.language=en",
            "-Duser.country=US",
            "-Dcruise.config.dir=D:\\app\\Go Server\\config",
            "-Dcruise.config.file=D:\\app\\Go Server\\config\\cruise-config.xml",
            "-Dcruise.server.port=8153",
            "-Dcruise.server.ssl.port=8154",
            "-DJAVA_SYS_MON_TEMP_DIR=D:\\app\\Go Server\\tmp",
            "-Dno_debugging",
            "-Dno_gc_logging",
            "-DreservedForFuture.4",
            "-DreservedForFuture.5",
            "-Dfile.encoding=Cp1252",
            "-Djava.library.path=lib",
            "-Dwrapper.key=rqtKI6UrP6aTlQi1d7v8tuFDOECwk0of",
            "-Dwrapper.port=32000",
            "-Dwrapper.jvm.port.min=31000",
            "-Dwrapper.jvm.port.max=31999",
            "-Dwrapper.pid=8924",
            "-Dwrapper.version=3.5.30-st",
            "-Dwrapper.native_library=wrapper",
            "-Dwrapper.arch=x86",
            "-Dwrapper.service=TRUE",
            "-Dwrapper.cpu.timeout=10",
            "-Dwrapper.jvmid=1",
            "-Dwrapper.lang.domain=wrapper",
            "-Dwrapper.lang.folder=../lang"
        ],
        "System Properties": {
            "JAVA_SYS_MON_TEMP_DIR": "D:\\app\\Go Server\\tmp",
            "awt.toolkit": "sun.awt.windows.WToolkit",
            "cruise.config.dir": "D:\\app\\Go Server\\config",
            "cruise.config.file": "D:\\app\\Go Server\\config\\cruise-config.xml",
            "cruise.server.port": "8153",
            "cruise.server.ssl.port": "8154",
            "file.encoding": "Cp1252",
            "file.separator": "\\",
            "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
            "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
            "java.class.path": "lib/wrapper.jar;go.jar",
            "java.class.version": "55.0",
            "java.home": "D:\\app\\Go Server\\jre",
            "java.io.tmpdir": "C:\\Windows\\TEMP\\",
            "java.library.path": "lib",
            "java.protocol.handler.pkgs": "com.thoughtworks.gocd",
            "java.runtime.name": "OpenJDK Runtime Environment",
            "java.runtime.version": "11.0.1+13",
            "java.specification.name": "Java Platform API Specification",
            "java.specification.vendor": "Oracle Corporation",
            "java.specification.version": "11",
            "java.vendor": "Oracle Corporation",
            "java.vendor.url": "http://java.oracle.com/",
            "java.vendor.url.bug": "http://bugreport.java.com/bugreport/",
            "java.vendor.version": "18.9",
            "java.version": "11.0.1",
            "java.version.date": "2018-10-16",
            "java.vm.compressedOopsMode": "32-bit",
            "java.vm.info": "mixed mode",
            "java.vm.name": "OpenJDK 64-Bit Server VM",
            "java.vm.specification.name": "Java Virtual Machine Specification",
            "java.vm.specification.vendor": "Oracle Corporation",
            "java.vm.specification.version": "11",
            "java.vm.vendor": "Oracle Corporation",
            "java.vm.version": "11.0.1+13",
            "jdk.debug": "release",
            "jdk.tls.ephemeralDHKeySize": "matched",
            "jetty.base": "D:\\APP\\Go Server",
            "jetty.git.hash": "82b8fb23f757335bb3329d540ce37a2a2615f0a8",
            "jetty.home": "D:\\APP\\Go Server",
            "jetty.xml.file.name": "jetty.xml",
            "jruby.compile.invokedynamic": "false",
            "jruby.ji.objectProxyCache": "false",
            "jruby.management.enabled": "true",
            "line.separator": "\r\n",
            "net.sf.ehcache.skipUpdateCheck": "true",
            "no_debugging": "",
            "no_gc_logging": "",
            "os.arch": "amd64",
            "os.name": "Windows Server 2016",
            "os.version": "10.0",
            "path.separator": ";",
            "rails.use.compressed.js": "true",
            "reservedForFuture.4": "",
            "reservedForFuture.5": "",
            "reservedForFuture.6": "",
            "sun.arch.data.model": "64",
            "sun.boot.library.path": "D:\\app\\Go Server\\jre\\bin",
            "sun.cpu.endian": "little",
            "sun.cpu.isalist": "amd64",
            "sun.desktop": "windows",
            "sun.io.unicode.encoding": "UnicodeLittle",
            "sun.java.command": "org.tanukisoftware.wrapper.WrapperJarApp go.jar",
            "sun.java.launcher": "SUN_STANDARD",
            "sun.jnu.encoding": "Cp1252",
            "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
            "sun.os.patch.level": "",
            "user.country": "US",
            "user.dir": "D:\\APP\\Go Server",
            "user.home": "C:\\Windows\\system32\\config\\systemprofile",
            "user.language": "en",
            "user.name": "[SERVERNAME]$",
            "user.script": "",
            "user.timezone": "Europe/Paris",
            "user.variant": "",
            "wrapper.arch": "x86",
            "wrapper.cpu.timeout": "10",
            "wrapper.java.pid": "11420",
            "wrapper.jvm.port.max": "31999",
            "wrapper.jvm.port.min": "31000",
            "wrapper.jvmid": "1",
            "wrapper.key": "rqtKI6UrP6aTlQi1d7v8tuFDOECwk0of",
            "wrapper.lang.domain": "wrapper",
            "wrapper.lang.folder": "../lang",
            "wrapper.native_library": "wrapper",
            "wrapper.pid": "8924",
            "wrapper.port": "32000",
            "wrapper.service": "TRUE",
            "wrapper.version": "3.5.30-st"
        },
        "Environment Variables": {
            "=D:": "D:\\APP\\Go Server",
            "ALLUSERSPROFILE": "C:\\ProgramData",
            "APPDATA": "C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming",
            "COMPUTERNAME": "[SERVERNAME]",
            "CRUISE_SERVER_DIR": "D:\\app\\Go Server",
            "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
            "ChocolateyLastPathUpdate": "Tue Feb 19 15:17:46 2019",
            "ComSpec": "C:\\Windows\\system32\\cmd.exe",
            "CommonProgramFiles": "C:\\Program Files\\Common Files",
            "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
            "CommonProgramW6432": "C:\\Program Files\\Common Files",
            "DEFLOGDIR": "C:\\ProgramData\\McAfee\\DesktopProtection",
            "GC_LOG": "-Dno_gc_logging",
            "GC_LOG_LOCATION": "\"D:\\app\\Go Server\\go-server-gc.log\"",
            "GO_AGENT_DIR": "C:\\Program Files (x86)\\Go Agent",
            "GO_AGENT_JAVA_HOME": "C:\\Program Files (x86)\\Go Agent\\jre",
            "GO_SERVER_JAVA_HOME": "D:\\app\\Go Server\\jre",
            "GO_SERVER_URL": "https://127.0.0.1:8154/go",
            "JAVA_HOME": "D:\\app\\Go Server\\jre",
            "JVM_DEBUG": "-Dno_debugging",
            "JVM_DEBUG_PORT": "5005",
            "LANG": "en_US.UTF-8.UTF-8",
            "LOCALAPPDATA": "C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local",
            "NUMBER_OF_PROCESSORS": "4",
            "OS": "Windows_NT",
            "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
            "PROCESSOR_ARCHITECTURE": "AMD64",
            "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 63 Stepping 0, GenuineIntel",
            "PROCESSOR_LEVEL": "6",
            "PROCESSOR_REVISION": "3f00",
            "PSModulePath": "WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Windows\\DIMA\\Engine\\Modules;C:\\Program Files\\Microsoft Message Analyzer\\PowerShell\\;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\",
            "PUBLIC": "C:\\Users\\Public",
            "Path": "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\PowerShell\\6\\;C:\\opscode\\chef\\bin\\;C:\\Program Files\\Git\\cmd;c:\\opt\\sensu\\bin;c:\\opt\\sensu\\embedded\\bin;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps",
            "ProgramData": "C:\\ProgramData",
            "ProgramFiles": "C:\\Program Files",
            "ProgramFiles(x86)": "C:\\Program Files (x86)",
            "ProgramW6432": "C:\\Program Files",
            "SystemDrive": "C:",
            "SystemRoot": "C:\\Windows",
            "TEMP": "C:\\Windows\\TEMP",
            "TMP": "C:\\Windows\\TEMP",
            "UATDATA": "C:\\Windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77",
            "USERDOMAIN": "[DOMAN]",
            "USERNAME": "[SERVERNAME]$",
            "USERPROFILE": "C:\\Windows\\system32\\config\\systemprofile",
            "VSEDEFLOGDIR": "C:\\ProgramData\\McAfee\\DesktopProtection",
            "WRAPPER_ARCH": "x86",
            "WRAPPER_BIN_DIR": "D:\\APP\\Go Server",
            "WRAPPER_BITS": "64",
            "WRAPPER_CONF_DIR": "D:\\APP\\Go Server\\config",
            "WRAPPER_FILE_SEPARATOR": "\\",
            "WRAPPER_HOSTNAME": "[SERVERNAME]",
            "WRAPPER_HOST_NAME": "[SERVERNAME]",
            "WRAPPER_INIT_DIR": "C:\\Windows\\system32",
            "WRAPPER_LANG": "en",
            "WRAPPER_OS": "windows",
            "WRAPPER_PATH_SEPARATOR": ";",
            "WRAPPER_PID": "8924",
            "WRAPPER_WORKING_DIR": "D:\\APP\\Go Server",
            "windir": "C:\\Windows"
        }
    },
    "Server Health Information": {
        "Messages Count": 0,
        "Messages": [
            
        ]
    },
    "com.thoughtworks.go.server.service.support.CacheInformationProvider": "Provider class com.thoughtworks.go.server.service.support.CacheInformationProvider threw an exception: null",
    "Config Git Repository": {
        "Number of commits": 28095,
        "GC Statistics": {
            "numberOfPackedRefs": 0,
            "numberOfPackFiles": 1,
            "sizeOfLooseObjects": 2122867,
            "numberOfLooseObjects": 405,
            "numberOfPackedObjects": 83124,
            "numberOfLooseRefs": 2,
            "sizeOfPackedObjects": 14735125
        }
    },
    "Feature Toggles": {
        "Available Toggles": [
            {
                "key": "pipeline_comment_feature_toggle_key",
                "description": "Enables commenting on a pipeline run, in the pipeline history view. See more at: https://docs.gocd.org/current/beta/comment_on_pipeline_run.html. Default: off.",
                "value": false,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "browser_console_log_ws_key",
                "description": "Enables rendering console logs via websockets. Default: disabled.",
                "value": false,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "use_old_auth_config_spa",
                "description": "Switch to old authorization configuration spa. Default is new spa.",
                "value": false,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "use_old_artifact_stores_spa",
                "description": "Switch to old artifact stores spa. Default is component based spa.",
                "value": false,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "users_page_using_rails",
                "description": "Switch users page to use spark.",
                "value": true,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "use_old_roles_spa",
                "description": "Switch roles configuration spa to use old spa.",
                "value": false,
                "hasBeenChangedFromDefault": false
            },
            {
                "key": "use_old_environments_api",
                "description": "Switch to using rails environments API.",
                "value": false,
                "hasBeenChangedFromDefault": false
            }
        ]
    },
    "Plugin information": {
        "plugins": [
            {
                "id": "yum",
                "type": [
                    
                ],
                "version": "2.0.3",
                "bundled_plugin": true,
                "status": {
                    "state": "INVALID",
                    "messages": [
                    "Plugin with ID (yum) is not valid: Incompatible with current operating system \u0027Windows\u0027. Valid operating systems are: [Linux]."
                    ],
                    "rootCauseIfInvalid": null
                }
            },
            {
                "id": "cd.go.authentication.passwordfile",
                "type": [
                    "authorization"
                ],
                "version": "1.0.3-57",
                "bundled_plugin": true,
                "status": {
                    "state": "ACTIVE",
                    "messages": [
                        
                    ],
                    "rootCauseIfInvalid": null
                }
            },
            {
                "id": "cd.go.authentication.ldap",
                "type": [
                    "authorization"
                ],
                "version": "1.0.3-62",
                "bundled_plugin": true,
                "status": {
                    "state": "ACTIVE",
                    "messages": [
                        
                    ],
                    "rootCauseIfInvalid": null
                }
            },
            {
                "id": "yaml.config.plugin",
                "type": [
                    "configrepo"
                ],
                "version": "0.8.6",
                "bundled_plugin": true,
                "status": {
                    "state": "ACTIVE",
                    "messages": [
                        
                    ],
                    "rootCauseIfInvalid": null
                }
            },
            {
                "id": "json.config.plugin",
                "type": [
                    "configrepo"
                ],
                "version": "0.3.6",
                "bundled_plugin": true,
                "status": {
                    "state": "ACTIVE",
                    "messages": [
                        
                    ],
                    "rootCauseIfInvalid": null
                }
            },
            {
                "id": "sonar.quality.gate.plugin",
                "type": [
                    "task"
                ],
                "version": "1.0.0",
                "bundled_plugin": false,
                "status": {
                    "state": "ACTIVE",
                    "messages": [
                        
                    ],
                    "rootCauseIfInvalid": null
                }
            }
        ]
    }
}

```

###### Basic environment details

Go Server Version: | 19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4)
JVM version: | 11.0.1
OS Information: | Windows Server 2016 10.0
Invoked language was powershell

###### Additional Environment Details

None
##### Steps to Reproduce

I created a secure variable in an early version of go server 17.xx. I have upgraded the go server on minor version at a time and is using the environments api to extract variables, and decipher them.
I created the script in powershell 5 that when executed will find the first secure environment variable and decrypt it. The script works prior when version is less than or equal to 18.12 and fails on version 19.1.

```
$InformationPreference = "Continue"
$pair = "USERNAME:PASSWORD"
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
$CredentialHeaders = @{Authorization = "Basic $encodedCreds"}
$ApiVersion2Header = @{Accept = "application/vnd.go.cd.v2+json"}


$GoServerDnsName ="GOSERVER-HOSTNAME/DNS"
$AesCipherPath = "PATH-TO-AES-CIPHER-FILE"


Write-Information "Fetching Environments:" 
$environments = Invoke-RestMethod -Method Get -Uri  "https://${GoServerDnsName}:8154/go/api/admin/environments/" -Headers ($CredentialHeaders + $ApiVersion2Header) -ContentType 'application/json'  -Verbose
Write-Information "Environments found:"
Write-Information ($environments._embedded.environments.name)

$secureVariable = $environments._embedded.environments.environment_variables | Where-Object {$_.secure} | Select-Object -First 1

Write-Information "Testing Decryption of Value: $($secureVariable.encrypted_value)"

$GoEncryptedVariableArray = $secureVariable.encrypted_value -split ":"
$InitializationVector = $GoEncryptedVariableArray[1]
$InitializationVectorBytes = [System.Convert]::FromBase64String($InitializationVector)

$EncryptedValue = $GoEncryptedVariableArray[2] 
$EncryptedValuebytes = [System.Convert]::FromBase64String($EncryptedValue)


$Cipher = Get-Content $AesCipherPath
$CipherKeyBytes = [byte[]]::new($Cipher.Length / 2)
For ($i = 0; $i -lt $cipher.Length; $i += 2) {
    $CipherKeyBytes[$i / 2] = [convert]::ToByte($Cipher.Substring($i, 2), 16)
}


$aesManaged = New-Object "System.Security.Cryptography.AesManaged"
$aesManaged.Mode = [System.Security.Cryptography.CipherMode]::CBC
$aesManaged.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7
$aesManaged.BlockSize = 128
$aesManaged.KeySize = 256
$aesManaged.IV = $InitializationVectorBytes
$aesManaged.Key = $CipherKeyBytes
$decryptor = $aesManaged.CreateDecryptor()
$DeCryptedBytes = $decryptor.TransformFinalBlock($EncryptedValuebytes, 0, $EncryptedValuebytes.Length)
$aesManaged.Dispose()

Write-Information ([System.Text.Encoding]::UTF8.GetString($DeCryptedBytes).Trim([char]0))

```

##### Expected Results
I would expect the environments api to return AES encrypted variables as described in the API.

I tried to create a new variable in version 19.1 to see if this was a migration issue, but the api still returns **** as the encrypted_value property for the variables.

##### Actual Results
The API return variables with the value '****'

**Comment by ketan** [comment] 2019-04-11 12:16
Marking as duplicate of #5956. This issue has been fixed and due for release with 19.3.

**Closed by ketan** 2019-04-11 12:16 UTC
