### ISSUE TITLE
Unneeded classes from class path are loaded with plugin

### ISSUE THREAD

**Issue by margueritepd** [gocd/gocd#1351] opened 2015-07-15 18:36 UTC
Hello,

I have compiled and installed [the gocd hipchat plugin](https://github.com/PagerDuty/gocd-hipchat-plugin). During plugin load, there are errors in the gocd logs:

```
2015-05-13 08:45:12,320 ERROR [Thread-65] FelixGoPluginOSGiFramework:124
- Failed to load plugin: plugins_work\gocd-hipchat-plugin.jar. Plugin is
  invalid. Reasons [
Class [scala.tools.ant.ClassloadVerify] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.FastScalac] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.Pack200Task] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.Same] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.Scalac] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.Scaladoc] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.ScalaMatchingTask] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.ScalaTool] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.sabbus.Break] could not be loaded. Message: [org/apache/tools/ant/Task].,
Class [scala.tools.ant.sabbus.Make] could not be loaded. Message: [org/apache/tools/ant/Task].,
Class [scala.tools.ant.sabbus.ScalacFork] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.ant.sabbus.Use] could not be loaded. Message: [org/apache/tools/ant/taskdefs/MatchingTask].,
Class [scala.tools.nsc.interpreter.JLineDelimiter] could not be loaded.  Message: [scala/tools/jline/console/completer/ArgumentCompleter$ArgumentDelimiter].,
Class [scala.tools.nsc.interpreter.JLineReader$$anon$1] could not be loaded. Message: [scala/tools/jline/console/completer/Completer].,
Class [scala.tools.nsc.interpreter.JLineReader$JLineConsoleReader] could not be loaded. Message: [scala/tools/jline/console/ConsoleReader].,
Class [scala.tools.nsc.interpreter.session.FileBackedHistory] could not be loaded. Message: [scala/tools/jline/console/history/History].,
Class [scala.tools.nsc.interpreter.session.JLineHistory$JLineFileHistory] could not be loaded. Message: [scala/tools/jline/console/history/History].,
Class [scala.tools.nsc.interpreter.session.JLineHistory] could not be loaded.  Message: [scala/tools/jline/console/history/History].,
Class [scala.tools.nsc.interpreter.session.SimpleHistory$Entry] could not be loaded. Message: [scala/tools/jline/console/history/History$Entry].,
Class [scala.tools.nsc.interpreter.session.SimpleHistory] could not be loaded. Message: [scala/tools/jline/console/history/History].
]
```

I believe the errors regarding `org/apache/tools/ant/taskdefs/MatchingTask` are because the plugin depends on `scala-compiler`, which has an optional (and, in our case, unneeded) dependency on `ant`. However, [this line in gocd](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-activator/src/com/thoughtworks/go/plugin/activation/DefaultGoPluginActivator.java#L272) loads all the classes in the class path, including the unneeded classes in `scala-compiler` that need `ant`. Thus we get the errors above. (The second set of errors is due to a similar situation.)

Would it be possible to leverage class auto-loading, instead of explicitly loading all classes in the class path?

**Comment by arvindsv** [comment] 2015-07-15 20:51
> Would it be possible to leverage class auto-loading, instead of explicitly loading all classes in the class path?

Not really. It is doing that to find and load all classes with the @Extension annotation. It looks like the plugin has been created by exploding all of the dependencies into the base directory. As you can see from [the documentation](http://www.go.cd/documentation/developer/writing_go_plugins/go_plugins_basics.html#structure-of-a-go-plugin), dependency JARs are supposed to be packaged into the `lib/` directory and not exploded. That's the change that is needed. It might need some messing around with the sbt-assembly plugin. Unfortunately, I don't know enough about scala or sbt-assembly to help. I see that you've found [another way](https://github.com/PagerDuty/gocd-hipchat-plugin/pull/9) to fix it as well, but I'd try and get the dependency JARs packaged in `lib/` instead. Go will not do anything to those JARs and will just make them available for auto loading.

I'll close this for now, since I think it is working as designed and is not something that is likely to change. However, we can continue discussing this and I will be happy to reopen it if we all agree.

**Closed by arvindsv** 2015-07-15 20:51 UTC

**Comment by arvindsv** [comment] 2015-07-15 20:53
Also, exploding the dependencies there will slow down loading of the plugin, since those classes need to be scanned. Without scanning, Go won't even know what plugin endpoints are implemented inside the plugin JAR.

**Comment by margueritepd** [comment] 2015-07-17 14:22
Thanks for the explanation. I will try with this new information!
