### ISSUE TITLE
When using "Trigger with options" on a pipeline with a non-polling material it doesnt reflect the latest commits

### ISSUE THREAD

**Issue by ryudice** [gocd/gocd#6387] opened 2019-06-04 14:45 UTC
##### Issue Type

- Bug Report

##### Summary

When running a ippeline with "Trigger with Options", it doesnt refresh changes from version control, if the material has been set to not poll for new changes

###### Basic environment details

* Go Version: `GoCD Version: 19.3.0 `
* JAVA Version: `1.8.0_201`
* OS: `Linux 4.4.0-148-generic`
* Browser vendor and version (if relevant): `Chrome`

##### Steps to Reproduce

1. Uncheck 
![image](https://user-images.githubusercontent.com/125211/58888394-8ecbf300-86a4-11e9-9eb4-8b3b372ec4ab.png)

2. Press on 
![image](https://user-images.githubusercontent.com/125211/58888071-03eaf880-86a4-11e9-8db5-28a50678ee56.png)

3. Material doesnt show latest commits
![image](https://user-images.githubusercontent.com/125211/58888441-9f7c6900-86a4-11e9-87ad-e4a78db3dd3b.png)

4

##### Expected Results
Material should update with latest commits

##### Actual Results
It doesnt show the latest commits since the last non-parametrized execution of pipeline

**Comment by arvindsv** [comment] 2019-06-04 20:02
Hello @ryudice. This is by design. If you turn off polling, it does not poll (run `git pull`) till you trigger. If you want to see it in the trigger with options dropdown, you'll need to turn on polling and then [make the stage manual](https://docs.gocd.org/current/configuration/dev_choose_when_stage_runs.html).

Closing, since this is not a bug, as far as I can see. Happy to reopen if we have further discussions and decide it's an issue. Thanks!

**Closed by arvindsv** 2019-06-04 20:02 UTC
