### ISSUE TITLE
Pipeline control buttons are not updated correctly

### ISSUE THREAD

**Issue by sfuhrm** [gocd/gocd#8629] opened 2020-10-09 07:57 UTC
##### Issue Type

- Bug Report

##### Summary

Frontend buttons of pipeline control are updated wrongly.

##### Environment

```plain
    "Version": "20.8.0 (12213-1e23a06e496205ced5f1a8e83d9b209fc0a290cb)"
    "OS Name": "Linux",
    "OS Version": "3.10.0-1062.9.1.el7.x86_64",
    "System Architecture": "amd64",
    "Available Processors": 4,
    "Average System Load": 0.1
```

###### Basic environment details

* Go Version: 20.8.0 (12213-1e23a06e496205ced5f1a8e83d9b209fc0a290cb)
* JAVA Version: 11.0.8
* OS: Linux 3.10.0-1062.9.1.el7.x86_64

* Browser vendor and version: Firefox 78.3.0.esr (Debian)

##### Steps to Reproduce

It is not clear how to reproduce this, it looks like a race condition.
Re-running the same pipeline does not trigger the same behaviour.

##### Expected Results

The buttons get updated, but there are not new button instances added over and over.
Only the button states (enabled/disabled) should be changed.

##### Actual Results

The pipeline control buttons (trigger pipeline, trigger with options, pause pipeline) get added to the pipeline pane over and over (see screenshot).

![gocd-buttonbug](https://user-images.githubusercontent.com/5055427/95557337-f28eca80-0a14-11eb-8b9e-9d3e0c580797.png)

The display of the status in the pipeline pane (green) differs from the display in the stage popup (yellow). I think this is the origin of the problem.

As you can see in the screenshot, the little arrow indicating which pipeline stage is being displayed in the popup is still show to be yellow while the pipeline itself is green.

**Comment by GaneshSPatil** [comment] 2020-10-12 08:51
@sfuhrm - Thank you for reporting the bug.

If you see this error happening again,
- can you go the developer's console and capture the errors/stacktraces from the console tab
- And capture the network call information to see any of the XHR call fails?

Please make sure you redact all the sensitive information (if any) before providing the above-mentioned details.

**Comment by sfuhrm** [comment] 2020-10-12 15:20
Hi @GaneshSPatil 

I'm beginning to believe that this is a Firefox bug and not a GoCD bug. Why should GoCD add the buttons over and over again?
Can you check whether the buttons are added or just attributes changed?

Stephan

**Comment by GaneshSPatil** [comment] 2020-10-13 03:08
Hello @sfuhrm 

There was a similar issue https://github.com/gocd/gocd/issues/8502 reported in the past. In that particular issue, the issue was with the stage overview API response. GoCD failed to parse the stage api json, causing multiple operation buttons on the pipeline tile.
Hence, it's likely some sort of race condition (a bug) within GoCD. 
Previously, with the help of the stack trace, we were able to reproduce and fix the issue. We will take a look at this issue again to see if we've missed any of the edge case scenarios.

**Comment by sfuhrm** [comment] 2020-10-13 07:47
@GaneshSPatil thanks, this is valuable input. The issue #8502 had a Chrome browser and I was using Firefox. So this is more probably on the GoCD side.

I'll watch out for the bug, but it's really hard to trigger. I've seen it only once. Do you have some ideas how to trigger this?

**Comment by GaneshSPatil** [comment] 2020-10-15 05:21
@sfuhrm - Hmm, race conditions are always hard to reproduce. 

Based on the information you've provided and the screenshot, it looks like a state issue when a stage changes from "building" to "passed". May be all the jobs from the stage are passed, but one of the job is in uploading artifacts state or something?

**Comment by sfuhrm** [comment] 2020-10-20 13:06
@GaneshSPatil I don't remember exactly, but I'd guess the race condition was ongoing long after the pipeline was finished.

**Comment by sfuhrm** [comment] 2021-01-23 13:31
I haven't seen this again.

**Comment by maheshp** [comment] 2021-01-25 05:45
Thanks, will close this issue for now. If you face this issue again please reopen with details.

**Closed by maheshp** 2021-01-25 05:45 UTC
