### ISSUE TITLE
Go redirects to 443 using a reverse proxy with non 443 port

### ISSUE THREAD

**Issue by hakito** [gocd/gocd#6068] opened 2019-04-03 13:57 UTC
##### Issue Type
Bug Report
##### Summary
Similar to #741 the access over a https reverse proxy seems still buggy. It works only if the proxy uses the standard 443 port. Probably this issue duplicates #3229.
##### Environment
It should be easy to reproduce using the following docker-compose.yml (replacing with a proper domain name of course)
```plain
version: '3.2'
services:
  gocd-server:
    image: gocd/gocd-server:v19.2.0

  gocd-ssl:
    image: danieldent/nginx-ssl-proxy
    environment:
      UPSTREAM: gocd-server:8153  
      SERVERNAME: example.com
    ports:
      # 443:443 would work
      - 583:443
```

**Comment by arvindsv** [comment] 2019-04-03 14:08
@hakito There's a [documented nginx proxy configuration](https://docs.gocd.org/current/installation/configure-reverse-proxy.html#gocd-with-nginx) which is known to work. In the case you brought up, it's unlikely that `X-Forwarded-For` and `X-Forwarded-Proto` are set, as mentioned in the resolution of issue 741: https://github.com/gocd/gocd/issues/741#issuecomment-287948224

The [documentation of danieldent/nginx-ssl-proxy](https://hub.docker.com/r/danieldent/nginx-ssl-proxy#optional-use-upstream-x-forwarded-for-headers) suggests using an environment variable to turn those on. Please try that. If that doesn't work, please try and reproduce it with a vanilla nginx config rather than this docker image proxy. That should help narrow down the issue.

Thank you!

**Comment by hakito** [comment] 2019-04-04 06:24
Sorry, I made a mistake in the issue description. Actually it is not redirecting to HTTP, it is stripping the port information in the HTTPS url.

I could reproduce it using the official [nginx](https://hub.docker.com/_/nginx) image.

I simply replaced the default.conf in the container with an adapted version of the [documented reverse-proxy configuration](https://docs.gocd.org/current/installation/configure-reverse-proxy.html#gocd-with-nginx). I replaced the domain and cert paths and added a proxy_pass entry.

```diff
@@ -26,5 +26,6 @@ server {
     proxy_http_version      1.1;
     proxy_set_header 	    Upgrade $http_upgrade;
     proxy_set_header 	    Connection $connection_upgrade;
+    proxy_pass              http://gocd-server:8153/;
   }
 }
```

It shows the _GoCD server is starting_ message on https://example.com:483 but then redirects to https://example.com without the port. I also set siteurl ande secure site url in the config to be sure that that is not the cause for the redirect.

**Comment by arvindsv** [comment] 2019-05-03 16:27
@hakito This seems more like an nginx question than a GoCD question, but something like this should work, with your docker-compose file (and an SSL cert + key in the `./gocd-ssl` directory).

```conf
server {
  # Redirect any http requests to https
  listen         80;
  server_name    gocd.example.com:483;
  return 301     https://$server_name$request_uri;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen                    443 ssl;
  server_name               gocd.example.com:483;

  ssl_certificate           /ssl/server.crt;
  ssl_certificate_key       /ssl/server.key;

  # Proxy everything over to the GoCD server
  location / {
    proxy_set_header        Host            $host:483;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_http_version      1.1;
    proxy_set_header 	      Upgrade $http_upgrade;
    proxy_set_header 	      Connection $connection_upgrade;
    proxy_pass              http://gocd-server:8153/;
  }
}
```

Since you're using a non-standard port, it'll need to be passed on to the server (in this case, GoCD). The default configuration in the documentation assumes port 443, which works fine since browsers automatically assume that port from the scheme.

I'm no nginx expert and I'm sure some [nginx variables](http://nginx.org/en/docs/varindex.html) are available so that the 483 does not need to be repeated. I'm tentatively going to close this issue, but I'm happy to reopen it if needed (or if I didn't understand the problem correctly).

**Closed by arvindsv** 2019-05-03 16:27 UTC
