### ISSUE TITLE
Add a option for remove history and artifacts when remove a pipeline

### ISSUE THREAD

**Issue by xbox1994** [gocd/gocd#3581] opened 2017-06-09 03:46 UTC
#879

**Comment by arvindsv** [comment] 2017-06-09 12:56
Closing this since it's an obvious duplication of #879. :) I guess the only change is the part where it is optional. Since this issue is linked, it can still be seen when #879 is picked up.

**Comment by xbox1994** [comment] 2017-06-10 03:47
Hi @arvindsv , I'd like to contribute code to this feature that adds an optional checkbox, is there any possible for current requirement or priority?

**Comment by xbox1994** [comment] 2017-06-10 15:54
![image](https://user-images.githubusercontent.com/15871975/27004185-7b189414-4e37-11e7-824c-433fd95ea3f0.png)

What I want to do is this. If a user clicks this checkbox, GoCD will remove history of this pipeline and related artifacts.

I'm not sure about its robustness if I change its feature and whether users really need it, please give me some suggestions, thanks.

**Comment by arvindsv** [comment] 2017-06-12 14:42
@xbox1994 - The problem is that #879 is not available yet. At this point, you can't choose to delete history and artifacts. That's what #879 is about. So, adding this checkbox will not help. If #879 was available, then this checkbox *might* make sense - though I would be interested to know why someone would want to keep history around, if they cannot see it.

**Comment by xbox1994** [comment] 2017-06-12 15:06
@arvindsv - I'm not clear about the unavailable status for #879, because its status is still open. Is there a technical problem or people has the different voice? 

For me, I want to keep history in case I made a wrong operation, but I also want to delete history when I want to delete each pipeline triggered history.

**Comment by arvindsv** [comment] 2017-06-12 15:36
@xbox1994 - I mean, #879 is not implemented yet. Without #879 implemented, when a pipeline is deleted from the config, it does not go away from the database. So, you really have no choice to delete (or not delete) history from the DB.

**Comment by arvindsv** [comment] 2017-06-12 15:37
If you're talking about implementing #879, it's quite a big effort and it's probably best to continue the conversation there. We will need to involve others such as @jyotisingh in the conversation - since it involves a lot of DB changes, which are not easy.

**Comment by xbox1994** [comment] 2017-06-12 15:52
Yes, I do want to implement the #879, I'm sorry for my bad expression before. I'm excited because I hate the current implementation so much for a long time. I will study how to implement it in future because I'm not familiar with the codebase. Thanks for your @. The other thing is will the issue return to open?

**Comment by arvindsv** [comment] 2017-06-12 16:52
Fine. I will re-open this if you want, but I don't see how it helps, since you said you're interested in #879 and this is a duplicate of it. If you're interested in implementing #879, then all conversation about it should happen there and *not* in this issue.

**Comment by xbox1994** [comment] 2017-06-13 01:34
OK, I will continue to our discussion in #879.

**Comment by varshavaradarajan** [comment] 2017-12-08 13:32
Duplicate of #879

**Closed by varshavaradarajan** 2017-12-08 13:32 UTC
