### ISSUE TITLE
No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]; nested exception is org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]

### ISSUE THREAD

**Issue by ronalcelaya** [gocd/gocd#8217] opened 2020-06-08 18:44 UTC
##### Issue Type

- Bug Report

##### Summary

I configured a pipeline using the API pointing to a branch that no exists in a git repository. After the pipeline was configured, I created the branch and GO.CD start to gives this error: 
```
Modification check failed for material: URL: *******, Branch: develop
Affected pipelines are ******* .05 Jun, 2020 at 18:37:02 Local Time
No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]; nested exception is org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]
```
###### Basic environment details

* Go Version: `19.11.0`
* JAVA Version: `13.0.1`
* OS: `Linux 3.10.0-1062.9.1.el7.x86_64`

##### Steps to Reproduce

1. Create repository 
2. Configure pipeline pointing to unexisting branch (develop)
3. Create branch (develop) in repository
4. Push changes to repository or play pipeline in GO.CD UI

##### Expected Results
Pipeline scheduled and executed

##### Actual Results
Pipeline can not be scheduled nor executed

##### Log snippets

```
ERROR [135@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: ******
org.springframework.orm.hibernate3.HibernateObjectRetrievalFailureException: No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]; nested exception is org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]
        at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:693)
        at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:416)
        at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:416)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:342)
        at com.thoughtworks.go.server.persistence.MaterialRepository.findLatestModification(MaterialRepository.java:742)
        at com.thoughtworks.go.server.persistence.MaterialRepository.findLatestModification(MaterialRepository.java:727)
        at com.thoughtworks.go.server.materials.MaterialChecker.findLatestRevisions(MaterialChecker.java:81)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:170)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:148)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:84)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:64)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.thoughtworks.go.domain.MaterialInstance#6495419]
        at org.hibernate.impl.SessionFactoryImpl$2.handleEntityNotFound(SessionFactoryImpl.java:435)
        at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:233)
        at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:269)
        at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:152)
        at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:1090)
        at org.hibernate.impl.SessionImpl.internalLoad(SessionImpl.java:1038)
        at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:630)
        at org.hibernate.type.EntityType.resolve(EntityType.java:438)
        at org.hibernate.engine.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:139)
        at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:982)
        at org.hibernate.loader.Loader.doQuery(Loader.java:857)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
        at org.hibernate.loader.Loader.doList(Loader.java:2542)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
        at org.hibernate.loader.Loader.list(Loader.java:2271)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:459)
        at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:365)
        at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
        at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268)
        at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
        at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:890)
        at com.thoughtworks.go.server.persistence.MaterialRepository.lambda$findLatestModification$7(MaterialRepository.java:746)
        at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
        ... 12 common frames omitted
```

**Comment by arvindsv** [comment] 2020-06-09 09:44
@ronalcelaya I followed those four steps. It ran fine. I tried it on 20.4.0, not 19.11.0. However, this functionality is quite deep and it's not changed much over those 5 months or so, as far as I know.

The `No row with the given identifier exists` can happen if the server is killed (with `kill -9` say) while it is doing something, leaving the DB in an inconsistent state. _Maybe_ it is possible due to something else, but the steps provided to reproduce this does not seem to.

**Comment by ronalcelaya** [comment] 2020-06-09 12:52
Hello @arvindsv thanks for your anwer. The server was not killed but as you say maybe it is another situation that we are not seeing.

We solved this deleting the pipeline, restarting the go-server process, and configuring the pipeline again.

Thanks for your time and help

**Comment by arvindsv** [comment] 2020-06-09 12:57
@ronalcelaya Glad it's ok now. If someone else faces a similar problem, they can try what you did as well.

I'll close this issue now.

**Closed by arvindsv** 2020-06-09 12:57 UTC
