### ISSUE TITLE
Encoding issue - changes pop up

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#3509] opened 2017-05-15 05:57 UTC
##### Issue Type

- Bug Report

##### Summary

<img width="748" alt="screen shot 2017-05-15 at 11 25 01 am" src="https://cloud.githubusercontent.com/assets/4715748/26044348/5b5a8f64-3961-11e7-89c2-0dd82b05c72b.png">

**Comment by marques-work** [comment] 2017-05-15 18:19
I'm having trouble reproducing this issue on build.gocd.io. This appears to be the same commit, but the comment content renders correctly:

![image](https://cloud.githubusercontent.com/assets/723642/26072356/08eec46c-3960-11e7-9364-1134fa4b5fdb.png)

FWIW I'm on OS X, Google Chrome 58.0.3029.110 (64-bit)

**Comment by varshavaradarajan** [comment] 2017-05-18 10:23
@marques-work , I checked on OS X, Chrome 58.0.3029.110 (64-bit). I see that you saw the changes for `build-windows`. Check `build-windows-PR` build 1403 (Its in page 4) in the pipeline history page. 

Trying to reproduce it locally.

**Comment by arvindsv** [comment] 2019-01-09 18:32
Closing since the dashboard has been rewritten since this was raised. Assuming it's fixed, unless I'm corrected. :)

**Closed by arvindsv** 2019-01-09 18:32 UTC
