### ISSUE TITLE
A problem should be reported to the user when a triggered build encounters a broken (Git) material (invalid branch)

### ISSUE THREAD

**Issue by MartinAhrer** [gocd/gocd#2194] opened 2016-05-18 18:17 UTC
##### Issue Type
- Bug Report
##### Summary

Go should report an error when trying to build a (Git) branch that does not exist (has been deleted)
###### Basic environment details

```
Go Server Version:  16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)
JVM version:    1.7.0_95
OS Information: Linux 4.4.8-boot2docker
Usable space in artifacts repository:   13 GB
Database schema version:    1503002
```
##### Steps to Reproduce
1. Setup a Git material with a branch 
2. Initial build works
3. Delete the branch from the repository
4. Trigger Build
5. Go will not schedule a build but will also not report the broken material configuration
##### Expected Results

Go should report a problem to the user
##### Actual Results

Nothing happens

**Comment by zabil** [comment] 2016-05-19 03:26
Isn't it reported on this box in the right bottom corner?

![screen shot 2016-05-19 at 8 51 37 am](https://cloud.githubusercontent.com/assets/54427/15381649/0e40097c-1d9f-11e6-8194-c9e1e41eaf12.png)

**Comment by varshavaradarajan** [comment] 2016-05-19 04:38
Hey,
Verified on 16.3 and 16.4 that once a branch is deleted, modification check for that material fails with the following error and comes up in the errors box as @zabil pointed out.
![modification_fail](https://cloud.githubusercontent.com/assets/4715748/15382341/21d064ca-1da7-11e6-8c60-38f967dabf29.png)

However, on 16.5 this bug exists. Probable cause could be a regression failure from https://github.com/gocd/gocd/pull/2149

**Comment by varshavaradarajan** [comment] 2016-05-19 10:12
The error message shown above is the result of a failed git fetch command - 

The command ```git fetch origin``` fails because the refspec for **shallowed** repositories is like this:
```
fetch = +refs/heads/<branch name>:refs/remotes/origin/<branch name>
```
For a **non-shallow repository**, the refspec is like this: 
```
fetch = +refs/heads/*:refs/remotes/origin/*
```
The reason that the git fetch command does not fail on 16.5 was because the shallow clone system property was turned off by default. So, any **new** material would have the latter refspec, which would not result in any error on running the command ```git fetch origin``` even if a particular branch did not exist. 
The bug exists on earlier versions of Go, before the shallow clone feature was introduced.

**Comment by MartinAhrer** [comment] 2016-05-19 17:55
Tested that again. Yes it works. Didn't pay attention to that very small box at the bottom. I apologize for raising that issue.

**Comment by benzvan** [comment] 2016-06-09 14:59
That box at the bottom has room for improvement. I have to tell people to check it when their pipeline fails really often.

**Comment by varshavaradarajan** [comment] 2017-06-27 15:30
The errors and warnings box has been moved to the header now. Closing this.

**Closed by varshavaradarajan** 2017-06-27 15:30 UTC
