### ISSUE TITLE
Upgrading from 16.1 to 17.4

### ISSUE THREAD

**Issue by aliensojurner** [gocd/gocd#3536] opened 2017-05-22 16:32 UTC
##### Issue Type

Bug report

##### Summary
We are trying to upgrade our old Go server from 16.1 to 17.5. I am running into a problem where after the upgrade it works, but then I restore the backed up data from our old server so I can restore it to 17.4, but after I copy in all the files, the server fails to start with the message 

"The Go Server service on Local Computer has started and then stopped. Some services stop automatically if they are not in use by other services or programs" 

Obviously it should stay running. The last step in this document says I should chown the files and folders but on Windows, I'm not sure how to set ACL's other than adding groups like Administrator to the folder or file. 
Backup and restore article - https://docs.gocd.io/17.5.0/advanced_usage/one_click_backup.html

When looking in event viewer under Windows Logs > System I only see a message that "the service has entered the stopped state"

Is this upgrade even possible, or am I missing a step somewhere that is causing the service to fails. Keep in mind that it works until I restore the data from the back up. 

##### Environment
I can't provide the environment info because it won't launch. I'm working with Windows server 2012r2

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

1. Back up 16.7
2. Install 17.4 
3. Restore 16.7 to 17.4
4. Try to launch Go server and it fails with the message above. 

##### Expected Results
It should start

##### Actual Results
It fails with the message "The Go Server service on Local Computer has started and then stopped. Some services stop automatically if they are not in use by other services or programs" 
##### Possible Fix
I don't know a fix so I'm reaching out for help.

**Comment by jyotisingh** [comment] 2017-05-22 16:39
Upgrade from 16.1 to  17.4 definitely works. 

Why are you trying to restore from backup? If you upgrade your existing server that should take care of upgrading the data and config too.  

Ofcourse fresh install followed by restoring from backup​ should also work, but may be you are missing a step. What does the go-server log say?

**Comment by arvindsv** [comment] 2017-05-22 17:36
GoCD 17.x need Java 8. Could be that too. As @jyotisingh said, you should look at the log files in the server's directory (`C:\Program Files (x86)\Go Server`).

**Comment by aliensojurner** [comment] 2017-05-22 18:16
Here is the log file. I chose to install the bundled JRE 8 instead of using my own. 

[Go logs.zip](https://github.com/gocd/gocd/files/1019760/Go.logs.zip)

To answer the previous question I was working in a test VM, installing the original server version, then restoring the backup from the older version to see if it would work. It should have, but it doesn't.

**Comment by aliensojurner** [comment] 2017-05-22 18:39
[Go Logs 16.1.zip](https://github.com/gocd/gocd/files/1019820/Go.Logs.16.1.zip)

I just tried starting fresh and installing server 16.1, then restoring the backup data to bring it up. In this case the service starts, and the stops itself after about a minute. I've attached the logs for that session as well. 

In both cases, if I don't restore any data, the buildserver regardless of the version, launches just fine and stays up. As soon as I copy the data over and start it back up, it fails.

**Comment by aliensojurner** [comment] 2017-05-22 19:07
One other update. When installing 16.1 and restoring the backup from our 16.1 server, when the service starts and then stops a minute later, event viewer is reporting the error "The Go Server terminated with the following service-specific error: Incorrect function"

**Comment by aliensojurner** [comment] 2017-05-23 16:17
Any thoughts? Do you need more information?

**Comment by varshavaradarajan** [comment] 2017-06-06 12:10
Hi, 
If you start the server without restoring any data, the default artifacts directory is the <go working dir>/artifacts. Once you start the upgraded server with the existing config, the error that shows up on the logs in `Caused by: java.lang.RuntimeException: Unable to create artifacts directory at E:\cruise-artifacts`.

**Comment by varshavaradarajan** [comment] 2017-07-18 03:24
Closing this. Please reopen if you think any action is required.

**Closed by varshavaradarajan** 2017-07-18 03:24 UTC
