### ISSUE TITLE
property xml parser fails incorrectly

### ISSUE THREAD

**Issue by sgran** [gocd/gocd#366] opened 2014-07-24 09:23 UTC
Given the xml fragment:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.0//EN" "report.dtd">
<report name="Git Buildhelper Webservice">
<counter type="CLASS" missed="0" covered="6"/>
</report>
```

a property declaration like:
```
<property name="coverage_classes_missed" src="target/site/jacoco/jacoco.xml" xpath="number(/report/counter[@type='CLASS']/@missed)" />
```

Should return 0.  It fails with an error from the xml parser because it can't find report.dtd.  However, this is unnecessarily strict, since the xml has standalone="yes", indicating the dtd is not needed for correct parsing.  I agree it's untidy to reference a dtd that you don't make available, and I'll take the issue up with jacoco as well, but it seems unnecessary to raise a parser failure in this case.

Cheers,

**Comment by arvindsv** [comment] 2016-06-04 11:59
Closing. Probably a duplicate of #342.

**Closed by arvindsv** 2016-06-04 11:59 UTC
