### ISSUE TITLE
Material clean up (eg: git clean -dff) does not happen if one of the materials is pipeline / package repository

### ISSUE THREAD

**Issue by webmaster128** [gocd/gocd#945] opened 2015-03-11 16:03 UTC
As seen earlier in https://github.com/gocd/gocd/issues/438, the option `Clean Working Directory` not seem to work as expected.

I have different C++ projects where `Clean Working Directory` is always unchecked. In some of these projects no directory cleanup is performed at all

```
[go] Start to prepare myproject/1142/build/1/Linux32 on ubuntu32 [/var/lib/go-agent] at Wed Mar 11 16:28:40 CET 2015

[go] Start updating farcaster at revision 3d5ef877cd3af8cf3e7b06c74ed47b487a8f84c1 from git@bitbucket.org:myuser/myproject.git
```

In other projects, build outputs are deleted

```
[go] Start to prepare myproject/97/my-stage/1/Linux32 on ubuntu32 [/var/lib/go-agent] at Wed Mar 11 16:44:16 CET 2015

[go] Keeping folder pipelines/myproject/cruise-output

[go] Keeping folder pipelines/myproject/somelib-source

[go] Deleting folder pipelines/myproject/build-myproject

[go] Keeping folder pipelines/myproject/myproject-source

[go] Start updating myproject at revision 2fa8b97dd9417e2a8b1b9dabb2fc2ad7d5c245d5 from git@bitbucket.org:myuser/myproject.git
```

The logic of what is deleted and what is kept looks good assuming I want my working directory to be cleaned. But I don't because re-building the entire C++ project takes 15-20 minutes.

**Comment by srinivasupadhya** [comment] 2015-03-11 16:29
[Here](https://github.com/gocd/gocd/blob/2b6c017b72ad427f517b324c3d633cd1410f7dac/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L291) we simply delete the whole working directory (eg: `/var/lib/go-agent/pipelines/<pipeline-name>`) and prints `Cleaning working directory 'x' since stage is configured to clean working directory` if `cleanWorkingDir` is selected. Agent then does a fresh clone for all materials required. If its not selected we simply update the materials (if its already present) to the correct revision & run tasks. Are you seeing something other than this behavior?

**Comment by webmaster128** [comment] 2015-03-11 16:42
Looks like the confusion starts in this call some lines below [materialRevisions.getMaterials().cleanUp(workingDirectory, consumer);](https://github.com/gocd/gocd/blob/2b6c017b72ad427f517b324c3d633cd1410f7dac/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L167) because it is one output per material and thus has nothing to do with the option `Clean Working Directory`.

**Comment by webmaster128** [comment] 2015-03-11 17:00
Okay, this is the code that decides whether or not the DirectoryCleaner is run at all: [Materials.java:123](https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/common/src/com/thoughtworks/go/config/materials/Materials.java#L123)

Now the question is, in which case `material.getFolder()` is `null`. Since `com.thoughtworks.go.domain.materials.Material` is an interface only, the bahavior might be different for different kinds of materials.

Ideas?

**Comment by webmaster128** [comment] 2015-03-11 17:57
Found a pattern: As long as I have GIT materials only, DirectoryCleaner runs. If there is one material of type pipeline, DirectoryCleaner does not run anymore.

**Comment by srinivasupadhya** [comment] 2015-03-11 18:06
looks like a great catch to me! need to dig deeper. the problem could be reproducible if one of the materials is Package Repository (basically any material which doesn't have a destination folder set).

**Comment by srinivasupadhya** [comment] 2015-03-12 06:45
Further analysis: the clause was put in to handle SVN repositories with `checkExternals` turned on.

**Comment by webmaster128** [comment] 2015-03-12 08:08
I think this can be split up in two independent problems:

1. The special case *one material has a `null` folder* is not clear to the user
2. There should not be a directory cleanup step at all after [BuildWork.java:158](https://github.com/gocd/gocd/blob/2b6c017b72ad427f517b324c3d633cd1410f7dac/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L158)

**Comment by arvindsv** [comment] 2015-05-28 20:37
@arikagoyal, @zabil: Can we mark this as a bug to be fixed in this milestone?

**Comment by robwiss** [comment] 2015-06-26 19:27
I have a pipeline with a git material set to destination directory "git". There is a directory created under the pipeline root directory called "instances" that I intend to use to store vagrant instances.

Looks like this
```
agent-manager/
    |- git/
    |- instances/
```

When I build with "Fetch Materials" checked on the first stage of the pipeline ("Clean Working directory" is not checked) the "instances" directory is deleted during the materials fetch:

```
15:14:40.286 [go] Start to prepare agent-manager-test/20/purge_agents/1/purge_agents on localhost.localdomain [/var/lib/go-agent]
15:14:40.302 [go] Keeping folder pipelines/agent-manager-test/git
15:14:40.302 [go] Keeping folder pipelines/agent-manager-test/cruise-output
15:14:40.302 [go] Deleting folder pipelines/agent-manager-test/instances
15:14:40.303 [go] Start to update materials.
```

This seems incorrect to me. Git shouldn't be cleaning up anything outside of the subdirectory it's checked into. Is this related to this bug?

**Comment by mdaliejaz** [comment] 2015-06-29 06:03
@robwiss This is an expected behaviour.
The pipeline root directory is not supposed to be used outside of Go.

**Reason why we need to clean the pipeline root directory**
If destination folder is not specified in the material, the pipeline root directory works as the working directory and the material is checked out in the root directory itself.
In case, the destination folder is specified (like you have specified: "git"), the material is checked inside that folder. However, if you change the destination directory (to let's say, "git1") and we don't clean up this root directory, there will now be two directories viz "git" and "git1" which is not a desired behaviour.

**Comment by robwiss** [comment] 2015-06-29 16:22
Thank you for your response.

I'm currently implementing the behavior I want by having go access a directory outside the pipeline root directory (path is passed in via ENV variable).

Would it be possible to inform the agent of pipeline changes since the last time it ran that pipeline? That way it could specifically delete directories that had been used for materials but are not any more. Not sure how a conflict between a directory that exists but isn't a material and a material that is newly associated with that directory name would go.

I noticed that files left in the root directory don't seem to get deleted. Isn't that an issue given the current scheme? The filename could conflict with a new material directory name.

**Comment by mdaliejaz** [comment] 2015-06-30 07:36
You're welcome.

Could you elaborate more on what this directory is supposed to be? I would like to understand why this cannot be a material itself.

> I noticed that files left in the root directory don't seem to get deleted. Isn't that an issue given the current scheme? The filename could conflict with a new material directory name.

Very true. I think this is a bug. I noticed this while fixing the present issue.

**Comment by robwiss** [comment] 2015-06-30 13:45
The directory is a working directory for vagrant managed build environments that are also go agents. The Vagrantfile and bootstrap scripts are checked into git along with a management script that, when pointed at a directory containing a Vagrantfile, will create N copies of that directory and run vagrant up.

My current scheme is:
```
agent-manager/          # pipeline working dir
    |- git/
    |- instances/
```
Where git is the repo containing the management script and the directories with the vagrant configurations for each environment. I need the instances directory to persist across operations so that when an SCM change is triggered machines whose configuration have changed can be destroyed and provisioned anew.

Would cloning the git repo into the top level working directory, turning off clean working directory, and keeping the instances folder as subdirectory in the git clone suffice to keep the instances folder persistent? Like this:
```
agent-manager/          # pipeline working dir
    |- <contents of git clone>
    |- instances/
```

If the instances directory is persistent this structure would be a workable solution.

Something else that would be really handy is the ability to run the go agent as the vagrant user. The vagrant user's environment is all set up and it would be nice to not have to duplicate that setup for the go user.

**Comment by mdaliejaz** [comment] 2015-07-02 05:24
Sorry for replying late.

>Would cloning the git repo into the top level working directory, turning off clean working directory, and keeping the instances folder as subdirectory in the git clone suffice to keep the instances folder persistent?

I see you have already found the answer :) 
If working directory (destination directory for material) is not specified, the repository is checked in the root directory itself. The cleanup (folder cleanup) as mentioned before doesn't happen as `git clean -dff` takes care of that. Since you have put the "instances" folder in .gitignore it won't be deleted. Clean Working Directory cleans up everything in the root folder irrespective of the destination directory specified.

>Something else that would be really handy is the ability to run the go agent as the vagrant user. The vagrant user's environment is all set up and it would be nice to not have to duplicate that setup for the go user.

Take a look [here](https://groups.google.com/forum/#!msg/go-cd/u3LHW8jWVQw/R6THfwt7QKkJ).

**Comment by srinivasupadhya** [comment] 2015-07-09 05:23
verified on `go-server-15.2.0-2219`

**Closed by srinivasupadhya** 2015-07-09 05:23 UTC
