### ISSUE TITLE
Broken links in 18.2

### ISSUE THREAD

**Issue by MarkTickner** [gocd/gocd#4527] opened 2018-03-15 11:45 UTC
##### Issue Type

- Bug Report

##### Summary

Since updating to 18.2 various links are broken, such as VSM and Changes from the new dashboard, and currently building pipeline/stage/job from the Agents page. The VSM and Changes links are still working on the old dashboard.

The broken links are like `http://go/go/pipelines/value_stream_map/...` rather than having the correct hostname part of the URL.

The site URL is correctly set in the server configuration, as well as the majority of links still working.

###### Basic environment details

* Go Version: `18.2.0`
* JAVA Version: `1.8.0_151`
* OS: `Linux 4.4.0-116-generic`

**Comment by arvindsv** [comment] 2018-03-15 12:32
Looks like a duplicate of #4503. So, I'll close this for now. If it's not a duplicate, will reopen it. Thank you!

**Closed by arvindsv** 2018-03-15 12:32 UTC
