### ISSUE TITLE
Loading many Config Repo Pipelines takes a long time

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#5010] opened 2018-08-07 08:58 UTC
##### Issue Type

- Feature enhancement

##### Summary

When restarting a GoCD instance with many config repo pipelines, it takes a long time for all of them to show up.

This is confusing to users ("where did my pipeline go?") and breaks dependencies (pipeline A depends on B, which is not available yet).

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: 1.8
* OS: Debian

###### Additional Environment Details

- 315 config repos
- 470 pipelines from these config repos
- 300 XML pipelines

##### Steps to Reproduce

1. Create a GoCD instance with many config repos
2. Wait until all of them show up properly
3. Restart GoCD
4. Look at pipeline overview, to see which pipelines show up

##### Expected Results
I expect all pipelines to show up immediately.

##### Actual Results
XML pipelines show up immediately. Config repo pipelines only show up after some time has passed. For many pipelines/repos, this is significant: it takes 20min for everything to show up again.

##### Possible Fix

I assume git materials are refreshed before parsing config pipelines on a fresh boot. Maybe cache pipeline definitions and then asynchronously refresh from git?

I'm happy to provide more details if needed.

**Comment by arvindsv** [comment] 2018-08-31 13:02
I remember discussions with @tomzo (the author of this) a long time ago - and we decided not to go down that path. Maybe @tomzo remembers more details? The flyweights do exist across restarts.

Given that we've discussed it before, I'm going to mark this as wont-fix for now. Happy to reopen if @tomzo thinks this should be reconsidered.

**Comment by arvindsv** [comment] 2018-08-31 13:02
Actually, I'll leave it open till we decide. Thanks.

**Comment by tomzo** [comment] 2018-08-31 13:36
@dziemba I can confirm this becomes an issue with 100+ config repos. For start I suggest you play around with following system properties:
 * `material.check.threads` which is the number of concurrent material checks which are not defined by config repos.
 * `material.config.check.threads` -  which is the number of concurrent material checks which are defined by config repos. The default is `2` which means your 350 config repos are handed by only 2 workers on start unless you already changed this.

You can set system properties with something like this:
```
export GO_SERVER_SYSTEM_PROPERTIES="-Dmaterial.check.threads=2 -Dmaterial.config.check.threads=8"
```

By changing above values I could keep our start time under 4 minutes. @dziemba please tell me if you have experimented with these settings, if not then please try and report back.

> Maybe cache pipeline definitions and then asynchronously refresh from git?

@jyotisingh explored this and actually started implementing it initially. But, among other things, this requires to serialize configuration to database (or any other store) on each config update, which is expensive.

Personally I don't think implementing a cache just to handle server start faster is the right approach. I would rather invest time into making polling and parsing faster in general, which would benefit normal server operations too.

We can speculate that most time is spent on actual polling, while parsing a directory is fast. Then one way to improve start time would be to once parse all the (potentially stale) flyweight folders before poling begins. The bad side of this approach is that for a brief moment there will be pipelines in server with configuration older than what is in the upstream configuration repository. This may be worse than having to wait for pipeline to show. @arvindsv I think that was the reason we didn't go this way.

**Comment by dziemba** [comment] 2018-08-31 13:41
@tomzo We have set both `material.check.threads` and `material.config.check.threads` to 32 when running the tests as documented above.
I have also experimented with much higher values on a test-instance, it does not improve anything. I assume there's a bottleneck somewhere else.

**Comment by brydoncheyney-slc** [comment] 2018-09-11 16:44
I can confirm this is also an issue for us.

It takes ~14minutes to render all pipelines in the UI. We have not experimented with values for `material.check.threads` and `material.config.check.threads`, based on the previous post.

###### Basic environment details
* Go Version: 18.8.0
* JAVA Version: 1.8.0_181
* OS: RHEL6
 
###### Additional Environment Details
* 64 config repos
* 503 pipelines from these config repos
* 42 XML pipelines

**Comment by ibnc** [comment] 2018-11-27 22:52
I'd be curious to see the server logs from when a server is starting up with 100+ config repos

**Comment by brydoncheyney** [comment] 2018-11-27 23:06
> Does anyone have one to share?

Let me see if I can dig one out for you sometime this week......

**Comment by ibnc** [comment] 2018-11-27 23:16
@brydoncheyney I'd greatly appreciate it!

**Comment by brydoncheyney** [comment] 2018-11-29 12:36
@ibnc incidentally, we're a Thoughtworks client with a GoCD support so if there's anything I can do to help, escalate, push for, etc. then just let me know...

I'll be back at work tomorrow so will get logs for you then. I take it you're most interested in the start up log with the number of config repos we have?

**Comment by arvindsv** [comment] 2018-11-29 15:50
@brydoncheyney Since it's open-source, it is open-source. :) We don't have any special mechanism to change priorities. It would be unfair.

We do listen to people and understand what would be pressing and useful, but often people will be disappointed because what they want is not picked up.

**Comment by brydoncheyney** [comment] 2018-11-29 18:07
apologies but that wasn’t meant to be about priorities - more about our ability to help and work closely, by whatever means may be useful. in this case, as someone with 500+ config pipelines!

**Comment by arvindsv** [comment] 2018-11-29 18:11
@brydoncheyney Oops. Sorry. What you said about working closely makes sense. 😊

**Comment by ibnc** [comment] 2018-11-29 18:18
@brydoncheyney I'm interested in the start up, but I'm mostly interested in the time after the start up to when all of the pipelines are displaying

**Comment by brydoncheyney-slc** [comment] 2018-11-30 11:56
Log extract from service start at **2018-11-30 10:17:26** until 'Update operation on merged configuration succeeded' at **2018-11-30 10:32:22**

[go-server.log.gz](https://github.com/gocd/gocd/files/2633084/go-server.log.gz)

let me know if any further extracts would be useful, debug logs, etc.

**Comment by arvindsv** [comment] 2018-11-30 13:11
@brydoncheyney It might also be interesting to know (in general), the structure of your repos. Are they all interdependent? Is there a hub-and-spoke kind of setup (meaning, one repo which is main and other repos have pipelines which depend on it)?

I would be curious to know whether GoCD _should_ be able to show pipelines as they come (all repos are independent) or it'll need to wait to parse all the repos.

**Comment by brydoncheyney-slc** [comment] 2018-11-30 14:07
@arvindsv this is certainly a good point. we do have dependencies in the graph and changes to service (i.e. deployment to an environment) will trigger automated test for that environment.

This certainly limits the independence of pipelines and the order in which we see pipelines made available.

I'll see if I can get a decent VSM that captures this......

**Comment by ibnc** [comment] 2018-12-05 21:47
@tomzo 

> @dziemba I can confirm this becomes an issue with 100+ config repos. For start I suggest you play around with following system properties:
> 
> * `material.check.threads` which is the number of concurrent material checks which are not defined by config repos.
> * `material.config.check.threads` -  which is the number of concurrent material checks which are defined by config repos. The default is `2` which means your 350 config repos are handed by only 2 workers on start unless you already changed this.

@tomzo I don't think changing these values will have much of an effect on the performance. Even with a higher number of those listeners, there's only one listener that actually updates the server's configuration with the config repo pipelines (ConfigMaterialUpdater).

**Comment by ibnc** [comment] 2018-12-05 22:46
@tomzo from the logs I looked at, it doesn't appear that the actual process of acquiring the lock, and writing the config takes very long (like 1-2 seconds). I think part of the issue is coming from the fact that we're processing each individual config repo config-update/merge in serial.

**Comment by ibnc** [comment] 2018-12-05 22:49
I've also created a repo with over 100 pipelines in it, and I see no performance issues locally.

**Comment by ibnc** [comment] 2018-12-13 19:48
A PR with a performance boost been merged. Hopefully it'll be release with 18.12. I'll comment on this issue when it's released.

**Comment by brydoncheyney** [comment] 2018-12-13 19:51
@ibnc fantastic! will pull as soon as that’s released...

**Comment by ibnc** [comment] 2018-12-14 21:14
@brydoncheyney Feel free to download the latest experimental release if you want to test things out (https://download.gocd.org/experimental/binaries/18.12.0-8203/generic/go-server-18.12.0-8203.zip)

**Comment by ibnc** [comment] 2018-12-19 18:23
18.12 has been released, and it contains the performance improvement. 

Increasing the value of `material.config.check.threads` should decrease the time it takes for all of the pipelines to be available.

Feel free to let me know if you are still experiencing this problem.

**Comment by brydoncheyney** [comment] 2018-12-19 23:07
@ibnc fantastic! back at work on Friday so will deploy this and provide feedback on results. I meant to respond to the experimental notification but, unfortunately, we only have a single (Production) deployment so preferred to wait for the official 18.12 release.

Is there a resource that could help determine an appropriate value of `material.config.check.threads` or is this limited by, for example, available CPU?

**Comment by brydoncheyney-slc** [comment] 2018-12-21 16:39
@ibnc a couple of quick data points - I've upgraded to 18.12.0 and the start up to successful merge configuration is now down to 4 minutes, over a previous 15 minutes. I've tried both the default `material.config.check.threads=2` and `material.config.check.threads=8` but this didn't differ by any meaningful value.

many thanks for the work on this!!!!

**Comment by ibnc** [comment] 2019-01-02 21:48
@brydoncheyney-slc I don't know of a recommended value for them. I'd suggest experimenting to see what works best for y'all's setup

**Comment by adityasood** [comment] 2019-01-18 08:45
Observations after verifying latest changes are listed on [here](https://github.com/gocd/gocd/issues/5673#issuecomment-455469067)

Available system properties to tweak threads are listed [here](https://github.com/gocd/gocd/pull/5663#issuecomment-452566912)

**Closed** 2019-02-06 18:59 UTC

**Comment by krarjun90** [comment] 2024-04-19 11:18
> Maybe cache pipeline definitions and then asynchronously refresh from git?
> 
> @jyotisingh explored this and actually started implementing it initially. But, among other things, this requires to serialize configuration to database (or any other store) on each config update, which is expensive.

Can we add this option and wrap it with a config if someone wants to use it?  Can we reconsider this approach to load it from a cache? We have a scenario with 250+ config repos and restarts are taking 2 hours to bring up the application. 

@maheshp  @arvindsv @adityasood @dziemba
