### ISSUE TITLE
Tasks continue to re-run in a loop

### ISSUE THREAD

**Issue by prmammoth** [gocd/gocd#3623] opened 2017-06-29 09:03 UTC
##### Issue Type

After upgrading to Go 17.5, we are noticing this. All tasks in a job are completed and then the same thing re-runs again. Happens multiple times and then the tests finish successfully. 

- Bug Report

##### Summary

Tasks are rerunning on a continuous basis. See the details here
[go-server.txt](https://github.com/gocd/gocd/files/1111437/go-server.txt)
[console.txt](https://github.com/gocd/gocd/files/1111438/console.txt)

##### Environment

```
Attached as a file
[go_support.txt](https://github.com/gocd/gocd/files/1111435/go_support.txt)

```
-->

###### Basic environment details

* Go Version: `17.5.0 (5095-3130b5ba96f8155ae86fefb261a559d4c7493326).`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.8.6-x86_64-linode78`
* Browser vendor and version (if relevant): `Not relevant`

**Comment by ketan** [comment] 2017-06-29 09:10
Please only attach logs from the time window when the agent was re-running the job over and over.

You may need to attach agent logs too. Usually under `/var/log/go-agent/` or `/var/lib/go-agent/logs`.

**Comment by ketan** [comment] 2017-06-29 09:14
Ok, I think, I may know what the problem is:

```
2017-06-27 10:51:08,202  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '5' minutes
2017-06-27 10:51:38,201  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '5' minutes
2017-06-27 10:52:08,201  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '6' minutes
2017-06-27 10:52:38,202  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '6' minutes
2017-06-27 10:53:08,201  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '7' minutes
2017-06-27 10:53:38,201  INFO [cancelHungJobThread] ConsoleActivityMonitor:95 - Job 'dv_unit_tests/261/UnitTests/3/unitTestsJob' has not updated console log for more than '7' minutes
```

It seems you have a job timeout setup and your job is being killed because it's not generating output for a long time...

Perhaps you need to setup a higher timeout on the job.

I'm closing this ticket out, but if the problem persists you may need to relook at the logs to see why the job is being re-run.

**Closed by ketan** 2017-06-29 09:14 UTC

**Comment by prmammoth** [comment] 2017-06-29 09:16
So does it end up re-running the whole job again ?

**Comment by prmammoth** [comment] 2017-06-29 09:16
Also this was not happening with the earlier releases. Is this a new feature ? We were on 16.11 I think before this

**Comment by ketan** [comment] 2017-06-29 09:18
> So does it end up re-running the whole job again ?

Yes. "timeout" assumes that the job hung, because it's not generating output

> Also this was not happening with the earlier releases. Is this a new feature ? We were on 16.11 I think before this.

This is not a new feature. It may be possible that your machine or job slowed down, or it's no longer "flushing" output to STDOUT/STDERR.

**Comment by prmammoth** [comment] 2017-06-29 09:19
In server administration section, I see that the job timeout setting is selected as never timeout

**Comment by varshavaradarajan** [comment] 2017-06-29 09:51
May be related to https://github.com/gocd/gocd/issues/2040. Can you please provide the agent logs? It does look like an issue when the artifact is being uploaded. As @ketan mentioned, the agent logs will be in `/var/log/go-agent/` and `/var/lib/go-agent/logs`. You can check both these location on any one of the agents which ran this job once and the job got rescheduled.

**Comment by prmammoth** [comment] 2017-06-29 17:12
See the logs from /var/lib/go-agent/logs/go-agent.log for the time duration when the issue is noticed. This time it ran two times.
[go-agent.txt](https://github.com/gocd/gocd/files/1112893/go-agent.txt)

**Comment by arvindsv** [comment] 2017-06-29 17:38
It says:

```
2017-06-29 17:50:07,787 [loopThread] ERROR springframework.scheduling.timer.MethodInvokingTimerTaskFactoryBean:68 - Invocation of method 'loop' on target class [class com.thoughtworks.go.agent.AgentHTTPClientController] failed
java.lang.OutOfMemoryError: Java heap space
```

Darren Rowley had mentioned this in the [mailing list thread](https://groups.google.com/d/msg/go-cd/r12ugR7BSOY/bImwIR96AgAJ).
