### ISSUE TITLE
Dashboard pause popup message is persistant

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4350] opened 2018-02-14 09:57 UTC
##### Issue Type

- Bug Report

##### Summary

The pause message in the popup is retained after closing it.

![untitled](https://user-images.githubusercontent.com/10598/36198033-84413ab4-119b-11e8-9d2f-51a16045fda7.gif)

**Comment by GaneshSPatil** [comment] 2018-02-14 10:15
Related/Duplicate of: https://github.com/gocd/gocd/issues/4309

@ketan -- A fix has been added for the same as part of [this](https://github.com/gocd/gocd/pull/4344) PR

**Closed** 2018-02-14 10:16 UTC
Labels: bug, dashboard
