### ISSUE TITLE
Dependent Pipelines triggered multiple times on update of cruise-config

### ISSUE THREAD

**Issue by slavina-rumenova** [gocd/gocd#3515] opened 2017-05-15 13:34 UTC
**Issue Type**

_Bug Report_

**Summary**
On an update of cruise-config all pipelines are triggered independent of the order, meaning that if we have multiple related pipelines which are interconnected, they would be triggered as many times as they are in the chain + 1 for the update.

**Basic environment details**

* Go Version: `16.12.0`
* JAVA Version: `1.8.0_111`
* OS: `Linux 4.4.0-31-generic`

**Steps to Reproduce**
1. Create 3 pipelines A,B,C
2. Create dependencies between B->C and A->B->C
3. Update the cruise-config.xml

**Expected Results**
Pipelines A,B,C are triggered just once

**Actual Results**

Pipeline C will be triggered 3 times, B 2 times

**Comment by arvindsv** [comment] 2017-05-15 16:52
Hello. An update of the config XML should not be re-triggering pipelines. Can you provide more details and maybe a small config XML as an example?

I'll close this for now and will re-open when more data is provided. Thank you.

**Closed by arvindsv** 2017-05-15 16:52 UTC

**Comment by ouzo66** [comment] 2017-05-16 12:45
Hi,

an update in the material section of the xml is re-triggering the pipelines. 

Here a small example:
[gocd_test.txt](https://github.com/gocd/gocd/files/1004338/gocd_test.txt)

case1: 
- By adding a material to one of the Pipelines as dependency will retrigger the pipeline. (ex. Pipeline "merge2" adding "start" as dependency"), without execution of the previous ones.

case2:
- By adding a exact copy of existing pipeline to the xml (ex: "merge2" -> "merrge3) will immediately execute the new pipeline.

case3:
- changing multiple "material"-sections of different pipelines will trigger them individually as described by @slavina-rumenova .

**Comment by jyotisingh** [comment] 2017-05-16 12:56
@ouzo66 

>case1:
By adding a material to one of the Pipelines as dependency will retrigger the pipeline. (ex. Pipeline "merge2" adding "start" as dependency"), without execution of the previous ones.

Any update to the material of a pipeline is supposed to trigger that pipeline, this is by design.

>case2:
By adding a exact copy of existing pipeline to the xml (ex: "merge2" -> "merrge3) will immediately execute the new pipeline.

If a pipeline was added via the pipeline creation wizard, it gets saved in `paused` state. However, if you save it using the config xml tab, then it is saved in unpaused state. If the pipeline is not setup for manual trigger, it will get triggered automatically. This is also by design.

>case3:
changing multiple "material"-sections of different pipelines will trigger them individually as described by @slavina-rumenova .

As mentioned for case1, updates to material config will trigger the pipeline. Updates to other part of the config will not. Again, if the materials of just `merge2` pipeline changes, then only `merge2` will get triggered, other pipelines will not get triggered.
