### ISSUE TITLE
deleting commits does not trigger pipeline

### ISSUE THREAD

**Issue by matthias-k** [gocd/gocd#5179] opened 2018-09-18 14:43 UTC
##### Issue Type

Bug Report

##### Summary

deleting the latest commits in a source repository, e.g. by `git reset --hard HEAD^` and then force pushing the branch does not update the material and subsequently does not trigger depending pipelines to run again. We use gocd to build docker images and subsequently deploy them to kubernetes and this bug means we cannot go back from a bad commit.

##### Environment

We run gocd on our kubernetes cluster using the latest version of the official helm chart from https://github.com/helm/charts/tree/master/stable/gocd, i.e. chart version 1.4.3 with gocd 18.9.0

###### Basic environment details

* Go Version: 18.9.0 (7478-f202ea9416939d7ce356cf3939239ef953ec423b).
* JAVA Version: 1.8.0_171
* OS: Linux 4.4.0-119-generic
* Browser vendor and version (if relevant): Chrome 69.0.3497.81 (Official Build) (64-bit)

###### Additional Environment Details

We use the gocd-yaml-config plugin to configure our pipelines

##### Steps to Reproduce

1. set up a git repository, commit something
2. set up a trivial pipeline, e.g.

```
pipelines:
  test:
    group: test
    materials:
      source:
        git: url-of-my-repo
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                     - -c
                     - "git log"
```
3. make sure pipeline runs for a first time
4. make changes to the source repo, e.g. `echo foo > foo.txt && git commit  -am 'changes' && git push`
5. wait till pipeline completes with new commit
6. reset last changes in source repo: `git reset --hard HEAD^ && git push --force`

##### Expected Results

I expect the pipeline to run again because `master` changed. E.g. the pipeline might deploy the code version of the  `master` branch, as for example in the documentation: https://docs.gocd.org/current/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_deploy_pipeline.html

##### Actual Results

The pipeline did not trigger. Apparently gocd did notice that the repository changed: In the log I get repeated instances of

```2018-09-18 13:14:51,257  INFO [155@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:73 [plugin-cd.go.contrib.elasticagent.kubernetes] - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.

2018-09-18 13:17:53,040 INFO  [121@MessageListener for MaterialUpdateListener] ScmMaterialUpdater:60 - [Material Update] Found '1' modifications for material 'GitMaterial{url=my-url, branch='master', submoduleFolder='null', shallowClone=false}' with flyweight '77d1b8d8595cf194c53505bff7125398655b58f5432ee43782642e4559bb0738' using working directory '/go-working-dir/pipelines/flyweight/ff5db2a7-492b-4d0b-b5ff-4e9a2cb1125e'
2018-09-18 13:17:53,044 INFO  [121@MessageListener for MaterialUpdateListener] MaterialRepository:847 - Saving revisions for material [URL: my-url, Branch: master] after removing the following duplicates [e496b6c438944bab4c78e1a3b29d62e8bafdbc65]
```

but they don't trigger the pipeline (and the material update happens several minutes after the push although it usually happens within a minute for me). The fact that gocd noticed multiple times that the material changed seems a bit odd to me.

If I add another commit after the reset (e.g. by `echo bar > foo.txt && git commit -am "other changes" && git push`), then the pipeline is triggered again.

I can understand this behaviour in a pure continuous integration setting: if the commit has already been tested, why test it again. But in the case of continuous deployment this doesn't seem plausible anymore. It makes sense to go back (e.g. after a failed experiment, on feature branches etc) and then I need to make sure that this old commit is deployed again.

**Comment by ketan** [comment] 2018-09-18 15:03
This is by design. If you're doing a simple reset to previous commit, and gocd has already seen that previous commit, a build will not be kicked off. In GoCD's view it's already seen that commit and built it.

If you'd really want to kick off a build from a git commit, you can trigger it again, or make a dummy commit and push it. `git commit --allow-empty -m "Trigger notification" && git push`.

**Comment by arvindsv** [comment] 2018-09-19 15:45
Closing as wont-fix based on the comment.

It might not matter, but my preference for a bad commit would be to `git revert` so that the mistake is still in history. But, I can see that it's not the right approach for some.

**Closed by arvindsv** 2018-09-19 15:45 UTC

**Comment by matthias-k** [comment] 2018-09-19 20:22
Thanks for your help! I understand the reasoning and I agree about `git revert` for production branches, but I am very much in favor of keeping development and feature branches clean. It makes debugging and bisecting later on easier.

I think my main concern would be that when using gocd for continuous delivery, this is a bit counterintuitive.

Anyway, now that I am aware, I will be able to work around it :).

**Comment by adelahoz-meli** [comment] 2021-09-27 05:41
rp retest
