### ISSUE TITLE
Provide arm64 Mac installers/zips rather than relying on Rosetta for Apple Silicon

### ISSUE THREAD

**Issue by ian-mcdowell** [gocd/gocd#10887] opened 2022-10-03 08:01 UTC
##### Issue Type

Enhancement

##### Summary

I downloaded the latest stable GoCD release (22.2.0), and all commands executed in pipelines are running via Rosetta emulation on an Apple Silicon Mac.

Since the `java` binary in the embedded JRE is only compiled for Intel, all child processes it spawns also run as Intel.

##### Environment

Server:
https://download.gocd.org/binaries/22.2.0-14697/osx/go-server-22.2.0-14697-osx.zip

Agent:
https://download.gocd.org/binaries/22.2.0-14697/osx/go-agent-22.2.0-14697-osx.zip

Problematic binary:
```plain
↪ file jre/Contents/Home/bin/java 
jre/Contents/Home/bin/java: Mach-O 64-bit executable x86_64
```

Some binaries in the package are compiled for arm64, though, which is good.
```plain
↪ file wrapper/wrapper-macosx-arm-64
wrapper/wrapper-macosx-arm-64: Mach-O 64-bit executable arm64
```

**Comment by ian-mcdowell** [comment] 2022-10-03 08:09
I was able to successfully work around this by swapping out the `jre` folder with the contents of the arm64-built JDK 17 from Oracle:

https://download.oracle.com/java/19/latest/jdk-19_macos-aarch64_bin.tar.gz

**Comment by chadlwilson** [comment] 2022-10-03 08:21
This is a dupe of #8544 and #9029 essentially although it probably needs to be broken down more clearly into providing installers (and validating wrapper and server along with bootstrappers) separately to containers to make it incrementally achievable.

Note that this is an unvalidated/tested configuration but there's no reason it shouldn't work. Any observations you have would be useful.

**Comment by chadlwilson** [comment] 2022-10-03 08:23
I have been updating the tanuki wrapper specifically to get support for this but hadn't got around to all the logistics and testing infrastructure changes required to validate things 😅

Note that we'd probably use temurin/adoptium JVM builds in the 'real thing', for consistency.

**Closed** 2022-10-16 10:55 UTC
Labels: enhancement, installers

**Comment by chadlwilson** [comment] 2022-10-17 02:41
@ian-mcdowell If you want to give these a go, would welcome any feedback on the experimental installers at https://www.gocd.org/download/#osx (experimental tab). Otherwise these should get published with the next release. Probably goes without saying, but don't recommend using experimental installers with production data or environments, just local sanity testing :-)

Direct links:
https://download.gocd.org/experimental/binaries/22.3.0-15164/osx/go-server-22.3.0-15164-osx-aarch64.zip
https://download.gocd.org/experimental/binaries/22.3.0-15164/osx/go-agent-22.3.0-15164-osx-aarch64.zip

**Comment by chadlwilson** [comment] 2022-10-22 10:25
There's also an [Apple Silicon test-drive available](https://www.gocd.org/test-drive-gocd.html?dl=latest) now which is probably the easiest way to play with GoCD server+agent locally with example pipelines.
