### ISSUE TITLE
Login redirection behind proxy incorrect

### ISSUE THREAD

**Issue by samritchie** [gocd/gocd#741] opened 2014-12-02 05:47 UTC
I have Go running behind an SSL-enabled Elastic Load Balancer, but for some reason the login redirection ALWAYS redirects to HTTP - I only want to run the application over HTTPS. Is this a known issue?

**Comment by rdsubhas** [comment] 2015-01-30 11:21
+1, Facing this same issue on this case:

* When there is a SSL proxy (e.g. Amazon ELB or Nginx)
* And the SSL proxy does SSL offloading
* And proxies to Go.CD over **plain HTTP**
* Then Go.CD responds with a HTTP redirect

I trust its one of:

* Go.CD doesn't read `X-Forwarded-Proto` header that proxies generally use to indicate the original request protocol. Instead it sees that the proxy hit using **HTTP** and redirects to HTTP
* Even if the `Site URL` is configured as something else, Go.CD still responds to direct IP hits without any URL redirection (agree this is good for dev productivity, but could be a reason)
* Something else I'm ignorant of :)

**Comment by framegrace** [comment] 2015-05-27 07:09
+1 Same issue here. 
Any solution?

**Comment by ketan** [comment] 2015-05-28 08:34
If it helps, here's an Apache configuration that is known to work (copied from build.go.cd) Note that SSL port 443 is being forwarded to 8154, so that `X-Forwarded-Proto` is not needed.

In another example of an nginx setup I'd done (at the bottom), port 443 was proxied onto port 8153 along with the `X-Forwarded-Proto` header.

``` apache
# cat /etc/httpd/conf.d/go-server.conf
Listen ip.add.re.ss:80
Listen ip.add.re.ss:443
NameVirtualHost ip.add.re.ss:80

<VirtualHost ip.add.re.ss:80>
  ServerName build.go.cd
  DocumentRoot /var/www/html
  RewriteEngine On
  RewriteRule ^/(.*)$ https://build.go.cd/$1 [R=permanent,L]
</VirtualHost>
 
<VirtualHost ip.add.re.ss:443>
  ServerName build.go.cd
  DocumentRoot /var/www/html
  SSLProxyEngine on
  SSLEngine on
  SSLHonorCipherOrder On
  SSLInsecureRenegotiation Off
  SSLProtocol -ALL +TLSv1
  SSLCipherSuite RC4-SHA:HIGH:!ADH:!kEDH:!MD5:!aNULL:!EDH
  SSLCertificateFile /etc/pki/httpd/go.cd.crt
  SSLCertificateChainFile /etc/pki/httpd/go.cd-intermediate.crt
  SSLCertificateKeyFile /etc/pki/httpd/go.cd.key.unsecure
  ProxyPass / https://localhost:8154/
  ProxyPassReverse / https://localhost:8154/
  ProxyPreserveHost On
</VirtualHost>
```


``` nginx
# cat /etc/nginx/conf.d/ci.snap-ci.com.conf
 
#
# File autogenerated by chef. All changes will be lost
#
 
server {
    listen         80;
    server_name    ci.example.com;
    return 301     https://ci.example.com$request_uri;
}
 
server {
  listen                    443 ssl;
  server_name               ci.example.com;
  ssl_certificate           /etc/pki/nginx/ci.example.com/ci.example.com.crt;
  ssl_certificate_key       /etc/pki/nginx/ci.example.com/ci.example.com.key.unsecure;
  ssl_protocols             SSLv3 TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;
 
 
  access_log          /var/log/nginx/ci.example.com.access.log  combined;
  error_log           /var/log/nginx/ci.example.com.error.log   error;
 
  keepalive_timeout   65;
  gzip                on;
  gzip_comp_level     6;
  gzip_types          text/plain text/css text/javascript application/x-javascript application/javascript application/json text/json text/xml application/xml;
 
  # Preserve hostname for backend server
  proxy_set_header    Host       $http_host;
 
  location / {
    proxy_buffering         on;
    proxy_buffer_size       128k;
    proxy_buffers           100  128k;
    proxy_pass              http://127.0.0.1:8153/;
    proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
  }
}
```

**Comment by ketan** [comment] 2015-05-28 08:41
Also it might help debugging if you can make a curl call with the relevant `X-Forwarded-*` headers directly to the go server bypassing the ELB and see what sort of responses you get.

``` bash
curl http://1.2.3.4:8153/your/path \
    -H 'X-Forwarded-For: 5.6.7.8' \
    -H 'X-Forwarded-Proto: https' \
    -v
```

**Comment by davidpaniz** [comment] 2015-07-17 14:14
+1
Happens with gocd-server 15.1 and 15.2.

**Comment by rdsubhas** [comment] 2015-07-18 18:34
@ketan thanks for the pointers, unfortunately I don't have access to that instance anymore so I'm unable to run the tests. hope to run them again soon.

**Comment by olvesh** [comment] 2015-08-05 14:54
I am trying to set up gocd-server  behind a haproxy using the docker images. Wanted to test the oauth clients, but since the oauth needs https I need to get this working, but I can't find a workaround.

I have tested the proposed ways for apache/nginx above (for haproxy) but still the browser gets redirected onto itself.

This curl attempt is directly against the docker instance, not via haproxy (gocd.vimond.dev is in my hosts file).

Is there any more I can do 
``` 
curl -v http://gocd.vimond.dev:32788/go/oauth/admin/clients \
 -H 'X-Forwarded-For: 192.168.33.60' \
 -H 'X-Forwarded-Proto: https' \
 -H 'X-Proto: https'
* Hostname was NOT found in DNS cache
*   Trying 192.168.33.60...
* Connected to gocd.vimond.dev (192.168.33.60) port 32788 (#0)
> GET /go/oauth/admin/clients HTTP/1.1
> User-Agent: curl/7.37.1
> Host: gocd.vimond.dev:32788
> Accept: */*
> X-Forwarded-For: 192.168.33.60
> X-Forwarded-Proto: https
> X-Proto: https
>
< HTTP/1.1 302 Found
< Date: Wed, 05 Aug 2015 14:53:21 GMT
< Set-Cookie: JSESSIONID=1ezhh94ezwho71vcsrk7izexlh;Path=/go;Expires=Wed, 19-Aug-2015 14:53:21 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: https://gocd.vimond.dev/go/oauth/admin/clients
< Content-Length: 0
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
<
* Connection #0 to host gocd.vimond.dev left intact
```

**Comment by jeisen** [comment] 2015-08-05 18:37
Seeing the same issue with GoCD sitting behind an Nginx/HAProxy LB. SSL is handled entirely by the LB, with a redirect from any http:// request to https://ci.example.com/.

From there:
- Go redirects to the relative '/go/home', maintaining the protocol imposed by the LB
- That redirects to the fully-qualified 'http://ci.example.com/go/auth/login'
- That redirects to 'https://ci.example.com'
- Repeat

The nginx config posted above does not appear to solve the issue. We've also changed the config so that siteUrl is explicitly https://ci.example.com, but that also does not solve the problem.

**Comment by olvesh** [comment] 2015-08-05 19:18
I have been poking around in the source, but I don't know where to look.. Not sure if this redirect happens in rails or in java source. 

I believe the culprit is staring here:
https://github.com/gocd/gocd/blob/cdaaac75c95a6c77a668aff110bb3aab8cd8ff2b/server/webapp/WEB-INF/rails.new/vendor/engines/oauth2_provider/lib/oauth2_provider/ssl_helper.rb#L13-13

as ```def ssl?``` returns false, even if all the headers are set correctly. This leads me to believe that either the headers are being stripped or some wrong implementation of the ```request.rb``` in jruby is being used.

I am not sure which ruby implementation of request is used, but  
https://github.com/gocd/gocd/blob/cdaaac75c95a6c77a668aff110bb3aab8cd8ff2b/server/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/request.rb#L84-84

should work.. But there are many implementations of ```request.rb``` in ruby in the source, and I really don't know how to be sure which is used.

**Comment by ketan** [comment] 2015-08-06 04:44
@olvesh - Are you still able to reproduce this issue after setting [site urls](http://www.go.cd/documentation/user/current/installation/configuring_server_details.html#configure-site-urls). If you're unable to hit the server specifically with the `/oauth/` URLs, may I suggest opening another issue. OAuth is handled by a separate plugin as you probably figured out, we would like to track that issue separately from this one.

**Comment by ketan** [comment] 2015-08-06 04:47
@jeisen - What is the output of running this command (note that you have to connect straight to the IP address of your go server, **without** going through any proxies/load balancers)

```ruby
curl http://1.2.3.4:8153/\
    -H 'Host: ci.example.com' \
    -H 'X-Forwarded-For: 5.6.7.8' \
    -H 'X-Forwarded-Proto: https' \
    --location \
    -v
```

**Comment by olvesh** [comment] 2015-08-06 06:15
@ketan - Yes, I have set the site urls. As you see from my output I get a redirect to a https://gocd.vimond.dev which is what I have configured in siteurls. 

I will open a new issue.

**Comment by jeisen** [comment] 2015-08-06 16:53
@ketan I'm not sure if you're literally looking for that, since in my actual setup ci.example.com isn't actually set. Here's what I got:

```
* Hostname was NOT found in DNS cache
*   Trying <server IP>...
* Connected to <server IP> (<server IP>) port 8153 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: ci.example.com
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 06 Aug 2015 16:45:20 GMT
< Location: /go/home
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 13
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
< 
* Ignoring the response-body
* Connection #0 to host <server IP> left intact
* Issue another request to this URL: 'http://<server IP>:8153/go/home'
* Found bundle for host <server IP>: 0xf79970
* Re-using existing connection! (#0) with host <server IP>
* Connected to <server IP> (<server IP>) port 8153 (#0)
> GET /go/home HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: ci.example.com
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 302 Found
< Date: Thu, 06 Aug 2015 16:45:20 GMT
< Set-Cookie: JSESSIONID=1r17l0d39j8fy2zhtyfryfsa8;Path=/go;Expires=Thu, 20-Aug-2015 16:45:20 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://ci.example.com/go/auth/login
< Content-Length: 0
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
< 
* Connection #0 to host <server IP> left intact
* Issue another request to this URL: 'http://ci.example.com/go/auth/login'
* Hostname was NOT found in DNS cache
* Could not resolve host: ci.example.com
* Closing connection 1
curl: (6) Could not resolve host: ci.example.com
```

With ci.example.com standing in for the URL the load balancer is responding to, it goes into a redirect loop:

```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8153 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: ci.example.com
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Location: /go/home
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 13
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:8153/go/home'
* Found bundle for host localhost: 0xa3e930
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8153 (#0)
> GET /go/home HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: ci.example.com
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 302 Found
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Set-Cookie: JSESSIONID=16kxn6xmwm3gb1ndxk12nwydrz;Path=/go;Expires=Thu, 20-Aug-2015 16:40:45 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://ci.example.com/go/auth/login
< Content-Length: 0
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://ci.example.com/go/auth/login'
* Hostname was NOT found in DNS cache
*   Trying 123.45.67.89...
* Connected to ci.example.com (123.45.67.89) port 80 (#1)
> GET /go/auth/login HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://ci.example.com/
< 
* Ignoring the response-body
* Connection #1 to host ci.example.com left intact
* Issue another request to this URL: 'https://ci.example.com/'
* Found bundle for host ci.example.com: 0xa3e7c0
* Hostname was NOT found in DNS cache
*   Trying 123.45.67.89...
* Connected to ci.example.com (123.45.67.89) port 443 (#2)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES128-SHA
* Server certificate:
* 	 subject: <***> <the LB's certificate>
* 	 start date: <***>
* 	 expire date: <***>
* 	 subjectAltName: ci.example.com matched
* 	 issuer: <***>
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 13
< Connection: keep-alive
< Location: /go/home
< 
* Ignoring the response-body
* Connection #2 to host ci.example.com left intact
* Issue another request to this URL: 'https://ci.example.com/go/home'
* Found bundle for host ci.example.com: 0xa3e7c0
* Re-using existing connection! (#2) with host ci.example.com
* Connected to ci.example.com (123.45.67.89) port 443 (#2)
> GET /go/home HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 302 Found
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: JSESSIONID=1fgoklcwxk73z1wexik77tacsg;Path=/go;Expires=Thu, 20-Aug-2015 16:40:45 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://ci.example.com/go/auth/login
< 
* Connection #2 to host ci.example.com left intact
* Issue another request to this URL: 'http://ci.example.com/go/auth/login'
* Found bundle for host ci.example.com: 0xa3e7c0
* Re-using existing connection! (#1) with host ci.example.com
* Connected to ci.example.com (123.45.67.89) port 80 (#1)
> GET /go/auth/login HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://ci.example.com/
< 
* Ignoring the response-body
* Connection #1 to host ci.example.com left intact
* Issue another request to this URL: 'https://ci.example.com/'
* Found bundle for host ci.example.com: 0xa3e7c0
* Re-using existing connection! (#2) with host ci.example.com
* Connected to ci.example.com (123.45.67.89) port 443 (#2)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 13
< Connection: keep-alive
< Location: /go/home
< 
* Ignoring the response-body
* Connection #2 to host ci.example.com left intact
* Issue another request to this URL: 'https://ci.example.com/go/home'
* Found bundle for host ci.example.com: 0xa3e7c0
* Re-using existing connection! (#2) with host ci.example.com
* Connected to ci.example.com (123.45.67.89) port 443 (#2)
> GET /go/home HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 302 Found
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: JSESSIONID=n88wg4c5oo501v6pg9cnvgokl;Path=/go;Expires=Thu, 20-Aug-2015 16:40:45 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://ci.example.com/go/auth/login
< 
* Connection #2 to host ci.example.com left intact
* Issue another request to this URL: 'http://ci.example.com/go/auth/login'
* Found bundle for host ci.example.com: 0xa3e7c0
* Re-using existing connection! (#1) with host ci.example.com
* Connected to ci.example.com (123.45.67.89) port 80 (#1)
> GET /go/auth/login HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.example.com
> Accept: */*
> X-Forwarded-For: 5.6.7.8
> X-Forwarded-Proto: https
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 06 Aug 2015 16:40:45 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://ci.example.com/

<... repeated 50 times ...>
````

**Comment by skress** [comment] 2016-05-05 06:35
Ran into the same issue. The following setup is working for me:

- SiteURL and SecureSiteURL point to the https url
- Apache used as SSL endpoint, proxies to http (port 8153)
- Apache has to set X-Forwarded-Proto header

This is my Apache config

```apacheconf
<VirtualHost x.x.x.x:443>
    ServerAdmin webmaster@...
    ServerName ...
    DocumentRoot /var/www/html
    SSLEngine on
    SSLHonorCipherOrder On
    SSLInsecureRenegotiation Off
    SSLProtocol -ALL +TLSv1
    SSLCipherSuite RC4-SHA:HIGH:!ADH:!kEDH:!MD5:!aNULL:!EDH
    SSLCertificateFile /etc/...
    SSLCertificateChainFile /etc/...
    SSLCertificateKeyFile /etc/...
    ErrorLog /var/log/apache2/xxx.log
    CustomLog /var/log/apache2/xxx.log combined
    ProxyPreserveHost On
    ProxyPass / http://localhost:8153/
    <LocationMatch "/">
        RequestHeader set X-Forwarded-Proto "https"
    </LocationMatch>
</VirtualHost>
```

**Comment by ketan** [comment] 2016-05-05 06:41
@skress — This was handled as part of #1688. What version of go are you on?

FYI: build.go.cd has this configuration —

```xml
<server siteUrl="https://build.go.cd" secureSiteUrl="https://build.go.cd" />
```

```apacheconf
<VirtualHost *:443>
  ServerName build.go.cd

  # ----------------- #
  # SSL Configuration #
  # ----------------- #

  SSLEngine on

  SSLCertificateFile ...
  SSLCertificateKeyFile ...
  SSLCertificateChainFile ...

  # Intermediate compatibility: Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7
  SSLProtocol ...
  SSLCipherSuite ...
  SSLHonorCipherOrder on

  # Enable this if your want HSTS (recommended)
  Header add Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

  BrowserMatch "MSIE [2-6]" \
    nokeepalive ssl-unclean-shutdown \
    downgrade-1.0 force-response-1.0
  # MSIE 7 and newer should be able to use keepalive
  BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown


  ErrorLog          ...
  CustomLog         ...

  RewriteEngine On
  RewriteCond %{REQUEST_URI} ^/go/api/admin/feature_toggles/plugin_upload_feature_toggle_key$ [NC]
  RewriteRule ^.*$ - [F,L]

  SSLProxyEngine on
  SetEnv proxy-initial-not-pooled 1

  ProxyPass         /  https://localhost:8154/
  ProxyPassReverse  /  https://localhost:8154/
  ProxyPreserveHost On
  RequestHeader set X-Forwarded-Proto "https"

</VirtualHost>
```

**Comment by ketan** [comment] 2016-05-05 06:45
I also tried with `ProxyPass` and `ProxyPassReverse` set to http://localhost:8153`, I think you may be seeing a problem because of a missing `ProxyPassReverse`

**Comment by skress** [comment] 2016-05-05 06:51
I'm on 16.4 and I don't see any problems. My setup is working. Just wanted to post my config as this thread seemed to be still open.

**Comment by ketan** [comment] 2016-05-05 06:53
> My setup is working. Just wanted to post my config as this thread seemed to be still open

Closing issue, thank you for posting the config snippet.

**Closed by ketan** 2016-05-05 06:53 UTC

**Comment by dukejones** [comment] 2017-03-21 01:21
+1 on X-Forwarded-Proto.  My nginx config had:
`proxy_set_header X-Forwarded-Proto $scheme`

Which didn't work because the ELB had stripped https already.  Changing it to:
`proxy_set_header X-Forwarded-Proto 'https'`

Worked.
