### ISSUE TITLE
Add button for easily selecting / rerunning failed jobs

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#4502] opened 2018-03-08 14:37 UTC
##### Issue Type
- Feature enhancement
##### Summary
It would be very helpful to have a button that selects all failed jobs so they can be easily rerun.
One of  my F5 load balancer consistently runs out of resources when I try to enable 200 members, and leaves 17 or 18 jobs failed, which I then have to selected one by one to rerun.

**Comment by ketan** [comment] 2018-03-08 14:40
Closing as duplicate of #3570. This was released in https://www.gocd.org/releases/#17-6-0

**Closed by ketan** 2018-03-08 14:40 UTC

**Comment by joel74** [comment] 2018-03-08 14:43
Cheers
