### ISSUE TITLE
Move agent configuration out the main <cruise> configuration

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#911] opened 2015-02-24 10:51 UTC
Agent configuration  

```
    <agents>
        <agent>
            <resources>
                <resource/>
            </resources>
        </agent>
    </agents>
```

is currently part of main config under the `<cruise>` tag and is modified during agent registration or changes via agent tab on the UI. 

Manual updates to this part of the config is not recommended. As of today we need to validate/merge/save the whole config whenever agent info changes. To avoid this we need to move it out to a separate file called "agents.xml" under "/etc/go" and from the code:
- Move it out of the [CruiseConfig](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/config/CruiseConfig.java)
- Make [AgentConfigService](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/AgentConfigService.java) not depend on [GoConfigService](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/GoConfigService.java)
- Move/change the implementation of Agent registration from [ApproveAgentCommand](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/config/update/ApproveAgentCommand.java), [UpdateResourceCommand](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/config/update/UpdateResourceCommand.java), [UpdateEnvironmentsCommand](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/config/update/UpdateEnvironmentsCommand.java)
- Look at how things are wired at [AgentRegistrationController](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/controller/AgentRegistrationController.java)
- Modify [AgentService](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/AgentService.java)

Things to consider
- Environments part of the config

```
  <environments>
    <environment name="UAT">
      <environmentvariables>
      <variable name="FOO"><value>bar</value></variable>
      </environmentvariables>
      <agents>
        <physical uuid="94fcb7ad-8b97-4078-b5f6-3c7436d6a390"/>
      </agents>
      <pipelines>
        <pipeline name="yourproject"/>
      </pipelines>
    </environment>
  </environments>
```

is modified on agent registration. Do we move this out of the main config?

**Comment by ciotlosm** [comment] 2015-03-10 08:47
This should be given higher priority. 
From the looks of it, if you're having configuration related performance problems, the more active agents you have, the more you will affect your own server. 
We've seen the need to disable agents in order to get the server responding again in times of peak load. 
This is far from ideal and looking at the details here, this seems like a huge performance bottleneck as soon as you increase the number of agents. 

Considering as you get more pipelines and jobs you want more agents as well, the performance degradation is no longer linear, but it increases at a higher rate.

**Comment by mmb** [comment] 2015-03-11 03:46
@ciotlosm @zabil How many agents do you have?

We currently have 75 and are looking into this as a potential cause of some performance issues we are experiencing.

**Comment by jefftrimm** [comment] 2015-03-13 21:03
+1 We intend to use Go agents running on application servers to orchestrate deployment tasks.  The number of deployment agents will grow quickly into the 100's.

**Comment by zabil** [comment] 2015-03-16 07:08
@ciotlosm @mmb @jefftrimm 
There are a few bugs we are fixing ease the load on the server agent communication #104 #901  
These are slated for 15.1 release. It's possible that they contribute to current slowness.

@mmb I haven't yet tested this with a lot of agents. This issue is spawned out of our discussion on #838 
We are trying to save some cpu cycles by avoiding a full validation on the config xml. We are also discussing about doing the validation intelligently for e.g in this case skip validating other parts of the config xml and simply do the save.

**Comment by reidca** [comment] 2015-03-18 12:27
+1 This sounds like an excellent idea. Any improvements to the ability to manage agents and reduce the time taken gets a big plus from me.

**Comment by ketan** [comment] 2015-05-07 10:31
This has been slotted into release `15.2`, I'm looking at ways to remove the `<agents/>` section out of the `cruise-config.xml`.

There is no definite answer to where it'll move to next, or if users may be able to edit it as an XML like they are doing now. APIs to manage agents will remain unchanged.

**Comment by reidca** [comment] 2015-05-07 11:52
Please, if you are going to move it ensure there is a place where it can be edited.

We make use of the ability to manage agents in the xml because of the lack of good API support for agents.

In particular, because there is nowhere to change the name of the agent we edit this directly in the xml. Each of our agent machines is named using a non-semantic host name therefore it is crucial that we have a way of naming the agents. 

Of course enhancing the agents APIs to support additional actions would mean the xml is irrelevant and becomes an implementation detail.

Thanks

**Comment by ketan** [comment] 2015-05-07 12:16
> We make use of the ability to manage agents in the xml because of the lack of good API support for agents.

Thank you for bringing this up :)

> In particular, because there is nowhere to change the name of the agent we edit this directly in the xml. Each of our agent machines is named using a non-semantic host name therefore it is crucial that we have a way of naming the agents.

Are there other agent APIs that you'd find useful that are currently not available?

**Comment by reidca** [comment] 2015-05-07 14:55
Thank you for your interest in this area. My aim is to completely automate the installation and configuration of agents. This is especially important when the machines that we install agents on are short-lived. I understand there is other work in the space on elastic agents however I do not know the details on that.

I have already raised a couple of agent related issues here.

For reference these are:
#484
#958
#959

In addition we have had issues with agents that are temporarily unavailable because the machine is shut-down (Windows 7 client machines typically that we use as additional agents) therefore an easy way for the agents to be able to de-register themselves from the server at shut-down would be very useful.

Thanks

**Comment by lenucksi** [comment] 2015-10-02 17:07
Config change validation and saving would probably also benefit from this due to way less configuration changes when autoscaling Go agents. See also: #1498

**Comment by grahamc** [comment] 2016-02-24 16:57
I would like to put a hearty :+1: on this feature, as I much prefer to declaratively configure GoCD, and having Go alter the configuration during run-time makes this much more difficult.

**Comment by mmindenhall** [comment] 2018-05-09 16:42
Has any work been done on this?  We have hand-built most of cruise-config.xml, and keep it in source control.  We also keep our pipelines in source control, using the [YAML config plugin](https://github.com/tomzo/gocd-yaml-config-plugin).  

It's very difficult to manage this when the `<agents>`, `<environments>`, and `<pipelines group="a-group-defined-by-yaml">` tags are being dynamically added to the file at runtime.  When we copy new changes in (without these tags), the server stops processing pipelines, and we have to kill all of the elastic agents and bounce the server.

It would be great to have config files that are read-only from the server, so we can safely copy in changes and have them picked up and applied.

**Comment by arvindsv** [comment] 2018-09-19 16:06
Also see https://github.com/gocd/gocd/issues/1498#issuecomment-422404610

There's still no progress on this. It's a big change which hasn't been picked up. It has some effect on environments as well.

**Comment by Stono** [comment] 2018-09-19 16:11
Hey.
So this for me is critical to the Kubernetes work.  People on k8 (such as us) are more likely to be using ephemeral agents!

**Comment by vrushaliwaykole** [comment] 2019-05-22 06:46
**ISSUE:**

With current flow for agents, we maintain three copies of agent information:

1. In memory as `AgentInstances` - Stores the information of all agents including pending agents
2. `cruise-config.xml` - Stores the information of registered agents
3. Database - Specifically stores the information of `cookie`

As we are moving agents out of config, there will be only two copies
1. In memory as `AgentInstances` - Stores the information of all agents including pending agents
3. Database - Information which used to be stored in `cruise-config.xml` and database(including a cookie)

The agent can auto-register itself or with the normal registration flow (where it goes into pending state and someone has to enable it manually)

The issue comes in the auto registration flow

Current auto registration flow is:

1. Add the agent in `AgentInstances`
2. Add the agent in `cruise-config.xml`
3. Assign the certificate

`cookie` is assigned as part of a `ping` and `getWork` call. Once the cookie is assigned, the agent gets added into the database.

Now, as agents are removed from `cruise-config.xml`, we need to add agent directly into the database at the time of registration where `cookie` field is mandatory.
We cannot assign a cookie as part of the registration flow because this will not ensure that the agent gets a cookie.

**SOLUTION:**

- While adding an entry in the database at the time of registration, we will assign a dummy cookie.
- Actual `cookie` will be assigned as part of a `ping` or `getWork` call where we have to add one extra check for a dummy cookie.
- Rest of the flow will work as it is.

\cc: @maheshp @bdpiparva @arvindsv

**Comment by bdpiparva** [comment] 2019-05-22 07:03
> where we have to add one extra check for a dummy cookie.

In **SOLUTION** 2nd point, What do you mean by adding extra check?

**Comment by viraj2712** [comment] 2019-05-22 12:37
Gone through the code, and realized that there is no need to add an extra check
Also, we need to add the `Random(dummy)` cookie in the normal registration flow as well

\cc: @bdpiparva @vrushaliwaykole

**Comment by ckaushik** [comment] 2019-09-03 10:46
@arvindsv is this targetted for 19.8.0 release?

**Comment by arvindsv** [comment] 2019-09-03 11:43
@ckaushik No. It's quite big and is in progress (lots and lots of corner cases to consider). So, it's for 19.9. Tentatively October.

**Comment by arvindsv** [comment] 2019-09-03 11:51
By the way, it's happening in https://github.com/gocd/gocd/pull/6271

**Comment by rajiesh** [comment] 2019-09-04 14:58
cc: @maheshp @kritika-singh3 @adityasood 

WIP: Test scenarios for validating PR #6271 

Test setup: Prepare test setup with minimal of,

- Static and elastic agents registered and building jobs
- Few Pending/disabled/Missing/Lost contact agents
- Agents associated with environments and resources from config XML
- Agents associated with environments via config repo
- Agents Analytics populated with data
- Agents from multiple OS types

Migration: Upgrade from 19.x and 18.x versions of server to 19.9 version

Migration should take care of,

- All agents(irrespective of its state) removed from config XML and moved to Agents table in DB - validate in DB
- Agents SPA should show the status as it was before migration
- Pending agents should be still be in pending state
- Ensure Idle/Building/Disabled/Lost Contact/Missing agents are listed as it was before migration
- Check for Disabled(Building) state too
- Ensure agents association with resources and environments are maintained after migration
- Config repo association of agents and environments should also be maintained
- Config XML should not have agents associated with environments
- Ensure DB has the environments/resources association to agents
- Ensure analytics data are shows as before after migration
- Ensure job run history for each agent is populated as expected
- Check these scenarios for both static and elastic agents

Migration Performance:
- Validate migration using a setup with 300 agents. Measure the time for migration. More details about the setup needs to be fill in
- Some of our dog fooding environments will be used to measure the migration performance

After migration perform below tests,

- New agent registration(local and remote) should work as expected - with and without auto register properties
- Association of resources and environments using auto register properties should be successful
- Multiple agents on single host scenario
- Enable of disabled agents should work as expected
- Deletion of disabled agents should be successful  - verify DB
- Agents which were missing(agent process stopped) before migration should update to Idle state when agent process started after migration
- Run on all agents option on Jobs should work as expected
- Create environment and associate with few agents. Delete the environment from config XML - this scenario will lead to agent being still associated to environment but no pipeline in the same environment, agent will stay connected but no assignment - how will user get feedback?
- Ensure duplicate UUIDs are not allowed - this can be validated by running 2 agents on single host by duplicating agent working directory. Without clearing the guid.txt file registration of second agent should not be allowed
- Agents can be switched to point to another GoCD server
- Agent disabled while building should move to Disabled(Building) state and complete the job

- Agents - environment association in config repo
    - Create environments config repo with agent associated. Agents page should reflect the association
    - Update environments config repo to change the association(remove some agents/add some agents) - changes should reflect on the agents page
    - Job assignment should be as per the association
    - DB Agents table should not be updated for config repo associations
    - Remove environments config repo - Agent association should be removed too in that case
    - Non exiting/Deleted/Disabled UUIDs should not be allowed to use in environments config

- Agents API(v6)
    - Perform GET and Update operations, bulk updates
    - Non existing environments are also allowed now - no validation on environments
    - Failure scenarios should be handled - Invalid/non-existing/deleted UUID in request, single/bulk update of deleted agent UUID
    - Enabling deleted UUID should not be allowed

- Agent page
    - For user, page should function as is - All agent operations should be as expected
    - Agent runtime info changes should be reflected on Agents page and in DB
    - Validate the agent state transitions - Idle/Building/Disabled/Disabled(Building)/Lost contact/Missing

- Environments API(v3)
    - Older versions not supported
    - v3 should not support agent - environment association

- Environments page
    - For user, the page should function as is - association of pipelines/agents and environment variables should be successful
    - Verify environments create and update requests makes both environments API call and Agents API call(for association with agents)
    - Failure in environments API call should roll back agents API changes - To reproduce this scenario create environment and associate it with a pipeline, an agent and an environment variable with secret(let secret param be invalid - non existing secret configuration). The environments API should fail, which should revert the DB change to Agents table. Verify DB for the same

- Elastic agents
    - Verify agent state transitions - Idle/Building/Disabled/Delete
    - Agents in building state when disabled should transition to Disabled(building) and complete the job and get deleted
    - Agent in building state when cancelled should transition to Building(Cancelled) and then to deleted state
    - Agents created for pipeline in environment should get associated with that environment when register with server
    - Verify agent termination scenario - if an elastic agent container is destroyed while processing job, job should get assigned to new elastic agent
    - Agents should not be allowed to be associated with resource or environment from agent API/page
    - Validate on all elastic agents plugin
    
- Analytics
    - No behavior change in analytics
    - Agent state transition graph and Agents with highest utilization graphs should be showing data as per its behavior
    - Compare the analytics data before and after migration

**Comment by rajiesh** [comment] 2019-09-26 03:55
Verified in 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)

**Closed by rajiesh** 2019-09-26 03:55 UTC
Labels: [stream] other
