### ISSUE TITLE
Migrating from 20.4 to 20.7 GoCD crash after starting

### ISSUE THREAD

**Issue by lgs** [gocd/gocd#8631] opened 2020-10-09 08:44 UTC
##### Issue Type

- Bug Report

##### Summary

Migrating GoCD from 20.4 to 20.7 business continuity does not work as expected

##### Environment
The full http:// go-server-host /go/api/support is to big to be submitted here. 
Please have a look at [full go api support here](https://gist.github.com/lgs/b29c9097890d4eb99909990b74313f38)

###### Basic environment details

* GoCD Version: 20.7.0 (12097-f4f86ca8d433edaf9235ed92790c11e19d7be4ed).
* JAVA Version: | 13.0.2
* OS Information: | Linux 3.10.0-862.14.4.el7.x86_64
* Postgres 9.6.10
* Usable space in artifacts repository: | 3.37 GB
* Pipelines Count: | 83

###### Additional Environment Details

He have two hosts, the Primay (GoCD + Postgres) and Secondary (GoCD + Postgres) 
The secondary share NFS file system with cruise-config.xml with the primary:
```
weloadm@go02:~ # df -h /shared
Filesystem                 Size  Used Avail Use% Mounted on
xxx.xxx.x.48:/root/shared   37G  3.8G   34G  11% /shared

weloadm@go01:~ # df -h /shared
Filesystem                 Size  Used Avail Use% Mounted on
xxx.xxx.x.48:/root/shared   37G  3.8G   34G  11% /shared
```

##### Steps to Reproduce

1.  just following standard doc:  https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html
2.  as a second try we did this:    https://extensions-docs.gocd.org/upgrade_to_gocd_20.5.0/

##### Expected Results
Coming from 20.4 where we had business continuity jar extension, we were used to see both primary and secondary GoCD servers up when the service was on primary. 

##### Actual Results
Starting the secondary GoCD suddenly crash, while both of DBs are up & running 
Also, failing over manually we can get the server up on secondary and the DB is fine but the dashboard is not able to authenticate and we are not sure why.

##### Possible Fix
...

##### Log snippets

```
INFO   | jvm 1    | 2020/09/22 12:24:40 | Unable to create database upgrade script for database. The problem was: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'go02-000-021-0', LOCKGRANTED = '2020-09-22 12:24:40.632' WHERE ID = 1 AND LOCKED = FALSE: ERROR: cannot execute UPDATE in a read-only transaction. The cause was: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'go02-000-021-0', LOCKGRANTED = '2020-09-22 12:24:40.632' WHERE ID = 1 AND LOCKED = FALSE: ERROR: cannot execute UPDATE in a read-only transaction

INFO   | jvm 1    | 2020/09/22 12:24:40 | liquibase.exception.LockException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'go02-000-021-0', LOCKGRANTED = '2020-09-22 12:24:40.632' WHERE ID = 1 AND LOCKED = FALSE: ERROR: cannot execute UPDATE in a read-only transaction
```

##### Code snippets/Screenshots
```
go02:root:/root # journalctl -u go-server
Oct 01 14:11:25 go02 go-server[13601]: Starting go-server...
Oct 01 14:11:29 go02 go-server[13601]: Waiting for go-server......
Oct 01 14:11:29 go02 systemd[1]: Started go-server.
Oct 01 14:11:45 go02 systemd[1]: go-server.service: main process exited, code=exited, status=1/FAILURE
Oct 01 14:11:45 go02 systemd[1]: Unit go-server.service entered failed state.
Oct 01 14:11:45 go02- systemd[1]: go-server.service failed.
```

##### Any other info
We tried going 20.4 to 20.5 and also 20.4 to 20.8 and got the same result.

**Failing over manually we can get the server up on secondary and the DB is fine but the dashboard is not able to authenticate and we are not sure why.**

**Comment by arvindsv** [comment] 2020-10-09 10:01
Closing as a duplicate of #8630

**Closed by arvindsv** 2020-10-09 10:01 UTC
