### ISSUE TITLE
/go/api/config/pipeline_groups error

### ISSUE THREAD

**Issue by BLOPESLO** [gocd/gocd#7588] opened 2020-01-13 13:50 UTC
##### Issue Type
bug

##### Summary

/go/api/config/pipeline_groups  get error 
    "message": "Either the resource you requested was not found, or you are not authorized to perform this action."

gocd version:19.12.0

We received the "message": "Either the resource you requested was not found, or you are not authorized to perform this action." when execute /go/api/config/pipeline_groups.
Whats apened?

best regards,
Bruno Lobo

**Comment by GaneshSPatil** [comment] 2020-01-13 13:55
@BLOPESLO -- Looks like this issue is duplicate of https://github.com/gocd/gocd/issues/7521
Closing...

Feel free to reopen the issue if you've any further questions.

**Closed by GaneshSPatil** 2020-01-13 13:55 UTC
