### ISSUE TITLE
Show a confirmation dialog box when triggering a pipeline, a stage or a job.

### ISSUE THREAD

**Issue by atrgegit** [gocd/gocd#4064] opened 2017-12-06 12:54 UTC
##### Issue Type
- Feature proposal

##### Summary
Show a confirmation dialog box when triggering a pipeline, a stage or job (deploy job for example)

##### Environment
It is possible to trigger a deployment with one click, provided that you have the right authorizations. In order to reduce human mistakes, is it possible to add a confirmation dialog box on some actions.

###### Basic environment details

* Go Version: 17.11.0
* JAVA Version: 1.8.0_121
* OS: Linux 2.6.32-642.15.1.el6.x86_64
* Browser vendor and version (if relevant): not related

##### Steps to Reproduce
Trigger a pipeline, a stage or a job

##### Expected Results
In order to avoid some mistakes it would be useful to show a confirmation dialog box.

##### Actual Results
The action starts without confirmation on one click. 

##### Possible Fix
Adding an extra stage with manual approval or some checks on environment variables is a bit heavy. 

##### Any other info
Similar case is described at https://groups.google.com/forum/#!msg/go-cd/KgsOGTPGqpM/UsR0HvfH9UkJ;context-place=forum/go-cd, but implementing a simple confirmation dialog box would be nice.

**Comment by atrgegit** [comment] 2017-12-08 16:51
As for an update, a workaround would be to disable the following triggers :
operate.trigger_wrapper
button.force-run-pipeline
Which would force the use of "Trigger with options".
A switch to do that in go default properties ?

**Comment by arvindsv** [comment] 2017-12-08 16:58
Closing as a duplicate of #50. Might also be possible to consider as a part of the dashboard rewrite (https://github.com/gocd/gocd/issues/4037).

**Closed by arvindsv** 2017-12-08 16:58 UTC
