### ISSUE TITLE
UTF-8 umlauts from Mercurial not displayed correctly

### ISSUE THREAD

**Issue by greuelpirat** [gocd/gocd#7699] opened 2020-02-04 05:46 UTC
##### Issue Type
Bug Report

##### Summary
UTF-8 umlauts from Mercurial not displayed correctly. Usernames as well as comments are corrupt.

###### Basic environment details
Go Server Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0)
JVM version: 13.0.1
OS Information: Windows Server 2019 10.0
Usable space in artifacts repository: 31.08 GB
Database schema version: 1910006
Pipelines Count: 3

##### Steps to Reproduce
1. use a pipeline with mercurial repository
2. commit with user-name that contains umlaut

##### Expected Results
name and commit comments are displayed correctly

##### Actual Results
umlauts are displayed with corrupt-symbol.

##### Code snippets/Screenshots
![image](https://user-images.githubusercontent.com/16866222/73716920-aa4a3a80-4718-11ea-9476-14ae8174858f.png)

**Comment by arvindsv** [comment] 2020-02-07 14:37
@greuelpirat This seems similar to https://github.com/gocd/gocd/issues/6097.

I've seen that the character encoding in Windows is often not UTF-8 (sometimes it is cp1252). When GoCD finds output like that, it assumes that it is UTF-8 and the conversion can cause these issues. Can you see if that's the case here?

**Comment by greuelpirat** [comment] 2020-02-07 16:13
That is embarrassing :-( I totally forgot, that I have already reported this.

The text is encoded with UTF-8.

In windows command prompt:
![image](https://user-images.githubusercontent.com/16866222/74045051-667f5b80-49cc-11ea-868c-ba60e10e36f9.png)

In cygwin/mintty:
![image](https://user-images.githubusercontent.com/16866222/74045077-7139f080-49cc-11ea-97b7-3eaf969b176b.png)

In TortoiseHG:
![image](https://user-images.githubusercontent.com/16866222/74045121-844cc080-49cc-11ea-8118-5e416270c960.png)

In GO:
![image](https://user-images.githubusercontent.com/16866222/74044962-42237f00-49cc-11ea-9430-d5a8d955e0ea.png)

Seems to me that only TortoiseHG handles that correctly.

**Comment by arvindsv** [comment] 2020-02-07 16:19
Yes, since GoCD just uses `git` from the command-line, it probably gets whatever `git` reports. That might be why it is not seeing the right characters.

**Comment by greuelpirat** [comment] 2020-02-08 05:19
`git` or `hg`?

in windows command prompt and cygwin I can fix this issues be setting the correct code page with `chcp.com 65001`

**Comment by arvindsv** [comment] 2020-02-08 06:40
Oops. I meant `hg`, not `git`. It's the same with both, actually. It will just call out to `hg` in PATH and will expect the response to be in UTF-8. If you think `git` or `hg` are set up correctly, the next thing to look at will be the character encoding that GoCD server itself is started with. If that is not UTF-8, then it might be a problem (meaning, if it has taken the encoding from the system, for instance). Not sure how that can be checked. Maybe [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) shows it.

**Comment by greuelpirat** [comment] 2020-02-10 10:55
We tried adding 
`wrapper.java.additional.7=-Dfile.encoding=UTF-8` to `wrapper-config\wrapper.conf`, but this had no effect.

We took a look into `db\h2db\cruise.h2.db`. `SELECT * FROM MODIFICATIONS` returns following in the H2-Browser:
![image](https://user-images.githubusercontent.com/16866222/74143020-4fbe4c00-4bfa-11ea-8518-742527966f5e.png)

So the persisted data is already corrupt. The `ü` is saved with 3 bytes as `0xEF 0x3F 0x3D`. I have no clue which encode/interpret-combination can result in these 3 bytes.

**Comment by arvindsv** [comment] 2020-02-10 16:46
@greuelpirat I brought up a Windows Server 2019 box and reproduced what you see. I then tried to run `hg log` there on a small repository both in the command-prompt and in Powershell. I found that the output is in UTF-16.

The umlaut on Mac shows up in UTF-8 as `C3 BC`, as [it should](https://en.wikipedia.org/wiki/%C3%9C)). In UTF-16, it is `FEFF00FC` or just `00FC` (see [this](https://www.fileformat.info/info/unicode/char/00fc/index.htm)).

I consistently see the output show up as `00FC` on Windows. I tried to use `CHCP 65001` to change it to `UTF-8`, but it did not make any real difference.

Then, I wrote a small Java program to try and isolate this. I came up with this:

```java
import java.io.*;

public class ReadOutput {
    public static void main(String[] args) throws IOException {
        logThroughStreamReader();
        logThroughRedirect();
    }

    private static void logThroughRedirect() throws IOException {
        ProcessBuilder pb = new ProcessBuilder("hg", "log");
        File log = new File("log.through.process.txt");
        pb.redirectErrorStream(true);
        pb.redirectOutput(ProcessBuilder.Redirect.appendTo(log));
        pb.start();
    }

    private static void logThroughStreamReader() throws IOException {
        ProcessBuilder pb = new ProcessBuilder("hg", "log");
        pb.redirectErrorStream(true);
        Process process = pb.start();

        try (FileWriter log = new FileWriter(new File("log.through.inputstreamreader.txt"))) {
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), "utf-8"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    log.write(line);
                    log.write("\n");
                }
            }
        }
    }
}
```

The stream reader approach is closest to what happens within GoCD (if you trace all the way down into [StreamPumper](https://github.com/gocd/gocd/blob/ccc4ef16d6e37ee62641bfd86fdf65b7b4b1c61f/util/src/main/java/com/thoughtworks/go/util/command/StreamPumper.java#L53) in GoCD codebase). The output from this simple Java program also maps quite well to what I saw earlier. The output from `hg` itself comes in an encoding that Java ends up "corrupting" when it tries to read it as UTF-8. I hesitate to use the word "corrupting" because the encodings are wrong -- it's more of a wrong expectation between the two.

There are a couple of parts I can't explain, such as the output seen in the browser. The GoCD server seems to send this for that character (`EF BF BD`), which is _similar_ to the 3 bytes you saw. I suspect, if I dig further down into what is happening when it writes to the DB, etc. it'll become more clear.

However, since the output from `hg` itself is in a different encoding that what is expected, that's a bit of a moot point. That `hg` output is what needs to be fixed, in my opinion. Once it outputs in UTF-8, what I see happening in a Mac, should happen there as well.

I've attached all the supporting data in this gist: https://gist.github.com/arvindsv/b9ef8b19db4085f1ed208783f364db5e

If you think that the output is in UTF-8, can you run that Java program and attach the output?

Just for reference, here's what I see on a Mac (you can see `c3 bc` there):

```
$ od --endian=big -xc log.through.inputstreamreader.txt
...
0000100    2045    6872    656e    6dc3    bc6c    6c65    7220    3c74
              E   h   r   e   n   m   �   �   l   l   e   r       <   t
...
```

This is what I see on Windows, through Java's streamreader:

```
$ od --endian=big -xc log.through.inputstreamreader.txt
...
0000100    2045    6872    656e    6d3f    6c6c    6572    203c    7465
              E   h   r   e   n   m   ?   l   l   e   r       <   t   e
...
```

This is what I see, more or less directly (you can see `FC` there):

```
$ od --endian=big -xc log.through.process.txt
...
0000100    2045    6872    656e    6dfc    6c6c    6572    203c    7465
              E   h   r   e   n   m   �   l   l   e   r       <   t   e
...

[All these files are in the gist].
```

**Comment by greuelpirat** [comment] 2020-02-10 18:21
Here is my output with `java -classpath out/production/gocd-utf8-problem ReadOutput`
```
$ od --endian=big -xc log.through.inputstreamreader.txt
...
0000100    2045    6872    656e    6dfc    6c6c    6572    203c    7465
              E   h   r   e   n   m 374   l   l   e   r       <   t   e
...
```
[log.through.inputstreamreader.txt](https://github.com/gocd/gocd/files/4182396/log.through.inputstreamreader.txt)
[log.through.process.txt](https://github.com/gocd/gocd/files/4182399/log.through.process.txt)

**BUT**: When I run `java -Dfile.encoding=UTF-8 -classpath  out/production/gocd-utf8-problem ReadOutput` both files have correct UTF-8 content 🎉 . So may be the way we set the environment variable above (`wrapper.java.additional.7=-Dfile.encoding=UTF-8`) was wrong. Any idea for another way to set it?

**Comment by arvindsv** [comment] 2020-02-11 07:28
@greuelpirat I'll take a look later today. You can check whether that parameter was passed in properly to GoCD server using http://your-gocd-server:8153/go/api/support. All command-line parameters, etc. should show up there.

**Comment by ketan** [comment] 2020-02-11 08:13
This HG document <https://www.mercurial-scm.org/doc/hg.1.html> seems to
hint that setting the variable `HGENCODING` to `utf-8` might do the trick?

- Ketan

**Comment by arvindsv** [comment] 2020-02-11 10:35
You're right. It's worth trying.

I found that there's a whole page about this issue in Mercurial's wiki: https://www.mercurial-scm.org/wiki/CharacterEncodingOnWindows

@greuelpirat Can you try setting `HGENCODING` as an environment variable in `wrapper-properties.conf` and verifying it using /go/api/support?

**Comment by greuelpirat** [comment] 2020-02-11 14:31
Got it:

![image](https://user-images.githubusercontent.com/16866222/74243485-22e46480-4ce0-11ea-9891-53ac358ab9a5.png)

1. `wrapper.java.additional.7=-Dfile.encoding=UTF-8` in wrapper.conf (otherwise file.encoding defaults to `Cp1252`)
2. `HGENCODING` must be set as environment variable. If it is set in wrapper.conf (like `wrapper.java.additional.8=-DHGENCODING=UTF-8`) it has no effect. It must be a real environment variable.

Additional hint: the system property `sun.jnu.encoding` is according to .../go/api/support still set to `Cp1252`, but has no relevants here.

**Comment by arvindsv** [comment] 2020-02-12 09:27
@greuelpirat Glad it is working! There's a way to set environment variables in wrapper-properties.conf. See: https://github.com/gocd/gocd/blob/4fd4a7a9a5065362b3045e067115de7371cdeed2/installers/include/wrapper-properties.conf.example#L13

Maybe that would work too. I'll close this issue.

**Closed by arvindsv** 2020-02-12 09:27 UTC

**Comment by greuelpirat** [comment] 2020-02-12 18:24
You're right. This works also. Finally to make HG and UTF-8 working on Windows there are only 2 lines to be added to `wrapper-config\wrapper.conf`:

```
wrapper.java.additional.7=-Dfile.encoding=UTF-8
set.HGENCODING=UTF-8
```

Would be nice if you add it to your documentation.

**Comment by arvindsv** [comment] 2020-02-13 14:25
I couldn't think of a good place in the documentation to add this to, since it's very specific to hg on Windows. The docs are all open too: https://github.com/gocd/docs.go.cd/

I'm trying to make the wrapper-properties.conf be documented better. In case a later version of GoCD makes a change to wrapper.conf, it will overwrite your changes. So, it is recommended to use wrapper-properties.conf.
