### ISSUE TITLE
Pipeline specialization from templates

### ISSUE THREAD

**Issue by fabriciocduarte** [gocd/gocd#3568] opened 2017-06-03 18:37 UTC
##### Issue Type

- Feature proposal

##### Summary

Pipeline templates allows for fast and easy setup of new pipelines that perform the same type of work. This is specially useful for the introduction of new pipelines. 

As generic pipelines setup with templates over time specializes and needs to become more unique, it would be great if we had a quick way to set it back to not using templates but be with the same configuration the template had at the time of transition from generic (template) to unique. This also makes it easier to later decouple pipelines from their templates.

**Comment by arvindsv** [comment] 2017-06-05 12:41
Marking as a duplicate of #1090 and closing it. If anyone wants to contribute this, I think this can get accepted. I can see that it can useful. Need to think about discoverability of this feature, though.

**Closed by arvindsv** 2017-06-05 12:41 UTC
