### ISSUE TITLE
Pipeline creation wizard missing package material type

### ISSUE THREAD

**Issue by donita85** [gocd/gocd#7022] opened 2019-09-30 09:16 UTC
##### Issue Type

- Bug Report

##### Summary

The pipeline creation wizard introduced in version 19.8 of gocd is lacking the possibility to create a new pipeline by using the package material type. 

##### Environment

```
"Go Server Information": {
    "Version": "19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)"
  }
```
-->

###### Basic environment details

* Go Version: `19.9.0`
* JAVA Version: `12.0.1`
* OS: `Linux`
* Browser vendor and version (if relevant): `Chrome and Firefox`

##### Steps to Reproduce

1. A gocd server is running on version 19.9.0
2. Trying to create a new pipeline via the web GUI
3. Trying to set as material type for the new pipeline the Package option
4. The package option is missing from the drop-down menu

##### Expected Results
Like in versions < 19.8, package should be one of the options for material type

##### Actual Results
Cannot select package as material type.

##### Any other info
When creating a new pipeline via the API with the package option for material type everything looks ok. Even in the GUI, afterwards, the pipeline created like this can be selected, a new material can be added, and the type of this new material can be set to package. It's just that the wizard is lacking this option.

**Comment by adityasood** [comment] 2019-09-30 09:33
@donita85 the issue is captured in a brief [here](https://github.com/gocd/gocd/issues/6445) with some thoughts on the user flow.

**Comment by donita85** [comment] 2019-09-30 11:54
Thank you for the answer @adityasood! Do you have an estimation when this feature would be implemented? We are just now looking to upgrade our gocd instances from 19.5 and this feature would be really important for us. Our workflow includes a lot of pipelines created with package as material type and sometimes they are manually created.
Can maybe a fallback be implemented when one would not want to use the new wizard for pipeline creation? In this case, the old menu could appear?

**Comment by marques-work** [comment] 2019-09-30 18:40
@donita85 Thanks for bringing this to our attention. I don't have a timeframe yet, but we haven't forgotten about this and will be working on it soon (i.e., adding an option to choose a package repo in the material selector).

**Comment by jlusiardi** [comment] 2020-04-02 12:00
Hello,

this is also missing in the docker image `gocd/gocd-server:v20.2.0`. 

You can't select `package` as material type.

**Comment by arvindsv** [comment] 2020-04-02 12:42
Maybe some of the work @kritika-singh3 and @GaneshSPatil are doing around pipeline config SPA could be re-used here? @marques-work might have some thoughts as well.

**Comment by kritika-singh3** [comment] 2020-04-03 06:31
There is some work going on for supporting package materials and pluggable scms on https://github.com/gocd/gocd/pull/7920.
Feedback is welcomed!

**Comment by arvindsv** [comment] 2020-04-03 14:38
Thanks, @kritika-singh3. [Your comment there](https://github.com/gocd/gocd/pull/7920#issuecomment-608270368) is very relevant to this.

**Comment by mrmanc** [comment] 2020-04-08 18:01
Just wanted to mention #2947 here in case you feel it is a duplicate issue.

**Comment by arvindsv** [comment] 2020-04-21 11:05
Closing this as https://github.com/gocd/gocd/pull/7920 is done.

**Closed by arvindsv** 2020-04-21 11:05 UTC
