### ISSUE TITLE
Mercurial clone fails when repository contains files with paths greater than 171characters

### ISSUE THREAD

**Issue by splatteredbits** [gocd/gocd#534] opened 2014-09-17 22:43 UTC
Go leaves its artifacts in C:\Program Files (x86)\Go Server\pipelines\flyweight\{GUID}. This path is 89 characters long. Windows only allows paths to have a maximum of 260 characters. Thus, if your repository contains a path with more than 171 characters, Go can't clone/update that repository.

Steps to reproduce (in PowerShell):

 1. Create the repo:

      > hg init GoEval
      > cd .\GoEval
      > '' | Set-Content ('f' * 172)
      > hg add f*
      > hg ci -m 'Adding file with 172 characters.'
 2. Create a new Go pipeline, whose Materials points to the repository above (see attached screen shot). ![image](https://cloud.githubusercontent.com/assets/1082153/4312591/e2e2b072-3ebb-11e4-9876-2750739330a7.png)
 3. Note that Go can't clone the repository, even though it tries and tries and tries.

**Comment by arvindsv** [comment] 2016-06-04 12:10
Closing. This is either a mercurial issue (for not having an option like git's core.longpaths) or a duplicate of #484. Either way, it's a little sad.

**Closed by arvindsv** 2016-06-04 12:10 UTC
