### ISSUE TITLE
Message in trigger with options modal does not render

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4597] opened 2018-04-02 13:08 UTC
##### Issue Type

- Bug Report

##### Summary

The gray "solid line" underneath the revision is supposed to contain a message. It's currently being truncated so it does not show up.

![screen shot 2018-04-02 at 6 37 24 pm](https://user-images.githubusercontent.com/10598/38197224-e107c1e0-36a4-11e8-828c-aad3f3f57ef4.png)

**Comment by yankurk** [comment] 2018-04-02 16:28
Is there a way to reproduce this? I see you've tried it on trigger pipeline in go-cd PR. When I tried it, I could see the message.

**Comment by ketan** [comment] 2018-04-02 16:43
Hmm... I can't seem to be able to reproduce this anymore. Closing.

**Comment by yankurk** [comment] 2018-04-04 05:40
I saw this happening on the new dashboard. I couldn't reproduce it too. Need to investigate why it is happening. Can we open this issue again so that we know it exists? It can be investigated at a later point in time when the higher priority ones are solved and merged.

**Comment by GaneshSPatil** [comment] 2018-12-24 03:49
@ketan @yankurk -- Could not reproduce the above-mentioned issue with GoCD `v18.12.0`.
Closing this issue as of now.

Feel free to reopen the issue if observed again.

**Closed by GaneshSPatil** 2018-12-24 03:49 UTC
Labels: dashboard
