### ISSUE TITLE
Cache is getting created multiple times for the dashboard during server startup

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#5603] opened 2018-12-19 14:07 UTC
##### Issue Type
- Bug Report

##### Summary

Dashboard cache was being recreated thrice during server startup - once while registering config-change-listener for GoDashboardActivityListener, then for featureToggleService and finally for CachedGoConfig.onTimer. Making the cache recreation happen only if the config has really changed, using md5 checksum to check the same.

Related to PR #4560

**Comment by GaneshSPatil** [comment] 2019-01-02 11:08
Related issue: https://github.com/gocd/gocd/issues/4457

**Comment by GaneshSPatil** [comment] 2019-05-07 09:41
Closing this issue. Marking this duplicate of #4457

More information can be found on PR: https://github.com/gocd/gocd/pull/4560 and issue https://github.com/gocd/gocd/pull/4457

**Closed by GaneshSPatil** 2019-05-07 09:41 UTC
