### ISSUE TITLE
GoCD home page design padding weirdness

### ISSUE THREAD

**Issue by ringxw** [gocd/gocd#3066] opened 2017-01-03 22:05 UTC
##### Issue Type

- Bug Report

##### Summary

The main page of GoCd seems to have some UI padding issue. When we go on full screen, we can only see 4 pipelines on the same row, when the window is made smaller, it shows 5 pipelines.

###### Basic environment details

* Go Version: `16.12`
* JAVA Version: `1.8.0_91`
* OS: `Linux 3.10.0-229.el7.x86_64`
* Browser vendor and version (if relevant): `Chorme/Firefox`

##### Steps to Reproduce

1. Just visit the home page of GoCD

##### Expected Results
Full screen should show at least as many pipelines in a row

##### Actual Results
Full screen on browser shows less pipelines than modifying the pipeline
##### Possible Fix
Something to do with the interactive page design?

##### Code snippets/Screenshots

Here's when Chrome in full screen mode
![full](https://cloud.githubusercontent.com/assets/3411149/21624826/8de6d598-d1d6-11e6-9bd8-d46e0a95eb2c.png)
Here's what it looks when it's in partial screen mode
![partial1](https://cloud.githubusercontent.com/assets/3411149/21624883/edddc3f8-d1d6-11e6-9c60-2d521f3f1a78.png)

**Comment by arvindsv** [comment] 2017-01-03 22:57
I believe this is a duplicate of https://github.com/gocd/gocd/issues/2992. But, @naveenbhaskar and @maheshp know best.

**Comment by ringxw** [comment] 2017-01-04 02:16
Looks like a duplicate, sorry I didn't search the issues list thoroughly.  Will keep an eye on 17.1 for a fix.

**Comment by maheshp** [comment] 2017-01-05 05:49
@ringxw thanks for bringing this up though. This issue has been fixed as part of the PR https://github.com/gocd/gocd/pull/3025 and changes should be available as part of 17.1.

With this fix, on larger screen the pipelines page would use the entire width. 

Since its a duplicate, closing this issue.

**Closed by maheshp** 2017-01-05 05:49 UTC
Labels: dashboard, ui / ux
