### ISSUE TITLE
Adding notes to a pipeline?

### ISSUE THREAD

**Issue by gocd-catalyst** [gocd/gocd#444] opened 2014-08-19 07:17 UTC
Is it possible to add a note  to a pipeline? Would be a handy feature.

**Comment by srinivasupadhya** [comment] 2015-07-02 05:01
duplicate of #707?

**Comment by arvindsv** [comment] 2016-06-04 12:22
No response. Closing. As a duplicate of #707.

**Closed by arvindsv** 2016-06-04 12:22 UTC
