### ISSUE TITLE
Add git material fails, with color options in the .gitconfig file.

### ISSUE THREAD

**Issue by oblodgett** [gocd/gocd#326] opened 2014-07-11 18:23 UTC
When adding a git material the following message comes out in the log, on manual trigger of pipeline:

2014-07-11 14:19:54,026  WARN [268060942@qtp-768129156-14] MaterialUpdateService:146 - [Material Update] Skipping update of material GitMaterial{url=git@github.com:oblodgett/GoProjectExample.git, branch='master', submoduleFolder='null'} which has been in-progress since Fri Jul 11 14:19:53 EDT 2014
2014-07-11 14:19:54,039  INFO [268060942@qtp-768129156-14] PipelineScheduler:144 - [Pipeline Schedule] [Processed] Manual trigger of pipeline 'GoProjectToProduction' processed with result 'com.thoughtworks.go.serverhealth.ServerHealthState@653d20e2[healthStateLevel=OK,type=<HealthStateType DATABASE_DISK_FULL LogScope[GLOBAL, scope=GLOBAL]>,message=,description=,expiryTime=<null>,timestamp=Fri Jul 11 14:19:54 EDT 2014]'
2014-07-11 14:19:54,843 ERROR [68@MessageListener for MaterialUpdateStatusNotifier] BuildCauseProducerService:313 - not scheduling pipeline GoProjectToProduction after manual-trigger because update of material failed with reason description cannot be null

It doesn't matter if I use the http url:
https://github.com/oblodgett/GoProjectExample.git
or the git url:
git@github.com:oblodgett/GoProjectExample.git
However when I switch to the subversion url:
https://github.com/oblodgett/GoProjectExample
everything seems to work fine.

Fresh install of 14.2.

Olin

**Comment by j133y** [comment] 2015-01-21 00:26
I had the same problem here, moving to ```ui=auto``` worked! Thanks

**Comment by webthusiast** [comment] 2015-10-01 12:20
I had the same problem with

    [log]
        decorate=true

in my `.gitconfig`. Looks like [this](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/materials/git/GitModificationParser.java#L35) is a bit too strict a pattern for a commit message.

**Comment by worstadmin** [comment] 2016-03-17 19:39
Bump'ing. I hit this issue as well

**Comment by ibnc** [comment] 2019-03-21 21:02
I'm working on fixing the issues caused by git-log decoration

**Comment by ibnc** [comment] 2019-03-25 23:29
I fix for this issue has been merged, and will be released in 19.3.0

**Closed** 2019-03-25 23:29 UTC
