### ISSUE TITLE
Pipeline returns exit value 0 in case of an error

### ISSUE THREAD

**Issue by v1v** [gocd/gocd#335] opened 2014-07-18 11:28 UTC
For some how Go doesn't trap the errorlevel return by Go agent if the build fails:

Server configuration:
  * Go Server Version:	14.1.0(18882-d0272e1d227b5e)
  * JVM version:	1.7.0_51
  * OS Information:	Linux 2.6.32-279.14.1.el6.x86_64
  * Usable space in artifacts repository:	71368 Mb
  * Database schema version:	1401001

Agent configuration:
   * OS Windows XP
   * "Install_Dir"="d:\go"
   * "Version"="14.1.0-18882"
   * "Ver"="141018882"
   * JVM version:	1.6.0_51

Stage configuration
```xml
 <stage name="build">
        <jobs>
          <job name="build">
            <tasks>
              <exec command="./gradlew" args="clean build uploadArchives --stacktrace" workingdir="#{BRANCH.VERSION}">
                <runif status="passed" />
              </exec>
            </tasks>
            <resources>
              <resource>windows</resource>
            </resources>
          </job>
        </jobs>
      </stage>
```

Console error
```
Note: D:\go\pipelines\ContainerLibrary-main\main\src\test\java\com\acme\xlang\container\ItemTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\go\pipelines\ContainerLibrary-main\main\src\test\java\com\acme\xlang\container\impl\ChannelImplTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
1 warning
:compileTestJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --info or --debug option to get more log output.

BUILD FAILED
Total time: 11.062 secs

[go] Start to create properties ContainerLibrary-main/294071/build/3/build on ci-xp-021 D:\go] at Fri Jul 18 11:40:29 BST 2014
[go] Start to upload ContainerLibrary-main/294071/build/3/build on ci-xp-021 D:\go] at Fri Jul 18 11:40:29 BST 2014
[go] Job completed ContainerLibrary-main/294071/build/3/build on ci-xp-021 D:\go] at Fri Jul 18 11:40:29 BST 2014
```

But it works fine if I run same command remotely (it returns 1)
```
Note: Recompile with -Xlint:unchecked for details.
2 errors
1 warning
:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
Total time: 33.047 secs

D:\go\pipelines\ContainerLibrary-main\main>echo %ERRORLEVEL%
1
```

**Comment by arvindsv** [comment] 2016-06-04 11:49
Closing with an "Unable to reproduce" for now. Re-open if it's still happening.

**Closed by arvindsv** 2016-06-04 11:49 UTC
