### ISSUE TITLE
pipelines page is not accessible from iPhone

### ISSUE THREAD

**Issue by mvasilenko** [gocd/gocd#5172] opened 2018-09-17 09:19 UTC
##### Issue Type

- Bug Report

##### Summary

GoCD 18.5.0 pipelines page is not accessible from iPhone

##### Environment

```plain
    "Version": "18.5.0 (6679-a54c3fd44ef9ccbab1b0d856a8d735929eab97f7)"
```

###### Basic environment details

* Go Version: `18.5.0 (6679-a54c3fd44ef9ccbab1b0d856a8d735929eab97f7)`
* JAVA Version: `1.8.0_181`
* OS: `Linux 4.13.0-45-generic`
* Browser vendor and version (if relevant): `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/67.0.3396.87 Mobile/14G60 Safari/602.1`

##### Steps to Reproduce

1.  Open GoCD pipelines page, https://gocd.server/go/pipelines#!/

##### Expected Results

Pipelines list

##### Actual Results

Spinner rotating in infinite loop

##### Code snippets/Screenshots

https://prnt.sc/kvaome

##### Any other info

I've tried chrome and safari on iphone, with the same result, please clarify, can I view pipelines page from mobile, or it's not supported, thank you

**Comment by arvindsv** [comment] 2018-09-17 12:32
@naveenbhaskar would be the best person to answer this. As far as I know, mobile browsers are not supported.

You _might_ be interested in this iPhone app: [CI Remote](https://itunes.apple.com/US/app/id1031029921?mt=8), written by @timoa.

**Comment by timoa** [comment] 2018-09-18 06:04
Hi @naveenbhaskar,

For now, CI Remote allows to access (read-only):

- Pipelines list
- Pipeline history
- Pipeline stages
- Pipeline jobs
- Pipeline job logs
- Agents list
- Agent details and history
- Go.CD server details

I'm working to trigger pipelines and more feature but you are right, we need the support for the mobile browsers instead of a mobile client only (CI Remote use the Go.CD API).

For example, I can't open any page under a WebView because it doesn't support mobile browser :(

@arvindsv: Do we have anything under the backlog for mobile browser support?

**Comment by naveenbhaskar** [comment] 2018-09-19 11:43
Gocd is not responsive . but if you open Gocd  on mobile in desktop mode , it should work. Currently making Gocd support for mobile is not on priority, but will have a look on that in the near future.

**Comment by arvindsv** [comment] 2018-09-19 11:52
> Do we have anything under the backlog for mobile browser support?

@timoa: Nothing at this point. There are a bunch of changes around the pages, which are planned. A lot of it involves moving away from server-side rendering and into more performant pages. I think it's useful to consider responsive pages, but we're not actively looking at it.

A big reason for that is the effort of testing it (automated, on mobile and/or simulators), to make sure it continues to work. We already test on multiple browsers and OSes and this will add to that matrix and goes beyond our current capacity to support it.

**Comment by arvindsv** [comment] 2018-09-19 11:54
@mvasilenko Can you try on 18.10.0? We tried it and it seems to "work". Definition of work = No spinner. :) It's ugly but we weren't able to reproduce the original issue on 18.10.0.

In case you don't have it, you can see it on https://build.gocd.org (click on "Guest").

I'll close this issue, for now. However, I'm happy to reopen it if it's reproducible on 18.10. Thank you so much!

**Closed by arvindsv** 2018-09-19 11:54 UTC

**Comment by mvasilenko** [comment] 2018-09-21 04:12
@arvindsv, thank you for suggestion

I've tried on 18.10.0 and latest Chrome on IPhone, got partial success, I can access [environments](http://prntscr.com/kww783), but still no luck with [pipelines](http://prntscr.com/kww6lp) or [agents](http://prntscr.com/kww7oa)

Also, I can access all those pages from Android phone.

**Comment by arvindsv** [comment] 2018-09-21 14:14
@mvasilenko Weird. I see this (see below) in Safari and Chrome, in portrait and landscape. Do you have any content blockers? Not that they should be blocking anything on that page, since there's nothing external - but still. I'm in iOS 12.

### Safari Landscape:
<img src="https://user-images.githubusercontent.com/172235/45886217-9782d000-bd86-11e8-9fd6-d0a0b78d9217.PNG" width="75%" />

### Safari Portrait:
<img src="https://user-images.githubusercontent.com/172235/45886220-981b6680-bd86-11e8-8e7e-115245d0e74b.PNG"  width="70%"/>

### Chrome Landscape:
<img src="https://user-images.githubusercontent.com/172235/45886219-981b6680-bd86-11e8-9c05-cefa5f61a19c.PNG" width="75%" />

### Chrome Portrait:
<img src="https://user-images.githubusercontent.com/172235/45886218-9782d000-bd86-11e8-8590-90e8953830da.PNG" width="75%" />
