### ISSUE TITLE
"pause until" or "requires revision" command for pipelines

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#2132] opened 2016-04-21 19:18 UTC
Feature request:

It would be really useful to be able to tell GoCD that "this pipeline requires upstream repo/revision to be in the materials somewhere, and don't build until you see it"

Use case:

We have a long value stream testing master (~50 pipelines), and we've got 5 testing streams setup using branches + duplicated pipelines (yay templates). When one of these testing streams is finished all the way to the end, then someone triggers something that simultaneously merges all of the pull requests associated with repos on the stream. Super useful.

What happens is that after this mass merge, the things at the end of the pipeline tend to break, because they don't have the required changes from the beginning. It's a bit annoying because you have to look at it and say "oh right, it hasn't gotten the upstream changes yet".

The most obvious solution is to use the GoCD API to tell GoCD "this pipeline git material revision X depends on some upstream revision Y", and to refuse to build until it sees that it's upstream contains revision Y.

I'm open to other solutions as well, but it seems like a generally useful capability. Maybe it could be implemented as a plugin (not sure how capable plugins are).

**Comment by arvindsv** [comment] 2016-04-21 23:28
I don't quite get this. I'd like to understand more. Usually dependencies should be setup between pipelines to enable them to not run till something they're waiting on is ready. Maybe an image will help. I got lost in the second paragraph.

Without fully understanding this, I'll hazard a guess that an SCM material will suit this purpose. It'll just need [to return](https://developer.go.cd/current/writing_go_plugins/scm_material/version_1_0/latest_revisions_since.html) "no modification found yet", till it is ready.

**Comment by virtuald** [comment] 2016-04-22 18:39
Does GoCD do that automatically? I think it builds when pushed, because it perceives that there was a prior good build. Imagine pipeline A, B, C, D:

```
A -> B -> C -> D
```

If I push simultaneously to A and D, they will both start building because there was some build in the past of A, so GoCD uses that. However, D's build will fail, because I made some change in A that it depends on. It would be nice to make D not build until A propagates through.

Does that make more sense?

**Comment by arvindsv** [comment] 2016-04-22 20:24
Since you said "push to A and D", do you mean that it is more like this?

```
Git 1 -> Pipeline A -> Pipeline B -> Pipeline C -> Pipeline D
                                                       ^
                                                       |
                                                    Git 2
```

**Comment by virtuald** [comment] 2016-04-22 20:25
Yes, that is more precise. :)

**Comment by arvindsv** [comment] 2016-04-22 20:35
Ok. In that case, it'll do what you said. However, this is why [fan-in](https://www.go.cd/getting-started/part-3/#concept_fan_out_fan_in) exists. Take a look at the example below the concept in the page I linked to. You should setup the pipeline this way:

```
Git 1 -> Pipeline A -> Pipeline B -> Pipeline C -> Pipeline D
             ^                                         ^
             |                                         |
Git 2  -------------------------------------------------
```

So, the setup is that pipeline D depends on Pipeline C as well as Git 2. Pipeline A depends on Git 2 as well as Git 1.

Now, when a commit is made on either Git 1 or Git 2, Pipeline D won't trigger. they'll only trigger in order. And, when the time comes for Pipeline D to trigger, it'll pick the version of Git 2 that Pipeline A built from. This is the consistency guarantee that fan-in gives you. Of course, this means that Pipeline D will wait for Pipeline A, B and C to finish and it'll never trigger out of order.

**Comment by arvindsv** [comment] 2016-04-22 20:39
Of course, this means that a commit in Git 2 will cause A, B and C to run. That's needed to ensure that revisions of A and D are in sync and it waits. If you really need them to be modeled the way you said, then you'll need to write an SCM plugin, because the logic you mentioned "wait till A has built" is extremely timing dependent. What if they come a few seconds apart, for instance? What if they come together, but Git 2 is polled first? Many caveats.

**Comment by virtuald** [comment] 2016-04-22 20:45
Hm, that seems inverted from what I would expect, why isn't your drawing like this?

```
           Pipeline A -> Pipeline B -> Pipeline C -> Pipeline D
             ^                                         ^  ^
             |                                         |  |
Git 1  -------------------------------------------------  |
                                                        Git 2
```

After all, 1 isn't required to build A. A is required to build D.

**Comment by arvindsv** [comment] 2016-04-22 20:51
Sure. It depends on what you want. In this case, what will happen is that a commit to "Git 1" will make Pipeline D wait for Pipeline A to complete (and then B and C). A commit to Git 2 will start Pipeline D immediately, and it picks up the latest successful revision of pipeline C (and by extension, pipeline A). If that's how you want to model it, that's fine.

But, a simultaneous commit to both Git 1 and Git 2 will not make Pipeline D wait, in this case. If you make Pipeline A depend on Git 2 as well, that's a way of telling GoCD that there's a dependency and you need A to finish before the corresponding run of D starts.

So, in that sense, it's not different from your first diagram. In this case, you're just saying that you want the code of Git 1 checked out when a job in Pipeline D starts.

**Comment by arvindsv** [comment] 2016-04-22 20:55
To add a bit to that: a commit to Git 2 is an indication to Pipeline D that it can start independently (in your example). It's in no way tied to Pipeline A, and so for all practical purposes, it's independent of Git 1 and Pipeline A. So, it kicks off Pipeline D. But, from what you've described, there is a (or an implicit?) dependency between Git 2 and Pipeline A that you want modeled.

**Comment by virtuald** [comment] 2016-04-22 21:02
So if I were trying to build a bunch of service packages that all use the same base platform library (assume a one to one relationship where each pipeline builds something primarily associated with a single git repo):

```
          +----- Service 1
          |
  Base -- + ---- Service 2
          |
          + ---- ...
          |
          + ---- Service N
```

To guarantee correctness via the fan-in mechanism, I would have to add the git repos for Service 1..N to Base?

That seems really convoluted, particularly as the tree of things grows. I would have to add 50 git repos to every pipeline sitting at the very beginning of my value stream.

I didn't realize fan-in addressed this problem (nor did I understand it), so I think this issue can be closed. But then I think I would rather want the ability to invoke the fan-in mechanism a different way -- eg, declare that D has a build dependency on A. Unless there is such a thing and I missed it?

**Comment by virtuald** [comment] 2016-04-22 21:07
And to note, in the original example, the reality is that D has a build dependency on C which has a dependency on B which has a dependency on A. However, the end result is still the same; when I change the thing in A then D breaks.

**Comment by arvindsv** [comment] 2016-04-22 21:14
The thing is, as I said, about your intention. In this case, if Service 1 has Git 1, and Service 2 has Git 2, etc. and Base has Git 0, then a commit to Git 0 will build Base and then trigger all the downstreams. But, a commit to Git 1 has no way of knowing that there is a corresponding revision of Git 0 it needs to "wait" for. Especially given that the word "corresponding" makes no sense here. Right?

In the earlier example, if you commit *simultaneously* to Git 1 and Git 2, then you're thinking that GoCD needs to see them both at the *same time* and then realize that these happened simultaneously and then hold off the commit for Git 2 from triggering D, so that pipeline A can trigger, and then pipeline B can trigger and then pipeline C and then when it comes to D, pick up the commit that it held off. However, given the dependency graph, there is no reason for Git 2 to wait. By the setup, you've said: "When Git 2 has a commit, D gets affected". The problem is that there's nothing showing such a dependency between Git 1 and Git 2 in the config.

Also, if you wait, and there are continuous commits to Git 1, you'll never build Git 2 and that violates building as soon as you can. However, you can simulate this behavior using a plugin, but it would seem like wrong modeling to me.

As you suggested, I'll close this. Thanks!

**Closed by arvindsv** 2016-04-22 21:14 UTC

**Comment by arvindsv** [comment] 2016-04-22 21:16
In your base to service example, I'd expect that a commit to the git repo of service 1 will fail, if it is incompatible with the base. A later commit to base to fix the issue will fix the service pipeline. That's what you'd want to happen. Just in case you commit to service 1's repo and forget to commit to base, you'd want GoCD to tell you.

**Comment by virtuald** [comment] 2016-04-22 21:23
Aha! That triggered a thought:

> The problem is that there's nothing showing such a dependency between Git 1 and Git 2 in the config.

You're precisely right! And most of the time that's ok, because 'normally' while there's a build dependency between D and A, in practice as long as breaking changes aren't introduced in A then D will be fine regardless of which revision is built. So not using fan-in is fine.

However, because we have this explicit duplicate testing stream, when the merge happens then the external merge mechanism *does* know there is an explicit dependency between specific revisions, and could communicate that to GoCD before it actually does the merge.  Therefore, it would be convenient to communicate to GoCD this explicit dependency. It wouldn't make sense to write it into the configuration file -- it's only a temporary dependency.

**Comment by arvindsv** [comment] 2016-04-22 21:30
Yes, I understand about the temporary dependency. And, as long as you can convey that to GoCD (possibly through a special convention in the commit message, watched by a plugin?) then you can do this.

I think the closest discussion to this I can think of is [here](https://groups.google.com/d/topic/go-cd/IfbaSZndeik/discussion). I have thought about a "Microservice SCM plugin" for this, which depends on specially crafted message conventions. If you write it, that would be cool! :)
