### ISSUE TITLE
Make it easier to get to the pipeline settings.

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2606] opened 2016-08-27 04:26 UTC
##### Issue Type

- Feature enhancement

##### Summary
At the moment, the only way to get to a pipeline's settings is via the dashboard, or via the admin window.

It'd be useful to have the same settings "gear" icon + link in the pipeline detail view and the Value Stream Map Pipeline windows as well.

**Comment by varshavaradarajan** [comment] 2016-10-26 08:52
Closing this as a duplicate of https://github.com/gocd/gocd/issues/2783

**Closed by varshavaradarajan** 2016-10-26 08:52 UTC
