### ISSUE TITLE
"java.lang.NullPointerException: null"

### ISSUE THREAD

**Issue by lukyanov** [gocd/gocd#5531] opened 2018-12-07 10:33 UTC
##### Issue Type
- Bug Report

##### Summary

Just faced the issue. Constantly reproducable on the current pipeline run. No apparent reasons.
The pipline consists of three stages with one job each. The error appears on the last stage.

```
2018-12-07 10:26:36,169 INFO  [qtp391618063-30] ScheduleService:221 - [Stage Schedule] Scheduling stage terminate for pipeline aproxy-launch-prod-us-vir1
2018-12-07 10:26:42,516 INFO  [97@MessageListener for WorkFinder] Stage:225 - Stage is being completed by transition id: 11688
2018-12-07 10:26:42,522 ERROR [97@MessageListener for WorkFinder] JobInstanceService:149 - error notifying listener for job JobInstance{stageId=1954, name='terminate', state=Completed, result=Failed, agentUuid='null', stateTransitions=[com.thoughtworks.go.domain.JobStateTransition@5f20f4ef[currentState=Scheduled,stateChangeTime=Fri Dec 07 10:26:36 UTC 2018,jobId=1964,stageId=1954,id=11686], com.thoughtworks.go.domain.JobStateTransition@1b777ae8[currentState=Completing,stateChangeTime=Fri Dec 07 10:26:42 UTC 2018,jobId=1964,stageId=1954,id=11687], com.thoughtworks.go.domain.JobStateTransition@3d6b0bb9[currentState=Completed,stateChangeTime=Fri Dec 07 10:26:42 UTC 2018,jobId=1964,stageId=1954,id=11688]], scheduledDate=Fri Dec 07 10:26:36 UTC 2018, timeProvider=com.thoughtworks.go.util.TimeProvider@193044e3, ignored=false, identifier=JobIdentifier[aproxy-launch-prod-us-vir1, 1, 1, terminate, 13, terminate, 1964], plan=null, runOnAllAgents=false, runMultipleInstance=false}
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.thoughtworks.go.server.domain.AgentInstances.loadAgentInstance(AgentInstances.java:78)
	at com.thoughtworks.go.server.domain.AgentInstances.findAgent(AgentInstances.java:74)
	at com.thoughtworks.go.server.service.AgentService.findAgent(AgentService.java:329)
	at com.thoughtworks.go.server.service.ElasticAgentPluginService.jobStatusChanged(ElasticAgentPluginService.java:221)
	at com.thoughtworks.go.server.service.JobInstanceService$2.afterCommit(JobInstanceService.java:147)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:133)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:121)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:962)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:807)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.StageService.changeJob(StageService.java:465)
	at com.thoughtworks.go.server.service.StageService.failJob(StageService.java:461)
	at com.thoughtworks.go.server.service.ScheduleService.failJob(ScheduleService.java:727)
	at com.thoughtworks.go.server.service.ScheduledPipelineLoader.pipelineWithPasswordAwareBuildCauseByBuildId(ScheduledPipelineLoader.java:79)
	at com.thoughtworks.go.server.service.BuildAssignmentService.lambda$createWork$3(BuildAssignmentService.java:308)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:61)
	at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:302)
	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:168)
	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:147)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:60)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:33)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
2018-12-07 10:26:42,545 INFO  [97@MessageListener for WorkFinder] BuildAssignmentService:172 - [Agent Assignment] Assigned job [JobIdentifier[aproxy-launch-prod-us-vir1, 1, 1, terminate, 13, terminate, 1964]] to agent [Agent [us-vir1-build0-1, 172.16.11.178, 1112c1f2-7e15-4318-93d1-70be1199dbb5]]
```

**Comment by kritika-singh3** [comment] 2019-06-14 05:24
Hello @lukyanov, can you please share the environment details i.e. the Go Version, Java version and OS you found the bug on. This will help us reproduce the error.

Note: Details of the environment GoCD is running in can be fetched from the GoCD support api - `http://<go-server-host>/go/api/support`

**Comment by japzio** [comment] 2019-07-29 08:08
Encountered this issue when a couple of pipelines are being triggered at the same time that subscribe a common upstream pipeline with only one agent running.

go-server
```
2019-07-25 03:04:56,850 ERROR [101@MessageListener for WorkFinder] JMSMessageListenerAdapter:90 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@633cad4d
java.lang.NullPointerException: null
2019-07-25 03:05:06,855 ERROR [101@MessageListener for WorkFinder] JMSMessageListenerAdapter:90 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@633cad4d
java.lang.NullPointerException: null
```

go-agent
```
2019-07-25 04:42:39,982 ERROR [scheduler-1] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2019-07-25 05:12:51,057 ERROR [scheduler-1] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
```

Environment on VM (non docker):
```
GoCD : 19.5
OS      : Linux 4.4.0-1087-aws amd64
Java   : Oracle JDK1.8
```

**Comment by kritika-singh3** [comment] 2019-09-03 06:07
@japzio 
> Encountered this issue when a couple of pipelines are being triggered at the same time that subscribe a common upstream pipeline with only one agent running.

I tried the following GoCD setup: one pipeline with 7 downstream pipelines and a single agent. Using the schedule pipeline API, I triggered all the downstream pipelines.
But I didn't receive any error log as mentioned in the comment.
Can you send the complete stacktrace of the exception. It would help in debugging as I could not recreate the exception. 
My GoCD server properties:
```
Go Server Version: 19.5.0 (9272-496bf8b95e603c1f3980ae59042bc559eecbbbc0)
OS Name: Mac OS X,
OS Version: 10.13.6,
System Architecture: x86_64
```

**Comment by japzio** [comment] 2019-09-03 07:05
Ok i'll try to reproduce this again on linux and macos

**Comment by japzio** [comment] 2020-01-06 07:19
looks like this is no longer happening on my end.

**Comment by kritika-singh3** [comment] 2020-01-06 08:28
@japzio Thanks for confirming. I will close this issue. Please create another in case you get the error again.

**Closed by kritika-singh3** 2020-01-06 08:28 UTC
