### ISSUE TITLE
Inconsistent Elastic profiles UI

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#6196] opened 2019-04-25 02:23 UTC
##### Issue Type

- Bug Report

##### Summary

<img width="1418" alt="Screen Shot 2019-04-24 at 7 21 11 PM" src="https://user-images.githubusercontent.com/4715748/56705591-59f07780-66c6-11e9-98a4-6673058be712.png">

###### Basic environment details

* Go Version: `19.3.0 (8951-ce45c93dc4b648b51054bc348c3f9232169f5429).`

**Comment by GaneshSPatil** [comment] 2019-04-25 03:41
Duplicate of the first point mentioned in the issue https://github.com/gocd/gocd/issues/6154

Also, fixed as part of https://github.com/gocd/gocd/pull/6189, where we've removed the plugin ID from the header

**Closed** 2019-04-25 03:41 UTC
