### ISSUE TITLE
 Agent reconnects but forgets all properties from autoregister.properties 

### ISSUE THREAD

**Issue by chellgren** [gocd/gocd#3147] opened 2017-02-01 11:49 UTC
##### Issue Type

- Bug Report
- Feature proposal?

##### Environment

Amazon
GoCD Server and Agents as EC2 instances running on the Amazon Linux AMI.

Our Agents connect through a Classic ELB.
SSL is terminated by the GoCD Server, NOT the ELB.
Agents connect successfully and can take jobs and everything.
-->

###### Basic environment details

* Go Version: `17.1.0`
* JAVA Version: `1.8.0_111`
* OS: `Amazon Linux AMI, Linux 4.4.35-33.55.amzn1.x86_64`

##### Steps to Reproduce

1. Startup Server 
2. Startup Agents
2. Take down server (terminate it, not only shutdown or restart)
3. ELB starts replying HTTP 502 (because the server is gone behind it)
4. Agents loose connection to the Server, start trying to reconnect.
5. Create and startup Server again and after a while the ELB starts replying OK.

Why do we terminate the server? To do software upgrades, changes to config, seccurity patches, AMI-updates etc). All these updates are done as updates to the scripts used to setup the server (Infrastructure as code).
Reason for terminating GoCD Server instead of restarting of doing updates to the existing server is that we want to avoid having a snowflake-server. And we like to remove it during night to reduce cost.

##### Expected Results
Agents reconnect and show up again as active with the Name, Resources it read from autoregister.properties when it started up initially before the Server went down. The Agent process has not stopped running during the time the Server is down, it keeps trying to reconnect.

##### Actual Results
Agents now show up in GoCD Server as Pending, all settings from the autoregister.properties such as key, name and resources are lost. Shows IP as name, no resources specified. 

It seems it either reads the, by now, commented out autoregister.properties file when it finally gets a reply from the server? Or it has forgotten all the values it initially read before it comments them out as part of the security measures?

**Comment by arvindsv** [comment] 2017-02-01 12:42
From what I can see, you're terminating the server, which is fine, but you're losing state. The agent auto register properties are supposed to be removed upon first connection, because the auto register key, if found by someone, can be used to connect other agents to the server, without any notifications or approvals (this is a feature, not a bug).

However, the agent and server, upon first connection, exchange certificates so that they can connect to each other from them on, without the key.

In this case, it looks to me like you lose the `/etc/go/agentkeystore` file when you terminate the server and bring it back. Is it possible for you to save all of these locations (at the least) and bring them back upon a restore?

```
/etc/go/
/var/lib/go-server/db/config.git/
/var/lib/go-server/db/h2db/
```

You'll lose artifacts, unless you write them out to S3 or something. But you probably know that already.

On the agent side, `/var/lib/go-agent/config/` is important and has state that allows it to connect to the server.

**Comment by chellgren** [comment] 2017-02-01 12:53
Ah, I see, so the `/etc/go/agentkeystore` is found on the server? And that's where it keeps the state of the connected agents certificates?

We run a cronjob-script each night on the Server that call's the GoCD API and trigger a backup ([go/api/backups](url)) and then we move the resulting backup files to S3. When the Server is re-created it downloads the backup from S3 and restores state. I think the path's you mention are included in that backup?

I will change so the backup-script runs more frequently (once a minute or something) and then try again the scenarios.

**Comment by arvindsv** [comment] 2017-02-01 13:16
That's right. They are. You need to restore them to the right places:

```
config-dir.zip => /etc/go/
config-repo.zip => /var/lib/go-server/db/config.git/
db.zip => /var/lib/go-server/db/h2db/
```

Do a diff before and after. Make sure you've restored the files at the right place, with the right ownership and permission. I'll close this issue for now. Can be reopened, if needed.

**Closed by arvindsv** 2017-02-01 13:16 UTC

**Comment by chellgren** [comment] 2017-02-01 13:49
Works now when restoring with an updated backup!

**Comment by arvindsv** [comment] 2017-02-01 13:56
Good to know! If you decide to write a blog post about your setup or about how you use GoCD, please let us know. I assume you use some scripts. If you're inclined to share them, maybe others will be interested as well.

**Comment by chellgren** [comment] 2017-02-01 14:06
I am considering open sourcing the scripts we use. They're Cloud Formation scripts currently so anyone interested in GoCD on AWS could use them. If I do I'll definitely write a blog post for the GoCD-blog!

**Comment by arvindsv** [comment] 2017-02-01 14:10
Sounds good! Thanks!
