### ISSUE TITLE
Upload Artefact issue

### ISSUE THREAD

**Issue by mat44444** [gocd/gocd#3593] opened 2017-06-16 15:53 UTC
##### Issue Type
Bug Report

##### Summary

When we upload a WebSite on artefact, there issue in uploading artefact:

2017-06-16 11:33:59,568 ERROR [qtp1717159510-18] ArtifactsService:107 - Failed to save the file to: [/opt/go_artifacts/pipelines/SAAV_Build/7/CreateArtifact/1/BUILD/WEB]
com.thoughtworks.go.util.IllegalPathException: File MENU/Documentation/SAAV/Clip/AccÃ¨s S.A.A.V..swf is outside extraction target directory

##### Environment

Serveur on CentOs, Agent on windows

###### Basic environment details

There appear to have issue when upload files in artefact who containt multiple dot (.) caractere in the filename

##### Steps to Reproduce

1. Make a git repo who containt this filename MENU\Documentation\SAAV\Clip\Accès S.A.A.V..swf
2. try to upload the fil in artefact
3. We got an erro 500 on the agent side
2017-06-16 11:33:53,191 [loopThread] INFO  thoughtworks.go.util.HttpService:136 - Got back 500 from server
2017-06-16 11:33:53,192 [loopThread] ERROR thoughtworks.go.publishers.GoArtifactsManipulator:113 - 
4. We got this message on serveur side
2017-06-16 11:33:59,568 ERROR [qtp1717159510-18] ArtifactsService:107 - Failed to save the file to: [/opt/go_artifacts/pipelines/SAAV_Build/7/CreateArtifact/1/BUILD/WEB]
com.thoughtworks.go.util.IllegalPathException: File MENU/Documentation/SAAV/Clip/AccÃ¨s S.A.A.V..swf is outside extraction target directory

**Comment by arvindsv** [comment] 2017-06-19 15:44
Closing this as a duplicate of https://github.com/gocd/gocd/issues/2894. I guess the check should be something like `^../` or `/../` (and handle backslashes, etc). Might need some thought and seems like a small enough fix for someone to contribute a fix, even without too much context about the rest of the codebase.

**Closed by arvindsv** 2017-06-19 15:44 UTC
