### ISSUE TITLE
Cannot upgrade Helm chart from 1.19.3 to latest.

### ISSUE THREAD

**Issue by rayburgemeestre** [gocd/gocd#9227] opened 2021-04-21 13:21 UTC
##### Issue Type

- Bug Report

##### Summary

My initial deployment was done as follows:

`helm install gocd-app gocd/gocd --version 1.19.3 --namespace gocd --set server.persistence.storageClass=gocd-app-server-data --set server.persistence.size=200Gi`

Upgrading it with broke my CI:

`helm upgrade gocd-app gocd/gocd -n gocd`

I was able to rollback:

`helm rollback gocd-app -n gocd`

##### Environment

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps to Reproduce

I managed to narrow the problem down, by updating to each version provided by: `helm list -n gocd`

```
[...]
helm upgrade gocd-app gocd/gocd -n gocd --version 1.22.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.23.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.24.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.25.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.26.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.27.0  # This is the last one that doesn't fail.
helm upgrade gocd-app gocd/gocd -n gocd --version 1.28.0  # This upgrade fails
```

This one succeeds:

```
Press ENTER or type command to continue
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART      	APP VERSION
gocd-app	gocd     	14      	2021-04-21 13:20:18.88871596 +0000 UTC	deployed	gocd-1.27.0	20.4.0     
```

This one fails:

```
root@deskmini:/mnt2/NAS/kube/gocd# helm list -n gocd
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION
gocd-app	gocd     	13      	2021-04-21 12:35:43.982578584 +0000 UTC	deployed	gocd-1.28.0	20.5.0   
```

##### Expected Results

Upgrade doesn't crash gocd server

##### Actual Results

```
root@deskmini:/mnt2/NAS/kube/gocd# kubectl get pod -n gocd
NAME                               READY   STATUS             RESTARTS   AGE
gocd-app-server-65f5b6cb7f-dbwww   0/1     CrashLoopBackOff   9          42m
```
See the attached log for the full output.

##### Log snippets

See attached file.

##### Any other info
[gocd.log](https://github.com/gocd/gocd/files/6351129/gocd.log)

**Comment by kritika-singh3** [comment] 2021-04-22 03:09
Duplicate of #9228

**Closed by kritika-singh3** 2021-04-22 03:09 UTC
