### ISSUE TITLE
as invalid cookie; nested exception is com.thoughtworks.go.server.service.AgentWithDuplicateUUIDException

### ISSUE THREAD

**Issue by BLOPESLO** [gocd/gocd#7351] opened 2019-12-02 15:00 UTC
##### Issue Type
bug

##### Summary
Agent [Agent [WVMESQ6EC1111, 180.31.24.113, 87a8501d-50bc-4a02-8d85-4058be6aae80, 6f9ea1b6-e5c4-4be6-8c16-fe55ab61fc51]] has invalid cookie; nested exception is com.thoughtworks.go.server.service.AgentWithDuplicateUUIDException: Agent [Agent [WVMESQ6EC5723, 180.31.11.000, 87a8501d-50bc-4a02-8d85-4058be6aae80, 6f9ea1b6-e5c4-4be6-8c16-fe55ab61fc51]] has invalid cookie!--- Provide a brief summary of the issue -->

In the pipeline execution did not get the correct resources. 
The pipeline ran through all existing resources.

* Go Version: GoCD Version: 19.10.0 (10357-44d61cc733a94287979f1fb99583d69139f386e4).
* JAVA Version: 12
* OS: windows 10
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

**Comment by arvindsv** [comment] 2019-12-03 16:15
This usually happens when an agent has been cloned or copied, leading to two agents having the same UUID. I'm going to close this issue for now, since this usually happens due to problems with the setup.

Happy to reopen if that's not the case and we have more information to reproduce this.

**Closed by arvindsv** 2019-12-03 16:15 UTC

**Comment by BLOPESLO** [comment] 2019-12-04 11:10
Hi, the guid file are diferent in every agents.
This problem start when we upgraded the gocd version.

**Comment by arvindsv** [comment] 2019-12-04 11:22
Ok. Can you then bring down the agent, remove the conifg/ directory and then bring it back up again to see if it helps?
