### ISSUE TITLE
Git repo not-polled triggering pipelines

### ISSUE THREAD

**Issue by MHP47** [gocd/gocd#3242] opened 2017-03-09 03:40 UTC
##### Issue Type

- Bug Report

##### Summary

GIT repository material selected to not poll for new changes is still triggering pipeline execution.

I have a pipeline group, which has 4 pipelines in it. All pipelines are 90% similar, the only major difference between them being the git repo's and the environment variable values (names are the same). These 3 each have 3 materials, all git repo's. They each have 2 unique repo's, which are set to poll for changes, and 1 which is shared across all 4 but is set to not poll for changes. The 4th pipeline also has a pipeline material dependency, which should prevent the pipeline from triggering from the repo change itself. It does work correctly mostly, as far as I can tell.

Changes pushed to the shared repo causes all 4 pipelines to trigger execution. 

This seems to be intermittent, as while trying to document this, the pipelines did not trigger. This is not a once off however, as I have noticed it on multiple occasions.

One of the pipelines, when I click the drop down "Changes" shows the commit to the non-polled repo in yellow (assume this indicates what triggered the pipeline?).

##### Environment

```
"Go Server Information": {
    "Version": "16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)"
  }
```

###### Basic environment details

Server Info
Go Server Version:	16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)
JVM version:	1.8.0_77
OS Information:	Linux 3.8.13-98.7.1.el7uek.x86_64

##### Steps to Reproduce

Have tried to duplicate this is a small scale test, but can't determine what exactly is causing it to happen. Redacted definition of one of the pipelines from cruise-config.xml below.

Unsure where the main log file for go-server is on Linux, but can provide excerpt from that if location provided and when this issue happens again.

```
<pipeline name="PIPELINE_1">
  <environmentvariables>
    <variable name="VAR1">
      <value>ABC</value>
    </variable>
    <variable name="VAR2">
      <value>DEF</value>
    </variable>
    <variable name="VAR3">
      <value>GHI</value>
    </variable>
    <variable name="VAR4">
      <value>JKL</value>
    </variable>
    <variable name="VAR5">
      <value>MNO</value>
    </variable>
  </environmentvariables>
  <materials>
    <git url="ssh://git@SERVER_NAME/nag/REPO1.git" dest="REPO1" />
    <git url="ssh://git@SERVER_NAME/nag/REPO2.git" dest="REPO2" />
    <git url="ssh://git@SERVER_NAME/nag/REPO3.git" dest="REPO3" autoUpdate="false" />
  </materials>
  <stage name="backup">
    <jobs>
      <job name="backup123">
        <tasks>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
        </tasks>
        <resources>
          <resource>RESOURCE_1</resource>
        </resources>
      </job>
      <job name="backup456">
        <tasks>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
        </tasks>
        <resources>
          <resource>RESOURCE_1</resource>
        </resources>
      </job>
    </jobs>
  </stage>
  <stage name="deploy">
    <jobs>
      <job name="deploy123">
        <tasks>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
          </exec>
          <exec command="/bin/bash" workingdir="REPO1">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash" workingdir="REPO1">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
        </tasks>
        <resources>
          <resource>RESOURCE_1</resource>
        </resources>
      </job>
      <job name="deploy456">
        <tasks>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
          </exec>
          <exec command="/bin/bash" workingdir="REPO2">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash" workingdir="REPO2">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
        </tasks>
        <resources>
          <resource>RESOURCE_1</resource>
        </resources>
      </job>
    </jobs>
  </stage>
  <stage name="validate">
    <jobs>
      <job name="validate">
        <tasks>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
          </exec>
          <exec command="/bin/bash" workingdir="REPO3">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash" workingdir="REPO3">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="passed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="failed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="failed" />
          </exec>
          <exec command="/bin/bash">
            <arg>-c</arg>
            <arg>BASH CODE</arg>
            <runif status="any" />
          </exec>
        </tasks>
        <resources>
          <resource>RESOURCE_1</resource>
        </resources>
      </job>
    </jobs>
  </stage>
</pipeline>
```

##### Expected Results
Changes to repository should not trigger pipeline execution

##### Actual Results
Pipeline execution began

**Comment by arvindsv** [comment] 2017-03-09 04:02
@jyotisingh had once written about this somewhere. I'm pasting that below:

----------------------
There are three options in GoCD which come in handy while configuring your pipeline:

1. "Poll for new changes" on the material config screen : By default GoCD polls the repository for changes automatically. If this is set to `false` then GoCD will not poll the repository for changes. Instead it will check for changes only when you manually trigger a pipeline that contains this material. *If there are multiple pipelines* using this material and you manually trigger just one of them, the material update would happen and all the other pipelines would also be triggered (unless they are configured to be manual). This option is normally used to reduce load on the repository server.

2. "Blacklist" on materials config screen : This specifies files in changesets that should not trigger a pipeline automatically. Eg. If you do not want changes in a certain folder in a repo say "docs" to trigger the build, then specify the pattern for the path here eg: `docs/**/*`. Normally used when you have multiple materials configured and only for a subset of them you do not want the build to be automatically triggered.

3. Mark pipeline as manual : If a pipeline is meant to be triggered only manually, and not through any of the changes made to any of its material, then you should turn off "Automatic pipeline scheduling" on the Edit pipeline page. Alternatively, you may set the "Stage Type" of the first stage of the pipeline as "manual". Such a pipeline would now be triggered only when you perform a manual trigger of the pipeline. Normally used when you want to trigger a pipeline only manually or using a timer based trigger.

----------------------


Assuming REPO3 is shared between the 4 pipelines, can you see if triggering one of the other pipelines manually, triggers this pipeline? Because that's by design.

It looks like you turned off polling thinking that it won't trigger ever. If you turn off polling, then it'll never see a new commit, usually. So, it won't trigger. But, if it sees a new commit (because you manually triggered a pipeline with that material), it'll trigger all pipelines.

What you probably need is to enable polling, so that it sees the material, but blacklist ("filter" in material config) that material fully (`**/*`).

This is not easy to explain. This [mailing list thread](https://groups.google.com/d/msg/go-cd/1K_XXur-LIU/baY8qePJCQAJ) might also be helpful.

I really don't think this is a bug. So, I'll close it. We can reopen it if it's found to be.

**Closed by arvindsv** 2017-03-09 04:02 UTC

**Comment by MHP47** [comment] 2017-03-09 05:53
Hey @arvindsv, thanks for the quick reply, and thanks for the detailed explanation. After reading that, it seems I am using the wrong settings to achieve a goal, and I will look at using the blacklist (which explains a few things) :)
