### ISSUE TITLE
Write the console log to a temporary directory on go server

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#980] opened 2015-03-25 06:25 UTC
The go agent posts the console output to go server who saves it on the artifacts directory setup in the go configuration.

If the artifacts directory is a network drive this might be a problem (performance). Instead, write the console on the server and move it to the artifacts directory when the job completes.

**Comment by zabil** [comment] 2015-03-30 10:55
@arvindsv @jyotisingh @srinivasupadhya @mdaliejaz 

Appreciate it if you look at these bunch of changes before I send in the final pull request.
A summary of what's being done.

* Write the console.log to a temporary directory on the server under pipeline/stage/counter
* Listen to the change in the job status being completed.
* While the job is running serve the console file from the temporary folder.
* Once the job is being completed serve the log from the final artifacts folder.

The current code incorrectly notifies of job completion so had to change the order in console publisher. 
I am still struggling with figuring out how to clean up the temp directory because deleting the root folder (of a pipeline/stage) will affects jobs that run in parallel.

As of now I am thinking of a separate thread that runs low frequency and deletes empty folders. 
Is there any reason why we are missing a pipeline completed status or listener?

**Comment by arvindsv** [comment] 2015-03-30 14:56
For the others, you can see all the commits in one place [here](https://github.com/gocd/gocd/compare/master...zabil:tempdir).

Thoughts:

1. The movement of reportCompleted to be after reportCompletedAction. Can you dig into the history of the order of those two for a bit. I remember working on this with Sara a long time ago, where we decided on why the order should be what it is. It had something to do with what will happen if an agent (or n/w communication) fails after one of them happens. One of them leaves the DB in a state which needs a reschedule. One doesn't. Long time. I might be mistaken.

2. You've checked in ```server/config/cruise-config.xml```. It has a path of yours, etc. I think this should be removed.

3. I haven't closely looked at the code, but I get the idea. The problem is because you're putting each console log file into its own directory. Does it need to be? Can it be stored in a file with a GUID name? Does it matter? One problem I see with using a random GUID for the name is if the server restarts in the middle of a job, then the file will be lost (not moved). So, can we hash the pipelines/%s/stage/%s/job/%s ... and come up with a (repeatable) value we can use for the console file of the job, instead of using a directory?

4. Stage completion publishes an event. ```StageStatusListener```. That can be used. You don't need a pipeline completion listener. A pipeline completion listener is ... tricky. Would you consider a pipeline with the last stage being manual completed or not? I mean, it hasn't reached the last stage yet. But, it is "complete" in the sense that, no person might ever push it to the last stage.

**Comment by zabil** [comment] 2015-03-31 05:37
thanks @arvindsv 
I think point 3 solves a lot of problems. Deleting or moving the file will be easy and parallel jobs or stages need not worry about the directory hierarchy. The only two issues are locating the log file in case someone wants a tail -f  and the artifacts tab not displaying the console.log until the job is complete. is that ok?

**Comment by arvindsv** [comment] 2015-03-31 17:47
> The only two issues are locating the log file in case someone wants a tail -f and the artifacts tab not displaying the console.log until the job is complete. is that ok?

I think that's ok. We might want to think about redirecting ```https://server/go/files/pipeline/pipeline-counter/stage/stage-counter/job/cruise-output/console.log``` to the actual log (during "In progress" state) later, but the ```tail -f```, I'm not worried about. It's too much of an internal file, for someone to depend on. They shouldn't be doing it.

**Comment by zabil** [comment] 2015-04-03 05:37
For the benefit of testing things being done on this story.

* When the job is running write console on to a temporary file inside a folder called "local" wherever the server is running. The file name is an md5hex code generated from the pipeline/stage/counter/job/counter names. 
* After the job finishes move the file to the final location i.e cruise-output/console.log inside the artifacts folder.
There are no changes to the ui. This is something internal.

**Comment by zabil** [comment] 2015-04-03 06:22
One more point.
Earlier the line 
"[go] Job complete p/s/j on agent blah" used to be written after the job is complete

This has been modified to
"[go] Job complete p/s/j" as it is the server and not the agent who writes this info to the console.

**Comment by zabil** [comment] 2015-04-03 06:23
One more point.
Earlier the line 
"[go] Job complete p/s/j on agent blah" used to be written after the job is complete

This has been modified to
"[go] Job complete p/s/j" as it is the server and not the agent who writes this info to the console.

**Comment by zabil** [comment] 2015-04-03 06:23
One more point.
Earlier the line 
"[go] Job complete p/s/j on agent blah" used to be written after the job is complete

This has been modified to
"[go] Job complete p/s/j" as it is the server and not the agent who writes this info to the console.

**Comment by arvindsv** [comment] 2015-04-03 11:53
I forgot to ask this earlier. Instead of "local", would it be possible to use the "work" directory? Maybe "work/local". I this it is Jetty's work directory, where it explodes the WAR and uses it.

**Comment by zabil** [comment] 2015-04-03 14:45
@arvindsv 
 @jyotisingh and I discussed this. Isn't the work folder temporary? We did not want tie the lifecycle of local to jetty e.g. someone wanting to delete something stored by jetty.

**Comment by arvindsv** [comment] 2015-04-03 15:20
Well, it is part of the web application. The work/jetty-randomnumber... directory is temporary, and by default, does not persist across restarts. But, if "work/" is created it will. See references below. My concern was only about polluting the working directory. It's already quite busy and sometimes messy. I don't feel very strongly about it, either way. I'm ok whatever you two choose.

http://eclipse.org/jetty/documentation/current/ref-temporary-directories.html#d0e3824

https://wiki.eclipse.org/Jetty/Reference/Temporary_Directories

**Comment by zabil** [comment] 2015-04-06 08:38
I also feel strongly about not having extra dirs. From the docs you sent looks like we can use the work directory. Will make the change to create a dir called work/local instead of local

**Comment by arikagoyal** [comment] 2015-04-29 04:41
Works fine on 15.1.0-1863

**Closed by arikagoyal** 2015-04-29 04:41 UTC
Labels: console-log, enhancement, needs verification
