### ISSUE TITLE
 New Mechanism to configure GO.

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#1344] opened 2015-07-14 05:23 UTC
Currently, we are using **System properties** to configure Go. Instead of using System property I would like to propose some standard mechanism to store GO properties in a **config file**? 

The reason being, #1143 requires  a password to be stored in the system properties. But setting the password property via command line is not the secure way of setting the properties, because anyone can see the password by using ``` ps aux ``` command from command line.

**Note:** To implement the new mechanism, we have to decide the format of the property file (XML/JSON/Text).

**Comment by jyotisingh** [comment] 2015-07-28 10:53
Duplicate of #1313. Closing it.

**Closed by jyotisingh** 2015-07-28 10:53 UTC
