### ISSUE TITLE
[SCM endpoint] Passing in any value for `scm_name` param seems to return 200.

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1028] opened 2015-04-14 12:54 UTC
Steps to reproduce -

```
$ cat cruise-config.xml

<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="75">
  <server artifactsdir="artifacts" commandRepositoryLocation="default" serverId="9022a3ed-585b-41c3-b89a-0d82c3ceafbb" />
  <scms>
    <scm id="85587d5d-380d-4651-a077-8e6b79871fed" name="MyGitSCM" autoUpdate="false">
      <pluginConfiguration id="git" version="1" />
      <configuration>
        <property>
          <key>url</key>
          <value>https://gist.github.com/ketan/55d767390f175b2db755.git</value>
        </property>
      </configuration>
    </scm>
  </scms>
  <pipelines group="defaultGroup">
    <pipeline name="aaa">
      <materials>
        <scm ref="85587d5d-380d-4651-a077-8e6b79871fed" dest="MyGit" />
      </materials>
      <stage name="defaultStage" cleanWorkingDir="true">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="git" workingdir="MyGit">
                <arg>log</arg>
                <arg>-1</arg>
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

```
$ curl 'http://localhost:8153/go/api/material/notify/scm?scm_name=NonExistant' -XPOST -v --fail
$ echo $? # returns 0, expected non-zero value
```

**Comment by srinivasupadhya** [comment] 2015-04-15 04:49
this is a generic issue - [code](https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/server/src/com/thoughtworks/go/server/materials/MaterialUpdateService.java#L124). the fix is also going to be generic for all post commit hooks

**Comment by ketan** [comment] 2015-04-15 04:52
@srinivasupadhya - are you suggesting that the fix will be non-trivial and needs a conversation with the team?

**Comment by srinivasupadhya** [comment] 2015-04-15 04:54
no. i meant that the issue is not specific to scm end-point. Go supports post commit hooks for svn, git, hg & pluggable scm. the issue is generic to all.

**Comment by arikagoyal** [comment] 2015-04-15 05:00
This is an issue but it does not have any detrimental effect on post commit hook functionality. Due to lack of time moving it out to 15.2.

**Comment by arvindsv** [comment] 2015-04-15 11:03
Linking with #1029. Both should be worked on together.

**Comment by ketan** [comment] 2015-06-10 15:51
Verified, works as expected `15.2.0(2067-07d65665c731a6)`

**Closed** 2015-06-10 15:55 UTC
Labels: apis, bug, materials
