### ISSUE TITLE
Pipeline API: updating a lot of pipelines stops working

### ISSUE THREAD

**Issue by eugeneventer** [gocd/gocd#1753] opened 2016-01-04 21:38 UTC
Hi there,

We have a lot of pipelines. I have written a bit of python to keep our pipelines up to date via the API, but when running the script over all pipelines (sequentially), the PUT requests seem to work for a while (an X amount of pipelines) and then just stops ("hangs") - I assume waiting for a response from the server. Not sure if this is a problem with POSTs (add pipelines) as well.

Here's the little function I'm using to update a pipeline.
```
    def update_pipe(self, pipe, etag):
        requesturl = '%s/admin/pipelines/%s' % (self.apiurl, pipe['name'])
        requestheaders = {
            'Content-Type': 'application/json',
            'Accept': 'application/vnd.go.cd.v1+json',
            'If-Match': etag}
        request = requests.put(requesturl, data=json.dumps(pipe), headers=requestheaders, auth=self.creds, verify=False)
```
I tried adding a time.sleep to the end of the function. This seemed to help, but it still failed after a bit.

Any help would be appreciated - let me know if you have any questions.

Regards and thanks,
Eugene.

**Comment by ketan** [comment] 2016-01-05 03:05
All `POST`s that you perform are synchronous, so freezing after a certain number of `POST` requests seems rather odd.

It's possible that the server is frozen trying to process something else instead. When the server "freezes" again, can you capture the output of the url `/go/api/support`. We would need 3-4 such outputs spaced at an interval of about 10 seconds.

**Comment by eugeneventer** [comment] 2016-01-05 03:59
Hi Ketan,

It's not the server that freezes but rather the PUT request in this case. I am still able to browse the frontend, but performing pipeline updates via the UI also seem to stop working.

I'll replicate the problem tomorrow and provide you with the requested output. In order not to leak any sensitive information, are there any sections if the output I can leave out?

Thanks!

**Comment by ketan** [comment] 2016-01-05 04:06
> In order not to leak any sensitive information, are there any sections if the output I can leave out?

*Usually* any sensitive information can be part of the `Input Arguments`, `System Properties` or `Server health information`, but YMMV.

What we usually care about is the `Thread information` section, but the other sections may be helpful for e.g. in case your GC/memory/cache settings are suboptimal for the size of your go installation.

**Comment by jyotisingh** [comment] 2016-01-05 10:15
While you are testing this @eugeneventer, could you refrain from updating config through the UI at the same time. Updating config through the UI could become very slow for [many reasons](https://github.com/gocd/gocd/issues/838). Pipeline config API tries to address many of those issues, but then if a UI-based config save is in progress, the API will wait for it to finish, causing the request to take much longer (and may appear to be hung). 
All config save operations ie. PUTs and POSTs would behave the same way as far as waiting for other config-saves is concerned. api/support would certainly help.
BTW, how many pipelines do you have? 

Just curious about what you said earlier :
> I have written a bit of python to keep our pipelines up to date via the API

Where are you updating the pipelines from, manually crafted json or do you store your configs in some other repo and then sync it using this script?

**Comment by eugeneventer** [comment] 2016-01-05 20:33
@jyotisingh I will refrain from updating via the UI. FYI I left the update script running over the holidays and it was definitely hung - not just slow ;)

We have ~300 pipelines.

I'm syncing some of the pipeline config from a db ;)

**Comment by eugeneventer** [comment] 2016-01-05 22:07
[support.1.txt](https://github.com/gocd/gocd/files/79089/support.1.txt)
[support.2.txt](https://github.com/gocd/gocd/files/79087/support.2.txt)
[support.3.txt](https://github.com/gocd/gocd/files/79088/support.3.txt)

As requested, see the support output above.

**Comment by jyotisingh** [comment] 2016-01-06 12:27
From the api-support logs:
```
Found 2 dead locked threads. Here is there information.
LockInfo: com.thoughtworks.go.config.MergedGoConfig@37decfa7Monitor Info - Stack Frame where locks were taken.
The stack trace of the deadlocked thread
[]LockInfo: com.thoughtworks.go.config.CachedFileGoConfig@512f999Monitor Info - Stack Frame where locks were taken.
The stack trace of the deadlocked thread
```
There is a deadlock created. There is one thread which found some changes in config xml in file system so is trying to validate and save it(in a synchronized block). While it was doing that, one of the pipeline-config save calls happens. 

Stacktrace of timer thread(waiting to synchronize on MergedGoConfig):
```
com.thoughtworks.go.config.MergedGoConfig.saveValidConfigToCacheAndNotifyConfigChangeListeners(MergedGoConfig.java:182)
  com.thoughtworks.go.config.MergedGoConfig.tryAssembleMergedConfig(MergedGoConfig.java:102)
  com.thoughtworks.go.config.MergedGoConfig.onConfigChange(MergedGoConfig.java:70)
  com.thoughtworks.go.config.CachedFileGoConfig.notifyListeners(CachedFileGoConfig.java:232)
  com.thoughtworks.go.config.CachedFileGoConfig.saveValidConfigToCacheAndNotifyConfigChangeListeners(CachedFileGoConfig.java:175)
  com.thoughtworks.go.config.CachedFileGoConfig.loadFromDisk(CachedFileGoConfig.java:100)
  com.thoughtworks.go.config.CachedFileGoConfig.forceReload(CachedFileGoConfig.java:88)
  com.thoughtworks.go.config.CachedFileGoConfig.onTimer(CachedFileGoConfig.java:93)
```

Stacktrace of pipeline-config-api save(waiting to synchronize CachedFileGoConfig)
```
com.thoughtworks.go.config.CachedFileGoConfig.writePipelineWithLock(CachedFileGoConfig.java:150)
  com.thoughtworks.go.config.MergedGoConfig.writePipelineWithLock(MergedGoConfig.java:150)
  com.thoughtworks.go.config.GoConfigDao.updatePipeline(GoConfigDao.java:185)
  com.thoughtworks.go.server.service.GoConfigService.updatePipeline(GoConfigService.java:253)
  com.thoughtworks.go.server.service.PipelineConfigService.updatePipelineConfig(PipelineConfigService.java:99)
```

So, they end up in a deadlock, it is a bug that we need to fix - I will work on that. Just so you know, this could happen when you edit config directly from filesystem as well as change the config through the UI or API. 

@eugeneventer - Thanks for reporting it .

**Comment by rajiesh** [comment] 2016-01-15 08:56
regression test completed on 16.1.0-2855

**Comment by arvindsv** [comment] 2016-01-15 15:50
Closing this since it seems to be fixed.

**Closed by arvindsv** 2016-01-15 15:50 UTC
Labels: bug, pipeline configuration, [stream] other
