### ISSUE TITLE
Cannot create Elastic Agent Profiles through UI

### ISSUE THREAD

**Issue by maxbalan** [gocd/gocd#8201] opened 2020-05-29 17:40 UTC
**GOCD:** 20.4.0
**Kubernetes Elastic Agent Plugin:** 3.7.0-217

I migrated from 20.3.0 to 20.4.0 and I noticed that I cannot create a `Elastic Agent Profiles` thorough gocd UI. I thought it was a migration issue so I did a clean install of 20.4.0 and tried to setup the plugin from scratch it gave me the same error. 

I am trying to create agent profile using `Pod Yaml` option, I managed to work around it by changing the `Config XML` but its not really suitable for a long run.

This is the error shown next to the button
`Please fix the validation errors above before proceeding.`

GOCD Logs:
```
server_1  | jvm 1    | 2020-05-29 17:32:10,991 INFO  [qtp862510574-52] GoConfigDao:87 - Config update for entity request by com.thoughtworks.go.server.domain.Username@2a5e9d73[displayName=anonymous,username=anonymous] is in queue - com.thoughtworks.go.config.update.ElasticAgentProfileCreateCommand@bf27b56
server_1  | jvm 1    | 2020-05-29 17:32:10,991 INFO  [qtp862510574-52] GoConfigDao:90 - Config update for entity request by com.thoughtworks.go.server.domain.Username@2a5e9d73[displayName=anonymous,username=anonymous] is being processed
server_1  | jvm 1    | 2020-05-29 17:32:10,993 ERROR [qtp862510574-52] GoConfigDao:96 - Config update for entity failed
server_1  | jvm 1    | com.thoughtworks.go.config.exceptions.GoConfigInvalidException: Validation failed.
server_1  | jvm 1    |  at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingEntity(GoFileConfigDataSource.java:294)
server_1  | jvm 1    |  at com.thoughtworks.go.config.GoFileConfigDataSource.writeEntityWithLock(GoFileConfigDataSource.java:235)
server_1  | jvm 1    |  at com.thoughtworks.go.config.CachedGoConfig.writeEntityWithLock(CachedGoConfig.java:159)
server_1  | jvm 1    |  at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:94)
server_1  | jvm 1    |  at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:310)
server_1  | jvm 1    |  at com.thoughtworks.go.server.service.ElasticProfileService.update(ElasticProfileService.java:156)
server_1  | jvm 1    |  at com.thoughtworks.go.server.service.ElasticProfileService.create(ElasticProfileService.java:85)
server_1  | jvm 1    |  at com.thoughtworks.go.apiv2.elasticprofile.ElasticProfileControllerV2.create(ElasticProfileControllerV2.java:135)
server_1  | jvm 1    |  at spark.RouteImpl$1.handle(RouteImpl.java:72)
server_1  | jvm 1    |  at spark.http.matching.Routes.execute(Routes.java:61)
server_1  | jvm 1    |  at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
server_1  | jvm 1    |  at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
server_1  | jvm 1    |  at com.thoughtworks.go.spark.SparkPreFilter.doFilter(SparkPreFilter.java:63)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:625)
server_1  | jvm 1    |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:608)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
server_1  | jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
server_1  | jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
server_1  | jvm 1    |  at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:220)
server_1  | jvm 1    |  at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:79)
server_1  | jvm 1    |  at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
server_1  | jvm 1    |  at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
server_1  | jvm 1    |  at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
server_1  | jvm 1    |  at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
server_1  | jvm 1    |  at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilterInternal(FlashLoadingFilter.java:38)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.DenyIfRefererIsNotFilesFilter.doFilterInternal(DenyIfRefererIsNotFilesFilter.java:52)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.VerifyAuthorityFilter.doFilterInternal(VerifyAuthorityFilter.java:57)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AbstractUserEnabledCheckFilter.doFilterInternal(AbstractUserEnabledCheckFilter.java:55)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.ThreadLocalUserFilter.doFilterInternal(ThreadLocalUserFilter.java:41)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AccessTokenAuthenticationFilter.filterWhenSecurityDisabled(AccessTokenAuthenticationFilter.java:164)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AccessTokenAuthenticationFilter.doFilterInternal(AccessTokenAuthenticationFilter.java:96)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.filterWhenSecurityDisabled(AbstractBasicAuthenticationFilter.java:112)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.doFilterInternal(AbstractBasicAuthenticationFilter.java:70)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AssumeAnonymousUserFilter.doFilterInternal(AssumeAnonymousUserFilter.java:64)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.doFilterInternal(AbstractReAuthenticationFilter.java:66)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.InvalidateAuthenticationOnSecurityConfigChangeFilter.doFilterInternal(InvalidateAuthenticationOnSecurityConfigChangeFilter.java:105)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:40)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.AbstractSessionReduceIdleTimeoutFilter.doFilterInternal(AbstractSessionReduceIdleTimeoutFilter.java:44)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:79)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at com.thoughtworks.go.server.web.BackupFilter.doFilterInternal(BackupFilter.java:79)
server_1  | jvm 1    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
server_1  | jvm 1    |  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
server_1  | jvm 1    |  at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:79)
server_1  | jvm 1    |  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
server_1  | jvm 1    |  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
server_1  | jvm 1    |  at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:51)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
server_1  | jvm 1    |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
server_1  | jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
server_1  | jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
server_1  | jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
server_1  | jvm 1    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
server_1  | jvm 1    |  at org.eclipse.jetty.server.Server.handle(Server.java:500)
```

**Comment by maxbalan** [comment] 2020-05-29 19:27
@arvindsv thank you for looking into this, didn't knew where better to open it, though it was a compatibility issue

**Comment by maheshp** [comment] 2020-05-29 19:49
@maxbalan can you please provide the JSON response when you save the Agent Profile. The Network tab in your browser developer tools should have this information.

**Comment by maheshp** [comment] 2020-05-29 20:43
I was able to reproduce this, for a create profile request with the following JSON payload,

```json
{
  "id": "Profile1",
  "plugin_id": "cd.go.contrib.elasticagent.kubernetes",
  "cluster_profile_id": "clust1",
  "properties": [
    {
      "key": "Image",
      "value": ""
    },
    {
      "key": "MaxMemory",
      "value": ""
    },
    {
      "key": "MaxCPU",
      "value": ""
    },
    {
      "key": "Environment",
      "value": ""
    },
    {
      "key": "PodConfiguration",
      "value": "apiVersion: v1\nkind: Pod\nmetadata:\n  name: pod-name-prefix-{{ POD_POSTFIX }}\n  labels:\n    app: web\nspec:\n  containers:\n    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}\n      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}\n      securityContext:\n        privileged: true"
    },
    {
      "key": "SpecifiedUsingPodConfiguration",
      "value": ""
    },
    {
      "key": "PodSpecType",
      "value": "yaml"
    },
    {
      "key": "RemoteFile",
      "value": ""
    },
    {
      "key": "RemoteFileType",
      "value": "json"
    },
    {
      "key": "Privileged",
      "value": ""
    }
  ]
}
```

The error response is,
```json
{
  "message" : "Validations failed for agentProfile 'Profile1'. Error(s): [Invalid size: ]. Please correct and resubmit.",
  "data" : {
    "id" : "Profile1",
    "cluster_profile_id" : "clust1",
    "properties" : [ {
      "key" : "Image"
    }, {
      "key" : "MaxMemory",
      "errors" : {
        "MaxMemory" : [ "Invalid size: " ]
      }
    }, {
      "key" : "MaxCPU"
    }, {
      "key" : "Environment"
    }, {
      "key" : "PodConfiguration",
      "value" : "apiVersion: v1\nkind: Pod\nmetadata:\n  name: pod-name-prefix-{{ POD_POSTFIX }}\n  labels:\n    app: web\nspec:\n  containers:\n    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}\n      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}\n      securityContext:\n        privileged: true"
    }, {
      "key" : "SpecifiedUsingPodConfiguration"
    }, {
      "key" : "PodSpecType",
      "value" : "yaml"
    }, {
      "key" : "RemoteFile"
    }, {
      "key" : "RemoteFileType",
      "value" : "json"
    }, {
      "key" : "Privileged"
    } ],
    "errors" : { }
  }
}
```

Looks like this issue is a side effect of the changes done to handle ConfigurationProperty value as part of https://github.com/gocd/gocd/pull/8138. 
Due to the changes in #8138, the value for `MaxMemory` if not set is sent as empty string to the plugin. Earlier the plugin ignored a null value, but now it validates the empty string and throws this error.

I think we should fix this issue on the plugin side over making changes in the core.

**Comment by kritika-singh3** [comment] 2020-06-04 07:43
@maxbalan We have fixed this issue and created an experimental release of the [plugin](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.7.1-222-exp). Can you test it out and if everything works on your end, we can make a stable release. Thanks!

**Comment by maxbalan** [comment] 2020-06-05 12:50
Hi @kritika-singh3, I have tried it on a local build of gocd v20.4.0, and it worked as expected

**Comment by kritika-singh3** [comment] 2020-06-05 14:06
Thanks for confirming @maxbalan . I'll make a stable release then. Thanks!

**Comment by kritika-singh3** [comment] 2020-06-05 14:11
A release has been created with the fix [here](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.7.1-230). I'll close this issue.

**Closed by kritika-singh3** 2020-06-05 14:11 UTC
Labels: bug, elastic-agents
