### ISSUE TITLE
Email notifications stop sending after server restart

### ISSUE THREAD

**Issue by arch-bom-gocd-alerts** [gocd/gocd#9691] opened 2021-09-13 21:22 UTC
##### Issue Type

- Bug Report

##### Summary

Email notifications are no longer sent after N days (1 month?) from last login. Logging back in to GoCD seems to restore email notifications. 

This is our working theory after this has happened several times with a service user we use for notifications, along with how we have corrected it.

##### Environment

_I don't have access and doubt it is relevant, but will get it if it becomes necessary._ 

###### Basic environment details

* GoCD Version: 20.10.0 (12356-b16b6bc3f7ad3bb39e465ff2168d1cc66c95b4d5).
* JAVA Version: 15.0.1
* OS: Linux 5.4.129-63.229.amzn2.x86_64

##### Steps to Reproduce

1. Log in to GoCD as user X.
2. Set up email notifications for a pipeline that fails.
3. Log out of GoCD.
4. Wait N days (guess: one month?)
5. Notifications stop appearing.

##### Expected Results

Email notifications should not require a user to log in to GoCD to continue to receive them. This is especially annoying for service users, but a problem in general.

##### Actual Results

Email notifications eventually stop being sent. This lasts until the user logs in to GoCD again.

**Comment by robrap** [comment] 2021-09-14 13:32
Oops. I created this issue with the service account by mistake. I am the actual author of this issue.

**Comment by robrap** [comment] 2021-09-17 20:51
**UPDATE:** Our workaround is to add/remove a new notification to get them to save. Then the former notifications start firing again. This is in addition to the login that was mentioned in the original issue.

**Comment by chadlwilson** [comment] 2022-08-10 14:56
I can't see anything in GoCD that could explain this - GoCD doesn't store the last login time or anything like that in a way that could be used to drive this kind of logic directly. Unless you have some custom magic in your environment that disables unused accounts in GoCD somehow (disabled accounts won't receive mail)? Or there is a "downstream" problem with receiving the email to that account?

- Which login authentication/authorization mechanism are you using with the service account? GitHub OAuth2 login?
- And which email address are you sending the alerts to? One representing the service account?
- Is this an internal SMTP server?
- Is it possible that if you don't login as that user for 30 days, the email server stops forwarding email to that address because it is connected in some way?
- Can you check there are no errors in the GoCD Server logs relating to this email sending after the, say, 30 days?

**Comment by arch-bom-gocd-alerts** [comment] 2022-08-10 19:04
@chadlwilson: Thank you very much for checking in. 

First, some clarifications and additional notes:
-  When we notice that notifications are no longer being sent, our current workaround is to edit/save the notification preferences to get them started again. (I found I could add a new notification, and then remove the new notification, and that was a good enough kick to the tires.) I do *not* think this is related to login, although I need to login to update the notifications.
- I'd say "30 days" was more of an approximate of how often I think this problem seems to occur. I do not have any hard data on this, and I suspect the real cause (whatever that is) happens in the order of once a month.
- I had a hypothesis that possibly a GoCD server restart might cause this issue. I still would need to have this verified.
- I just added the ability to collect two new points of data: 1) I am sending email notifications to myself to see _when_ and _if_ they stop, and 2) I adjusted the alerting for the service alerts to create/auto-close tickets on "passed". This should help me better pinpoint when alerting actually stops, and whether it affects all emails/users.

Now, to your questions:

>  Which login authentication/authorization mechanism are you using with the service account? GitHub OAuth2 login?

Yes. We are using GitHub OAuth2 login. And as noted above, I don't think login alone will get notifications working once it stops.

>  And which email address are you sending the alerts to? One representing the service account?

Sort of. We use OpsGenie for alerting, and are using an OpsGenie Email Integration email.

>  Is this an internal SMTP server?

OpsGenie manages the email addresses. I imagine (and could confirm) that we are using AWS SES to send the email from GoCD.

>  Is it possible that if you don't login as that user for 30 days, the email server stops forwarding email to that address because it is connected in some way?

As noted above, I no longer think this is login related. I literally need to update notification preferences in GoCD as the workaround. I'm not clear how and if GoCD caches this information, and how and if it could be lost/restored when updating the notification preferences.

>  Can you check there are no errors in the GoCD Server logs relating to this email sending after the, say, 30 days?

I'm not seeing any relevant errors. Let me know if there is anything specific you wanted me to look for.

**Comment by chadlwilson** [comment] 2022-08-11 16:25
Hmm, your additional points of data might help. 

Something caching related might be an avenue of investigation, especially if restarting GoCD also can be correlated to email notifications starting to fire again (in addition to updating user preferences). I'm not familiar with what (if anything) is cached in this area, would need to dig.

As for logs I guess I'd just be scanning for anything WARN or ERROR related that looks relevant from the server logs, especially correlated to the time when you notice notifications stopped happening. I don't think it logs by default when it does send an email, although it might be possible to selectively turn up debug logging to achieve this.

**Comment by robrap** [comment] 2022-08-11 17:16
Thanks. A general search in the logs did not turn anything up, but hopefully I'll have a smaller window to search when this next recurs, since I am collecting some additional data.

**Comment by robrap** [comment] 2022-08-31 15:43
@chadlwilson: We have some evidence that the problem may start when the GoCD server is restarted. Is there anything required on startup to get notifications going again? Does it make sense that this might be the cause? Thank you!

**Comment by chadlwilson** [comment] 2022-09-01 06:02
Not that I can think of unless you have some custom scripts doing something funky at start, clean something from the DB or cause a change to the config.xml somehow.

Are you running via an installer or a docker image? Have you checked the config.xml to see if there are any changes being made there?

**Comment by robrap** [comment] 2022-09-01 15:32
Thanks @chadlwilson. I'll pass your questions along to the team responsible for the server.

**Comment by timmc-edx** [comment] 2022-09-01 18:48
New finding: Simply logging in to the UI seems to be sufficient to get notifications going again (for that user).

**Comment by robrap** [comment] 2022-09-01 21:34
@chadlwilson: We have a theory that this might be related to a configuration issue related to a Kubernetes deployment and AWS EBS volume multi-AZ setup. We're working to see if we can get it fixed. If this is not something you see on a typical deployment, you can decide if it makes sense to close this ticket. 

Also, not sure if you can edit the issue or description, but at this point, this ticket is about "Email notifications stop sending after server reboot", which is different from what I first thought. Thanks!

**Comment by chadlwilson** [comment] 2022-10-10 04:35
Sorry for the delayed reply here @robrap @timmc-edx - forgot about this.

Did you get to the bottom of this? Anything else you discovered would be useful to either mitigate this or understand the environmental/deployment challenge that led to this weird behaviour.

If you are using the built-in H2 database the information about who to send notifications to would typically be stored on the underlying volume mounted to `/godata`, but I'm not quite seeing how that could cause an issue like this without many other weird issues also being caused and errors being in the logs.

What it sounds "most" like, is either multiple GoCD server instances trying to write to the same volume or DB, or some kind of behind-the-scenes rollback to an earlier version of the underlying database where the users' notifications (or their personal user entry) are not persisted properly.

Can't really explain why logging in would fix anything though - except with the interesting factoid that you're using GitHub logins rather than "GoCD-managed" users. I don't know well the underlying implementation of this area, but I guess its _conceptually possible_ that some important knowledge about the user and their email address is someone gone until they login again (via GitHub) in some scenario. If you have any additional observations I could possibly dig into it a bit more.

**Comment by chadlwilson** [comment] 2022-10-28 13:57
Closing this for now on the assumption it's something environmental. Let me know if you have additional information that points to a GoCD issue and we can re-open it.

**Closed by chadlwilson** 2022-10-28 13:57 UTC
Labels: notifications

**Comment by robrap** [comment] 2022-10-28 17:43
@chadlwilson: Thanks again for all your thoughts. I think closing is a good move. I’ll reopen if anything ever changes, but I imagine it is related to an infrastructure hiccup that is outside of GoCD’s concerns.

**Comment by robrap** [comment] 2022-12-02 18:30
@chadlwilson: Not sure if it is worth reopening, but this is what I've gathered from my SRE team:
* On restart, it takes up to 30 minutes for GoCD to attach to its PVC (persistent volume claim). 
  * We haven't been able to figure out why this is happening, and an AWS support ticket did not help.
  * We are using a standard kubernetes gocd helm deployment.

I am just guessing that this issue might interrupt some process around start-up and notifications, but I have no idea if that is the case.

**Comment by chadlwilson** [comment] 2022-12-03 01:24
That is almost certainly unrelated and is due to Kubernetes design itself. See https://github.com/gocd/helm-chart/tree/master/gocd#slow-volume-mounting--pod-creation and https://github.com/gocd/helm-chart/pull/26 for an explanation and how to 'fix' it.

On the latest version of the Helm chart (2.0.0 which drops support for EOL Kubernetes versions) the default has been changed to what will be perceieved as instant volume mounting, with some risk of permissions issues if people do things they shouldn't with their volume :)

**Comment by robrap** [comment] 2022-12-05 18:27
Thanks @chadlwilson. I’ll pass along the info, and if it gets resolved, I can see if it affects our notifications on restart or not.

**Comment by robrap** [comment] 2022-12-07 15:22
@chadlwilson: 
1. Our SRE team was super excited to learn what you shared in your last comment. It helped them fix the restart issue. Thank you!
2. Unfortunately, the restarts are still killing the email notifications, and I'm not sure what I should do next to try to resolve. I might be able to try setting logging to debug, but not sure exactly what I'd be looking for. I could also try looking for warnings or errors again to see if I missed anything.
Let me know if you have any other thoughts. Thank you.

**Comment by arvindsv** [comment] 2022-12-11 11:40
I know this is not exactly what you want, but I wonder if writing a [notification plugin](https://plugin-api.gocd.org/current/notifications/#notifications-interested-in) could be an option for you to consider. It should allow for more control over the process anyway.

**Comment by robrap** [comment] 2022-12-13 18:11
Thanks @arvindsv for another potential workaround. We also have some GoCD pipelines doing notifications from within the pipeline code, but it gets complicated for this particular set of pipelines. But, these possible solutions may be quicker than getting to the bottom of the issue. For now, we're just dealing with resetting when we see our notifications have stopped.
