### ISSUE TITLE
agent has duplicate unique identifier which conflicts with

### ISSUE THREAD

**Issue by bormotov** [gocd/gocd#1134] opened 2015-05-18 08:01 UTC
after upgrading to 15.1.0 got messages like this:

> [Agent located at [fed01.bcm.local, 192.168.109.91, /var/lib/go-agent]] has duplicate unique identifier which conflicts with [Agent located at [fed01.bcm.local, 192.168.109.91, /var/lib/go-agent]] [May-18 11:59:31]

How to one agent can conflicts with itself?

**Comment by ketan** [comment] 2015-05-18 08:49
This is generally caused when there are two agent processes connecting to a go server using identical IDs.

In your case, you may be running multiple agent processes from the same directory.

If  `$ ps aux | grep agent` tells you that there are multiple processes, you should kill both the agents followed by restarting a new agent using the script.

If you're seeing one process, then let us know and we'll help investigate further.

**Comment by bormotov** [comment] 2015-05-18 09:01
at host "fed01" just one agent.  But, at another host was started another agent with same guid.
and we got strange behavior

> 11:01:39.779 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed01.bcm.local [/var/lib/go-agent]
> 11:02:02.666 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:02:02.705 [go] Job completed ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:02:09.778 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed01.bcm.local [/var/lib/go-agent]
> 11:02:32.407 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:02:32.431 [go] Job completed ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:02:39.780 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed01.bcm.local [/var/lib/go-agent]
> 11:03:02.419 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:03:02.433 [go] Job completed ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:03:09.776 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed01.bcm.local [/var/lib/go-agent]
> 11:03:32.403 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:03:32.423 [go] Job completed ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]
> 11:03:39.780 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed01.bcm.local [/var/lib/go-agent]
> 11:04:02.409 [go] Job is cancelled ICM-Build/505/Compile/1/Compile on fed2-test [/var/lib/go-agent]

 	
in this case, fed2-test not listed in "Agents" (not added, not enabled, not have resource properties for got job etc)

**Comment by ketan** [comment] 2015-05-18 09:29
> at host "fed01" just one agent. But, at another host was started another agent with same guid.

Are you spinning off agents by either -

* copying the agent directory
* from a pristine machine image with a pre-configured agent

If you're doing either of these, you'll need to remove the agent's `config` directory before you start the agent process.

The `config/guid.txt` file contains the agent identifier and multiple agent processes should not share the same identifier.

**Comment by bormotov** [comment] 2015-05-21 19:22
Ok, we run inconsistent configuraton.

But Go Server problem diagnostic say somthing strange, instead "You have two agents with same GUID, on these hosts, runnig this there configs dirrectories", and other problem details.

**Comment by ketan** [comment] 2015-05-23 10:38
> But Go Server problem diagnostic say somthing strange, instead "You have two agents with same GUID, on these hosts, runnig this there configs dirrectories", and other problem details.

I'm not sure I follow what that means - do you have the exact log message that we could possibly improve?

**Comment by bormotov** [comment] 2015-05-23 13:29
example of log entries 

https://gist.github.com/bormotov/2bc3837087aeef99c0d9

but at top of this issue - warning text from go server interface. More important clearly and accurately explain the problem at UI. Why in this message fed01.bcm.local "conflict" with itself?
Why agent from fed-test not shown at "Agents" page?  What is "agent cookiie"? 

quick-thinked varint:
1. all connected agents listed at "Agent" page in server UI
2. agent with same GUID - marked "red" or in some other way
3. admin check one of duplicated-guid-agent and send command "disconnect, generate new GUID and reconect"

if better describe "duplicated GUID" problem, in 99% - this is cloned go-agent. And go-server can safely tell to second connected agent "generate new GUID and reconect", without user interaction. Сan't imagine when we need to do something else with dupes, but just in case left 1%

**Comment by arvindsv** [comment] 2015-05-27 11:25
Hey @bormotov. I agree that it can be handled better, and in a more UI-centric way. I'm not yet sure about automatically asking it to change its GUID, but that's a possibility.

However, before we get to that, I'd like to understand this better. From what I can see, the problem is that  the agent seems to conflict with itself. That's strange. If this is still happening, can you help find the root cause of it? I'd like to start with running ```ps -ef | grep agent``` on the Go Agent machine, to see how many agents are running.

**Comment by arvindsv** [comment] 2015-05-27 11:26
To be clear, that needs to be run on fed01.bcm.local -192.168.109.91.

**Comment by bormotov** [comment] 2015-05-27 11:34
of course, if same warning appear again, I look to ps -ef at agent host

**Comment by bormotov** [comment] 2016-01-19 06:44
Same problem, again.
After update GoCd Server to 16.1.0, got warning

[Agent located at [srv-go1, 192.168.109.187, C:\GoAgent]] has duplicate unique identifier which conflicts with [Agent located at [, Unknown, ]] [Jan-19 09:45:35]

1. stop/start this agent - same warning
2. stop agent, remove guid.txt, start agent - same warning

**Comment by CzarScar** [comment] 2017-02-03 03:18
I have also met this issue on 16.12. As a result, our job is building and canceling on both two agents in a loop and never really execute the task.

**Comment by arvindsv** [comment] 2017-02-06 13:00
@bormotov - If you stop the agent, move the whole config/ directory to config.old/ or something and start the agent, does this still happen? If you've done this right, it should register as a new agent and you'll have to enable it in the "Agents" page.

I've seen this happen only when two agents share the same guid (you already ruled that out) or maybe other config such as the certificates that are in config/.

**Comment by bormotov** [comment] 2017-02-06 13:16
Сan't find errors "duplicate unique identifier" in logs of this year, 
Apparently something has changed, and the error is no longer reproduced.

**Comment by arvindsv** [comment] 2017-02-06 13:23
Hmm. Ok. Thanks for the update! I'll close this for now. You can reopen it anytime, as you know. :)

**Closed by arvindsv** 2017-02-06 13:23 UTC

**Comment by bormotov** [comment] 2017-02-14 07:09
Warnings in UI:

`[Agent located at [srv-go2, 192.168.109.208, C:\GoAgent]] has duplicate unique identifier which conflicts with [Agent located at [srv-go2, 192.168.109.208, C:\GoAgent]] [Feb-14 10:07:05]
`

`[Agent located at [srv-go2, 192.168.109.208, C:\GoAgent]] has duplicate unique identifier which conflicts with [Agent located at [srv-go2, 192.168.109.208, C:\GoAgent]] [Feb-14 10:07:07]`

**Comment by bormotov** [comment] 2017-02-14 07:16
result of 

`grep -i duplicate go-server.log > go-server-log-duplicate.txt`

attached
[go-server-log-duplicate.txt](https://github.com/gocd/gocd/files/773364/go-server-log-duplicate.txt)

**Comment by bormotov** [comment] 2017-02-14 09:34
this agent guid: 2a20e630-83e0-4d75-a914-0e8933e302bb

![2017-02-14_12-31-12](https://cloud.githubusercontent.com/assets/75397/22923244/afdadd74-f2b1-11e6-9e56-023c42c96476.png)

and look at C:\GoAgent\config - most files untochable from 2015.

**Comment by thecontrarycat** [comment] 2017-06-12 13:03
Had this issue with two agents after upgrading to 17.5.  Only way to fix it was to disable and delete the agents then let them re-register.

**Comment by thecontrarycat** [comment] 2017-06-12 14:00
On further investigation, it appears that there were orphaned java.exe processes that did not shutdown correctly when the service was stopped.  Finding and killing these may have negated the need to reregister the agents.

**Comment by bormotov** [comment] 2017-06-12 14:09
Don't need any "find and kill".

Look at situation (my first comment at 14 Feb):
- server know about agent: hostname, ip-address, GUID, agent path
- got *new* connection from agent with same: hostname, ip-address, GUID, agent path

* what reason to believe that new сonneсt from new agent - wrong?
* what are the possible problems if the server will replace the old connection with a new?
