### ISSUE TITLE
It is not possible to distinguish between scheduled and building pipelines/stages

### ISSUE THREAD

**Issue by NachbarsLumpi** [gocd/gocd#471] opened 2014-09-03 06:13 UTC
The color on those is the same, and thus one has to click on each item to find the building one.

**Comment by arvindsv** [comment] 2016-06-04 12:18
Closing as duplicate of a newer issues (#2173). Should do this as a part of the [dashboard rewrite](https://github.com/gocd/gocd/issues/1097).

**Closed by arvindsv** 2016-06-04 12:18 UTC
