### ISSUE TITLE
Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "STATECHANGETIME"; SQL statement

### ISSUE THREAD

**Issue by ankurga** [gocd/gocd#10631] opened 2022-07-28 13:33 UTC
##### Issue Type

- Bug Report

##### Summary

Getting this error very frequently in our GoCD server logs. After this error, no job is schedule on agents and the agents keep on sitting in "Idle" state.

###### Basic environment details

* Go Version: 22.1.0 (13913-f4c9c1650e2e27fe0a9962faa39536f94f57e297)
* JAVA Version: 17.0.2
* OS: Linux 4.19.0-21-cloud-amd64
* Browser vendor and version (if relevant): Brave/Chrome (not relevant)

##### Steps to Reproduce

1. Not sure, but I think it happens when we try to clear disk space using below command
```bash
rm -rf /var/go/.m2/repository/* /var/lib/go-agent*/pipelines/*
rm -rf /var/lib/go-server/artifacts/pipelines
```
##### Expected Results

Pipelines should get scheduled on agents.

##### Actual Results
All the jobs are stuck in `waiting for agent` state, even though agents are sitting in `Idle` state.

##### Log snippets

```bash
2022-07-28 15:17:29,239 WARN  [ThreadPoolTaskScheduler-4] MaterialUpdateService:204 - [Material Update] Skipping update of material GitMaterial{url=git@github.com:optile/itops_consul_configs.git, branch='master', shallowClone=false, submoduleFolder='null'} which has been in-progress since Thu Jul 28 15:14:59 CEST 2022
2022-07-28 15:17:29,880 ERROR [112@MessageListener for WorkFinder] JMSMessageListenerAdapter:87 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@47dedc8a
org.springframework.dao.DataIntegrityViolationException:
### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "STATECHANGETIME"; SQL statement:
INSERT INTO buildStateTransitions (currentState, stateChangeTime, buildId, stageId)
        VALUES (?, ?, ?, ?) [23502-200]
### The error may exist in com/thoughtworks/go/server/dao/maps/BuildStateTransition.xml
### The error may involve BuildStateTransition.insert-transition-param
### The error occurred while setting parameters
### SQL: INSERT INTO buildStateTransitions (currentState, stateChangeTime, buildId, stageId)         VALUES (?, ?, ?, ?)
### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "STATECHANGETIME"; SQL statement:
INSERT INTO buildStateTransitions (currentState, stateChangeTime, buildId, stageId)
        VALUES (?, ?, ?, ?) [23502-200]
; SQL []; NULL not allowed for column "STATECHANGETIME"; SQL statement:
INSERT INTO buildStateTransitions (currentState, stateChangeTime, buildId, stageId)
        VALUES (?, ?, ?, ?) [23502-200]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "STATECHANGETIME"; SQL statement:
INSERT INTO buildStateTransitions (currentState, stateChangeTime, buildId, stageId)
        VALUES (?, ?, ?, ?) [23502-200]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:242)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at jdk.proxy3/jdk.proxy3.$Proxy32.insert(Unknown Source)
```

**Comment by chadlwilson** [comment] 2022-07-28 14:33
1. How do you resolve the issue once it occurs?
2. If you think it is correlated, did you run those commands while there were active jobs running on an agent? If so, what's in the agent logs, and what makes you think the timing is correlated?

This looks similar to https://groups.google.com/g/go-cd/c/UEYM9NGcavI/m/PZp5L4wEBQAJ but there was insufficient information there to look any further.

**Comment by ankurga** [comment] 2022-08-01 07:54
1. Attaching full log from go-server. [go-server.log](https://github.com/gocd/gocd/files/9231926/go-server.log)
2. We stop, delete and re-register the agents again then it works for sometime or a day or two but then it again starts giving the same issue.
3. Yes, we did run these commands when there were active jobs on server and agents. We have noticed that whenever disk space gets full and we clear space using these commands only then this issue happens. Attaching agent logs as well. [go-agent.log](https://github.com/gocd/gocd/files/9231927/go-agent.log)

> https://groups.google.com/g/go-cd/c/UEYM9NGcavI/m/PZp5L4wEBQAJ

Even I saw this while searching for solution on google but didn't find any concrete solution so raising it here.

**Comment by chadlwilson** [comment] 2022-08-01 07:57
>     2. We stop, delete and re-register the agents again then it works for sometime or a day or two but then it again starts giving the same issue.

Do you need to restart the GoCD server at all?

**Comment by ankurga** [comment] 2022-08-01 14:37
yes, we have to restart GoCD server as well.

**Comment by chadlwilson** [comment] 2022-08-01 15:49
Broadly speaking, what appears to be happening is your server
- is using on disk H2 DB for storage using the same volume as for `artifacts`
- `08:03:32,485` runs out of disk space and cannot write to the database **at all**
- since it cannot write to the database, it probably loses track of which agents are running which jobs along with many other things
- `08:04:33,209` starts logging errors like `com.thoughtworks.go.remote.work.InvalidAgentException: AgentUUID has changed in the middle of a job`, likely due to the above
- `08:04:54,095 ERROR` soon you start getting integrity errors  `### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "STATECHANGETIME"; SQL statement:`. At this time the disk is **still** out of space.

Overall, especially if you are using the on-disk H2 database, you need to make sure it doesn't completely run out of disk space. It stops scheduling when there is less than 100MB available by default, but if you are sharing artifacts and DB disk space, artifacts could keep uploading and soon you will have have none left. Likely _bad things_ will start happening when you complete exhaust available disk space for the DB storage.

You might want to consider
- keeping artifacts and db on different storage volumes so there is more time before the DB cannot even be written to
- increasing system properties `db.full.size.limit` (default: `100M`), `db.warning.size.limit` (default: `1024M`), `artifact.full.size.limit` (default: `100M`), `artifact.warning.size.limit` (default: `1024M`) so you don't actually totally run out of space, i.e to buy you more time so it stops scheduling jobs earlier.
- Pay attention to the warnings.

If you stop the server from completely running out of disk space for DB storage, I think you will find that specific problem goes away. Doesn't address the issue of corruption, but might allow us to understand the cause.

**Comment by ankurga** [comment] 2022-08-03 06:04
Thank you for your prompt response !!

- We are trying to reduce number of volumes that we use. So, we don't want to create any extra volumes for this.

We also have postgresql installed locally on the same server on which GoCD is installed. Do you think it makes sense if we move our GoCD database from H2 database to postgresql? Can postgresql handle the DB better to prevent such kind of _bad things_?

**Comment by chadlwilson** [comment] 2022-08-03 06:22
The _bad things_ probably happen regardless of database type **if** the underlying database runs out of space, or can't be accessed/written to for any reason. Using a real database can add some additional challenges depending on how it is supported/configured/backed up etc. Usually folks move to something like Postgres for performance reasons rather than this. I guess what I am saying is that if your Postgres is a local one, and sharing the same volumes as above and artifacts, you might have the same risk.

Personally, I would suggest the quicker and lower risk "win" would be to either move your h2 `db` or `artifacts` to a different volume so they don't affect one another. You might want to check out https://docs.gocd.org/current/installation/install/server/linux.html#location-of-gocd-server-files and/or think about changing `/var/lib/go-server/db` to point to a different volume (this normally contains both the GoCD configuration database, and h2db "history" database if using H2).

**Comment by sriramnrn** [comment] 2022-08-03 06:27
On Wed, 3 Aug 2022 at 2:22 PM, Chad Wilson ***@***.***> wrote:

> The *bad things* probably happen regardless of database type *if* the
> underlying database runs out of space, or can't be accessed/written to for
> any reason. Using a real database can add some additional challenges
> depending on how it is supported/configured/backed up etc. Usually folks
> move to something like Postgres for performance reasons rather than this. I
> guess what I am saying is that if your Postgres is a local one, and sharing
> the same volumes as above and artifacts, you might have the same risk.
>
> Personally, I would suggest the quicker and lower risk "win" would be to
> either move your h2 db or artifacts to a different volume so they don't
> affect one another. You might want to check out
> https://docs.gocd.org/current/installation/install/server/linux.html#location-of-gocd-server-files
> and/or think about changing /var/lib/go-server/db to point to a different
> volume (this normally contains both the GoCD configuration database, and
> h2db "history" database if using H2).
>

During this move - especially if you use symlinks or volume mounts - please
ensure that the owner, group, and the permissions are set correctly.

**Comment by ankurga** [comment] 2022-08-03 08:23
Alright, thanks again for your inputs.

> increasing system properties db.full.size.limit (default: 100M), db.warning.size.limit (default: 1024M), artifact.full.size.limit (default: 100M), artifact.warning.size.limit (default: 1024M) so you don't actually totally run out of space, i.e to buy you more time so it stops scheduling jobs earlier.

And where do I need to specify these settings that you suggested? Could you please point me to the file-name, I couldn't quite understand from the docs. Do I need to create a `db.properties` file here?

```
[root@integration-agarg:/var/lib/go-server/db/config.git]# ls -lrth
total 864K
-rw-r--r-- 1 go go 863K Aug  2 14:44 cruise-config.xml
[root@integration-agarg:/var/lib/go-server/db/config.git]# pwd
/var/lib/go-server/db/config.git
[root@integration-agarg:/var/lib/go-server/db/config.git]#
```

**Comment by ankurga** [comment] 2022-08-03 08:27
Or maybe I need to specify them in:

`/usr/share/go-server/wrapper-config/wrapper-properties.conf`  ??

**Comment by arvindsv** [comment] 2022-08-12 10:21
Yes, in wrapper-properties.conf. Something like: `-Ddb.warning.size.limit=2048M`. 

https://docs.gocd.org/current/advanced_usage/other_config_options.html

Closing this.

**Closed by arvindsv** 2022-08-12 10:21 UTC
Labels: bug, agents
