### ISSUE TITLE
Backup Notifications should reference Site URL

### ISSUE THREAD

**Issue by jaymed** [gocd/gocd#3159] opened 2017-02-07 14:28 UTC
##### Issue Type

- Feature enhancement. Maybe a bug?

##### Summary

Go Backup Notifications, which look like the sample below, do not make use of the configured 'Site URL' value described [here](https://docs.gocd.io/current/installation/configuring_server_details.html#configure-site-urls). Instead they use the server IP address, which can be insignificant to the reader if the service is running inside a container, or not very easy to distinguish if there are multiple Go servers running backups. It would be much better if the 'Site URL' was used instead of the IP.

```
Backup of the Go server at '172.17.0.3' was successfully completed. The backup is stored at location: /data/go/artifacts/serverBackups/backup_20170207-090002. This backup was triggered by 'admin'.
```

###### Basic environment details

* Go Version: `16.12.0`
* JAVA Version: `	1.7.0_121`
* OS: `Linux 3.19.0-59-generic`

**Comment by arvindsv** [comment] 2017-10-18 21:09
Closing as a duplicate of #3653 (yes, I know that is newer).

**Closed by arvindsv** 2017-10-18 21:09 UTC
