### ISSUE TITLE
artifacts do not retain their mode

### ISSUE THREAD

**Issue by blalor** [gocd/gocd#1843] opened 2016-01-26 21:59 UTC
In v16.1.0 on Linux, if I define a set of artifacts to be published to the server, they do not retain their executable bit, if set.  The permissions should be retained when published and fetched.

**Comment by arvindsv** [comment] 2016-01-26 22:18
Agree but closing as a duplicate of #464. Problem with using zip rather than tar internally. Needs someone to work on it.

**Closed by arvindsv** 2016-01-26 22:18 UTC
