### ISSUE TITLE
ability to turn off param substitution for task plugin fields

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#772] opened 2014-12-12 09:20 UTC
else it causes issues like:

![screen shot 2014-12-12 at 2 49 37 pm](https://cloud.githubusercontent.com/assets/1587661/5409286/2e64ca9a-820e-11e4-80a2-f507d8855520.png)

**Comment by arikagoyal** [comment] 2015-02-02 07:36
Duplicate of #817. Closing it

**Closed by arikagoyal** 2015-02-02 07:36 UTC
