### ISSUE TITLE
Can't create pipeline with template that fetches artifacts from two pipelines

### ISSUE THREAD

**Issue by eylvisaker** [gocd/gocd#1458] opened 2015-08-26 22:52 UTC
I have a pipeline which has two different pipelines as materials, and there are tasks within that pipeline that fetch artifacts from both the upstream pipelines.

I have extracted a template from a pipeline. That worked fine and the pipeline continues to function.

I cannot add a new pipeline which uses this template. If I try, I get the following error message: Pipeline "NewPipeline" tries to fetch artifact from pipeline "UpstreamPipeline2" which is not an upstream pipeline.

The Add Pipeline pages only allow me to specify a single material, so there is no way I can satisfy both dependencies.

I can get around this by manually adding the pipeline to the config XML. But the UI is broken for adding a pipeline in this case because it does not allow me to specify more than one material for a pipeline.

**Comment by arvindsv** [comment] 2015-08-27 12:01
Yes, that's right. This is a known issue. Closing this as a duplicate of #986.

**Closed by arvindsv** 2015-08-27 12:01 UTC
