### ISSUE TITLE
Circular dependency detected while autoloading constant Spring - at server start

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1444] opened 2015-08-18 14:53 UTC
Apparently there is an inconsistently appearing error at server start.

```
2015-08-18 13:18:13,796 FATAL [qtp761356018-30] Rails:? - 
RuntimeError (Circular dependency detected while autoloading constant Spring):
  lib/services.rb:5:in `get_service'
  lib/services.rb:18:in `server_health_service'
  app/controllers/application_controller.rb:80:in `populate_health_messages'
```

Some [conversation we had](https://gitter.im/gocd/gocd?at=55d33b266b94865520d83589)
1. It happened in the past a few times but we do not exactly know why.
   mail from @srinivasupadhya, from Oct 2014, which says:
   Saw this in logs:

```
2014-10-19 21:37:58,499 FATAL [688788755@qtp-1354749546-16] Rails:? -
RuntimeError (Circular dependency detected while autoloading constant Spring):
  lib/services.rb:5:in `get_service'
  lib/services.rb:18:in `server_health_service'
  app/controllers/application_controller.rb:64:in `populate_health_messages’
```

 We couldn’t consistently reproduce it at that time.

Currently I can reproduce it only in go-sever installed from PRs for #1133

The fact that it happened before suggests that it might be some deeper bug, not necessarily connected to #1133

I'll publish more info in time after adding more logging

**Comment by ketan** [comment] 2015-08-18 15:05
For anyone trying to reproduce this issue, edit `lib/spring.rb` inside the rails app to add these lines

```ruby
class Spring

  Rails.logger.fatal("*** Class spring loaded from - ")
  Rails.logger.fatal(caller.join("\n”))
  ...
```

**Comment by tomzo** [comment] 2015-08-18 18:30
After adding extra log message:
```
2015-08-18 18:27:43,414 FATAL [qtp1606920670-18] Rails:? - *** Class spring loaded from - 
2015-08-18 18:27:43,425 FATAL [qtp1606920670-16] Rails:? - 
RuntimeError (Circular dependency detected while autoloading constant Spring):
  lib/services.rb:5:in `get_service'
  lib/services.rb:18:in `server_health_service'
  app/controllers/application_controller.rb:80:in `populate_health_messages'


2015-08-18 18:27:43,437 FATAL [qtp1606920670-18] Rails:? - /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/lib/spring.rb:21:in `(root)'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:330:in `require_or_load'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:1:in `(root)'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:463:in `load_missing_constant'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:184:in `const_missing'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:184:in `const_missing'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/lib/services.rb:5:in `get_service'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/lib/services.rb:18:in `server_health_service'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/app/controllers/application_controller.rb:80:in `populate_health_messages'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:400:in `_run__155994784__process_action__callbacks'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:31:in `process_action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/base.rb:136:in `process'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:44:in `process'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:195:in `dispatch'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:231:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:231:in `action'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:48:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:71:in `each'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:71:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:59:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:674:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/versionist-1.4.1/lib/versionist/middleware.rb:39:in `_call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/versionist-1.4.1/lib/versionist/middleware.rb:17:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/flash.rb:241:in `call'
file:/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/lib/jruby-rack-1.1.14.jar!/jruby/rack/session_store.rb:79:in `context'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/cookies.rb:486:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:29:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:376:in `_run__1286457872__call__callbacks'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:22:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/engine.rb:511:in `call'
/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/application.rb:97:in `call'
```

**Comment by ketan** [comment] 2016-04-15 11:29
Further investigation reveals that this is caused because the rails `lib` dir is part of [`autoload_paths`](https://github.com/gocd/gocd/blob/8d181d5bfdb8af102e165760643868a3af697bd0/server/webapp/WEB-INF/rails.new/config/application.rb#L25-L29).

Ideally `lib` dir is never autoloaded, all files in there are explicitly loaded in a very particular order.

**Comment by arvindsv** [comment] 2017-10-18 19:48
Closing this. Haven't seen it in a while. I think we put in some fix for this. Happy to reopen.

**Closed by arvindsv** 2017-10-18 19:48 UTC
