### ISSUE TITLE
Git clean unversioned files does not delete .gitignored files

### ISSUE THREAD

**Issue by mwalton236** [gocd/gocd#859] opened 2015-01-29 15:02 UTC

**Comment by mwalton236** [comment] 2015-01-29 15:02
Any files listed in the .gitignore file are not deleted when the working copy is cleaned

**Comment by arvindsv** [comment] 2016-06-04 12:46
Closing as duplicate of https://github.com/gocd/gocd/pull/1059, since there is more conversation there.

**Closed by arvindsv** 2016-06-04 12:46 UTC
