### ISSUE TITLE
Logged in users start getting redirected infinitely

### ISSUE THREAD

**Issue by ApsOps** [gocd/gocd#3915] opened 2017-10-04 11:27 UTC
##### Issue Type

- Bug Report

##### Summary

Logged in users start getting redirected infinitely to `http://<server_hostname>/go/auth/login?login_error=1` and `https://<server_hostname>/go/auth/login?login_error=1`.
Clearing cookies or restarting server fixes the problem.

##### Environment

https://gist.github.com/ApsOps/ef37ea3cbe6f6bdff4892c5dd32633d7

###### Basic environment details

* Go Version: `17.9.0 (5368-fd43db656e9d9b32d7ab9be1785208f346e9b1be)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.4.0-45-generic (Ubuntu 16.04.1 LTS)`
* Browser vendor and version (if relevant): `Latest Firefox/Chrome`

##### Steps to Reproduce

1. It happens randomly, mostly when any config is changed.

##### Log snippets
Error logs in server
```
2017-10-04 10:47:57,556 ERROR [qtp1096283470-32] BasicAuthenticationFilter:57 - java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authorization.google' implementing 'authorization' extension failed while requesting for 'go.cd.authorization.authenticate-user'. Reason: [org.brickred.socialauth.exception.SocialAuthException: Error while getting profile from https://www.googleapis.com/oauth2/v1/userinfo]
```

**Comment by bdpiparva** [comment] 2018-03-06 08:14
Duplicate of https://github.com/gocd/gocd/issues/4247 and fixed in https://github.com/gocd/gocd/pull/4274.

**Closed by bdpiparva** 2018-03-06 08:14 UTC
