### ISSUE TITLE
Validation of url after normalization

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#6226] opened 2019-04-29 12:03 UTC
Story: #6132

### Validation of url after normalization

During migration, we try to identify whether a URL is valid or not. In case of an invalid url, we don't migrate it. The validation of the URL is currently in representers. Ideally, it should be in MaterialConfig itself. 
Since we cannot guarantee that migration will happen for all the URLs, there may be a state in which a URL in cruise-config.xml is invalid, hence the server will never start up.

E.g.

```xml
<hg url="https://user:pass@domain.com##branch-name" />
```

Any URL with a double hash is invalid according to URI specs. Hence, migration will not happen. This URL, if present in config.xml, the server will not start.

**Comment by arvindsv** [comment] 2019-04-29 14:24
Do we have any other option apart from handling it specially? Users cannot change it from `##` to `#`, since that won't work.

**Comment by bdpiparva** [comment] 2019-05-06 07:40
#### Summary

The issue is mainly targeting where we can put the material URL validation for the git and hg see https://github.com/gocd/gocd/issues/6132#issuecomment-487015054 for more info.


#### Removing support of  credentials from URL

As mentioned in https://github.com/gocd/gocd/issues/6132#issuecomment-487015054 we are thinking of restricting the use of credentials in git and
hg material URL and use attributes instead. In order to achieve this, we have to validate material config from the user. The material can be configured using API, UI(old erb) or config.xml file. MaterialConfig classes are the ideal choice for this kind of validation.


#### Problem

The way migration is implemented is, if we [understand the URL](https://github.com/gocd/gocd/blob/9a99f370d2af5f60767de33ed42494ca2df6c873/config/config-api/src/main/java/com/thoughtworks/go/config/migration/UrlDenormalizerXSLTMigration121.java#L101) then the migration will happen for the URL otherwise not. Since this approach does offer guaranteed migration of all URLs, config may have urls with credentials.

- Following config has valid URL hence the migration will happen:

> Before

```xml
<git url="https://user:pass@domain.com" />
```

> Post migration

```xml
<git url="https://domain.com" username="user" password="pass" />
```

- Invalid config will be retailed as it is

example of it 

```xml
<hg url="https://user:pass@domain.com##branch-name" />
``` 


#### Solutions

1. Add a strict validation, A Url should be valid and it should not have any credentials in it
	- This will lead to server startup failure if migration skips any invalid URL
2. Add a week validation, If we understand the URL then check if has credentials otherwise do nothing(log a warning)
	This will work and it is the same as the XSLT migration. The only problem I see is there is a way for a user to get past the validation by providing an invalid URL

In an ideal situation, I will go with the 1st approach but that is not feasible because migration is not full-proof.


@gocd/committers  - WDYT?

**Comment by bdpiparva** [comment] 2019-05-07 04:24
Based on the conversation -

1. We will go with a pre-migration for hg, which will migrate the `branch name` out to an attribute and then a normal URL migration (for git and hg) to take username and password out of the URL and into attributes.

2. Once the above-mentioned migration is done, then the URL normalization migration will happen. It should migrate all the URLs and update the credentials as attributes

3. We will validate all URLs at startup, using `new URI` and it should not contain credentials. Any failures will mean, the server fails to start.

4. We will have a temporary, non-public flag which turns off that validation, just in case.

5. We will consider URLs such as: `https://#{USER_AND_PASS}@host/repo` and figure out what to do.

**Comment by maheshp** [comment] 2019-05-23 10:39
Closing since we are not migrating the URL's.

**Closed by maheshp** 2019-05-23 10:39 UTC
Labels: url-normalization
