### ISSUE TITLE
export pipeline as yaml or json error

### ISSUE THREAD

**Issue by charlesguo404** [gocd/gocd#7206] opened 2019-11-09 14:56 UTC
architecture as below
nginx https -- > istio ingress http --> gocd http
other function is ok ,but when i export pipeline as yaml or json

```
application-01df17f53dd0c5c312a33768963e82fe193617c12e07b3e96f37b629cee284a8.js:56796 Mixed Content: The page at 'https://test.com/go/admin/pipelines' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://test.com/go/api/admin/export/pipelines/user-service?plugin_id=json.config.plugin'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by ketan** [comment] 2019-11-10 06:10
This is usually the case because the "Host" header is not forwarded to the GoCD server. See [this document](https://docs.gocd.org/current/installation/configure-reverse-proxy.html#gocd-with-nginx) to know what headers need to be forwarded to the GoCD server.

**Comment by ketan** [comment] 2019-11-10 06:15
I'm closing this issue out, but if you're able to still reproduce it, perhaps add a comment so someone can take a look.

**Closed by ketan** 2019-11-10 06:15 UTC

**Comment by charlesguo404** [comment] 2019-11-11 02:11
@ketan 

but other request url working normaly
```
General:
Request URL: https://test.com/go/admin/pipelines
Request Method: GET
Status Code: 200 OK
Remote Address: 1.1.1.1:443
Referrer Policy: no-referrer-when-downgrade

Request Headers
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9,zh;q=0.8,ja;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: JSESSIONID=node01a9xj9o7c6rwnfrcdlf3ev2xe4179.node0
Host: itt-dop-dev.mercedes-benz.com.cn
Pragma: no-cache
Referer: https://test.com/go/pipelines
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
```


 except export pipeline

```
General:
Request URL: http://test.com/go/api/admin/export/pipelines/user-service?plugin_id=yaml.config.plugin
Referrer Policy: no-referrer-when-downgrade

Request Headers:
Provisional headers are shown
Accept: application/vnd.go.cd.v1+json
Origin: https://test.com
```
