### ISSUE TITLE
Authorization Mechanisms are evaluated in different order since at least 18.7.0

### ISSUE THREAD

**Issue by Z3po** [gocd/gocd#5120] opened 2018-09-03 09:47 UTC
##### Issue Type

In Former versions you could always attach a basic authentication header which was used if no valid cookie was supplied. Now the basic authentication header is always evaluated first even if a valid cookie is attached to the request.
This breaks multiple client libraries (e.g. yagocd https://github.com/grundic/yagocd) when using two-factor authentication as your credentials are only valid for the very first request.

In my Opinion the old behaviour should be restored, or does it make any sence to have it changed?

##### Summary

Somewhere between 17.12 and 18.7.0 (I'm not exactly sure which version implemented that changed behaviour) the order of authentication evaluation has changed.

##### Environment

```
GoCD Version: "18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)"
```

##### Steps to Reproduce

1.  Have a GOCD-Server Setup where authentication credentials are enrichted with a one-time-token (two-factor-authentication)
2. Authenticate with username and password to receive a valid session cookie
3. Try to authenticate with the cookie and the credentials in the same request

##### Expected Results

Like in versions before: If a valid cookie is found successfully authenticate.

##### Actual Results

The Server returns 401 credentials invalid.

**Comment by bdpiparva** [comment] 2018-09-03 11:49
Closing as this issue looks duplicate of the https://github.com/gocd/gocd/issues/4997. 

Please, can you verify the fix? An experimental release is available at https://hub.docker.com/r/gocdexperimental/gocd-server/tags/. Feel free to reopen it.

**Closed by bdpiparva** 2018-09-03 11:49 UTC
