### ISSUE TITLE
Fetch Artifact task does not appear in the dropdown while creating a job

### ISSUE THREAD

**Issue by PraveenSingh107** [gocd/gocd#3180] opened 2017-02-15 05:07 UTC
##### Issue Type
- Bug Report

##### Summary

While creating a job, we need to provide at least one task. Task dropdown does not show Fetch Artifact task in this flow. 

Once a job is created, we can add fetch artifact task from the dropdown.

Why can't we add fetch artifact task as part of job creation.

**Comment by zabil** [comment] 2017-02-15 05:15
Duplicate of https://github.com/gocd/gocd/issues/2126

**Closed by zabil** 2017-02-15 05:15 UTC
