### ISSUE TITLE
Go Server on OSX stuck in start up loop

### ISSUE THREAD

**Issue by anthonygreen** [gocd/gocd#1179] opened 2015-06-03 13:04 UTC
See output of osx-app.log & go-server.log 
https://gist.github.com/anthonygreen/64140b32bd6cdf0b1cc8

**Comment by arvindsv** [comment] 2015-06-03 20:27
Hmm. That's ... strange.

Can you please run this and tell me what happens? [The second command is long, I know]

```
cd "/Users/greena28/Library/Application Support/Go Server"

/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java \
  -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=256m \
  -Dapple.awt.UIElement=true -Duser.language=en -Duser.country=US \
  -Dcruise.config.file="/Users/greena28/Library/Application Support/Go Server/config/cruise-config.xml" \
  -Dcruise.config.dir="/Users/greena28/Library/Application Support/Go Server/config/" \
  -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 \
  -jar "/opt/homebrew-cask/Caskroom/go-server/15.1.0-1863/Go Server.app/Contents/Resources/go.jar"
```

Based on what happens when you run that command, I'll dig into this a bit deeper. Just for the record, ```brew cask install go-server``` works for me. I use jdk1.8.0_45, though. I don't think that's a problem.

**Comment by arvindsv** [comment] 2016-01-26 22:50
Closing this. Not enough info to reproduce this. Didn't hear back.

**Closed by arvindsv** 2016-01-26 22:50 UTC
