### ISSUE TITLE
Header row in new "Agent" view hides first agent if browser width is reduced.

### ISSUE THREAD

**Issue by PredatorVI** [gocd/gocd#3007] opened 2016-12-14 17:20 UTC
##### Issue Type
Bug Report

##### Summary

When using the new "Agent View", the new header row expands when the browser window width is reduced.  However, instead of moving the rows for the agent details down, the taller header row hides the first agent row.

##### Environment
Client:
Chrome/MS Edge/IE 11/FireFox
Windows 10

Server:
Ubuntu 16.04
Go-Server + Agents: 16.12.0

![image](https://cloud.githubusercontent.com/assets/1933277/21192775/ebca1954-c1e6-11e6-823b-ea60e94955ee.png)

**Comment by arvindsv** [comment] 2016-12-16 12:42
@naveenbhaskar Is this a duplicate of #2961?

**Comment by maheshp** [comment] 2016-12-19 04:35
Yes, its a duplicate of #2961, closing this.

**Closed by maheshp** 2016-12-19 04:35 UTC
