### ISSUE TITLE
Possible Caching Issue with config.xml

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#1708] opened 2015-12-14 20:09 UTC
A few times now I have made changes to pipeline configuration, executed the pipeline, and had the old configuration be the one that is executed. I suspect there is some issue with Go using a cached version of the pipeline configuration instead of the updated version. The instance today was:

1) Add environment variable to pipeline GRACEFUL_DEPLOY=true
2) Execute pipeline. Console output shows "[go] setting environment variable 'GRACEFUL_DEPLOY' to value ' ' " rather than "true"
3) Double-check pipeline configuration. Environment variable shows it is set correctly
4) Check admin -> config.xml which also shows it is set correctly.
5) Re-execute pipeline. Output still shows "[go] setting environment variable 'GRACEFUL_DEPLOY' to value ' ' "

**Comment by arvindsv** [comment] 2015-12-14 20:43
Hey @benzvan: Did you do a re-run stage, or trigger a new stage? As far as I know, a re-run stage will reuse the old environment variables (as it tries to recreate the run as close to the original as possible) and a re-trigger of the pipeline uses the new environment variable and everything else.

I might be wrong. I can verify later. But, just wanted to get that bit of information from you.

**Comment by benzvan** [comment] 2015-12-14 20:59
Great question and I should have answered it in the original post. I've actually tried both with the same results.

**Comment by benzvan** [comment] 2015-12-14 21:00
The really weird thing about this is that it knows I added the variable just not that I set it to true. I don't remember right now if I added it in two steps or not. I think I did. Once for the variables I was adding and once for the value of that one.

**Comment by benzvan** [comment] 2015-12-14 21:01
...which I guess means it isn't all that weird.

**Comment by benzvan** [comment] 2015-12-14 21:48
As a test, I just ran the pipeline again, 2+ hours after making the change, with the same result. As an additional test, I changed the value of GRACEFUL_DEPLOY to "nottrue" to see if it would jog something loose and it did not. The pipeline again executed with GRACEFUL_DEPLOY=''.

**Comment by arvindsv** [comment] 2015-12-14 22:27
Ok, thank you for that. Someone (maybe I :)) will try and reproduce this and see what's going on.

**Comment by benzvan** [comment] 2015-12-15 15:37
More info:
I've checked the environment and the pipeline template to make sure neither one has the variable defined.
I've also made several changes to other pipelines' configurations with no problems.

**Comment by arvindsv** [comment] 2015-12-15 21:44
Hey @benzvan, which version of the Go Server are you using? Also, can you please paste the whole beginning part of that task, with information redacted as you see fit? I'd like to see everything from `Starting to execute task` to any lines with `[go] Overriding environment variable ...` to the first couple of lines of the task execution.

I tried with this config:

```
<pipeline name="up42" isLocked="false">
  <environmentvariables>
    <variable name="ENV_VAR1">
      <value>env_var1_value</value>
    </variable>
  </environmentvariables>
  <materials>
    <git url="/tmp/test.git" dest="dest_dir" materialName="dummyhg" />
  </materials>
  <stage name="up42_stage">
    <jobs>
      <job name="up42_job">
        <tasks>
          <exec command="ls" />
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

The output was (*even* on a stage rerun):

```
16:39:31.172 [go] Start to execute task: <exec command="ls" />.
16:39:31.172 [go] setting environment variable 'GO_SERVER_URL' to value 'https://localhost:8154/go'
16:39:31.173 [go] setting environment variable 'GO_TRIGGER_USER' to value 'admin'
16:39:31.173 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'up42'
16:39:31.173 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '1'
16:39:31.174 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '1'
16:39:31.174 [go] setting environment variable 'GO_STAGE_NAME' to value 'up42_stage'
16:39:31.174 [go] setting environment variable 'GO_STAGE_COUNTER' to value '2'
16:39:31.175 [go] setting environment variable 'GO_JOB_NAME' to value 'up42_job'
16:39:31.175 [go] setting environment variable 'GO_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:39:31.175 [go] setting environment variable 'GO_TO_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:39:31.176 [go] setting environment variable 'GO_FROM_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:39:31.176 [go] setting environment variable 'ENV_VAR1' to value 'env_var1_value'
16:39:31.184 cruise-output
16:39:31.184 dest_dir
16:39:31.310 [go] Current job status: passed.
```

Then, I changed it and also added a new env var:

```
<pipeline name="up42" isLocked="false">
  <environmentvariables>
    <variable name="ENV_VAR1">
      <value>env_var1_new_value</value>
    </variable>
    <variable name="ENV_VAR2">
      <value>new_env_var</value>
    </variable>
  </environmentvariables>
  <materials>
    <git url="/tmp/test.git" dest="dest_dir" materialName="dummyhg" />
  </materials>
  <stage name="up42_stage">
    <jobs>
      <job name="up42_job">
        <tasks>
          <exec command="ls" />
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

and got this output:

```
16:42:10.972 [go] Start to execute task: <exec command="ls" />.
16:42:10.972 [go] setting environment variable 'GO_SERVER_URL' to value 'https://localhost:8154/go'
16:42:10.973 [go] setting environment variable 'GO_TRIGGER_USER' to value 'admin'
16:42:10.973 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'up42'
16:42:10.973 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '2'
16:42:10.974 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '2'
16:42:10.974 [go] setting environment variable 'GO_STAGE_NAME' to value 'up42_stage'
16:42:10.975 [go] setting environment variable 'GO_STAGE_COUNTER' to value '1'
16:42:10.975 [go] setting environment variable 'GO_JOB_NAME' to value 'up42_job'
16:42:10.975 [go] setting environment variable 'GO_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:42:10.976 [go] setting environment variable 'GO_TO_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:42:10.976 [go] setting environment variable 'GO_FROM_REVISION_DUMMYHG' to value '88166e11900cbde9c258f50595e8a85c575a5bdb'
16:42:10.977 [go] setting environment variable 'ENV_VAR1' to value 'env_var1_new_value'
16:42:10.977 [go] setting environment variable 'ENV_VAR2' to value 'new_env_var'
16:42:10.983 cruise-output
16:42:10.983 dest_dir
16:42:11.104 [go] Current job status: passed.
```

It seems to be working fine here. So, I must be doing something different.

**Comment by benzvan** [comment] 2015-12-15 22:07
The environment variable must be declared somewhere else in Go. I have a new pipeline for a higher instance of the app where I have not yet declared the variable yet Go is setting it at deploy time.

**Comment by benzvan** [comment] 2015-12-15 22:10
Okay...GRACEFUL_DEPLOY is defined with no value on the same job in the same stage of the template where I'm seeing a problem in the pipeline. So this isn't a config saving problem, it's an inheritance thing. I would actually expect the pipeline to override the template for environment variables.

**Comment by benzvan** [comment] 2015-12-15 22:12
In case it's still useful.

Go Version: 15.2.0(2248-c1f90a6aa3192a)

```
15:28:39.359 [go] Start to execute task: <exec command="bash" >
<arg>-c</arg>
<arg>[[ "${GRACEFUL_DEPLOY}" ]] && DEPLOY_VERSION="##${GO_PIPELINE_COUNTER}"; /opt/caweb/buildtools/ant/bin/ant deploy -f /opt/caweb/deployer/build.xml -Dusername=${DEPLOYER_USER} -Dpassword=${DEPLOYER_PASSWORD} -Dpath=/atlas${DEPLOY_VERSION} -Dwebapp.path=war/atlas</arg>
</exec>.
15:28:39.360 [go] setting environment variable 'GO_ENVIRONMENT_NAME' to value 'Atlas_ST'
15:28:39.360 [go] setting environment variable 'GO_SERVER_URL' to value 'https://go.capella.edu:8154/go/'
15:28:39.360 [go] setting environment variable 'GO_TRIGGER_USER' to value 'changes'
15:28:39.361 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'Atlas_Deploy_ST'
15:28:39.361 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '4'
15:28:39.361 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '96785ea09b50fd9308b4c37a7bb26498f69ac2cd'
15:28:39.361 [go] setting environment variable 'GO_STAGE_NAME' to value 'Deploy_War'
15:28:39.361 [go] setting environment variable 'GO_STAGE_COUNTER' to value '1'
15:28:39.362 [go] setting environment variable 'GO_JOB_NAME' to value 'Deploy_War-runOnAll-1'
15:28:39.362 [go] setting environment variable 'GO_DEPENDENCY_LABEL_ATLAS_BUILD' to value '96785ea09b50fd9308b4c37a7bb26498f69ac2cd'
15:28:39.362 [go] setting environment variable 'GO_DEPENDENCY_LOCATOR_ATLAS_BUILD' to value 'Atlas_Deploy_QA/51/Deploy_War/1'
15:28:39.362 [go] setting environment variable 'GO_REVISION_PROPERTIES' to value '334'
15:28:39.362 [go] setting environment variable 'GO_TO_REVISION_PROPERTIES' to value '334'
15:28:39.363 [go] setting environment variable 'GO_FROM_REVISION_PROPERTIES' to value '334'
15:28:39.363 [go] setting environment variable 'DEPLOYER_USER' to value 'tomcat.deployer.user'
15:28:39.363 [go] setting environment variable 'DEPLOYER_PASSWORD' to value '********'
15:28:39.363 [go] setting environment variable 'GRACEFUL_DEPLOY' to value ''
15:28:39.363 [go] setting environment variable 'UNDEPLOY_VERSION' to value ''
15:28:39.600 Buildfile: /opt/caweb/deployer/build.xml
15:28:40.030 Trying to override old definition of datatype resources
15:28:40.060 
15:28:40.060 deploy:
15:29:15.603    [deploy] OK - Deployed application at context path /atlas
15:29:15.615 
15:29:15.615 BUILD SUCCESSFUL
15:29:15.615 Total time: 35 seconds
15:29:15.638 [go] Current job status: passed.
```

**Comment by arvindsv** [comment] 2015-12-16 18:53
Ok, I'll try this out. I'll setup a template with an environment variable, and then override it in the pipeline and see what happens. I'd expect it to override as well.

**Comment by benzvan** [comment] 2015-12-16 21:01
I recall seeing documentation giving the order of precedence for variables. I can't seem to find that in the environment variables section (9.7) of the documentation.

**Comment by arvindsv** [comment] 2015-12-16 21:46
Could [this](https://www.go.cd/documentation/user/15.3.0/introduction/concepts_in_go.html#environment_variables) be where you saw it? It's in 15.3 documentation.

**Comment by benzvan** [comment] 2015-12-16 21:50
That's actually a lot clearer than what I had found.

**Comment by arvindsv** [comment] 2016-01-04 20:31
Hello!

I tried this out, with this config:

```
<pipelines group="first">
  <pipeline name="TestPipeline" template="TestTemplate">
    <environmentvariables>
      <variable name="VAR_PIPELINE">
        <value>3</value>
      </variable>
      <variable name="VAR_JOB">
        <value>4</value>
      </variable>
      <variable name="VAR_STAGE">
        <value>5</value>
      </variable>
    </environmentvariables>
    <materials>
      <git url="/tmp/test.git" dest="dest_dir" />
    </materials>
  </pipeline>
</pipelines>
<templates>
  <pipeline name="TestTemplate">
    <stage name="stage1">
      <environmentvariables>
        <variable name="VAR_STAGE">
          <value>2</value>
        </variable>
      </environmentvariables>
      <jobs>
        <job name="stage1_job1">
          <environmentvariables>
            <variable name="VAR_JOB">
              <value>1</value>
            </variable>
          </environmentvariables>
          <tasks>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</templates>
```

I see that it prints out:

```
15:19:07.806 [go] Start to build TestPipeline/2/stage1/1/stage1_job1 on my-box.local [/path]
15:19:07.806 [go] Current job status: passed.

15:19:07.806 [go] Start to execute task: <exec command="ls" />.
...
15:19:07.811 [go] setting environment variable 'VAR_PIPELINE' to value '3'
15:19:07.811 [go] setting environment variable 'VAR_STAGE' to value '2'
15:19:07.811 [go] setting environment variable 'VAR_JOB' to value '1'
```

This is a consequence of the inheritance I linked to in an earlier comment. The job and stage of a template are defined at the template level. They're "lower" than the level of a "pipeline" for environment variable inheritance. So, even though they're defined in the template, they override the value defined at the pipeline level (which is at a higher level).

If the pipeline level environment variable overrode the job and stage level environment variables, then it would not be possible to have different jobs in a stage have different values for the environment variable (they'd all get overridden by the pipeline level variable).

I think a way to get past this is to use parameters. Define a param at the template level and override it at the pipeline level, and use that param as the value of the environment variable in the job or wherever.

Given my understanding, I'm marking this as "Not a bug" and closing it. Happy to talk about it further.

**Closed by arvindsv** 2016-01-04 20:31 UTC
Labels: bug, pipeline configuration, [stream] other

**Comment by benzvan** [comment] 2016-01-05 17:28
Unfortunately, using a parameter isn't a possibility for this one since I need users to be able to override it with the "trigger with options" button. I was hoping that defining the variable in the template would be a way of having a default value, but I'll work without that.
In the mean time, the documentation you linked to needs to have "pipeline template" added to the bottom as the final overriding environment value. If I'm understanding correctly, then "pipeline trigger options" should go directly above "pipeline template" too.
