### ISSUE TITLE
Pipeline Configuration Peforce, unable to specify "ssl:"

### ISSUE THREAD

**Issue by adamprescott** [gocd/gocd#1450] opened 2015-08-24 14:53 UTC
I'm currently trying to setup a Pipeline which uses Perforce. Even though the format I entered is correct and the Connection test returns OK, the validation taking place on the field is incorrectly saying that it's an invalid format
![screenshot at 15-41-48](https://cloud.githubusercontent.com/assets/321588/9443058/f4159aa4-4a76-11e5-8166-87b858e6c23d.png)

**Comment by adamprescott** [comment] 2015-08-25 08:39
I also tried changing the config directly on disk as a mean to bypass this validation, but it seems that it applies the same validation to the config file too.

**Comment by ketan** [comment] 2015-08-25 12:32
In case someone decides to pick this up -

[This line](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/config/materials/perforce/P4MaterialConfig.java#L69-69) is likely where you want to fix the pattern for the p4 port.

The corresponding tests are here - https://github.com/gocd/gocd/blob/master/config/config-api/test/com/thoughtworks/go/config/materials/perforce/P4MaterialConfigTest.java

**Comment by adamprescott** [comment] 2015-08-25 12:35
I believe it has something to do with this pattern [here](https://github.com/gocd/gocd/blob/master/config/config-api/test/com/thoughtworks/go/config/materials/perforce/P4MaterialConfigTest.java#L69) If we were to follow the spec defined [here](http://www.perforce.com/perforce/r15.1/manuals/cmdref/P4PORT.html) I think a regex like this would work, though I'm not great with regex and my experience with Java is limited
```
"^(tcp:|(tcp4:|(tcp6:|(tcp46:|(tcp64:|(ssl:|(ssl4:|(ssl6:|(ssl46:|(ssl64:|))))))))))[^:^\\s]+:\\d+$"
```

**Comment by adamprescott** [comment] 2015-08-25 12:37
That above regex seem to work on these tests I ran.
![screenshot at 13-36-55](https://cloud.githubusercontent.com/assets/321588/9466656/6002f5ec-4b2e-11e5-8b1d-7bfd222e59b5.png)

**Comment by ketan** [comment] 2015-08-25 13:03
@arvindsv 

Can we get rid of the port validation using a regex pattern? We don’t do test URLs for other SCMs, and since there is already a check connection button to test the connection, why bother with complex regex based validation that only serve to get in the way.

**Comment by arvindsv** [comment] 2015-08-25 13:08
Yes, I think that makes sense.

**Comment by adamprescott** [comment] 2015-09-09 08:43
Hi,
I was wondering what the status of this ticket was? We've just started evaluating this for use in our dev processes at [RealityMine](http://realitymine.com) but we use Perforce.

**Comment by fire** [comment] 2015-09-24 23:58
@srinivasupadhya @arvindsv is there status on this?

**Comment by arvindsv** [comment] 2015-09-25 12:01
I've submitted a PR (#1521). It's running some tests, and I think it should get accepted early next week at the latest.

**Comment by arvindsv** [comment] 2015-09-25 20:16
Experimental build 15.3.0-2536, available on go.cd/download should have this now.

**Comment by adamprescott** [comment] 2015-09-29 08:00
Thanks a lot for the release/fix, will test it next week with our Perforce SSL setup

**Comment by adamprescott** [comment] 2015-11-19 11:35
Finally got round to testing this fix with our set up, works perfectly now. Thanks for the fix :+1:

**Comment by zabil** [comment] 2015-11-19 12:14
Will be closing it after a round of regression testing

**Comment by rajiesh** [comment] 2015-11-23 09:55
This PR has completely got away with any validation (other than empty and space validations) for the material server and port. May be we need to do a "Check Connection" during the save to catch any issues in the URL provided

**Comment by rajiesh** [comment] 2015-11-23 10:08
Regression test completed, issue can be closed

**Comment by zabil** [comment] 2015-11-23 10:12
@rajiesh as with the others can you add the build version where this is verified?

**Comment by rajiesh** [comment] 2015-11-23 13:52
this issue verified on 15.3.0 (2663-7566bd96b9a35fb9954c84380934c597bd502a90)

**Closed** 2015-11-23 13:52 UTC
