### ISSUE TITLE
pipeline artifact URL is incorrect

### ISSUE THREAD

**Issue by lgwapnitsky** [gocd/gocd#12309] opened 2023-11-28 13:01 UTC
##### Issue Type

- Bug Report

##### Summary

I have a pipeline that successfully uploads one file (not a whole directory, that's another story) as an artifact. When I try to retrieve that artifact from another pipeline, the URL the downstream uses is incorrect.

##### Environment

```
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "5.15.116-1-pve",
    "System Architecture": "amd64",
    "Available Processors": 2,
    "Average System Load": 3.06689453125
  },
```
###### Basic environment details

* Go Version: `23.4.0 (17731-4deb96d823b921419680560be080588e900d406e)`
* JAVA Version: `17.0.9`
* OS: `Linux 5.15.116-1-pve`

##### Expected Results
URLs in pipelines should match

##### Actual Results
URL in downstream has added portion named 'remoting'

##### Log snippets
From Downstream:
```
##|07:38:15.837 [go] Start to build upload-lgw-blog/22/replace-public-files/1/get-from-hugo-build on blog [/var/lib/go-agent]
!!|07:38:15.847 [go] Task: fetch artifact [public/index.html] => [build] from [get_lgw_hugo_master/build_prod_website/build_with_hugo]
&1|07:38:15.848 [go] Fetching artifact [public/index.html] from [get_lgw_hugo_master/18/build_prod_website/2/build_with_hugo]
&2|07:38:16.154 [go] Could not fetch artifact http://10.150.88.34:8153/go/remoting/files/get_lgw_hugo_master/18/build_prod_website/2/build_with_hugo/public/index.html. Pausing 15 seconds to retry. Error was : Unsuccessful response '404' from the server
&2|07:38:31.162 [go] Could not fetch artifact http://10.150.88.34:8153/go/remoting/files/get_lgw_hugo_master/18/build_prod_website/2/build_with_hugo/public/index.html. Pausing 23 seconds to retry. Error was : Unsuccessful response '404' from the server
&2|07:38:54.168 [go] Could not fetch artifact http://10.150.88.34:8153/go/remoting/files/get_lgw_hugo_master/18/build_prod_website/2/build_with_hugo/public/index.html. Pausing 31 seconds to retry. Error was : Unsuccessful response '404' from the server
```

From Upstream:
```
http://10.150.88.34:8153/go/files/get_lgw_hugo_master/18/build_prod_website/2/build_with_hugo/lgw-blog_build/index.html
```

**Comment by chadlwilson** [comment] 2023-11-28 14:00
Hiya - please try and describe the problem you are actually having and what you are trying to achieve rather than your theory about what the root cause of that problem is. I infer you are trying to upload an artifact in one pipeline and then fetch it in another.

Agents retrieve artifacts via a different URL prefix to normal user traffic because the traffic is authenticated differently by different routes, and also have permissions to upload artifacts as well which is not available via user-authenticated routes. This is expected.

Are you sure you have configured the artifact properly? Your agent seems to be looking for `public/index.html` but your “upstream” has `lgw-blog_build/index.html`.

**Comment by chadlwilson** [comment] 2023-11-29 05:25
Will close this one now, as it seems like an artifact fetch or upload configuration issue creating the `404`. Can discuss further if you're still having challenges.

**Closed by chadlwilson** 2023-11-29 05:25 UTC
Labels: artifacts, question
