### ISSUE TITLE
Downstream Pipelines are scheduled and asgined but not starting

### ISSUE THREAD

**Issue by therealchrispin** [gocd/gocd#5092] opened 2018-08-29 15:40 UTC
##### Summary

I´m adding several pipelines through the json config plugin. The Server seems to start the first Pipeline and upload all the materials. Then he triggers 2 downstream pipes who´ll fetch the materials. 

The 2 Downstream pipelines are beeing scheduled and asingned to an agent but they are not starting.

##### Any other info
I´ve stopped the stages to see if the error was still comming. 

![bildschirmfoto 2018-08-29 um 17 41 30](https://user-images.githubusercontent.com/14979067/44798857-dae88500-abb2-11e8-8716-605d3ab1c8aa.png)
##### Environment
I´m running the Server and the Agents as Alpine Docker containers  on a linux machine
-->

###### Basic environment details

* Go Version: ` 18.7.0`
* JAVA Version: `1.8.0_171`
* OS: `Linux 4.15.0-20-generic`

##### Log snippets
```
2018-08-29 15:34:28,029 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
2018-08-29 15:34:36,919 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
2018-08-29 15:34:38,040 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
```
##### Code snippets/Screenshots
Thats how the some of the pipelines are configured in the repository
```
{
  "format_version" : 3,
  "group": "group1",
  "name": "Test-Pipeline-Stage",
  "label_template": "${COUNT}",
  "enable_pipeline_locking" : false,
  "parameters": [],
  "materials": [
    {
      "type": "git",
      "url": ""
      }
    ],
  "stages": [
    {
      "name": "Test",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval" : null,
      "jobs": [{
        "name": "RunUnittestAndCoverage",
        "run_instance_count" : "all",
        "environment_variables": [],
        "timeout": 1,
        "tabs": [
           {
             "name": "coverage",
             "path": "coverage/coverage.html/index.html"
           }
         ],
        "artifacts": [
          {
            "source":"project.tar.gz",
            "destination":"project_source",
            "type":"build"
          },
          {
            "source": "test_result.xml",
            "destination": "testoutput",
            "type": "test"
          },
          {
            "source": "coverage.html",
            "destination": "coverage",
            "type": "build"
          },
          {
            "source": "coverage.xml",
            "destination": "coverage",
            "type": "build"
          }
          ],
        "tasks":[
          {
            "type": "exec",
            "run_if": "passed",
            "on_cancel": null,
            "command":"tox"
          },
          {
           "type":"exec",
            "run_if": "passed",
            "on_cancel": null,
            "command":"/usr/bin/xmllint",
            "arguments": [
                "--format",
                "test_resulto.xml",
                "--output",
                "test_result.xml"
              ]
            },
          {
            "type":"exec",
            "run_if": "passed",
            "on_cancel": null,
            "command": "/bin/ls",
            "arguments":[
              "-al"
            ]
          },
          {
            "type":"exec",
            "run_if": "passed",
            "on_cancel": null,
            "command": "/bin/tar",
            "arguments":[
              "-cvzf",
              "project.tar.gz",
              "/godata/pipelines/Test-Pipeline-Stage"
            ]
          }
          ]
        }
      ]
    }
  ]
}
```
```
{
  "format_version" : 3,
  "group": "group1",
  "name": "Docker-Deployment-Pipeline-Stage",
  "label_template": "${COUNT}",
  "enable_pipeline_locking" : false,
  "parameters": [],
  "materials": [
      {
        "type": "dependency",
        "pipeline": "Build-Pipeline-Stage",
        "stage": "BuildPythonProduct",
        "name": "project_source"
      },
      {
        "type": "dependency",
        "pipeline": "Analyse-Pipeline-Stage",
        "stage":"Analyse",
        "name":"analyse_result"
      }
    ],
  "stages":[
    {
      "name": "BuildDockerImage",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval" : null,
      "jobs":[
        {
          "name": "BuildImage",
          "run_instance_count" : "all",
          "environment_variables": [],
          "timeout": 1,
          "tasks": [
            {
                "type": "fetch",
                "artifact_origin": "gocd",
                "run_if": "any",
                "pipeline": "Build-Pipeline-Stage",
                "stage": "BuildPythonProduct",
                "job": "BuildAndUpLoadWheel",
                "is_source_a_file": true,
                "source": "docker/Dockerfile",
                "destination": ""
            },
            {
                "type": "fetch",
                "artifact_origin": "gocd",
                "run_if": "any",
                "pipeline": "Build-Pipeline-Stage",
                "stage": "BuildPythonProduct",
                "job": "BuildAndUpLoadWheel",
                "is_source_a_file": true,
                "source": "docker/production.ini",
                "destination": ""
            },
            {
                "type":"exec",
                "run_if": "passed",
                "on_cancel": null,
                "command":"/usr/bin/docker",
                "arguments": [
                 "build",
                 "-t",
                 "project_creator",
                 "."
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by arvindsv** [comment] 2018-08-31 12:40
@therealchrispin Can you provide the whole stack trace or even better, the whole log file?

Definitely need more context around this:

```
2018-08-29 15:34:28,029 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
2018-08-29 15:34:36,919 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
2018-08-29 15:34:38,040 ERROR [85@MessageListener for WorkFinder] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@2c731a16
java.lang.NullPointerException: null
```

**Comment by therealchrispin** [comment] 2018-08-31 15:05
Hes not showing the whole stack trace but heres the logfife you can find this error throughout the file.

[go-server.log](https://github.com/gocd/gocd/files/2340560/go-server.log)

**Comment by arvindsv** [comment] 2018-08-31 15:53
Damn it. :( There was an issue with how the log message is logged. The exception is lost. I've put in a [fix to log the stack trace](https://github.com/gocd/gocd/pull/5108/files).

18.8.0 should be out early next week. Let's try it again on that and see what the stacktrace says. That extra information should help find the problem.

**Comment by arvindsv** [comment] 2018-08-31 17:15
@therealchrispin Do you have any JAR files in the libs/ or addons/ directories under `/var/lib/go-server`? Or any JAR files at a Java level, say at `$JAVA_HOME/jre/lib/ext/`?

**Comment by therealchrispin** [comment] 2018-08-31 20:53
I'm actually using the out of the box docker image. This behavior seems only to appear when I use the json repo config option to get the pipeline configuration for a specific project. means I only use this and the ldap plug in

**Comment by arvindsv** [comment] 2018-09-11 20:52
@therealchrispin I tried to reproduce this, without luck. Can you help? Here's what I did:

### Repo 1: https://github.com/arvindsv/gocd_issue_5092_server_agent_docker

- Has a docker-compose file, which has a DB and config checked in.
- The GoCD server is [configured](https://github.com/arvindsv/gocd_issue_5092_server_agent_docker/blob/a2bc3e8b60298aeaf5a9db67a5af4eee410ffedf/data/config/cruise-config.xml#L5-L7) to use "Repo 2" (below) as its config repo.

### Repo 2: https://github.com/arvindsv/gocd_issue_5092_config_repo

- Has 4 files, which I used to try and reproduce this issue. If possible, take a look and see how it has deviated from your setup. If you can change it, so that the issue is reproduced, then I might be able to help fix it.

### Repo 3: https://github.com/arvindsv/gocd_issue_5092_material

- This is the material configured in [the config repo](https://github.com/arvindsv/gocd_issue_5092_config_repo/blob/87ad67dfcce0189e473934d4d1a79a759675996b/test.gopipeline.json#L10-L11).


I'll give you access to all three repos so you can make commits to "Repo 3" to try it out. The README.md of "Repo 1" tells you how to start the server using `docker-compose`. You should be able to just clone than and go from there.

**Comment by arvindsv** [comment] 2018-09-11 20:54
@therealchrispin You should now have (invites giving you) access to all three repos.

**Comment by arvindsv** [comment] 2019-01-09 18:20
Didn't hear anything. Closing as stale.

**Closed by arvindsv** 2019-01-09 18:20 UTC

**Comment by japzio** [comment] 2019-07-25 03:03
Encountered this issue when a couple of pipelines are being triggered that subscribes a common upstream pipeline with only one agent running.
