### ISSUE TITLE
Console page seems slow sometimes, when it has lots of data (20MB page)

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1849] opened 2016-01-28 15:43 UTC
[slow_job_console_load.har.txt](https://github.com/gocd/gocd/files/108416/slow_job_console_load.har.txt)

Reference: https://gitter.im/gocd/gocd?at=56aa33fb8fbaf4220af9e000

**Comment by BrewRunner** [comment] 2016-03-21 19:49
This is painfully slow for many of our pipelines.  The previous versions that did not colorize the log loaded much much faster.  Is there a way to turn off the white on black theme and receive console log output "the old way"?

**Comment by zabil** [comment] 2016-04-01 12:34
Profiled this for a log of 223kb with 2662 lines without ansi colors

![screen shot 2016-04-01 at 5 52 15 pm](https://cloud.githubusercontent.com/assets/54427/14206712/a4348a8a-f832-11e5-83f9-ddef62511364.png)

It takes close to 7 seconds to perform [this](https://github.com/gocd/gocd/blob/aa5a08467523ff8875f3366bead899d4dd193003/server/webapp/WEB-INF/rails.new/app/assets/javascripts/build_output_observer.js#L145) operation.

Just toggling off the ansi up coloring will not improve the performance. Gets exponentially bad as the size of the file goes up throwing the dreaded unresponsive page error.

Rendering the raw output as an iframe on the same page loads the page solves the issue. (The page loads without delay). However the console log won't be colored. 

![screen shot 2016-04-01 at 6 03 17 pm](https://cloud.githubusercontent.com/assets/54427/14206900/1c4d82aa-f834-11e5-9605-71b85a55c0f3.png)

**Comment by BrewRunner** [comment] 2016-04-01 15:11
Yes!  That's it exactly. The console log has become largely unusable for the majority of our pipelines, most of which, produce logs that are larger than what you are testing with. An option to just turn off the formatted console output and use raw would be ideal for users with "lengthy" console logs.

**Comment by ketan** [comment] 2016-04-04 09:43
Can you share the raw logs via a gist so we can use that data to run some browser profilers?

**Comment by BrewRunner** [comment] 2016-04-05 18:50
Here's a somewhat lengthy example: https://gist.github.com/BrewRunner/b980afbc3caab727ff4de6c49c594419

**Comment by wpc** [comment] 2016-04-07 08:14
I got some time today and had quick look of the problem. The code appending log content to the DOM in BuildOutputObserver looks like problematic:
```javascript
while(lines.length){
    var slice = lines.splice(0, 1000);
    var htmlContents = this.ansi_up.ansi_to_html(slice.join("").escapeHTML(), {use_classes: true});
        this.consoleElement.append(htmlContents);
    }
}
```
Although I got the intend progressively append large logs, but the while loops there means it will hog the browser main thread until all lines appended anyway. So the page render timeline looks like this:

<img width="1117" alt="screen shot 2016-04-07 at 12 49 49 am" src="https://cloud.githubusercontent.com/assets/10283/14344147/c6133012-fc5a-11e5-9af2-92ef112ead57.png">


I broke the while loop with setTimeout, render first 100 line then release the control. Code sort of looks like this:
```
    _render_lines: function(lines) {
      var self = this;
      if(!lines.length) {
        return;
      }
      var slice = lines.splice(0, 100);
      var htmlContents = this.ansi_up.ansi_to_html(slice.join("").escapeHTML(), {use_classes: true});
      this.consoleElement.append(htmlContents);
      if(lines.length) {
       window.setTimeout(function() { self._render_lines(lines)}, 10);
      } 
    },
```
The timeline looks like this:
<img width="1112" alt="screen shot 2016-04-07 at 12 54 08 am" src="https://cloud.githubusercontent.com/assets/10283/14344245/52ebaeb0-fc5b-11e5-8411-fb27ca58a0e4.png">

Although appending all log content takes a little bit longer (the timeline didn't fully captured all invokes of _render_lines), and huge log still consume big amount CPU, but page start to be responsive right after load (about 1 seconds), and there are some log content for user to read. So I feel it's a pretty good work around for now.

If nobody reject, I can make a PR base this approach. 

(Profiling is base on 2425 lines of log from https://build.go.cd/go/tab/build/detail/qa-packages-PR/60/dist/1/rpm)

**Comment by ketan** [comment] 2016-04-07 09:56
> If no one object, I can make a PR base on this approach.

:+1: 

Looks good to me, it's a simple enough fix to not have to create a feature toggle of sorts. I like this approach. Might even want to consider using raw DOM API instead of jQuery/prototype for the append operation for this specific case to get improved performance.

As an improvement (strictly not priority, but only if you really want to make feel better about a cleaner approach): 
I was also experimenting with [`document.createDocumentFragment()`](https://developer.mozilla.org/en/docs/Web/API/Document/createDocumentFragment) and [`window.requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) which claims to have better performance for such sort of periodic DOM operations, but did not get to spend much time on it.

**Comment by ketan** [comment] 2016-04-07 09:59
Also, might want to tweak the timeout interval and number of lines in each chunk so that moderately large logs (<20MB) render in a reasonable time.

**Comment by zabil** [comment] 2016-04-07 14:18
> to not have to create a feature toggle of sorts

Finishing up on the toggle code, I think we should have until we implement a low mem/cpu approach.

**Comment by d-led** [comment] 2016-04-14 07:43
has anyone actually tried it with Firefox? On my machine, Firefox does not have this problem, whereas Chrome does. Win64 Chrome 49 / Firefox 45.

[This page](https://build.go.cd/go/tab/build/detail/qa-packages-PR/60/dist/1/rpm) on FF:

![image](https://cloud.githubusercontent.com/assets/1716584/14520468/fd9a0f4a-0224-11e6-8584-2d55e87318db.png)

![image](https://cloud.githubusercontent.com/assets/1716584/14520526/527c7c8c-0225-11e6-8206-efd029f13df5.png)


on Chrome:

![image](https://cloud.githubusercontent.com/assets/1716584/14520503/31d94faa-0225-11e6-8621-03d7e8eb0799.png)

**Comment by zabil** [comment] 2016-04-14 08:48
@d-led did not even think of trying this on firefox but like you mentioned it actually **is** snappier than chrome.

Also chrome freezes while switching tabs something that does not happen on firefox, really strange. 

Chrome: 49.0.2623.112 (64-bit)
Firefox: 45.0.2

**Comment by d-led** [comment] 2016-04-14 08:50
@zabil indeed, it's a positive surprise - currently using it as the simplest work-around

**Comment by zabil** [comment] 2016-04-14 08:57
Makes me wonder now if a chrome upgrade is the reason for the sudden uptick in issues around this.

**Comment by zabil** [comment] 2016-04-14 09:44
Just confirmed by checking against multiple versions of chrome.
This problem is specific to Chrome: 49

Earlier versions of chrome renders this [page](https://build.go.cd/go/tab/build/detail/build-linux/868/build-server/1/server-split-runInstance-1) 

I don't think we should fix this. A chrome upgrade must solve it.

**Comment by d-led** [comment] 2016-04-14 10:17
should someone perhaps submit a bug report to Chrome with the aforementioned page?

**Comment by zabil** [comment] 2016-04-14 10:35
Just sent a report to chrome about the page.

Will try to make a test case.

**Comment by ketan** [comment] 2016-04-14 11:02
I'm on chrome dev channel (currently version 51). The page completely freezes even after a couple of minutes. I can't even profile the page.

On chrome 42, the page freezes for a few seconds (while the console log DOM is rendered) and it's responsive again. I very clearly recall seeing this behaviour when I'd implemented this feature.

**Comment by BrewRunner** [comment] 2016-04-14 15:43
Internet Explorer behaves similarly to Chrome.  Of the 3 browsers that I have installed (IE, Chrome, and Firefox), only Firefox renders the console output in a reasonable amount of time.

**Comment by mnbittorrent** [comment] 2016-04-15 01:52
I wouldn't just rely on Google to fix it. This should be an opportunity to improve the performance, especially if it locks up the main thread. The console logs are critically important, and any chance to make it more stable and performant should be pursued.

**Comment by zabil** [comment] 2016-04-18 05:27
An issue logged against chromium with sample code quite similar to our logic

https://bugs.chromium.org/p/chromium/issues/detail?id=595492&q=appendChild&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by arvindsv** [comment] 2016-04-18 15:56
I ran a [bisect](http://www.chromium.org/developers/bisect-builds-py) on Chrome. Here's the result:

```
$ python bisect-builds.py -a mac -g 361438 -b 361497 --use-local-cache -- --no-first-run --user-data-dir=`pwd`/tmp 'https://build.go.cd/go/tab/build/detail/build-windows/812/build-server-windows/1/server-split-runInstance-1#tab-console'
Downloading list of known revisions...
Loaded revisions 15734-387904 from /private/var/folders/30/sss72tpj3s7c9vgl_8j3j1gh0000gn/T/duck.kXRugF/.bisect-builds-cache.json
Downloading revision 361472...
Received 85493455 of 85493455 bytes, 100.00%
Bisecting range [361438 (good), 361497 (bad)].
Trying revision 361472...
Revision 361472 is [(g)ood/(b)ad/(r)etry/(u)nknown/(s)tdout/(q)uit]: g
Downloading revision 361490...
Bisecting range [361472 (good), 361497 (bad)].
Trying revision 361490...
Revision 361490 is [(g)ood/(b)ad/(r)etry/(u)nknown/(s)tdout/(q)uit]: b
You are probably looking for a change made after 361472 (known good), but no later than 361490 (first known bad).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/8844981696a05f72b6814771a74bec4e410ad71e..32305380195864dce4ac3ad965302a338e4c92d0
```

The changes between the good and bad are [these](https://chromium.googlesource.com/chromium/src/+log/8844981696a05f72b6814771a74bec4e410ad71e..32305380195864dce4ac3ad965302a338e4c92d0). There's a V8-autoroll there (that means that they brought in changes from V8, the JS engine). That's the one I have my eye on. Will need to bisect into V8 using the manual bisect tool to figure out the exact commit. Don't know if I have the time for it. Will do, if I can. That will involve building chrominum for every commit. Could take a bit of time.

**Comment by Par** [comment] 2016-05-09 19:29
I tested using IE 11.0.9600.18282, Google Chrome 49.0.2623.110 and 50.0.2661.94. Issue exists on both versions. Log file size is greater than 10 MB.

**Comment by achoice** [comment] 2016-05-10 08:47
Log of 5 MB hangs browser tab in Chrome 50.0.2661.94 m and IE 11.9600.18283.
In my world this is critical. We have hard time see why build fails.

**Comment by zabil** [comment] 2016-05-10 09:01
Can you try using firefox?

**Comment by achoice** [comment] 2016-05-10 10:58
Firefox works OK. (But please put some prio on finding a real fix.)

**Comment by zabil** [comment] 2016-05-10 11:14
If you've read the comments.

On chrome 49+ fixing this means spoiling the user experience (e.g. implement partial log, check log file size and render raw output etc.) 

So we'll wait for chrome to roll out a release fixing their regression. 
That means no priority until the next few chrome releases are out.

You can help the chrome team by commenting (with details) [here](https://bugs.chromium.org/p/chromium/issues/detail?id=595492)

**Comment by ketan** [comment] 2016-05-10 11:24
I just want to clarify that this problem is my a regression caused by go.
This is performance regression caused by chrome. Older versions of chrome
are much snappier at rendering console log.

**Comment by mnbittorrent** [comment] 2016-06-03 15:30
Any updates on having a fix for this?

**Comment by darrenr** [comment] 2016-06-14 21:18
I believe this may have been fixed in Chrome. You may want to re-test and close in your environment.

**Comment by zabil** [comment] 2016-06-15 10:47
Tried loading on
Chrome: Version 51.0.2704.84 (64-bit)

https://build.go.cd/go/files/build-linux/970/build-server/1/server-split-runInstance-1/cruise-output/console.log 

There is lag as the file is close to 20MB in size, however the un-responsive pop ups are gone.
Closing this.

**Closed by zabil** 2016-06-15 10:47 UTC
Labels: console-log, performance
