### ISSUE TITLE
Logging in as AD user causes an error

### ISSUE THREAD

**Issue by kramer101** [gocd/gocd#900] opened 2015-02-20 17:38 UTC
When attempting to log in as an AD (LDAP) user the error occurs. 
The full stack trace takes up the entire screen.

The user name contains the "!" symbol.

Attached is a screenshot and  stack trace from the go-server.log file

Go Version: 14.4.0(1356-86064ef5ee28e0) 
![go authenticate ldap user error](https://cloud.githubusercontent.com/assets/2284205/6305950/0112eda8-b8e4-11e4-981a-674e84d81e1d.jpg)

```
2015-02-20 11:31:32,096 ERROR [18472036@qtp-25556151-17] log:87 - /go/auth/security_check
org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2
    at org.springframework.security.ldap.SpringSecurityLdapTemplate$3.executeWithContext(SpringSecurityLdapTemplate.java:204)
    at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:784)
    at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:771)
    at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:190)
    at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:118)
    at com.thoughtworks.go.server.security.LdapUserSearch.searchForUser(LdapUserSearch.java:91)
    at org.springframework.security.providers.ldap.authenticator.BindAuthenticator.authenticate(BindAuthenticator.java:82)
    at com.thoughtworks.go.server.security.LdapAuthenticator.authenticate(LdapAuthenticator.java:34)
    at org.springframework.security.providers.ldap.LdapAuthenticationProvider.authenticate(LdapAuthenticationProvider.java:229)
    at com.thoughtworks.go.server.security.providers.UserLicenseEnforcementProvider.authenticate(UserLicenseEnforcementProvider.java:48)
    at org.springframework.security.providers.ProviderManager.doAuthentication(ProviderManager.java:195)
    at org.springframework.security.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:46)
    at org.springframework.security.ui.webapp.AuthenticationProcessingFilter.attemptAuthentication(AuthenticationProcessingFilter.java:82)
    at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:252)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
    at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:40)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:65)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:60)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
    at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.web.ConfigValidityFilter.doFilter(ConfigValidityFilter.java:73)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.PerformanceLoggingFilter.doFilter(PerformanceLoggingFilter.java:45)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:939)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by arvindsv** [comment] 2015-02-20 19:04
Do you have multiple OUs or search bases setup? I think this can happen if a user shows up more than once, usually through different OUs. Or, one username gets mapped to two users somehow, in AD.

**Comment by kramer101** [comment] 2015-02-20 19:28
Yes there are multiple OUs in the LDAP search/filter.
And the user does belong to multiple OUs.

Is this a limitation?..

**Comment by arvindsv** [comment] 2015-02-20 20:16
Well, I don't know what to call it. :) But, yes, I suppose it can be called a limitation. What is happening is that Spring (specifically [FilterBasedLdapUserSearch](http://docs.spring.io/spring-security/site/apidocs/org/springframework/security/ldap/search/FilterBasedLdapUserSearch.html#searchForUser(java.lang.String))) is trying to find a user, given a username. When it finds two, it fails and it fails the authentication.

**Comment by kramer101** [comment] 2015-02-20 21:01
I see. Well, there are many organizations out there that have their AD users in multiple OUs and other AD containers. This is entirely not uncommon.
So it would be nice to have a solution for this once way or another.

Also it would be nice to have the poor exception handling fixed when instead of the user friendly error message the entire screen is replaced with the stack trace.

Thanks anyway.

**Comment by arvindsv** [comment] 2015-02-20 21:11
> Also it would be nice to have the poor exception handling fixed when instead of the user friendly error message the entire screen is replaced with the stack trace

Oh yes, completely agree.

**Comment by jefftrimm** [comment] 2015-03-13 21:24
Somewhat related this, we ran into this an issue with our AD integration where every login resulted in an error complaining about more than one entry coming back.  YMMV depending on the root cause of your login errors in Go, but we found that adding this search filter fixed our issue:

(sAMAccountName={0})

**Comment by kramer101** [comment] 2015-03-16 15:47
@jefftrimm 
Thanks for the note. However, the "(sAMAccountName={0})" is not a part of our AD Filter due to the specific AD structure.

**Comment by srinivasupadhya** [comment] 2015-04-30 05:59
@arvindsv - was this fixed? can we close this?

**Comment by arvindsv** [comment] 2015-04-30 12:13
No, it needs to be fixed. Better error message, and better handling needed.

**Comment by arvindsv** [comment] 2019-01-09 19:07
Closing. LDAP auth has been moved out into a plugin and rewritten since this time.

**Closed by arvindsv** 2019-01-09 19:07 UTC
Labels: [stream] other, authentication

**Comment by chance2021** [comment] 2022-09-29 19:28
In my case, I have to narrow down the scope of base DN. For example, update `rootDN: dc=example,dc=org` to `rootDN: cn=users,cn=accounts,dc=example,dc=org`, so that there is no duplicated username
> Note: I am using Jenkins helm chart for the deployment.
