### ISSUE TITLE
Support secure environment variables at environment/stage/job
levels

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#107] opened 2014-04-16 06:11 UTC
## Description
Currently secure environment variables have been implemented only at the pipeline level. Go should also support environment/stage/job level secure environment variables.

http://support.thoughtworks.com/entries/22004466-Secure-Env-variables-at-the-Env-level-currently-only-can-do-this-for-a-pipeline-?page=1#post_21736954

**Comment by agileassistance** [comment] 2015-01-08 17:14
I would really appreciate this feature in the upcoming release; it's vital for keeping sensitive information secured in the build and the lack of it leads to some convoluted/unnecessary workarounds that makes the pipelines hard to maintain.

**Comment by ketan** [comment] 2015-06-23 07:27
Closing as duplicate of #194. Please track progress there.

**Closed by ketan** 2015-06-23 07:27 UTC
Labels: enhancement
